// Deep Talk cards: conversation starters in three levels, from light and silly to
// heartfelt. Drawn one at a time; both people see the same card.

const D = (level, n, text) => ({ id: `dt${level}-${String(n).padStart(2, "0")}`, level, text })

export const DEEP_LEVELS = [
  { level: 1, name: "Light", blurb: "Warm-up questions to get you smiling." },
  { level: 2, name: "Deeper", blurb: "Stories, feelings and what makes you tick." },
  { level: 3, name: "Deepest", blurb: "The big, tender stuff. Take your time." },
]

const LIGHT = [
  "What's a song that instantly puts you in a good mood?",
  "What was the best thing you ate this month?",
  "If your life had a theme song, what would it sound like?",
  "What tiny thing made you happy today?",
  "Which fictional world would you move into for a year?",
  "What's your most useless talent?",
  "What would your perfect lazy Sunday look like, hour by hour?",
  "What's a smell that takes you straight back to childhood?",
  "If you opened a little shop, what would it sell?",
  "What's the funniest thing that happened to you at school?",
  "Which animal do you think you'd get along with best, and why?",
  "What's a hobby you'd pick up if you had a free month?",
  "What would you name a boat if you had one?",
  "What's the best gift you've ever received for under ten dollars?",
  "If you could master one dance, which one would it be?",
  "What's your go-to order at your favorite restaurant?",
  "What's something you were weirdly obsessed with as a kid?",
  "What's a movie you could watch a hundred times?",
  "If you had a robot helper for one chore, which chore?",
  "What's the most spontaneous thing you've ever done?",
  "What would be on the menu at your dream dinner party?",
  "What's a word you love the sound of?",
  "If you could have any view from your bedroom window, what would it be?",
  "What's a small luxury you'd never give up?",
  "What's the best compliment a stranger ever gave you?",
  "Which season would you live in forever, and what would you do first?",
  "What was your first favorite band or singer?",
  "What's a game you always want to win?",
  "If you were a kind of weather, what would you be today?",
  "What's one thing on your bucket list that's easy to do soon?",
]

const DEEPER = [
  "What's a moment in the last year when you felt really proud of yourself?",
  "Who taught you the most about being kind?",
  "What's something you changed your mind about as you grew up?",
  "When do you feel most like yourself?",
  "What's a fear you've gotten over, and how?",
  "What does a perfect day of rest look like for your mind, not just your body?",
  "What's a tradition you'd love to start?",
  "What's something people often get wrong about you?",
  "Which memory would you put in a time capsule?",
  "What's a habit you're quietly working on?",
  "What do you wish you'd been told at sixteen?",
  "What's the best advice you've ever ignored?",
  "Which friendship has changed you the most?",
  "What makes you feel calm when the world is loud?",
  "What's a risk you're glad you took?",
  "How do you like to be comforted when you've had a hard day?",
  "What's a small act of kindness you still think about?",
  "Which version of yourself are you trying to grow into?",
  "What's a place that feels like home to you, besides your home?",
  "What does a good apology sound like to you?",
  "When was the last time you laughed until it hurt?",
  "What's a dream you had as a kid that still tugs at you?",
  "What do you think you're better at than you give yourself credit for?",
  "What's one thing you'd like to do more of next year?",
  "What does feeling appreciated look like to you?",
  "What's a decision that shaped who you are today?",
  "What's something you find beautiful that others might overlook?",
  "What would you do with a whole year off, no strings attached?",
  "What's a lesson a hard time taught you?",
  "What are you most grateful for this week?",
]

const DEEPEST = [
  "What do you hope people say about you when you're not in the room?",
  "What part of your story do you rarely tell?",
  "What does love feel like to you, in one everyday moment?",
  "When have you felt the most supported by someone?",
  "What's something you need more of that you rarely ask for?",
  "What scares you about the future, and what excites you?",
  "What would you want to be remembered for?",
  "Is there something you've forgiven that changed you?",
  "What's a promise you've made to yourself?",
  "What does a home you've built together look like in ten years?",
  "Which moment between us would you replay if you could?",
  "What do you think we're best at as a team?",
  "What's something you'd like us to try that we never have?",
  "How has knowing me changed you, even a little?",
  "What's a worry you carry that I could help hold?",
  "When did you first feel truly safe with me?",
  "What's something about yourself you're still learning to love?",
  "If you could give your younger self a hug and one sentence, what would you say?",
  "What does 'growing old together' look like in your mind?",
  "What's a dream you haven't said out loud yet?",
  "What makes you feel most loved: being heard, being held, or being helped?",
  "What's the bravest thing you've ever done for someone else?",
  "Which of your values would you never trade away?",
  "What did your family teach you about love, for better or worse?",
  "What's one thing you want me to always remember about you?",
  "What does a perfect ordinary day together look like?",
  "What's a fear you'd like us to face together?",
  "When you picture being really happy, who's there and where are you?",
  "What do you need from me when you're struggling?",
  "What is a question you wish someone would ask you?",
]

export const DEEP_TALK = [...LIGHT.map((t, i) => D(1, i + 1, t)), ...DEEPER.map((t, i) => D(2, i + 1, t)), ...DEEPEST.map((t, i) => D(3, i + 1, t))]
export const deepById = (id) => DEEP_TALK.find((c) => c.id === id) || null
