// "Which of us is more likely to..." prompts, offered as ready-made questions in the quiz
// builder (the author picks: me, you, or both of us).

export const LIKELY = [
  "fall asleep during a movie",
  "cry at a commercial",
  "get us lost on a road trip",
  "eat the last slice of pizza",
  "start a dance party in the kitchen",
  "forget where they parked",
  "adopt a stray animal",
  "plan a surprise party",
  "laugh at their own joke",
  "spend too long choosing what to watch",
  "talk to strangers in line",
  "burn dinner",
  "win a game night",
  "sing loudly in the car",
  "remember an anniversary",
  "hog the blanket",
  "be late to brunch",
  "text back instantly",
  "buy something they don't need",
  "say \"I told you so\"",
  "get scared during a horror movie",
  "start a new hobby and quit in a week",
  "take a hundred photos of one sunset",
  "befriend the neighbors",
  "apologize first",
  "suggest a spontaneous trip",
  "keep every birthday card",
  "check the weather three times a day",
  "fall in love with a new TV show",
  "write a love note",
].map((text, i) => ({ id: `lk-${String(i + 1).padStart(2, "0")}`, text: `Which of us is more likely to ${text}?` }))
