// This or That (quick pairs) and Would You Rather (little dilemmas). Everyone picks a
// side; then you see where you match.

const T = (n, a, b) => ({ id: `tt-${n}`, kind: "tot", prompt: "This or that?", a, b })
const W = (n, a, b) => ({ id: `wy-${n}`, kind: "wyr", prompt: "Would you rather...", a, b })

export const THIS_OR_THAT = [
  T(1, "Coffee", "Tea"),
  T(2, "Beach", "Mountains"),
  T(3, "Sunrise", "Sunset"),
  T(4, "Cats", "Dogs"),
  T(5, "Sweet", "Salty"),
  T(6, "Movie at home", "Movie at the theater"),
  T(7, "Pancakes", "Waffles"),
  T(8, "Texting", "Calling"),
  T(9, "Summer", "Winter"),
  T(10, "Books", "Movies"),
  T(11, "City lights", "Starry countryside"),
  T(12, "Early bird", "Night owl"),
  T(13, "Pizza", "Tacos"),
  T(14, "Road trip", "Flight"),
  T(15, "Plan everything", "Go with the flow"),
  T(16, "Hot shower", "Bubble bath"),
  T(17, "Chocolate", "Vanilla"),
  T(18, "Board games", "Video games"),
  T(19, "Breakfast in bed", "Brunch out"),
  T(20, "Rain", "Snow"),
  T(21, "Camping", "Fancy hotel"),
  T(22, "Fries", "Onion rings"),
  T(23, "Hugs", "Kisses on the forehead"),
  T(24, "Comedy", "Horror"),
  T(25, "Dance all night", "Talk all night"),
  T(26, "Handwritten note", "Long voice message"),
  T(27, "Window seat", "Aisle seat"),
  T(28, "Big party", "Small dinner"),
  T(29, "Ice cream", "Cake"),
  T(30, "Spontaneous trip", "Trip planned for months"),
  T(31, "Socks in bed", "No socks in bed"),
  T(32, "Sing in the car", "Quiet drive"),
  T(33, "Cook together", "Order in"),
  T(34, "Picnic", "Restaurant"),
  T(35, "Morning walk", "Evening walk"),
  T(36, "Fluffy blanket", "Cool sheets"),
  T(37, "Old songs", "New songs"),
  T(38, "Sneakers", "Sandals"),
  T(39, "Puzzles", "Crafts"),
  T(40, "Lake", "Ocean"),
  T(41, "Theme park", "Museum"),
  T(42, "Pasta", "Rice"),
  T(43, "Surprise gift", "Gift you picked"),
  T(44, "Hot chocolate", "Lemonade"),
  T(45, "Cozy sweater", "T-shirt weather"),
  T(46, "Sleep in", "Get up and go"),
  T(47, "Bake cookies", "Buy cookies"),
  T(48, "Karaoke", "Bowling"),
  T(49, "Sushi", "Burgers"),
  T(50, "Big dog", "Small dog"),
  T(51, "Matching outfits", "Never match"),
  T(52, "Aquarium", "Zoo"),
  T(53, "Candles", "Fairy lights"),
  T(54, "Cinnamon", "Mint"),
  T(55, "Strawberries", "Blueberries"),
  T(56, "Ferris wheel", "Roller coaster"),
  T(57, "Slow dance", "Silly dance"),
  T(58, "Bookstore", "Record store"),
  T(59, "Popcorn", "Nachos"),
  T(60, "Stay up for the stars", "Get up for the sunrise"),
]

export const WOULD_YOU_RATHER = [
  W(1, "Have breakfast for every meal", "Have dessert for every meal"),
  W(2, "Live by the beach", "Live in a cabin in the woods"),
  W(3, "Be able to fly", "Be able to breathe underwater"),
  W(4, "Travel to the past", "Travel to the future"),
  W(5, "Always be a little too warm", "Always be a little too cold"),
  W(6, "Have a pet dragon", "Have a pet unicorn"),
  W(7, "Read minds for a day", "Be invisible for a day"),
  W(8, "Never have to sleep", "Never have to eat"),
  W(9, "Speak every language", "Play every instrument"),
  W(10, "Give up music", "Give up movies"),
  W(11, "Have a tiny house with a huge garden", "A huge house with no garden"),
  W(12, "Take a trip around the world in a year", "Have one perfect week anywhere"),
  W(13, "Win a cooking contest", "Win a dance contest"),
  W(14, "Always know the time", "Always know the way"),
  W(15, "Have a personal chef", "Have a personal driver"),
  W(16, "Relive your favorite day", "Skip your worst day"),
  W(17, "Explore the deep ocean", "Explore outer space"),
  W(18, "Be famous", "Be quietly rich"),
  W(19, "Laugh at everything", "Never be bored"),
  W(20, "Have a rewind button for your life", "A pause button for your life"),
  W(21, "Live without your phone for a month", "Live without dessert for a year"),
  W(22, "Go on a hot-air balloon ride", "Go on a submarine ride"),
  W(23, "Have a holiday every week", "Have a three-month summer vacation"),
  W(24, "Talk to animals", "Talk to plants"),
  W(25, "Only whisper", "Only shout"),
  W(26, "Have your dream job", "Have your dream home"),
  W(27, "Sing everything you say", "Dance everywhere you walk"),
  W(28, "See a show every week", "Eat at a new restaurant every week"),
  W(29, "Spend a day as a cat", "Spend a day as a bird"),
  W(30, "Know how every movie ends", "Never be able to rewatch a movie"),
  W(31, "Have perfect memory", "Have perfect timing"),
  W(32, "Live in a castle", "Live on a houseboat"),
  W(33, "Get a handwritten letter every week", "Get flowers every month"),
  W(34, "Have endless pizza", "Have endless ice cream"),
  W(35, "Live one year in your favorite movie", "One year in your favorite video game"),
  W(36, "Be the best at a sport", "Be the best at a game show"),
  W(37, "Stay young forever", "Be wise forever"),
  W(38, "Wake up to breakfast in bed", "Fall asleep to a back rub"),
  W(39, "Plan the perfect date", "Be surprised with the perfect date"),
  W(40, "Have a theme song that plays when you walk in", "Have a laugh track for your jokes"),
]

// Date Night: sweet and a little flirty pairs for two
const D = (n, a, b) => ({ id: `dn-${n}`, kind: "date", prompt: "Date night: this or that?", a, b })

export const DATE_NIGHT = [
  D(1, "Candlelit dinner", "Picnic under the stars"),
  D(2, "Stargazing on a blanket", "Rooftop city lights"),
  D(3, "Matching pajamas", "Matching sweaters"),
  D(4, "Love letter", "Love song"),
  D(5, "Forehead kisses", "Cheek kisses"),
  D(6, "Holding hands", "Arm around the shoulder"),
  D(7, "Cook dinner together", "Order in and cuddle"),
  D(8, "Sunrise hike", "Sunset drive"),
  D(9, "Surprise date", "Planned-together date"),
  D(10, "Breakfast date", "Late-night dessert date"),
  D(11, "Rom-com marathon", "Scary movie and hiding behind them"),
  D(12, "Couples massage", "Bubble bath for two"),
  D(13, "Sweet texts all day", "One long call at night"),
  D(14, "Big spoon", "Little spoon"),
  D(15, "Dress up fancy", "Stay in sweatpants"),
  D(16, "Wine tasting", "Milkshake date"),
  D(17, "Arcade date", "Museum date"),
  D(18, "Karaoke duet", "Paint-and-sip night"),
  D(19, "Weekend getaway", "Staycation at home"),
  D(20, "Flowers", "Chocolates"),
  D(21, "Kiss in the rain", "Kiss under fireworks"),
  D(22, "Couple's costume", "Surprise each other's costume"),
  D(23, "Matching tattoos (temporary!)", "Matching bracelets"),
  D(24, "Inside jokes", "Pet names"),
  D(25, "Fall asleep on the couch together", "Stay up talking until 3 a.m."),
  D(26, "Bake cookies together", "Build a blanket fort"),
]

export const PAIRS = [...THIS_OR_THAT, ...WOULD_YOU_RATHER, ...DATE_NIGHT]
export const pairById = (id) => PAIRS.find((p) => p.id === id) || null
