// Party Pack trivia: general-knowledge questions anyone can play. Written as
// (question, right answer, three wrong answers); the right answer lands in a different
// spot from question to question.

const pack = (id, name, blurb, rows) => ({
  id,
  name,
  blurb,
  questions: rows.map(([q, right, wrong], i) => {
    const at = (i * 3 + id.length) % 4
    const options = [...wrong]
    options.splice(at, 0, right)
    return { id: `tv-${id}-${String(i + 1).padStart(2, "0")}`, q, options, answer: at }
  }),
})

export const TRIVIA_PACKS = [
  pack("retro", "Retro Tech", "Floppies, dial-up and pixels.", [
    ["What does the \"www\" in a web address stand for?", "World Wide Web", ["Wide Web World", "World Web Window", "Web Wide Works"]],
    ["About how much data does a standard 3.5-inch high-density floppy disk hold?", "1.44 MB", ["144 KB", "14.4 MB", "1.44 GB"]],
    ["What does \"CD-ROM\" stand for?", "Compact Disc Read-Only Memory", ["Computer Disc Running On Memory", "Compact Data Random Output Media", "Central Disc Read-Only Module"]],
    ["Which company made the original Game Boy?", "Nintendo", ["Sega", "Sony", "Atari"]],
    ["\"Modem\" is short for what?", "Modulator-demodulator", ["Mobile data module", "Modern memory", "Monitor-demonstrator"]],
    ["What does \"HTML\" stand for?", "HyperText Markup Language", ["High Tech Modern Language", "Home Tool Markup Language", "HyperTransfer Mail Link"]],
    ["Which virtual pet, hatched from a little egg-shaped toy, was a craze in the late 1990s?", "Tamagotchi", ["Furby", "Pokemon", "Neopet"]],
    ["What does \"USB\" stand for?", "Universal Serial Bus", ["Unified System Board", "Universal Storage Box", "User Serial Bridge"]],
    ["What does \"GIF\" stand for?", "Graphics Interchange Format", ["Graphic Image File", "General Image Format", "Group Interchange File"]],
    ["What does \"VHS\" stand for?", "Video Home System", ["Visual Home Screen", "Video High Speed", "Variable Height Signal"]],
    ["Which programming language shares its name with an Indonesian island?", "Java", ["Python", "Ruby", "Pascal"]],
    ["The word \"pixel\" comes from which two words?", "Picture element", ["Pixie cell", "Pixelated label", "Print exactly"]],
    ["How many bits are in a byte?", "8", ["2", "4", "16"]],
    ["Which of these storage formats came out first?", "The compact disc (CD)", ["The DVD", "The USB flash drive", "The Blu-ray disc"]],
    ["What does \"RAM\" stand for?", "Random Access Memory", ["Read And Modify", "Rapid Action Module", "Remote Access Machine"]],
    ["The phone game \"Snake\" was famously preinstalled on phones made by which company?", "Nokia", ["Motorola", "Ericsson", "BlackBerry"]],
    ["The \"Y2K bug\" worried people because computers stored years with how many digits?", "Two", ["One", "Three", "Eight"]],
    ["What does \"CPU\" stand for?", "Central Processing Unit", ["Computer Power Unit", "Core Program Utility", "Central Peripheral Unit"]],
  ]),
  pack("food", "Food & Drink", "A tasty little menu of questions.", [
    ["Guacamole is made mainly from which fruit?", "Avocado", ["Lime", "Green pepper", "Kiwi"]],
    ["Which country did sushi come from?", "Japan", ["China", "Thailand", "Korea"]],
    ["What is the main ingredient in hummus?", "Chickpeas", ["Lentils", "Peanuts", "Black beans"]],
    ["Marzipan is made mostly from which nut?", "Almonds", ["Peanuts", "Cashews", "Walnuts"]],
    ["Which spice gives many curries their golden-yellow color?", "Turmeric", ["Cinnamon", "Paprika", "Cumin"]],
    ["Traditional Japanese sake is brewed from what?", "Rice", ["Barley", "Potatoes", "Plums"]],
    ["Traditional mozzarella di bufala is made from the milk of which animal?", "Water buffalo", ["Goat", "Sheep", "Camel"]],
    ["Which vegetable gives borscht its deep red color?", "Beets", ["Red peppers", "Tomatoes", "Red cabbage"]],
    ["Which pasta's name means \"little tongues\" in Italian?", "Linguine", ["Penne", "Farfalle", "Rigatoni"]],
    ["Which fruit wears its seeds on the outside?", "Strawberry", ["Raspberry", "Blueberry", "Cherry"]],
    ["Tofu is made from which bean?", "Soybeans", ["Kidney beans", "Lima beans", "Green beans"]],
    ["What makes yeast bread dough rise?", "Yeast making gas bubbles", ["Salt", "Sugar melting", "Cold water"]],
    ["Paella is a famous rice dish from which country?", "Spain", ["Italy", "Mexico", "Portugal"]],
    ["What is a dried plum called?", "A prune", ["A raisin", "A date", "A fig"]],
    ["Which drink is made by fermenting honey?", "Mead", ["Cider", "Sake", "Kombucha"]],
    ["Classic pesto is made with which herb?", "Basil", ["Parsley", "Mint", "Cilantro"]],
    ["Raisins are dried versions of which fruit?", "Grapes", ["Plums", "Cherries", "Cranberries"]],
    ["The long, crusty baguette is a classic bread from which country?", "France", ["Belgium", "Switzerland", "Germany"]],
  ]),
  pack("geo", "Geography", "Around the world in a few questions.", [
    ["What is the largest ocean on Earth?", "Pacific Ocean", ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"]],
    ["What is the capital of Australia?", "Canberra", ["Sydney", "Melbourne", "Perth"]],
    ["Which is the longest river in South America?", "The Amazon", ["The Orinoco", "The Parana", "The Magdalena"]],
    ["The Sahara Desert is on which continent?", "Africa", ["Asia", "Australia", "South America"]],
    ["What is the capital of Canada?", "Ottawa", ["Toronto", "Vancouver", "Montreal"]],
    ["Mount Everest sits on the border between Nepal and which other country?", "China", ["India", "Bhutan", "Pakistan"]],
    ["Which country is shaped like a boot?", "Italy", ["Greece", "Portugal", "Chile"]],
    ["Which is the smallest continent by land area?", "Australia", ["Europe", "Antarctica", "South America"]],
    ["What is the capital of Japan?", "Tokyo", ["Kyoto", "Osaka", "Hiroshima"]],
    ["Which US state is made up entirely of islands?", "Hawaii", ["Alaska", "Florida", "Rhode Island"]],
    ["Which river flows through Cairo?", "The Nile", ["The Tigris", "The Congo", "The Jordan"]],
    ["What is the capital of Brazil?", "Brasilia", ["Rio de Janeiro", "Sao Paulo", "Salvador"]],
    ["Which country has the largest land area in the world?", "Russia", ["Canada", "China", "United States"]],
    ["The Andes mountains are on which continent?", "South America", ["Africa", "Europe", "Asia"]],
    ["What imaginary line divides Earth into the Northern and Southern Hemispheres?", "The Equator", ["The Prime Meridian", "The Tropic of Cancer", "The Arctic Circle"]],
    ["What is the capital of Iceland?", "Reykjavik", ["Oslo", "Helsinki", "Nuuk"]],
    ["Which sea lies between southern Europe and northern Africa?", "The Mediterranean Sea", ["The Red Sea", "The Black Sea", "The Caspian Sea"]],
    ["In the common seven-continent model, how many continents are there?", "7", ["5", "6", "8"]],
  ]),
  pack("animals", "Animals", "Furry, scaly and feathery facts.", [
    ["What is the largest animal on Earth?", "Blue whale", ["African elephant", "Whale shark", "Giraffe"]],
    ["How many legs does a spider have?", "8", ["6", "10", "12"]],
    ["What is a baby kangaroo called?", "A joey", ["A kit", "A pup", "A cub"]],
    ["Which of these birds cannot fly?", "Penguin", ["Eagle", "Sparrow", "Parrot"]],
    ["What is the fastest land animal?", "Cheetah", ["Lion", "Horse", "Greyhound"]],
    ["How many hearts does an octopus have?", "3", ["1", "2", "8"]],
    ["What is a group of lions called?", "A pride", ["A pack", "A herd", "A school"]],
    ["What do giant pandas eat most of the time?", "Bamboo", ["Fish", "Berries", "Insects"]],
    ["Which is the only mammal that can truly fly?", "The bat", ["The flying squirrel", "The sugar glider", "The colugo"]],
    ["What is a baby frog called?", "A tadpole", ["A cygnet", "A fry", "A nymph"]],
    ["How many legs does an insect have?", "6", ["4", "8", "10"]],
    ["Which animal is nicknamed the \"ship of the desert\"?", "Camel", ["Horse", "Desert tortoise", "Fennec fox"]],
    ["What is the tallest animal in the world?", "Giraffe", ["Elephant", "Ostrich", "Moose"]],
    ["What is a group of crows called?", "A murder", ["A pride", "A parliament", "A gaggle"]],
    ["Which of these animals is a marsupial, carrying its young in a pouch?", "Koala", ["Panda", "Sloth", "Lemur"]],
    ["Dolphins breathe air through what?", "A blowhole", ["Gills", "Their skin", "Their mouth only"]],
    ["How many arms do most sea stars have?", "5", ["4", "6", "8"]],
    ["Which bird is famous for copying human speech?", "Parrot", ["Pigeon", "Owl", "Flamingo"]],
  ]),
  pack("science", "Science & Space", "Planets, atoms and the human body.", [
    ["Which planet is closest to the Sun?", "Mercury", ["Venus", "Mars", "Earth"]],
    ["What is the chemical symbol for gold?", "Au", ["Go", "Gd", "Ag"]],
    ["Which planet is known as the Red Planet?", "Mars", ["Jupiter", "Venus", "Saturn"]],
    ["At sea level, water boils at what temperature in Celsius?", "100 degrees", ["90 degrees", "212 degrees", "50 degrees"]],
    ["Which gas do plants take in from the air to make food?", "Carbon dioxide", ["Oxygen", "Nitrogen", "Helium"]],
    ["What is the largest planet in our solar system?", "Jupiter", ["Saturn", "Neptune", "Earth"]],
    ["How many bones are in the typical adult human body?", "206", ["106", "300", "412"]],
    ["What force keeps our feet on the ground?", "Gravity", ["Magnetism", "Friction", "Static electricity"]],
    ["What is the hardest natural substance?", "Diamond", ["Gold", "Iron", "Quartz"]],
    ["Which planet is famous for its bright, wide rings?", "Saturn", ["Mars", "Mercury", "Venus"]],
    ["Roughly how fast does light travel?", "About 300,000 km per second", ["About 300 km per second", "About 3,000 km per hour", "About the speed of sound"]],
    ["What is the center of an atom called?", "The nucleus", ["The electron", "The core shell", "The orbit"]],
    ["What is the chemical symbol for iron?", "Fe", ["Ir", "In", "I"]],
    ["Who was the first person to walk on the Moon?", "Neil Armstrong", ["Buzz Aldrin", "Yuri Gagarin", "John Glenn"]],
    ["Water freezes at what temperature in Fahrenheit?", "32 degrees", ["0 degrees", "10 degrees", "100 degrees"]],
    ["Which organ pumps blood around your body?", "The heart", ["The lungs", "The liver", "The kidneys"]],
    ["Which blood cells carry oxygen around the body?", "Red blood cells", ["White blood cells", "Platelets", "Nerve cells"]],
    ["About how long does Earth take to travel once around the Sun?", "About 365 days", ["About 24 hours", "About 30 days", "About 100 days"]],
  ]),
  pack("general", "General Knowledge", "A little bit of everything.", [
    ["How many days are in a leap year?", "366", ["365", "364", "367"]],
    ["How many sides does a hexagon have?", "6", ["5", "7", "8"]],
    ["Which of these is NOT one of the three traditional primary colors of paint?", "Green", ["Red", "Yellow", "Blue"]],
    ["How many minutes are in a day?", "1,440", ["1,200", "2,400", "3,600"]],
    ["Which instrument usually has 88 keys?", "Piano", ["Accordion", "Violin", "Harp"]],
    ["What is the Roman numeral for 50?", "L", ["C", "D", "X"]],
    ["How many players does each soccer team have on the field?", "11", ["9", "10", "12"]],
    ["Which month has the fewest days?", "February", ["April", "June", "November"]],
    ["How many is a \"baker's dozen\"?", "13", ["12", "14", "24"]],
    ["In chess, which piece moves only diagonally?", "The bishop", ["The rook", "The knight", "The king"]],
    ["How many strings does a standard guitar have?", "6", ["4", "5", "8"]],
    ["Which language has the most native speakers in the world?", "Mandarin Chinese", ["English", "Spanish", "Hindi"]],
    ["What is the square root of 81?", "9", ["8", "7", "9.5"]],
    ["How many zeros are in one million?", "6", ["5", "7", "9"]],
    ["In which direction does the Sun rise?", "East", ["West", "North", "South"]],
    ["What do you call a word that reads the same forwards and backwards, like \"level\"?", "A palindrome", ["An anagram", "A homophone", "An acronym"]],
    ["How many colors are in a rainbow, as traditionally counted?", "7", ["5", "6", "9"]],
    ["How many cards are in a standard deck, not counting jokers?", "52", ["48", "50", "54"]],
  ]),
]

export const TRIVIA = TRIVIA_PACKS.flatMap((p) => p.questions)
export const triviaById = (id) => TRIVIA.find((q) => q.id === id) || null
