// Imposter's built-in word lists: family-friendly categories of "Word:Close word" pairs. The
// close word is what the imposter gets in the Decoy and Undercover variants, and their hint.

const RAW = {
  food: ["Food", "Pizza:Burger|Sushi:Ramen|Taco:Burrito|Pancake:Waffle|Spaghetti:Lasagna|Hot dog:Sausage|Sandwich:Wrap|Soup:Stew|Salad:Coleslaw|Fried chicken:Chicken nuggets|Popcorn:Pretzel|French fries:Onion rings|Cheese:Butter|Bacon:Ham|Omelet:Scrambled eggs|Dumpling:Spring roll|Bagel:Donut|Nachos:Chips and salsa|Steak:Pork chop|Mac and cheese:Grilled cheese|Cereal:Oatmeal|Toast:Croissant|Meatball:Hamburger patty|Curry:Chili"],
  desserts: ["Desserts", "Ice cream:Frozen yogurt|Cupcake:Muffin|Brownie:Cookie|Cheesecake:Pie|Chocolate:Caramel|Lollipop:Candy cane|Marshmallow:Cotton candy|Pudding:Jelly|Milkshake:Smoothie|Birthday cake:Wedding cake|Churro:Funnel cake|Popsicle:Snow cone|Gummy bears:Jelly beans|Apple pie:Peach cobbler|Whipped cream:Frosting|Cinnamon roll:Danish|S'mores:Hot cocoa|Sprinkles:Chocolate chips|Macaron:Meringue|Tiramisu:Trifle"],
  drinks: ["Drinks", "Coffee:Tea|Lemonade:Iced tea|Orange juice:Apple juice|Milk:Chocolate milk|Hot chocolate:Latte|Soda:Sparkling water|Smoothie:Milkshake|Water:Ice|Root beer:Cola|Punch:Fruit juice|Bubble tea:Iced coffee|Coconut water:Sports drink|Espresso:Cappuccino|Slushie:Snow cone|Eggnog:Cider"],
  fruitveg: ["Fruit & Veggies", "Apple:Pear|Banana:Plantain|Strawberry:Raspberry|Watermelon:Cantaloupe|Orange:Tangerine|Grape:Raisin|Pineapple:Mango|Lemon:Lime|Cherry:Blueberry|Peach:Apricot|Coconut:Kiwi|Carrot:Sweet potato|Broccoli:Cauliflower|Corn:Peas|Potato:Onion|Tomato:Red pepper|Lettuce:Spinach|Cucumber:Zucchini|Pumpkin:Squash|Avocado:Olive|Mushroom:Garlic|Celery:Asparagus"],
  animals: ["Animals", "Dog:Wolf|Cat:Tiger|Lion:Leopard|Elephant:Rhino|Giraffe:Zebra|Monkey:Gorilla|Penguin:Puffin|Owl:Eagle|Horse:Donkey|Cow:Goat|Pig:Sheep|Rabbit:Hamster|Kangaroo:Koala|Bear:Panda|Fox:Raccoon|Snake:Lizard|Frog:Turtle|Bat:Moth|Squirrel:Chipmunk|Deer:Moose|Camel:Llama|Parrot:Flamingo|Hedgehog:Porcupine|Mouse:Rat"],
  ocean: ["Under the Sea", "Shark:Dolphin|Whale:Walrus|Octopus:Squid|Jellyfish:Sea anemone|Crab:Lobster|Starfish:Sea urchin|Seahorse:Clownfish|Sea turtle:Stingray|Coral reef:Seaweed|Shipwreck:Treasure chest|Submarine:Scuba diver|Seal:Sea lion|Shrimp:Oyster|Pufferfish:Angelfish|Sand dollar:Seashell|Narwhal:Swordfish"],
  house: ["Around the House", "Couch:Armchair|Bed:Hammock|Refrigerator:Freezer|Oven:Microwave|Toaster:Blender|Bathtub:Shower|Toilet:Sink|Lamp:Candle|Television:Computer|Pillow:Blanket|Mirror:Window|Doorbell:Door knocker|Vacuum:Broom|Washing machine:Dishwasher|Stairs:Elevator|Fireplace:Radiator|Bookshelf:Dresser|Clock:Calendar|Curtains:Blinds|Carpet:Doormat|Garage:Basement|Mailbox:Doorstep|Attic:Closet|Remote control:Phone charger"],
  kitchen: ["In the Kitchen", "Spoon:Fork|Knife:Scissors|Frying pan:Pot|Spatula:Whisk|Plate:Bowl|Cup:Mug|Cutting board:Tray|Oven mitt:Apron|Kettle:Coffee maker|Rolling pin:Measuring cup|Can opener:Bottle opener|Colander:Grater|Napkin:Paper towel|Salt:Pepper|Ice cube tray:Lunchbox|Chopsticks:Toothpicks|Ladle:Tongs|Teapot:Pitcher"],
  places: ["Places", "Beach:Lake|Library:Bookstore|Hospital:Pharmacy|Airport:Train station|School:College|Zoo:Aquarium|Museum:Art gallery|Movie theater:Concert hall|Restaurant:Cafe|Supermarket:Mall|Park:Playground|Farm:Ranch|Castle:Palace|Bank:Post office|Gym:Swimming pool|Hotel:Campsite|Bakery:Pizzeria|Stadium:Arena|Lighthouse:Harbor|Amusement park:Water park|Church:Temple|Fire station:Police station|Desert:Canyon|Jungle:Forest"],
  city: ["Around Town", "Traffic light:Stop sign|Skyscraper:Apartment|Bus stop:Taxi stand|Bridge:Tunnel|Fountain:Statue|Parking lot:Garage|Sidewalk:Crosswalk|Subway:Tram|Billboard:Street sign|Food truck:Hot dog stand|Laundromat:Dry cleaner|Barber shop:Hair salon|Gas station:Car wash|Pet store:Vet|Ice cream truck:Lemonade stand|Fire hydrant:Mailbox"],
  jobs: ["Jobs", "Doctor:Nurse|Teacher:Principal|Firefighter:Police officer|Chef:Baker|Pilot:Flight attendant|Farmer:Gardener|Astronaut:Scientist|Dentist:Optometrist|Artist:Photographer|Musician:Singer|Mail carrier:Delivery driver|Lawyer:Judge|Plumber:Electrician|Mechanic:Engineer|Waiter:Bartender|Librarian:Bookseller|Actor:Magician|Hairdresser:Makeup artist|Lifeguard:Coach|Veterinarian:Zookeeper|Carpenter:Builder|Detective:Spy|Cashier:Barista|Programmer:Game designer"],
  sports: ["Sports", "Soccer:Rugby|Basketball:Volleyball|Baseball:Softball|Tennis:Badminton|Pickleball:Ping pong|Golf:Mini golf|Swimming:Diving|Skiing:Snowboarding|Ice hockey:Field hockey|Boxing:Wrestling|Bowling:Darts|Surfing:Skateboarding|Cycling:Running|Gymnastics:Cheerleading|Karate:Judo|Football:Frisbee|Archery:Fencing|Rowing:Kayaking|Figure skating:Roller skating|Rock climbing:Hiking|Horse riding:Polo|Yoga:Pilates"],
  games: ["Games & Toys", "Chess:Checkers|Puzzle:Crossword|Kite:Balloon|Yo-yo:Spinning top|Teddy bear:Doll|Toy bricks:Building blocks|Hide and seek:Tag|Jump rope:Hula hoop|Card game:Board game|Dice:Dominoes|Video game:Arcade machine|Marbles:Jacks|Puzzle cube:Fidget spinner|Trampoline:Bouncy castle|Water gun:Water balloon|Tic-tac-toe:Connect the dots|Swing:Slide|Scavenger hunt:Treasure hunt|Charades:Drawing game|Bingo:Lottery"],
  transport: ["Getting Around", "Car:Truck|Bicycle:Scooter|Airplane:Helicopter|Train:Subway|Boat:Ship|Bus:Van|Motorcycle:Moped|Rocket:Space shuttle|Hot air balloon:Blimp|Skateboard:Rollerblades|Taxi:Limousine|Canoe:Raft|Sailboat:Yacht|Tractor:Bulldozer|Ambulance:Fire truck|Cable car:Ski lift|Golf cart:Go-kart|Horse and carriage:Sleigh|Unicycle:Tricycle|Jet ski:Speedboat"],
  nature: ["Nature", "Mountain:Hill|River:Stream|Volcano:Geyser|Waterfall:Rapids|Rainbow:Sunset|Tree:Bush|Flower:Weed|Cave:Tunnel|Island:Peninsula|Glacier:Iceberg|Sand dune:Beach|Rose:Tulip|Sunflower:Daisy|Cactus:Palm tree|Pine cone:Acorn|Mushroom:Moss|Pond:Swamp|Meadow:Field|Rock:Pebble|Leaf:Branch"],
  weather: ["Weather & Sky", "Rain:Drizzle|Snow:Hail|Thunder:Lightning|Tornado:Hurricane|Fog:Mist|Sunshine:Heat wave|Cloud:Smoke|Wind:Breeze|Rainbow:Aurora|Snowman:Snow angel|Umbrella:Raincoat|Icicle:Frost|Puddle:Flood|Blizzard:Sandstorm|Moon:Sun|Star:Planet|Comet:Meteor|Eclipse:Full moon"],
  space: ["Outer Space", "Astronaut:Alien|Rocket:UFO|Moon:Mars|Telescope:Satellite|Black hole:Wormhole|Galaxy:Solar system|Space station:Moon base|Asteroid:Comet|Saturn:Jupiter|Shooting star:Fireworks|Spacesuit:Helmet|Gravity:Orbit|Robot:Rover|Constellation:Star map"],
  school: ["School", "Pencil:Pen|Eraser:Correction tape|Backpack:Lunchbox|Notebook:Textbook|Ruler:Protractor|Calculator:Abacus|Chalkboard:Whiteboard|Homework:Quiz|Recess:Lunch break|Gym class:Art class|Field trip:Assembly|Principal:Janitor|Locker:Cubby|School bus:Crossing guard|Report card:Diploma|Glue stick:Tape|Crayons:Markers|Globe:Map|Spelling bee:Science fair|Graduation:Prom"],
  clothes: ["Clothes", "T-shirt:Sweater|Jeans:Shorts|Dress:Skirt|Hat:Cap|Socks:Slippers|Sneakers:Sandals|Boots:High heels|Scarf:Gloves|Jacket:Hoodie|Pajamas:Robe|Swimsuit:Wetsuit|Tie:Bow tie|Belt:Suspenders|Sunglasses:Goggles|Raincoat:Poncho|Backpack:Purse|Watch:Bracelet|Necklace:Earrings|Crown:Tiara|Mittens:Earmuffs|Tuxedo:Suit|Apron:Overalls"],
  music: ["Music", "Guitar:Ukulele|Piano:Keyboard|Drums:Tambourine|Violin:Cello|Trumpet:Trombone|Flute:Recorder|Saxophone:Clarinet|Harp:Banjo|Microphone:Speaker|Concert:Music festival|Choir:Band|Headphones:Earbuds|Karaoke:Talent show|Lullaby:Love song|DJ:Conductor|Xylophone:Bells|Harmonica:Accordion|Dance party:Ballet"],
  holidays: ["Holidays & Parties", "Birthday:Anniversary|Halloween:Costume party|Christmas tree:Wreath|Fireworks:Sparklers|Valentine's Day:Wedding|Easter egg:Easter basket|Thanksgiving:Potluck|New Year's Eve:Countdown|Piñata:Goodie bag|Snowball fight:Pillow fight|Pumpkin carving:Gingerbread house|Present:Card|Party hat:Balloon|Parade:Carnival|Sleepover:Camping trip|Picnic:Barbecue|Graduation party:Baby shower|Santa:Elf|Jack-o'-lantern:Scarecrow|Confetti:Streamers"],
  fantasy: ["Fantasy", "Dragon:Dinosaur|Unicorn:Pegasus|Wizard:Witch|Mermaid:Siren|Ghost:Zombie|Vampire:Werewolf|Fairy:Pixie|Giant:Troll|Knight:Prince|Castle:Tower|Treasure map:Compass|Magic wand:Crystal ball|Pirate:Viking|Superhero:Villain|Robot:Cyborg|Genie:Elf|Haunted house:Graveyard|Spell book:Potion|Phoenix:Griffin|Time machine:Teleporter"],
  vacation: ["Vacation", "Suitcase:Backpack|Passport:Ticket|Hotel:Cabin|Road trip:Cruise|Sunscreen:Sunglasses|Souvenir:Postcard|Tent:Sleeping bag|Campfire:Barbecue|Map:GPS|Beach towel:Beach umbrella|Snorkel:Flippers|Sandcastle:Seashell|Theme park:Water slide|Roller coaster:Ferris wheel|Ski trip:Snow cabin|Airport security:Boarding gate|Hammock:Lounge chair|Tour guide:Travel agent"],
  hobbies: ["Hobbies", "Painting:Drawing|Knitting:Sewing|Gardening:Farming|Cooking:Baking|Fishing:Hunting|Photography:Filmmaking|Reading:Writing|Camping:Hiking|Dancing:Singing|Bird watching:Stargazing|Skateboarding:Biking|Origami:Scrapbooking|Pottery:Sculpting|Magic tricks:Juggling|Puzzles:Sudoku|Video games:Board games|Chess:Poker|Collecting stamps:Collecting coins"],
  body: ["Body", "Eye:Ear|Nose:Mouth|Hand:Foot|Finger:Toe|Elbow:Knee|Hair:Eyebrow|Tooth:Tongue|Heart:Lungs|Brain:Skull|Shoulder:Hip|Neck:Back|Thumb:Wrist|Smile:Laugh|Sneeze:Cough|Yawn:Hiccup|Freckle:Dimple"],
  tools: ["Tools", "Hammer:Mallet|Screwdriver:Wrench|Saw:Axe|Drill:Nail gun|Ladder:Step stool|Shovel:Rake|Tape measure:Ruler|Flashlight:Lantern|Paintbrush:Paint roller|Glue:Tape|Wheelbarrow:Wagon|Toolbox:Tool belt|Sandpaper:File|Pliers:Tweezers|Hose:Sprinkler|Lawn mower:Leaf blower|Padlock:Key|Rope:Chain"],
  computers: ["Computers", "Mouse:Trackpad|Keyboard:Typewriter|Floppy disk:CD|Printer:Scanner|Email:Text message|Password:PIN|Website:App|Laptop:Tablet|Webcam:Microphone|Virus:Bug|Screensaver:Wallpaper|Recycle Bin:Trash can|Download:Upload|Emoji:Sticker|Video call:Phone call|Robot:Chatbot|Wi-Fi:Bluetooth|Battery:Charger|Selfie:Photo booth|Search engine:Encyclopedia"],
  countries: ["Countries", "Japan:China|Italy:Spain|France:Belgium|Mexico:Brazil|Canada:Alaska|Egypt:Greece|Australia:New Zealand|India:Thailand|England:Ireland|Germany:Switzerland|Russia:Norway|Hawaii:Fiji|Peru:Chile|Kenya:South Africa|Iceland:Greenland|Netherlands:Denmark|Korea:Vietnam|Argentina:Colombia|Portugal:Morocco|Sweden:Finland"],
}

export const CATEGORIES = Object.fromEntries(
  Object.entries(RAW).map(([id, [name, list]]) => [id, { id, name, words: list.split("|").map((p) => p.split(":")) }])
)
export const CATEGORY_IDS = Object.keys(CATEGORIES)
export const DEFAULT_CATEGORIES = ["food", "animals", "places", "jobs", "sports", "house", "transport", "holidays"]

// Custom words: one per line, "word" or "word:close word". Returns [[word, close]]
export const parseCustom = (text) =>
  String(text || "")
    .split(/[\n,]+/)
    .map((line) => line.split(":").map((s) => s.trim().slice(0, 24)))
    .filter(([w]) => w)
    .map(([w, close]) => [w, close || ""])
