// Help topics: the Accessories (Start > Programs > Accessories), plus Media Player and
// Magnifier. Format: see ../helpCore.js.

export const books = [{ id: "accessories", title: "Accessories", order: 30 }]

export const topics = [
  // ---- Notepad ----
  {
    id: "notepad",
    book: "accessories",
    title: "Notepad",
    summary: "Write plain notes, lists and diaries, and save them on drive C:.",
    keywords: ["text files", "notes", "writing", "find and replace", "time and date", ".LOG diary", "word wrap", "fonts in Notepad"],
    programs: ["Notepad"],
    body: [
      { img: "/assets/note.png", alt: "Notepad icon" },
      "Notepad is the simplest way to write something down: a shopping list, a note to yourself, a diary. It saves plain text (no bold or pictures; for those, use [[wordpad|WordPad]]).",
      { steps: ["Open Start > Programs > Accessories > Notepad.", "Type your text.", "Choose File > Save (or press {{Ctrl+S}}).", "Type a name, pick a folder (My Documents is a good place) and choose Save."], title: "To write and save a note:" },
      { h: "Opening a note again" },
      "Choose File > Open and pick the file, or find it in [[my-computer|My Computer]] and open it there. Text files on your desktop open in Notepad too.",
      { h: "Handy things in the menus" },
      {
        list: [
          "**Edit > Time/Date** (or {{F5}}) types the current time and date where your cursor is.",
          "**Edit > Word Wrap** keeps long lines inside the window. Turn it off to scroll sideways instead.",
          "**Edit > Set Font** picks the font and size for the whole window.",
          "**Search > Find** and **Search > Replace** look for a word, or swap one word for another everywhere at once.",
          "**File > Print** ({{Ctrl+P}}) prints the text on its own, with its name on top, through your phone's or computer's print window (pick a printer, or keep it as a PDF).",
          "**File > Send To** sends your text to your phone or to another app (see [[share-phone]]).",
        ],
      },
      { tip: "Make an instant diary: type **.LOG** as the very first line and save. Every time you open that file, Notepad adds the time and date at the end, ready for a new entry." },
      "If you close Notepad with changes you haven't saved, it asks whether to save them first.",
      { keys: [["Ctrl+N", "New note"], ["Ctrl+O", "Open"], ["Ctrl+S", "Save"], ["Ctrl+F", "Find"], ["F3", "Find next"], ["Ctrl+H", "Replace"], ["F5", "Insert the time and date"], ["Ctrl+P", "Print"], ["Ctrl+Z", "Undo"]], title: "Notepad shortcuts" },
      { open: "Notepad", label: "Open Notepad" },
    ],
    related: ["wordpad", "my-computer", "share-phone", "files-in-out"],
  },

  // ---- WordPad ----
  {
    id: "wordpad",
    book: "accessories",
    title: "WordPad",
    summary: "Write letters and documents with fonts, colors, bullets, pictures and printing.",
    keywords: ["documents", "letters", "bold", "fonts", "printing", "print preview", "rich text", "pictures in documents", "bullets"],
    programs: ["WordPad"],
    body: [
      { img: "/assets/program_icons/wordpad.svg", alt: "WordPad icon" },
      "WordPad is a little word processor. Use it for letters, stories and anything that should look nice: different fonts and sizes, bold and italic, colors, bullet lists, centered text and pictures.",
      { h: "Formatting text" },
      "Select some text, then click **Aa** on the toolbar to show the format bar (font, size, bold, italic, underline, color, alignment, bullets; WordPad remembers whether you left it showing), or choose **Format > Font** for everything at once. **Format > Paragraph** sets indents and alignment for a paragraph.",
      { h: "Adding a picture or the date" },
      {
        list: [
          "**Insert > Object** puts a picture from drive C: into your document (for example one you drew in [[paint|Paint]] or took with the [[camera|Camera]]).",
          "**Insert > Date and Time** lets you choose how the date looks, then types it in.",
        ],
      },
      { h: "Saving and printing" },
      "File > Save keeps your document on drive C:. When you save, you can choose Rich Text Format (keeps all the formatting) or Text Document (plain words only). **File > Print Preview** shows the pages first, and **File > Print** prints the document on its own (no desktop around it): after the Print box, your phone's print screen (AirPrint printers) or your computer's print window opens, where you can also keep it as a PDF.",
      { note: "Pages are Letter size with 1-inch margins at the top and bottom. Your browser's print window can change the paper and margins." },
      "**File > Send To** sends the document to your phone or another app. **View** turns the toolbar, format bar, ruler and status bar on or off.",
      { phone: "On a phone the toolbar keeps New, Open, Save, Print, Find, Undo and Aa. Print Preview, Cut, Copy, Paste and Date/Time are in the File, Edit and Insert menus." },
      { keys: [["Ctrl+N", "New document"], ["Ctrl+O", "Open"], ["Ctrl+S", "Save"], ["Ctrl+P", "Print"], ["Ctrl+Z / Ctrl+Y", "Undo / Redo"], ["Ctrl+B / I / U", "Bold / Italic / Underline"], ["Ctrl+L / E / R", "Align left / center / right"], ["Ctrl+F", "Find"], ["F3", "Find next"], ["Ctrl+H", "Replace"]], title: "WordPad shortcuts" },
      { open: "WordPad", label: "Open WordPad" },
    ],
    related: ["notepad", "paint", "share-phone", "fonts"],
  },

  // ---- Paint ----
  {
    id: "paint",
    book: "accessories",
    title: "Paint",
    summary: "Draw and edit pictures with the classic tools, then save them or make them your wallpaper.",
    keywords: ["drawing", "pictures", "brush", "fill", "colors", "set as wallpaper", "mspaint", "flip and rotate", "edit a photo"],
    programs: ["Paint"],
    body: [
      { img: "/assets/program_icons/paint.svg", alt: "Paint icon" },
      "Paint is the classic drawing program. Pick a tool from the tool box on the left, pick a color from the color box at the bottom, and draw.",
      { h: "The tools" },
      {
        list: [
          "**Pencil** and **Brush** draw freehand; **Airbrush** sprays.",
          "**Line**, **Curve**, **Rectangle**, **Polygon**, **Ellipse** and **Rounded Rectangle** draw shapes. The options under the tool box choose outline, filled, or both.",
          "**Fill With Color** pours paint into an area. **Pick Color** grabs a color from your picture.",
          "**Eraser** rubs out. **Text** types words onto the picture.",
          "**Select** and **Free-Form Select** pick part of the picture to move, cut, copy or delete.",
          "**Magnifier** zooms in for tiny details.",
        ],
      },
      { computer: "The left mouse button draws in the first color; the right button draws in the second color. Click a color with the left or right button to set each one.", phone: "Draw with one finger (an Apple Pencil works too). Use two fingers to scroll around a big picture." },
      { h: "Saving and sharing" },
      "File > Save keeps the picture on drive C: as a PNG. **File > Print** ({{Ctrl+P}}) prints just the picture, as big as the page allows (sideways when it's wide), or keeps it as a PDF. **File > Set As Wallpaper** puts it on your desktop (tiled, centered or stretched), and **File > Send To** sends it to your phone or another app.",
      "The **Image** menu can flip or rotate, stretch, invert the colors, change the picture's size (Attributes) or clear it.",
      { tip: "To touch up a photo, find it in My Pictures, right-click it (or touch and hold on a phone) and choose **Edit**. Opening a picture normally shows it in [[photos|Photos]] instead." },
      { keys: [["Ctrl+N", "New picture"], ["Ctrl+O", "Open"], ["Ctrl+S", "Save"], ["Ctrl+P", "Print"], ["Ctrl+Z", "Undo"], ["Ctrl+Y", "Repeat"], ["Ctrl+A", "Select all"], ["Ctrl+R", "Flip/Rotate"], ["Ctrl+E", "Attributes (picture size)"], ["Ctrl+I", "Invert colors"], ["Ctrl+PgUp / Ctrl+PgDn", "Normal size / Large size"], ["Ctrl+G", "Show grid (when zoomed in)"]], title: "Paint shortcuts" },
      { open: "Paint", label: "Open Paint" },
    ],
    related: ["photos", "display", "wordpad", "share-phone"],
  },

  // ---- Sound Recorder ----
  {
    id: "sound-recorder",
    book: "accessories",
    title: "Sound Recorder",
    summary: "Record your voice, add echo or play it backwards, and save it as a sound file.",
    keywords: ["recording", "microphone", "voice", "echo", "reverse", "wave sound", "audio"],
    programs: ["Sound Recorder"],
    body: [
      { img: "/assets/program_icons/recorder.svg", alt: "Sound Recorder icon" },
      "Sound Recorder records from your microphone, up to 60 seconds at a time, and lets you play with the sound.",
      { steps: ["Open Start > Programs > Entertainment > Sound Recorder.", "Press the red **Record** button. The first time, your browser asks to use the microphone: allow it.", "Speak, sing or make noises.", "Press **Stop**, then **Play** to hear it.", "Choose File > Save As to keep it on drive C:."], title: "To record a sound:" },
      { h: "Fun with effects" },
      "The **Effects** menu can make the sound louder or quieter, faster or slower, add an echo, or **Reverse** it so it plays backwards. You can apply them more than once.",
      { h: "Editing" },
      {
        list: [
          "Drag the slider to a spot, then use **Edit > Delete Before Current Position** or **Delete After Current Position** to trim.",
          "**Edit > Insert File** and **Mix with File** combine another saved sound with this one.",
          "**Edit > Insert Chime** adds a little chime.",
          "**File > Revert** goes back to the last saved version.",
        ],
      },
      "**File > Send To** sends the sound to your phone or another app.",
      { note: "On an iPhone, sound only plays after you've tapped something on the page. If you hear nothing, see [[no-sound]]." },
      { open: "Sound Recorder", label: "Open Sound Recorder" },
    ],
    related: ["media-player", "no-sound", "sounds", "share-phone"],
  },

  // ---- Calculator ----
  {
    id: "calculator",
    book: "accessories",
    title: "Calculator",
    summary: "Do sums in the Standard view, or trig, powers, statistics and binary in Scientific.",
    keywords: ["math", "sums", "calc", "scientific", "hex and binary", "memory", "statistics"],
    programs: ["Calculator"],
    body: [
      { img: "/assets/program_icons/calc.svg", alt: "Calculator icon" },
      "Calculator works like a pocket calculator. Click or tap the buttons, or type numbers and symbols on your keyboard.",
      { h: "Two views" },
      {
        list: [
          "**View > Standard**: everyday sums. It works left to right, like a simple calculator: 2 + 3 * 4 = 20.",
          "**View > Scientific**: adds sine, cosine, powers, logs, factorials, parentheses and statistics. It follows math order: 2 + 3 * 4 = 14. It also counts in hex, octal and binary.",
        ],
      },
      "**View > Digit grouping** puts commas in big numbers. **Edit > Copy** and **Paste** move numbers in and out.",
      "The keys are colored by kind: numbers are light gray, the operations (÷ × − +) blue, the memory keys green, the clear keys (C, CE, ⌫) red, and **=** dark blue. The readout shows what's waiting (like 12 +) above the number, and **M** when something is in memory.",
      "The memory buttons work as always: **MS** stores the number on the screen, **MR** brings it back, **M+** adds to it and **MC** clears it.",
      { phone: "Turn your phone sideways to get the Scientific keys; turn it back for the big Standard pad." },
      { keys: [["Esc", "C (clear)"], ["Del", "CE (clear entry)"], ["Enter or =", "Equals"], ["F9", "Change sign (+/-)"], ["@", "Square root"], ["r", "1/x"], ["Ctrl+M / R / L / P", "MS / MR / MC / M+"], ["s, o, t", "sin, cos, tan (Scientific)"], ["F5 F6 F7 F8", "Hex, Dec, Oct, Bin (Scientific)"], ["Ctrl+S", "Statistics box (Scientific)"]], title: "Keyboard keys" },
      { tip: "Help > Calculator Keys inside Calculator has the full list of keys." },
      { open: "Calculator", label: "Open Calculator" },
    ],
    related: ["character-map", "notepad"],
  },

  // ---- Character Map ----
  {
    id: "character-map",
    book: "accessories",
    title: "Character Map",
    summary: "Find symbols like the copyright sign, arrows or accented letters and copy them.",
    keywords: ["symbols", "special characters", "accents", "copyright sign", "copy a symbol", "charmap", "alt codes"],
    programs: ["Character Map"],
    body: [
      { img: "/assets/program_icons/charmap.svg", alt: "Character Map icon" },
      "Character Map shows every character in a font, so you can find symbols that aren't on your keyboard: hearts, arrows, accented letters, currency signs and more.",
      { steps: ["Choose a **Font** and a **Subset** (Windows Characters, Arrows, Greek, Currency Symbols, Dingbats...).", "Press a character to see it bigger.", "Choose **Select** (or double-click it) to add it to **Characters to copy**.", "Choose **Copy**, then paste it wherever you're typing."], title: "To copy a symbol:" },
      "The status bar at the bottom shows the character's code, and for the classic Windows characters the Alt key code you can type on a Windows keyboard (like Alt+0169 for the copyright sign).",
      { open: "Character Map", label: "Open Character Map" },
    ],
    related: ["fonts", "notepad", "wordpad"],
  },

  // ---- Camera ----
  {
    id: "camera",
    book: "accessories",
    title: "Camera",
    summary: "Take photos, bursts and photo-booth strips with retro effects and frames, or record short clips.",
    keywords: ["webcam", "selfie", "photo booth", "photo strip", "effects", "frames", "self-timer", "video clips", "camera permission"],
    programs: ["Camera"],
    body: [
      { img: "/assets/program_icons/camera.svg", alt: "Camera icon" },
      "Camera uses your phone's camera or your computer's webcam. The first time, your browser asks whether 98ish may use the camera: choose **Allow**.",
      { h: "Modes" },
      {
        table: {
          head: ["Mode", "What it does"],
          rows: [
            ["Photo", "One picture."],
            ["Burst", "Five pictures in a row."],
            ["Photo Strip", "Four poses on one strip, like a mall photo booth."],
            ["Video", "A clip of up to 15 seconds, saved to your device (it's too big for drive C:)."],
          ],
        },
      },
      { h: "Effects, frames and timer" },
      "The **Effects** menu changes the look live: Sepia, Black & White, CRT Monitor, Web Safe 216, Handheld, Pixelate, VHS Tape, Fisheye, Mirror, Heat Vision, Negative and Pop Art. **Frames** adds Instant Photo, Film Strip, 98ish Window, Camcorder, Hearts, Sparkles, Party Time or Gold Frame. The timer button counts down 3 or 10 seconds before the shot.",
      { phone: "Tap the big shutter button. The button beside it (or **Options > Switch Camera**) flips between the front and back cameras.", computer: "Click the shutter button or press {{Space}} or {{Enter}}. **Options** also has Mirror Front Camera, Shutter Sound and Record Sound in Clips." },
      "The modes, the timer button and the **Effects** button are under **More options »** above the shutter; its line says the mode, timer and effect you have now. The **Mode**, **Effects**, **Frames** and **Options** menus have them all too.",
      { h: "Where your photos go" },
      "Photos are saved as JPEGs in **C:\\My Pictures**. The status bar shows how much room is left. **File > Open Last Photo** shows it in [[photos|Photos]], and **File > Send Last Photo To** sends it to your phone or another app.",
      { note: "On an iPhone, video clips record the plain camera, without effects or frames." },
      { h: "If the camera doesn't show up" },
      {
        list: [
          "**Camera access is blocked**: on iPhone, tap **aA** in Safari's address bar > Website Settings > Camera > Allow, then tap Try Again. On a computer, click the camera icon in the address bar and choose Allow.",
          "**The camera is busy**: another app or tab is using it. Close that, then try again.",
          "No camera at all? **File > Picture from Your Device** lets you pick a photo instead.",
        ],
      },
      { open: "Camera", label: "Open Camera" },
    ],
    related: ["photos", "storage", "share-phone", "file-sync"],
  },

  // ---- Photos ----
  {
    id: "photos",
    book: "accessories",
    title: "Photos",
    summary: "Look through your pictures, zoom, crop and add effects, play slideshows and share.",
    keywords: ["pictures", "viewer", "slideshow", "crop", "rotate", "zoom", "wallpaper from a photo", "upload photos", "HEIC"],
    programs: ["Photos"],
    body: [
      { img: "/assets/program_icons/photos.svg", alt: "Photos icon" },
      "Photos shows the pictures on drive C:, starting with **My Pictures**. Opening any picture anywhere in 98ish opens it here.",
      { h: "Looking at pictures" },
      { phone: "Tap a picture to open it. Swipe left or right for the next one. Pinch or double-tap to zoom.", computer: "Double-click a picture to open it. Use the arrow keys for the next one, and the mouse wheel or the + and - keys to zoom (0 fits it back on screen). Esc goes back to the thumbnails." },
      { h: "Editing" },
      "The **Edit »** button on the toolbar shows the editing buttons (zoom, rotate, crop, adjust, effects and Undo), and Photos remembers whether you left them showing. The **Edit** menu has them too: **Rotate Left** or **Right**, **Crop** (free, square, 4:3, 3:4 or 16:9), adjust **Brightness/Contrast**, and add **Effects and Frames** like the ones in [[camera|Camera]]. **Undo** steps back. Nothing changes on the drive until you choose **File > Save** (replace the picture) or **Save As Copy** (keep the original). **Revert** throws your changes away.",
      { h: "Slideshows" },
      "Choose **View > Slideshow** (or press {{F5}}) to show the pictures full screen. You can pick a transition (Fade, Slide, Zoom, Wipe, Iris or Random), the motion (**Ken Burns** pans and zooms slowly across each picture, **Drift** zooms a little, **Still** doesn't move), a speed, and **music**: three tunes made for 98ish (Sunny Day, Daydream, Road Trip) or one of your own sounds from drive C:. Space pauses; Esc ends it.",
      { h: "Shared Albums and Memories" },
      "The **Albums** button opens [[shared-albums|Shared Albums]]: albums you share with buddies, where everyone adds photos and videos, likes and comments. A red number on it means something new. **Share > Add to Shared Album...** sends the picture you're looking at.",
      "When there's a memory to show, a **Memories** card sits above your pictures: photos from today's date in other years, and trips and days out. See [[memories]].",
      { h: "Sharing" },
      {
        list: [
          "**Share > Set as Wallpaper** puts the picture on your desktop.",
          "**Open in Paint** to draw on it, **Use in Photo Puzzle** to turn it into a jigsaw.",
          "**Send by 98ish Mail** or **Send to Network Neighborhood**.",
          "**Send to My Phone** or **Download to Your Device** to save it on your real phone or computer.",
        ],
      },
      { h: "Bringing photos in" },
      "**File > Upload from Your Device** adds pictures from your phone or computer to the folder you're in.",
      { tip: "iPhone photos are sometimes in a format called HEIC that some browsers can't open. Picking them from your Photos library in Safari usually turns them into JPEGs on the way. Or on the iPhone set Settings > Camera > Formats to **Most Compatible**." },
      "**File > Delete** sends a picture to the [[recycle-bin|Recycle Bin]].",
      { open: "Photos", label: "Open Photos" },
    ],
    related: ["shared-albums", "memories", "camera", "paint", "photo-puzzle", "files-in-out", "storage", "display"],
  },
  {
    id: "shared-albums",
    book: "accessories",
    title: "Shared Albums",
    summary: "Albums you share with buddies: everyone adds photos and videos, likes and comments.",
    keywords: ["shared album", "share photos", "photo album", "family album", "couple album", "invite to album", "likes", "comments on photos", "upload video", "albums"],
    body: [
      "A shared album is a place for you and a few buddies (your partner, family, friends) to put photos and short videos from a trip, a party or just your week. Everyone in the album can add to it, like and comment, and sees who added what. You need to be signed on to 98 Messenger.",
      {
        steps: [
          "In Photos, click **Albums** on the toolbar (or **View > Shared Albums**).",
          "Click **New Album** and give it a name.",
          "Click **People** and invite buddies by screen name (your Buddy List is suggested).",
          "Click **Add** to add pictures from My Pictures or from your phone or computer (photos and videos).",
        ],
        title: "To start an album:",
      },
      { h: "Adding photos from anywhere" },
      {
        list: [
          "In Photos: **Share > Add to Shared Album...** on any picture.",
          "In [[camera|Camera]]: **File > Send Last Photo To > Shared Album...**, or **Add to Shared Album...** on a video clip (up to a minute).",
          "Things shared to 98ish from other apps: **Add to a Shared Album...** in Received Items.",
          "In [[memories|Memories]]: **Share as Album...** makes an album from a memory.",
        ],
      },
      "Photos are sent at up to 2048 pixels (redrawn, which also leaves out the photo's hidden location and camera details). Videos go exactly as they are: MP4, MOV or WebM, up to a minute and 12 MB. If you're offline, or 98ish's free online storage is resting, they wait on your device (\"waiting to upload\") and go up by themselves later. **Details...** shows what's waiting, and lets you retry or remove one that couldn't be added.",
      { h: "Likes, comments and news" },
      "Open a photo to see who added it, **Like** it and add comments. When a buddy adds photos or comments, the album says **New**, the **Albums** button shows a red number, the [[notifications|Notification Center]] lists it, and (with notifications on) your phone gets a notification, which [[do-not-disturb|Do Not Disturb]] holds back like any other.",
      { h: "Leaving and deleting" },
      "Under **More options** in an album: **Leave Album** (what you added stays for the others; if you started it, it passes to the next person) or, if you started it, **Rename** and **Delete Album** (everything in it goes, for everyone). Whoever added a photo, or started the album, can **Remove** it. The person who started it can remove people under **People**.",
      { h: "Privacy" },
      "Only the people in an album can see what's in it. Photos are kept in private online storage (Vercel Blob) under scrambled names; 98ish hands a member a link to a photo that works for 5 minutes, so anyone that member passed the link to in those minutes could open it too. Leaving or being removed ends your access at once, but photos your devices already saved stay on them, and anyone can save a copy of what they can see. Share albums with people you trust. Each screen name can add up to 40 MB to shared albums. See [[privacy-server]].",
      { open: "Photos", label: "Open Photos" },
    ],
    related: ["photos", "memories", "camera", "privacy-server", "notifications"],
  },
  {
    id: "memories",
    book: "accessories",
    title: "Memories",
    summary: "On this day, trips and days out: your photos gathered into slideshows with music.",
    keywords: ["memories", "on this day", "trips", "photo slideshow with music", "ken burns", "years ago", "throwback"],
    body: [
      "Memories looks through the pictures on drive C: and gathers:",
      { list: ["**On this day**: pictures from today's date in earlier years.", "**Trips and days out**: pictures taken close together, over several days or lots in one day."] },
      "Click **Play** for a slideshow with a title card, slow Ken Burns pan-and-zoom and music, or **Share as Album...** to put a memory in a [[shared-albums|shared album]] with buddies.",
      "Memories go by when each picture was taken: the date saved in the photo by your phone's camera when you upload it, the date in names like IMG_20240305, or else when the file was made.",
      { h: "Settings" },
      "Under **More options** in Memories: the slideshow's music and motion, and **Tell me about \"On this day\" memories each morning**, which puts a note in the Notification Center once a day when there are some (off unless you turn it on; it all happens on this device).",
      { open: "Photos", label: "Open Photos" },
    ],
    related: ["photos", "shared-albums", "camera"],
  },

  // ---- Address Book ----
  {
    id: "address-book",
    book: "accessories",
    title: "Address Book",
    summary: "Keep everyone you know: screen names, phones, e-mail, birthdays and pictures.",
    keywords: ["contacts", "people", "phone numbers", "birthdays", "vCard", "import contacts", "groups", "favorites", "wab"],
    programs: ["Address Book"],
    body: [
      { img: "/assets/program_icons/addressbook.svg", alt: "Address Book icon" },
      "The Address Book holds a card for each person: their name and picture, 98 Messenger screen name, 98ish Mail address, phone numbers, e-mail, address, birthday, anniversary and notes.",
      { steps: ["Open Start > Programs > Accessories > Address Book.", "Choose **File > New Contact** (**+ New** on a phone).", "Type their name, phone and e-mail, and choose OK."], title: "To add someone:" },
      "A nickname, company, screen name, 98ish Mail address and Favorite are under **More options »** on the Name tab. More phone numbers and e-mail addresses, the home address, birthday, groups and notes are on the other tabs.",
      { h: "What a card can do" },
      "Open a card to **Send IM**, **Call** them on 98 Messenger or **Send Mail**. **More »** has **Video Call**, **Invite to Calendar**, Favorite and Delete. A colored dot shows whether they're on 98 Messenger right now (green means on).",
      {
        list: [
          "**Favorites** and **groups** (File > New Group) help sort people. Pick a folder on the left to see just those.",
          "Your 98 Messenger buddies show up in **98 Messenger Buddies**, ready to add.",
          "Give someone a **birthday** and it appears every year on Calendar's **Birthdays** calendar, with a reminder that morning.",
          "Type in the search box (Edit > Find People) to find someone fast.",
        ],
      },
      { h: "Bringing contacts from your phone" },
      { steps: ["In the iPhone Contacts app, tap a person.", "Tap **Share Contact**, then **Save to Files**.", "In the Address Book choose **File > Import vCard from this Device** and pick the file."], title: "On an iPhone:" },
      { tip: "To bring lots of people at once on an iPhone (iOS 16 or later): in Contacts tap Lists, touch and hold a list and choose Export. On Android, **File > Import from Phone Contacts** can pick contacts directly in Chrome." },
      "**File > Export All** saves everyone as a .vcf file you can open on your phone or in another address book.",
      { h: "Sync" },
      "While you're signed on to 98 Messenger, your contacts are saved with your account, so they follow you to your other devices. **View > Sync Now** syncs right away.",
      { open: "Address Book", label: "Open Address Book" },
    ],
    related: ["messenger", "mail", "calendar", "search", "messenger-calls"],
  },

  // ---- Notes ----
  {
    id: "notes",
    book: "accessories",
    title: "Notes (sticky notes)",
    summary: "Jot sticky notes with checklists, pin them to the desktop, and find them from the Start menu.",
    keywords: ["sticky notes", "stickies", "post-it", "notes", "checklist", "lists", "grocery list", "pin to desktop", "recycle bin for notes", "note colors"],
    programs: ["Notes"],
    body: [
      { img: "/assets/program_icons/notes.svg", alt: "Notes icon" },
      "Notes are little sticky notes: a title, some words, and a checklist if you want one. They save as you type.",
      { steps: ["Open Start > Programs > Accessories > Notes (or the Notes icon on the desktop).", "Choose **New note**.", "Type a title and your words. Choose **+ Add a checklist** for a list you can tick off."], title: "To write a note:" },
      { h: "Checklists" },
      {
        list: [
          "Tick an item's box when it's done. Press {{Enter}} in an item to add the next one; {{Backspace}} in an empty item removes it.",
          "Drag the dotted grip on the left of an item to move it (with a mouse or a finger). From the keyboard: {{Alt+Up}} and {{Alt+Down}}.",
          "**More options »** under the note has **Move checked to bottom**, **Uncheck all** and **Remove checked**, the note's **color**, **Pin to desktop**, **Share** and **Delete**.",
        ],
      },
      { h: "On the desktop" },
      "Right-click a note (or touch and hold it) and choose **Pin to Desktop**. On a computer it becomes a sticky note on your wallpaper: drag it by its top strip, resize it from a corner, type in it and tick its list right there. Double-click the strip to open it in Notes; the × unpins it.",
      { phone: "On a phone, pinned notes wait in the small **Notes** button in the bottom corner of the desktop. Tap it to see them, and tap one to open it." },
      { h: "Finding and sorting" },
      "Type in the search box at the top of Notes, or in the Start menu's search box (notes show under **Notes**). **View > Sort By** sorts by the date changed, pinned first, or color.",
      { h: "Deleting" },
      "Deleted notes go to **View > Recycle Bin** for 30 days, where **Restore** brings them back. After 30 days (or **Delete Now**, or **Empty Recycle Bin**) they're gone for good.",
      { h: "Where notes are kept" },
      "Without an account, notes are kept **only on this device** (Notes says so). Sign on to 98 Messenger and they're saved with your screen name too, so they follow you to your other devices and you can share them (see [[notes-sharing]]). Notes made while signed off go up the next time you sign on.",
      { tip: "Pinned notes are pinned on this device only, so your phone and your computer can each pin different notes." },
      { open: "Notes", label: "Open Notes" },
    ],
    related: ["notes-sharing", "tasks", "notepad", "search"],
  },
  {
    id: "notes-sharing",
    book: "accessories",
    title: "Sharing a note with a buddy",
    summary: "Make a grocery list or date ideas you both edit, live.",
    keywords: ["shared note", "share a note", "shared list", "grocery list together", "date ideas", "our notes", "stop sharing", "leave a note"],
    body: [
      "A shared note belongs to everyone in it: you all see the same note and can change it, and changes show up for everyone right away. You need to be signed on to [[messenger|98 Messenger]].",
      { steps: ["Open the note and choose **Share...** at the top.", "Type your buddy's screen name (your buddies are suggested) and choose **Share**.", "They get a notification, and the note appears in their Notes, marked **Shared with** you."], title: "To share a note:" },
      {
        list: [
          "Each checklist item is kept on its own, so if you tick \"milk\" while your partner adds \"eggs\", both changes stay. If two people change the very same thing, the newest change wins.",
          "**View > Shared Notes** shows only shared notes.",
          "Couples: **Us > Our Notes** (or View > Us in Notes) lists the notes you share with your partner, and a new note there is shared with them right away.",
          "When a buddy changes a shared note, the Notification Center says so (and your phone too, with notifications on: see [[notifications]]).",
        ],
      },
      { h: "Stopping" },
      "The person who shared a note can **Remove** someone or **Stop sharing** in the Share window. Anyone else can **Leave**. Whoever is taken out keeps their own copy of the note. Deleting a shared note just takes you out of it (your copy goes to the Recycle Bin); the others keep it.",
      { open: "Notes", label: "Open Notes" },
    ],
    related: ["notes", "us-pairing", "messenger", "notifications"],
  },

  // ---- Tasks ----
  {
    id: "tasks",
    book: "accessories",
    title: "Tasks (to-do list)",
    summary: "A to-do list with due dates, priorities, reminders and repeats, shown in Calendar too.",
    keywords: ["tasks", "to-do", "todo list", "chores", "due date", "priority", "task reminders", "repeating tasks", "outlook tasks", "someday"],
    programs: ["Tasks"],
    body: [
      { img: "/assets/program_icons/tasks.svg", alt: "Tasks icon" },
      "Tasks opens to **Today**: what's due today, and anything overdue (in red).",
      { steps: ["Open Start > Programs > Accessories > Tasks.", "Type in the **Add a task** box and press {{Enter}}. It's due today (from the Upcoming tab, tomorrow; from Someday, no date)."], title: "To add a task:" },
      "**More options »** under the box has the rest: a due **date** and **time**, **priority** (High shows a red !), a **reminder**, a **repeat** (every day, weekday, week, month or year), which **list** it goes on, who it's **for**, and **notes**.",
      { h: "The tabs" },
      { table: { head: ["Tab", "Shows"], rows: [["Today", "Due today or overdue"], ["Upcoming", "Due after today"], ["Someday", "No due date, plus Calendar's memo lists"], ["Done", "What you've ticked lately"]] } },
      "Tick a task's box when it's done. A repeating task then shows its next time. Click a task to change it; right-click it (or touch and hold) for **Due Tomorrow**, **Priority** and **Show in Calendar**.",
      { h: "Tasks and Calendar" },
      "A task is a **to-do in Calendar**, so it shows on the calendar on its due day, and a Calendar event marked To-do shows here. The **list** is the calendar it's in: **On this device**, **My Calendar**, the couple's **Us** calendar, or a shared group calendar, where everyone in it sees the task and can tick it off.",
      { note: "Reminders work like Calendar's: a Reminder window while 98ish is open, and on your phone with notifications on (for lists on 98ish, not \"On this device\"). See [[calendar]] and [[notifications]]." },
      { open: "Tasks", label: "Open Tasks" },
    ],
    related: ["calendar", "calendar-sharing", "notes", "notifications"],
  },

  // ---- Calendar ----
  {
    id: "calendar",
    book: "accessories",
    title: "Calendar",
    summary: "Plan events with repeats and reminders in month, week, day and list views, plus memos.",
    keywords: ["events", "appointments", "reminders", "schedule", "repeating events", "memos", "birthdays calendar", "agenda"],
    programs: ["Calendar"],
    body: [
      { img: "/assets/program_icons/calendar.svg", alt: "Calendar icon" },
      "Calendar keeps your plans: dates, appointments, trips and birthdays. It also has **memos**, notes with checklists that don't need a date.",
      { steps: ["Open Start > Programs > Accessories > Calendar.", "Choose **File > New Event** (or tap a day, then the add button).", "Type a title and pick the day and the time.", "Save. That's all most events need."], title: "To add an event:" },
      "Everything else is under **More options »** at the bottom of the event, with a line that says what's set now (like \"On this device · Doesn't repeat · Reminder 15 minutes before · Auto color\"): which **calendar** it goes on, **All day**, an end on another day, a **repeat** (every day, weekday, week, month, year, or Custom), **reminders**, a **color**, the **place**, **notes**, a **checklist**, whether it's a **to-do**, and who's going. Calendar remembers whether you left More options open (see [[more-options]]).",
      { h: "Views" },
      "The **View** menu switches between **Month**, **Week**, **Day**, **List** (what's coming up) and **Memos**. **Go to Today** jumps back to now.",
      { phone: "Swipe the month or week sideways to move to the next one. Tap a day to see its events below.", computer: "Click a day to select it; double-click an empty day or hour to add an event there." },
      { h: "Your calendars" },
      {
        list: [
          "**On this device** works for anyone, even without signing on. It's kept only in this browser.",
          "**My Calendar** is yours on 98ish once you sign on to 98 Messenger, and follows you to any device.",
          "**Us** appears for couples who've paired up (see [[us-pairing]]).",
          "**Group calendars** are shared with family or friends (see [[calendar-sharing]]).",
          "**Birthdays** fills itself from birthdays in your [[address-book|Address Book]].",
        ],
      },
      { h: "Reminders" },
      "When a reminder is due, a Reminder window pops up with a chime. Choose **Dismiss**, or **Snooze** to be reminded again later.",
      { note: "Reminders from calendars on 98ish can reach your phone even when 98ish is closed, if you've turned on notifications (see [[notifications]]). **On this device** calendars only remind you while 98ish is open." },
      { tip: "On the taskbar, right-click the clock (or touch and hold it) to open Calendar or Clock." },
      { open: "Calendar", label: "Open Calendar" },
    ],
    related: ["calendar-sharing", "calendar-phone", "clock", "notifications", "address-book"],
  },

  {
    id: "calendar-sharing",
    book: "accessories",
    title: "Sharing a calendar",
    summary: "Make a group calendar and invite family or friends by screen name or an 8-letter code.",
    keywords: ["shared calendar", "group calendar", "invite code", "join a calendar", "comments on events", "family calendar", "activity"],
    body: [
      "A group calendar is shared live with the people you invite: everyone sees the same events, and changes show up for everybody right away. You need to be signed on to [[messenger|98 Messenger]], because shared calendars belong to your screen name.",
      { steps: ["In Calendar choose **File > New Calendar**.", "Give it a name and a color, and choose Create.", "In its Properties, on the **People** tab, type someone's 98 Messenger screen name and choose **Invite**.", "Or share the **invite code** (like K7QX-M2PA) or **Copy invite link** and send it to them."], title: "To start a shared calendar:" },
      { steps: ["Open Calendar and choose **File > Join a Calendar**.", "Type the 8-letter code and choose **Join**."], title: "To join with a code:" },
      "Invitations sent to your screen name show up in Calendar, where you can choose **Join** or **No thanks**.",
      { h: "Living together on a calendar" },
      {
        list: [
          "Each person has their own color, so you can tell who added what. Change yours on the People tab.",
          "Open an event to leave **Comments** about it.",
          "The **Activity** tab shows what everyone has added, changed or removed.",
          "**Labels** lets you name the colors (like \"Work\" or \"Date night\").",
        ],
      },
      "The owner can make a **New code** (the old one stops working), remove people, or delete the calendar. Anyone can **Leave**.",
      { note: "Couples already have a shared **Us** calendar once they've paired, just for the two of them. Use a group calendar for family and friends." },
      { open: "Calendar", label: "Open Calendar" },
    ],
    related: ["calendar", "calendar-phone", "us-pairing", "messenger-accounts"],
  },

  {
    id: "calendar-phone",
    book: "accessories",
    title: "Calendar on your iPhone's Calendar app",
    summary: "Subscribe to a 98ish calendar in your phone's own Calendar app, or add one event.",
    keywords: ["subscribe", "webcal", "iPhone calendar", "Google Calendar", "ics file", "add to my phone", "Remove Alerts"],
    body: [
      "You can see a 98ish calendar inside your phone's own Calendar app. Then your phone reminds you about events even when 98ish is closed.",
      { steps: ["In Calendar choose **Calendar > (the calendar's name) Properties**.", "Open the **Phone** tab and choose **Get my subscription link**.", "On your iPhone, tap **Subscribe on this phone** and confirm with Subscribe.", "Check that **Remove Alerts** is turned **off** for the subscription, so your phone keeps the reminders."], title: "To subscribe on an iPhone:" },
      { steps: ["Choose **Copy link** on the Phone tab.", "On the iPhone open **Settings > Apps > Calendar > Calendar Accounts > Add Account > Other > Add Subscribed Calendar**.", "Paste the link and tap Next, then Save."], title: "Or add it by hand:" },
      "For Google Calendar, use **Other calendars > From URL** and paste the same link.",
      { note: "The link is private to you: anyone who has it can see that calendar. If it got out, choose **New link** and the old one stops working. Phones check for changes every hour or so, and changes made in the phone's Calendar app don't come back to 98ish." },
      { h: "Just one event" },
      "Open an event and choose **Add to my phone**. It downloads a small calendar file; open it to add that event to your phone's calendar. **Share...** sends the event to another app.",
      { tip: "The **On this device** calendar can't be subscribed to, because it lives only in this browser. Its Phone tab offers a download instead, or sign on and upload its events to a calendar on 98ish." },
    ],
    related: ["calendar", "calendar-sharing", "push-setup", "home-screen"],
  },

  // ---- Maps 98 ----
  {
    id: "maps",
    book: "accessories",
    title: "Maps 98",
    summary: "Find a place, see where you are, and get directions to drive, walk or bike, or hand off to Apple Maps.",
    keywords: ["map", "maps", "directions", "navigation", "route", "address", "where am I", "GPS", "turn by turn", "Apple Maps", "Google Maps", "drop a pin", "walk", "bike", "drive"],
    programs: ["Maps 98"],
    body: [
      { img: "/assets/program_icons/maps.svg", alt: "Maps 98 icon" },
      "Maps 98 finds places and shows you how to get there.",
      {
        steps: [
          "Type a place or an address in the box at the top (a few letters are enough; press **Search** for more). Pick one from the list, or one of the numbered squares on the map.",
          "Press **Directions**. Choose **Drive**, **Walk** or **Bike**: you see how long it takes, how far it is, and every turn written out (**steps**).",
          "Press **Start** to follow along: your blue dot moves and the next turn shows at the top of the card.",
        ],
        title: "To get directions:",
      },
      {
        list: [
          "**◎** (beside Search) shows where you are. The first time, your browser asks if 98ish may know your location.",
          "Touch and hold the map (or right-click it) to drop a pin anywhere and get directions there.",
          "No location? Directions asks where you're starting: type an address.",
          "Your recent places show when the search box is empty.",
          "Other programs open Maps 98 straight into directions: **Directions** on a buddy in [[buddy-locator|Buddy Locator]], on a court in Pickleball 98's Real Games and its **where & when** list, and on a **Meet me at** card in [[messenger-history|98 Messenger]].",
        ],
      },
      { phone: "For spoken turn-by-turn directions with the screen off, press **Open in Apple Maps**: the same place opens in the iPhone's Maps app.", computer: "On a Mac or iPhone the button says **Open in Apple Maps**; elsewhere it opens Google Maps." },
      { note: "Search comes from Photon (by komoot) and Nominatim, directions from Valhalla on FOSSGIS's servers, and the map from OpenFreeMap, all free services built on OpenStreetMap. What you search for and the two ends of a route go to them; your location only goes to the directions service when you ask for directions from where you are. Maps 98 keeps your recent places on this device only." },
      { open: "Maps 98", label: "Open Maps 98" },
    ],
    related: ["buddy-locator", "weather", "privacy-third-parties"],
  },

  // ---- Clock ----
  {
    id: "clock",
    book: "accessories",
    title: "Clock",
    summary: "World clocks, alarms, a timer and a stopwatch.",
    keywords: ["alarm", "timer", "stopwatch", "world clock", "time zones", "snooze", "alarm sound", "ringtone", "wake up"],
    programs: ["Clock"],
    body: [
      { img: "/assets/program_icons/clock.svg", alt: "Clock icon" },
      "Clock has four tabs:",
      {
        list: [
          "**World Clock**: add cities to see what time it is for faraway friends.",
          "**Alarm**: set a time and click **Add alarm**. **More options »** adds a label, the days it repeats (weekdays unless you change them) and its **sound**: Bedside Beeper, Sunrise Chimes, Old Brass Bell or 8-Bit Wake Up (press **▶ Play** to hear one). It starts a little softer and rings until you press **Stop** or **Snooze** (9 more minutes). Tick or untick the box next to an alarm to turn it on or off.",
          "**Timer**: pick a quick time (1 minute up to 1 hour) or set hours, minutes and seconds. You can pause it. Its sound is under **More options »**.",
          "**Stopwatch**: start, stop, take laps and reset.",
        ],
      },
      { note: "Alarms and the timer keep going when the Clock window is closed. With 98ish closed or in the background (a phone puts pages to sleep), they can't play a sound, so 98ish sends a **notification** instead, if you're signed on to 98 Messenger and turned notifications on ([[push-setup]]). Do Not Disturb never stops your own alarms." },
      { phone: "On an iPhone, alarms ring through the silent switch while 98ish is open. Tap the screen once after opening 98ish so the iPhone lets it play sound." },
      "Times show in 12-hour or 24-hour style, whichever you chose in [[regional|Regional Settings]].",
      { tip: "On the taskbar, right-click the clock (or touch and hold it) to open Clock or Calendar." },
      { open: "Clock", label: "Open Clock" },
    ],
    related: ["calendar", "date-time", "regional"],
  },

  // ---- Weather ----
  {
    id: "weather",
    book: "accessories",
    title: "Weather",
    summary: "The weather now, the next 24 hours and 7 days for your places, in the taskbar and on the desktop too.",
    keywords: ["weather", "forecast", "temperature", "rain", "snow", "humidity", "wind", "uv index", "sunrise", "sunset", "fahrenheit", "celsius", "my location", "places", "open-meteo"],
    programs: ["Weather"],
    body: [
      { img: "/assets/program_icons/weather.svg", alt: "Weather icon" },
      "Weather shows what it's like outside right now (the temperature, what it feels like, wind, humidity, the UV index, the chance of rain, sunrise and sunset), then the next 24 hours and the next 7 days.",
      { steps: ["Open Start > Programs > Accessories > **Weather**.", "Type your city or town and click **Search**.", "Choose it from the list."], title: "To see your weather:" },
      "Or click **Use My Location**: your browser asks first, and 98ish keeps only the place's position rounded to about a kilometer, never where you are exactly.",
      { h: "More than one place" },
      "Add as many places as you like with the **+** button (or Places > Add Place...): your city and your sweetheart's, where your family lives, where you're going on vacation. Switch between them with the drop-down at the top. **Places > Remove** takes one away.",
      { h: "Degrees F or C" },
      "The **°F** and **°C** buttons switch the units (so do View > Fahrenheit and View > Celsius). The choice is saved in [[regional|Regional Settings]], which also picks the starting unit for your region: °F in the United States, °C almost everywhere else. Wind is in miles per hour with °F and kilometers per hour with °C. Times follow your 12- or 24-hour choice.",
      { h: "In the taskbar and on the desktop" },
      {
        list: [
          "**View > Show in Taskbar** puts the weather icon and the temperature next to the clock (on a phone, just the icon). Click it to open Weather; right-click it to refresh or hide it. Taskbar Properties has the same switch (**Show weather**).",
          "**View > Show on Desktop** adds a small weather panel to your desktop with today and the next three days. Drag it by its title bar; its **X** takes it away.",
        ],
      },
      { h: "Offline and up to date" },
      "Weather keeps each forecast for 30 minutes before fetching a new one, and refreshes by itself while it's open. Press {{F5}} (or File > Refresh) to get the newest one now. With no Internet connection you still see the last forecast, and the status bar says when it's from.",
      { note: "Forecasts come from **Open-Meteo.com**, a free weather service with open data (CC BY 4.0). Your browser asks it directly; 98ish doesn't send your places anywhere else. Severe weather alerts aren't included, since there's no free source for them everywhere: check your local weather service for warnings." },
      { open: "Weather", label: "Open Weather" },
    ],
    related: ["regional", "clock", "calendar", "taskbar"],
  },

  // ---- Media Player ----
  {
    id: "media-player",
    book: "accessories",
    title: "Media Player",
    summary: "Your music and videos in one library: play them, pick up a video where you stopped, make playlists.",
    keywords: ["music", "songs", "video", "videos", "movie", "movies", "mp3", "mp4", "mov", "recordings", "playlist", "shuffle", "mplayer", "MIDI", "resume", "continue watching", "my videos", "picture in picture", "library"],
    programs: ["Media Player"],
    body: [
      { img: "/assets/program_icons/mediaplayer.svg", alt: "Media Player icon" },
      "Media Player is the library for **your own music and videos**. Pick **Music** or **Videos** above the list, then tap something to play it.",
      {
        list: [
          "**Music**: the songs in your [[music-98]] library and the recordings you made in [[sound-recorder]]. **Add Songs...** brings songs in from your phone or computer.",
          "**Videos**: your video files (MP4, MOV, WebM), each with a picture from the video and its length. **Add Videos...** brings them in; they're kept in **C:\\My Videos** exactly as they are. A video you stopped part way **picks up where you left off** next time (a red line under it shows how far you got; **Start Over** on the screen, or **Play from Start** in its **…** menu, begins again).",
          "Each row's **…** button (or right-click) has **Play**, **Add to Playlist** (a new one or one you made in Music 98: playlists can hold songs and videos) and **Show in My Computer**.",
        ],
      },
      "Press Play (it turns into Pause while something plays), Previous or Next. **More »** beside them shows Stop, **Shuffle**, **Repeat**, Mute and the volume, **Search** (by title, artist, album or file name), **Playlist** (play just one of your playlists) and, for a video, **Picture in Picture**. A video plays in the black screen at the top.",
      "**File > Open from Your Device...** plays a song or video once without keeping it: it plays from memory, isn't copied to the drive or sent anywhere, and leaves the list when you close Media Player.",
      { phone: "The lock screen and Control Center show what's playing with play/pause and skip. Songs keep playing with the screen locked; iPhone pauses a video when you leave Safari or lock the phone, unless you start **Picture in Picture** first.", computer: "Media keys on your keyboard (play/pause, next, previous) work while 98ish is open." },
      { note: "Songs and videos are kept as they came (no cutting or converting). Up to 8 MB each they're ordinary files that can sync; bigger ones (videos up to 2 GB, songs up to 300 MB) stay **on this device only**: they don't sync and aren't in backups, and the bottom of Media Player says so. See [[files-in-out]]." },
      { keys: [["Space", "Play or pause"], ["Left / Right arrow", "Back or forward 5 seconds"], ["Up / Down arrow", "Volume up or down"]], title: "Keys" },
      "The speaker by the taskbar clock sets the volume for every sound in 98ish, Media Player included.",
      { note: "On an iPhone, check the ringer switch and tap the page once if nothing plays. See [[no-sound]]. The 8 built-in tunes Media Player used to have are gone; untouched copies were removed from My Music." },
      { open: "Media Player", label: "Open Media Player" },
    ],
    related: ["music-98", "sound-recorder", "no-sound", "sounds", "files-in-out"],
  },
  // ---- PDF Viewer ----
  {
    id: "pdf-viewer",
    book: "accessories",
    title: "PDF Viewer",
    summary: "Read the PDFs on drive C:, page by page, and send them to your phone's apps.",
    keywords: ["pdf", "pdf viewer", "acrobat", "reader", "document", "manual", "ticket", "boarding pass", "menu", "open pdf", "zoom", "print pdf"],
    programs: ["PDF Viewer"],
    body: [
      { img: "/assets/program_icons/pdfviewer.svg", alt: "PDF Viewer icon" },
      "PDF Viewer shows a **PDF** from drive C: page by page. Open a PDF in My Computer (or anywhere on the desktop) and it opens here. Scroll to read; the top says which page you're on.",
      "PDFs come in **as they are** with **Upload from Phone...** (My Computer or the desktop), by dragging one onto My Computer, or from Compass's downloads. They land where you put them (Compass: C:\\Downloads).",
      {
        list: [
          "**Send to My Phone** hands the PDF to your phone: open it in Books or Files, AirDrop it, or print it.",
          "**More »**: zoom out, **Fit**, zoom in, **Open in Browser** (your browser's own viewer) and **Download**.",
        ],
      },
      { note: "The page viewer is pdf.js (made by Mozilla), downloaded from jsDelivr the first time you open a PDF; your PDF itself never leaves the device. Offline before that, PDF Viewer shows your browser's own viewer instead (on an iPhone that may show only the first page: use Send to My Phone). A PDF with a password can't be shown here." },
      { note: "PDFs up to 8 MB are ordinary files that can sync; bigger ones (up to 200 MB) stay on this device only. See [[files-in-out]]." },
      { open: "PDF Viewer", label: "Open PDF Viewer" },
    ],
    related: ["files-in-out", "share-phone", "my-computer"],
  },
  // ---- Visual Basic 98 ----
  {
    id: "visual-basic-98",
    book: "accessories",
    title: "Visual Basic 98",
    summary: "Make your own programs and games (draw a form, add code or blocks) and send them to friends in 98 Messenger.",
    keywords: ["visual basic", "vb", "vb6", "vb98", "programming", "code", "coding", "make a program", "make a game", "app builder", "blocks", "blockly", "form", "toolbox", "properties", "button", "label", "timer", "sprite", "poll", "quiz", "tic-tac-toe", "send a program", "shared", ".vb98"],
    programs: ["Visual Basic 98"],
    body: [
      { img: "/assets/program_icons/vb98.svg", alt: "Visual Basic 98 icon" },
      "Visual Basic 98 makes **your own programs**: draw a window (the **form**), put buttons, labels, text boxes and pictures on it, tell them what to do, and press **Run**. Start with **Templates...**: Hello, Poll, Quiz, Tic-Tac-Toe, Reaction Time, Magic 8-Ball, Soundboard, Countdown and Star Jumper (a tiny platform game).",
      {
        list: [
          "**Form** tab: tap a tool in the **Toolbox** to add it (or drag it onto the form). Drag a control to move it, its blue corner to size it. The **Properties** (on a phone, its own tab) change its words, colors and size.",
          "**Code** tab: pick a control and an event (Click, Change, Timer...) and type what happens, like **Label1.Caption = \"Hi!\"**. Mistakes are pointed out as you type, with the line.",
          "**Blocks** tab: snap blocks together instead of typing (When Command1 Click, set Label1.Caption to...). The blocks write the code for you.",
          "**Run** (F5) opens your program in its own window. **■ End** stops it.",
          "**File > Save** keeps it in C:\\Documents as a .vb98 file; double-click one to run it. **Make Desktop Icon** puts it on your desktop.",
        ],
      },
      { h: "Send it to friends" },
      "**Send...** puts your program in a 98 Messenger conversation (a buddy, a chat room you're in, or everyone in **Come Over**). They tap **Open** and it runs on their 98ish. Programs can keep **Shared** values that everyone sees change: votes in a poll, a Tic-Tac-Toe board, best times. **File > Shared with Me** lists programs friends sent you.",
      { h: "The language" },
      "A friendly slice of Visual Basic 6: **Dim**, **If...Then...Else**, **For...Next**, **Do...Loop**, **Select Case**, **Sub** and **Function**, **&** to join text. Handy extras: **MsgBox**, **InputBox**, **Random(1, 6)**, **Wait 500**, **Sound.Play \"tada\"**, **Me.Name**, **Friends**, **Shared(\"score\") = 3**, and **Sub Shared_Changed(Key As String)** that runs when anyone changes a Shared value. Sprites move with **Sprite1.Move 10, 0** and bump with **Sprite1.Touching(Sprite2)**.",
      { note: "Programs run boxed in: they can't open your files, read your messages, use the internet or change anything else on 98ish. One that gets stuck in an endless loop is stopped after a couple of seconds." },
      { h: "Limits" },
      "A program can be up to 256 KB (pictures are shrunk to fit). Shared values: 64 KB per shared program and 200 changes a day per person. A shared program nobody uses for 30 days is deleted.",
      { open: "Visual Basic 98", label: "Open Visual Basic 98" },
    ],
    related: ["messenger", "come-over"],
  },
  // ---- 3D Viewer 98 (Snap to 3D) ----
  {
    id: "viewer-3d",
    book: "accessories",
    title: "3D Viewer 98",
    summary: "Turn a photo into a 3D model, spin it, put it in My Park, make it a desktop toy or send it to a friend.",
    keywords: ["3d", "3d viewer", "snap to 3d", "make 3d", "3d model", "model", "glb", "gltf", ".glb", "photo to 3d", "bring to life", "rig", "pet", "desktop toy", "trellis", "anigen", "hugging face", "token"],
    programs: ["3D Viewer 98"],
    body: [
      { img: "/assets/program_icons/viewer3d.svg", alt: "3D Viewer 98 icon" },
      "3D Viewer 98 shows **3D models** and makes new ones from your photos. Models live on drive C: in **C:\\My 3D** (up to 20; the oldest goes), so they sync like your other files.",
      {
        list: [
          "**Make 3D from a Photo...**: pick or take a photo of **one thing** (a mug, a shoe, a toy, your dog) on a plain background. Free services on Hugging Face cut it out and build a model in about half a minute to three minutes: **TRELLIS.2** first (a textured model); when it's out of free time or busy, 3D Viewer moves on by itself to **Hunyuan3D-2**, **Hunyuan3D-2.1**, the community **TRELLIS** and **TripoSG**, and tells you which one is working and your place in its line. Hunyuan3D and TripoSG make the shape, and 3D Viewer colors it from your photo. You can also start from **Photos** (a picture's menu: Make 3D...) or **Camera** (right after a shot).",
          "**Import Model...** opens any **.glb** or **.gltf** file (a .gltf must carry its pictures inside). Big ones are simplified to 30,000 triangles so they stay quick on a phone.",
          "Drag to turn it, pinch to zoom. On a phone, **Tilt to Look** (More options) turns the view as you tilt the phone.",
        ],
      },
      { h: "Use it" },
      {
        list: [
          "**Place in My Park**: your model stands next to you in Pickleball 98's My Park and trots after you as you walk (it never moves you, and only you see it).",
          "**Set as Desktop Toy**: a small window where it spins. Open as many as you like.",
          "**Send in Messenger...**: pick a buddy; it's shrunk to 2 MB and sent like a picture. They tap **Open** and it lands in their C:\\My 3D.",
          "**Bring a Creature to Life...** (More options): from a photo of an animal or character, a second free service (AniGen) builds a model **with bones**, and it sways and breathes in the viewer.",
          "**Share a Picture** saves or shares an image of the view.",
        ],
      },
      { h: "Free time on Hugging Face" },
      "Making a model uses free graphics-card time on Hugging Face. Everyone gets a small amount a day, shared by all those services (a few minutes without signing in). TRELLIS.2 asks for about 2 minutes at a time; the Hunyuan3D services ask for much less, so they often still work when TRELLIS.2 says no.",
      {
        steps: [
          "Sign up free at huggingface.co.",
          "Go to Settings > Access Tokens > **Create new token**, choose **Read**, and copy it.",
          "In 3D Viewer 98, open **More options**, paste it into **Your Hugging Face token** and press **Check** (it says which Hugging Face name it belongs to).",
        ],
        title: "To get your own, bigger daily allowance:",
      },
      "The token is kept on this device for you only (each person on the computer has their own), sent only to Hugging Face, and removed when you press **Remove** or delete your 98 Messenger account. More options also says how much free time is left today when Hugging Face has told 3D Viewer, and when it comes back.",
      { note: "Your photo is sent to Hugging Face only when you tap Make 3D or Bring to Life (see [[privacy-third-parties]]). The services' models: TRELLIS.2 and TRELLIS (MIT), Hunyuan3D-2 and 2.1 (Tencent Hunyuan community license), TripoSG (MIT) and AniGen (MIT); the models you make are yours to keep and use." },
      { open: "3D Viewer 98", label: "Open 3D Viewer 98" },
    ],
    related: ["photos", "camera", "pickleball", "messenger"],
  },
  // ---- Music 98 ----
  {
    id: "music-98",
    book: "accessories",
    title: "Music 98",
    summary: "Your own songs (MP3, M4A, FLAC...) with albums, artists, playlists and lock-screen controls.",
    keywords: ["music", "songs", "mp3", "m4a", "itunes", "library", "album", "artist", "playlist", "shuffle", "repeat", "queue", "equalizer", "wmplayer", "windows media player", "lock screen"],
    programs: ["Music 98"],
    body: [
      { img: "/assets/program_icons/music98.svg", alt: "Music 98 icon" },
      "Music 98 plays **your own songs**: MP3, M4A/AAC, WAV, FLAC and OGG files from your phone or computer. Press **Add Songs...** and pick them. They're kept in **C:\\My Music** exactly as they are (full length, never cut or converted; up to 300 MB a song), and their names, artists, albums and album art come from the files themselves.",
      {
        list: [
          "**Songs**, **Albums**, **Artists**, **Playlists** and **Queue** across the top; **Search** finds a song by title, artist or album.",
          "Tap a song to play it (the rest of the list plays after it). An album or playlist has **Play** and **Shuffle**.",
          "Each song's **...** button has **Play Next**, **Add to Queue**, **Add to Playlist** and **Edit Info...** (right-click works too on a computer).",
          "The round buttons: **Shuffle**, Previous, **Play/Pause**, Next and **Repeat** (all, then this song).",
          "Music keeps playing while Music 98 is minimized or you use other programs. Closing its window stops it.",
        ],
      },
      { phone: "The phone's lock screen and Control Center show the song with its art, play/pause and skip. Volume is the phone's side buttons.", computer: "Media keys on your keyboard (play/pause, next, previous) work while 98ish is open. The taskbar speaker sets the volume." },
      { h: "More options" },
      "**Equalizer** (bass, mid, treble) and a **Visualizer** in the Now Playing panel.",
      { note: "On iPhone, the equalizer and visualizer route sound through the browser's audio engine, which can stop the music when the screen locks. Leave them off when listening with the phone in your pocket." },
      "Songs stay on this device. **File sync** copies them online only if you add My Music to the synced folders in Backup (online space is limited, so it's off), and even then songs over 8 MB stay on this device only (they aren't in backups either). Opening a song file in My Computer plays it here, and Send To > My Phone gives you back the original file. Your videos are in [[media-player]] (Videos).",
      { open: "Music 98", label: "Open Music 98" },
    ],
    related: ["media-player", "sound-recorder", "no-sound", "file-sync"],
  },

  // ---- Virtual PC 98 ----
  {
    id: "virtual-pc",
    book: "accessories",
    title: "Virtual PC 98",
    summary: "A real PC inside 98ish: FreeDOS boots from a floppy, or boot a disk image of your own.",
    keywords: ["Virtual PC", "FreeDOS", "emulator", "virtual machine", "v86", "disk image", "iso", "img", "boot", "x86"],
    programs: ["Virtual PC 98"],
    body: [
      { img: "/assets/program_icons/virtualpc.svg", alt: "Virtual PC 98 icon" },
      "**Virtual PC 98** (Start > Programs > Accessories) emulates a whole x86 PC with v86. It boots **FreeDOS** (a free MS-DOS) from floppy A:. Try **DIR**, **EDIT** or **HELP** at the prompt.",
      {
        list: [
          "**Machine > Insert Disk Image...** boots a floppy (.img), hard disk or CD (.iso) image of your own, like an old system disk you own. It stays in this window: it isn't uploaded or copied to drive C:.",
          "**Machine > Save State** keeps the whole computer, mid-whatever, in **C:\Games\Saves\VIRTUALPC.V86**; **Load State** picks it up again.",
          "**Typing:** on a phone, tap **Keyboard** (or the PC's screen) and type on the 98ish keyboard: its top row has Esc, Tab, Ctrl and the up and down arrows. A Bluetooth or computer keyboard types straight into the PC once you've clicked its screen (a blue frame shows the PC has the keyboard).",
        ],
      },
      { note: "FreeDOS is free software (GPL; sources at freedos.org). The PC emulator loads from the jsDelivr CDN the first time (see [[privacy-third-parties]])." },
      { open: "Virtual PC 98", label: "Open Virtual PC 98" },
    ],
    related: ["lan-party", "ms-dos"],
  },

  // ---- Magnifier ----
  {
    id: "magnifier",
    book: "accessories",
    title: "Magnifier",
    summary: "Show what's under the mouse pointer bigger, in its own window.",
    keywords: ["zoom", "bigger", "screen magnifier", "low vision", "enlarge"],
    programs: ["Magnifier"],
    body: [
      { img: "/assets/program_icons/cpl/magnifier.svg", alt: "Magnifier icon" },
      "Magnifier shows the area around your mouse pointer, enlarged, in a window you can move anywhere. Choose how much bigger with **Magnification** (2x to 6x), and whether it follows the **Mouse**, the **Keyboard focus**, or both.",
      "Web pages from other sites (like those in Internet Explorer) and videos show as gray boxes in the Magnifier.",
      { phone: "Magnifier follows a mouse, so it's for computers. On a phone, use **Larger tap targets** in [[accessibility|Accessibility Options]], or your phone's own zoom (on iPhone: Settings > Accessibility > Zoom).", computer: "Open it from Start > Programs > Accessories > Magnifier, then move the mouse around." },
      { open: "Magnifier", label: "Open Magnifier" },
    ],
    related: ["accessibility", "display", "mouse"],
  },
]
