// Help topics: getting started, files and storage, and the system tools.
// (Format: the top of ../helpCore.js. No imports here: Node's tests read this file directly.)

export const books = [
  { id: "start", title: "Getting started", order: 10 },
  { id: "files", title: "Files, storage and sync", order: 20 },
  { id: "system", title: "System tools", order: 80 },
]

export const topics = [
  // ---------------- Getting started ----------------
  {
    id: "help-home",
    book: "start",
    title: "Welcome to 98ish Help",
    summary: "Start here: how Help works and the most popular topics.",
    keywords: ["help", "home page", "getting help", "how do I", "questions", "support"],
    programs: ["98ish Help"],
    body: [
      "Hi! This is 98ish Help. It explains everything on this make-believe 1998 computer, from the Start button to every game, in plain words.",
      { h: "Popular topics" },
      {
        list: [
          "New here? Read [[what-is-98ish]], then [[desktop]] and [[start-menu]].",
          "On a phone? See [[phone-basics]] and [[home-screen]].",
          "Want to play with friends? See [[online-play]].",
          "Chatting and calling: [[messenger]] and [[messenger-calls]].",
          "For the two of you: [[us-pairing]].",
          "Keeping your stuff safe: [[file-sync]] and [[backup]].",
          "Something not working? Try [[trouble-start]].",
        ],
      },
      { h: "Finding your way around Help" },
      {
        list: [
          "**Contents** lists every topic, grouped into books. Open a book to see its pages.",
          "**Index** is an A to Z list of words. Start typing and it jumps to the closest one.",
          "**Search** looks through the words of every page and shows the best matches first.",
          "**Favorites** keeps the pages you want to come back to.",
        ],
      },
      {
        phone: "On a phone, Help shows the list first. Tap a page to read it, and tap Back to return to the list.",
        computer: "Press {{F1}} in any program to jump straight to its help page.",
      },
      { tip: "Most programs also have **Help > Help Topics** in their menu bar, and Floppy the helper can open the page for the program you're using." },
    ],
    related: ["using-help", "what-is-98ish", "phone-basics", "trouble-start"],
  },
  {
    id: "using-help",
    book: "start",
    title: "Using 98ish Help",
    summary: "Contents, Index, Search, Favorites, the toolbar, and opening help from any program.",
    keywords: ["F1", "help topics", "index", "search help", "favorites", "print a topic", "contents"],
    body: [
      "98ish Help works like the Help that came with Windows 98: a list of topics on the left and the page you're reading on the right.",
      { h: "Ways to open Help" },
      {
        list: [
          "Start > Help > **Help Topics**.",
          "Press {{F1}}: Help opens at the page for the program you're using.",
          "In most programs, choose **Help > Help Topics** from the menu bar.",
          "Settings windows have a small **?** button in their title bar.",
          "In the MS-DOS Prompt, type **WINHELP**, or **HELP** and a program's name (like HELP TETRIS).",
          "When Floppy the helper shows a tip, he can open help for that program too.",
          "Type a question in the Start menu's search box: help pages show up under Help Topics.",
        ],
      },
      { h: "The four tabs" },
      {
        list: [
          "**Contents**: books of topics. Open a book, then pick a page.",
          "**Index**: type a word (like wallpaper or zip) and the list jumps to it. If a word leads to more than one page, you get to pick.",
          "**Search**: type a few words and press Enter. The best matches come first, with a peek at where your words appear.",
          "**Favorites**: add the page you're reading, then come back to it any time.",
        ],
      },
      { h: "The toolbar" },
      {
        table: {
          head: ["Button", "What it does"],
          rows: [
            ["Hide / Show", "Hides the list of topics to give the page more room, or brings it back."],
            ["Back / Forward", "Goes through the pages you've already looked at."],
            ["Home", "Comes back to the Welcome page of Help."],
            ["Print", "Prints the page you're reading."],
            ["Options", "More choices, like these same commands."],
          ],
        },
      },
      { phone: "On a phone the list and the page take turns filling the screen. Tap a topic to read it, and tap Back to go back to the list." },
      { tip: "Blue underlined words are links to other pages. Related Topics at the bottom of a page lead to more." },
    ],
    related: ["help-home", "search", "keyboard-shortcuts"],
  },
  {
    id: "what-is-98ish",
    book: "start",
    title: "What is 98ish?",
    summary: "A make-believe computer from 1998 that lives in your web browser.",
    keywords: ["about 98ish", "windows 98", "introduction", "overview", "browser", "free"],
    body: [
      "98ish is a whole pretend computer from 1998, right in your web browser. It has a desktop, a Start button, windows you can move around, and lots of programs: games, little tools like Notepad and Paint, 98 Messenger for chatting, Mail, a Calendar, a Camera, and more.",
      "It works on a computer and on a phone. On a phone, every window fills the screen so it's easy to use with your fingers.",
      { h: "Where your stuff lives" },
      "Everything you make (documents, photos, high scores, settings) is saved in this browser on this device. Nothing leaves it unless you choose to: for example by signing on to 98 Messenger, sending mail, or turning on file sync.",
      { note: "Because your files live in the browser, clearing your browser's website data erases them. Turn on [[file-sync]] or make a [[backup]] if they matter to you." },
      { h: "Things to try first" },
      {
        list: [
          "Take the tour: Start > Help > Take the Tour. It takes about a minute.",
          "Open the Start menu and look in Programs > Games.",
          "Sign on to [[messenger]] and add your friends.",
          "Change the wallpaper: see [[display]].",
        ],
      },
      { open: "Welcome to 98ish", label: "Open Welcome to 98ish" },
    ],
    related: ["desktop", "start-menu", "phone-basics", "welcome-tour", "privacy-overview"],
  },
  {
    id: "desktop",
    book: "start",
    title: "The desktop and its icons",
    summary: "Open, move, arrange and make things on the desktop.",
    keywords: ["desktop", "icons", "arrange icons", "new folder", "shortcut", "icon spacing", "auto arrange", "new text document"],
    body: [
      "The desktop is the big area behind your windows. Its icons open programs, files and folders.",
      {
        phone: "Tap an icon to open it. To move an icon, drag it to a new spot: it snaps into place, and if another icon is already there the two swap. Press and hold an empty spot for the desktop's menu.",
        computer: "Double-click an icon to open it. Drag icons anywhere you like. Drag a box around several icons to select them all, then move or delete them together. Right-click an empty spot for the desktop's menu.",
      },
      { h: "The desktop's menu" },
      {
        list: [
          "**New > Folder** or **New > Text Document** makes one right on the desktop.",
          "**Paste** puts something you copied here. **Paste from Device Clipboard** brings in a picture, link or text you copied elsewhere on your phone or computer.",
          "**Upload from Phone...** (or **Upload from Your Device...**) brings in real files.",
          "**View** sets the icon spacing, **Auto Arrange** and **Align to Grid**. **Arrange Icons** sorts them by name or type.",
          "**Properties** opens Display Properties, where you change the wallpaper.",
        ],
      },
      { h: "Files on the desktop" },
      "Right-click (or press and hold) a file on the desktop for Open, Cut, Copy, Send To, Delete and Rename. Things you put on the desktop are kept in the Desktop folder of drive C:.",
      {
        keys: [
          ["Enter", "Open the selected icon"],
          ["Delete", "Delete the selected file"],
          ["F2", "Rename the selected file"],
          ["Tab", "Move between desktop icons"],
        ],
        title: "With a keyboard",
      },
      { tip: "Drag a desktop icon onto the Quick Launch bar next to the Start button to keep a one-click copy there." },
    ],
    related: ["start-menu", "windows", "right-click", "my-computer", "display"],
  },
  {
    id: "start-menu",
    book: "start",
    title: "The Start menu",
    summary: "Open programs, documents, settings, Find, Help, Run, and shut down.",
    keywords: ["start button", "start menu", "programs", "run", "shut down", "log off", "restart", "lock computer"],
    body: [
      "The **Start** button in the bottom-left corner opens the Start menu. Almost everything begins here.",
      {
        list: [
          "**Programs**: every program, sorted into folders like Accessories, Games, Internet, Community and Us.",
          "**Documents**: your My Documents folder and what's in it.",
          "**Favorites**: web pages you've saved in Internet Explorer.",
          "**Settings**: the Control Panel, wallpaper, date and time, keyboard, passwords, themes, taskbar, notifications and keyboard shortcuts.",
          "**Find**: search for files, people, or everything.",
          "**Help**: this Help, the Welcome screen, the tour, and the Read Me.",
          "**Run...**: type the name of a program (like TETRIS or NOTEPAD), a folder, or a web address.",
          "**Lock Computer**, **Log Off** and **Shut Down** are at the bottom.",
        ],
      },
      { h: "The search box" },
      "Type in the box at the top of the Start menu to find programs, settings, files, people, events, messages, mail, photos and help pages. See [[search]].",
      {
        phone: "On a phone the Start menu shows one list at a time. Tap a folder to go into it, and tap the top row to go back.",
        computer: "Point at a folder and its contents fly out to the side. Press {{Ctrl+Esc}} (or the Windows or Command key on its own) to open Start, then use the arrow keys and Enter.",
      },
      { h: "Shutting down" },
      "Shut Down asks whether to **Shut down**, **Restart** or **Restart in MS-DOS mode**. Nothing is lost: your files are saved as you go. Programs with unsaved changes ask first.",
      { note: "Some programs only live in the Start menu, not on the desktop. You can show or hide them with [[add-remove]]." },
    ],
    related: ["desktop", "search", "taskbar", "ms-dos", "lock-screen"],
  },
  {
    id: "windows",
    book: "start",
    title: "Working with windows",
    summary: "Move, resize, minimize, maximize, switch between and close windows.",
    keywords: ["window", "minimize", "maximize", "close", "resize", "title bar", "switch windows", "cascade", "tile"],
    body: [
      "Every program opens in a window. The blue strip at the top is the **title bar**, with buttons on the right.",
      {
        table: {
          head: ["Button", "What it does"],
          rows: [
            ["_ Minimize", "Tucks the window away into the taskbar. Click its taskbar button to bring it back."],
            ["Maximize / Restore", "Makes the window fill the screen, or puts it back (computers only)."],
            ["X Close", "Closes the window. If you have unsaved work, it asks first."],
            ["? Help", "On settings windows: opens the help page for it."],
          ],
        },
      },
      {
        phone: "On a phone every window fills the screen, so there's no Maximize. Use the taskbar at the bottom to switch between open windows, and the X to close one.",
        computer: "Drag the title bar to move a window, and drag its edges or corner to resize it. Double-click the title bar to maximize it. Right-click the title bar for Restore, Minimize, Maximize and Close.",
      },
      { h: "Lots of windows open?" },
      {
        list: [
          "Click a window's button on the taskbar to bring it to the front.",
          "Hold {{Alt}} and press {{Q}} to flip through your windows, then let go of Alt to pick one.",
          "Right-click the taskbar for **Cascade Windows**, **Tile Windows**, and **Minimize All Windows**.",
          "{{Ctrl+Alt+D}} shows the desktop. Press it again to bring the windows back.",
        ],
      },
      { tip: "Some programs, like the games, only open once. Opening them again just brings the open one to the front." },
    ],
    related: ["taskbar", "keyboard-shortcuts", "task-manager", "phone-basics"],
  },
  {
    id: "taskbar",
    book: "start",
    title: "The taskbar and the tray",
    summary: "Window buttons, Quick Launch, volume, notifications, the clock and more.",
    keywords: ["taskbar", "quick launch", "volume", "mute", "clock", "tray", "network icon", "auto hide"],
    body: [
      "The taskbar runs along the bottom of the screen. From left to right it has the Start button, the **Quick Launch** bar, a button for each open window, and the **tray** by the clock.",
      { h: "Quick Launch" },
      "Small icons next to Start open things in one click. Right-click Quick Launch to add a program, remove one, reset it, or hide the bar. You can also drag a desktop icon onto it.",
      { h: "The tray" },
      {
        list: [
          "**Speaker**: the volume for every sound in 98ish, with a Mute box.",
          "**Bell**: the Notification Center. See [[notifications]].",
          "**Network** (computers): whether you're connected to the 98ish server, which 98 Messenger and online games need.",
          "**Sync**, **Mail** and **Us** icons show up when you use those.",
          "**Floppy** (computers): when Floppy the helper is resting, click this to bring him back.",
          "**Clock**: double-click (or double-tap) for Date/Time Properties. Right-click or press and hold it for Calendar and Clock.",
        ],
      },
      { h: "Taskbar settings" },
      "Right-click an empty part of the taskbar and choose **Properties** (or Start > Settings > Taskbar & Start Menu...) to auto-hide the taskbar, hide the clock, or hide Quick Launch. See [[taskbar-settings]].",
      { phone: "On a phone, press and hold a window's taskbar button for Restore, Minimize and Close." },
    ],
    related: ["windows", "notifications", "taskbar-settings", "date-time", "server-waking"],
  },
  {
    id: "right-click",
    book: "start",
    title: "Right-click menus (and press and hold)",
    summary: "Every thing has a menu of what you can do with it.",
    keywords: ["right-click", "context menu", "long press", "press and hold", "menu", "shift+f10"],
    body: [
      "Almost everything in 98ish has its own little menu: the desktop, icons, files, the taskbar, window title bars, text boxes, links and pictures.",
      {
        phone: "Press and hold with your finger (about half a second) to open the menu. In text boxes your phone's own menu appears instead, because it's the most reliable way to paste.",
        computer: "Click with the right mouse button. With the keyboard, press {{Shift+F10}} or the Menu key, then use the arrow keys.",
      },
      { h: "Some handy ones" },
      {
        list: [
          "On the desktop: New Folder, New Text Document, Paste, Upload.",
          "On a file: Open, Cut, Copy, Send To > My Phone, Delete, Rename.",
          "On a title bar: Restore, Minimize, Maximize, Close.",
          "On a text box: Undo, Cut, Copy, Paste, Delete, Select All.",
          "On the taskbar: Cascade, Tile, Minimize All, Task Manager, Properties.",
        ],
      },
      { tip: "You can change how long a press and hold takes, or swap the mouse buttons, in Control Panel > Mouse. See [[mouse]]." },
    ],
    related: ["desktop", "my-computer", "mouse", "keyboard-shortcuts"],
  },
  {
    id: "phone-basics",
    book: "start",
    title: "Using 98ish on a phone",
    summary: "What's different on a phone or tablet, and how to get around.",
    keywords: ["iphone", "phone", "mobile", "tablet", "touch", "tap", "android", "ipad"],
    body: [
      "98ish works on phones and tablets as well as computers. A few things work a little differently so they're comfortable with your fingers.",
      {
        table: {
          head: ["On a computer", "On a phone"],
          rows: [
            ["Double-click to open", "Tap once to open"],
            ["Right-click for a menu", "Press and hold for a menu"],
            ["Windows float and resize", "Every window fills the screen"],
            ["Drag icons anywhere", "Drag icons and they snap into a grid"],
            ["Start menu flies out to the side", "Start menu shows one list at a time"],
            ["Your real keyboard", "The 98ish keyboard pops up when you type"],
          ],
        },
      },
      { h: "Getting around" },
      {
        list: [
          "Use the taskbar at the bottom to switch between open windows.",
          "Close a window with its X. Minimize it to go back to the desktop.",
          "Games have on-screen buttons. In many games you can move and resize them: see [[touch-controls]].",
          "Turning your phone sideways works too, and some games are best that way.",
        ],
      },
      { h: "Make it feel like an app" },
      "Add 98ish to your Home Screen. It then opens full screen like a real app, keeps your files safer, works offline after the first visit, and (on iPhone) is the only way to get notifications. See [[home-screen]].",
      { note: "On iPhone, sound starts after your first tap. That's a rule of the iPhone, not a problem with 98ish. See [[no-sound]]." },
    ],
    related: ["home-screen", "phone-keyboard", "touch-controls", "notifications", "no-sound"],
  },
  {
    id: "home-screen",
    book: "start",
    title: "Add 98ish to your Home Screen",
    summary: "Open 98ish like an app, keep your files safer and get notifications.",
    keywords: ["add to home screen", "install", "app", "home screen", "icon", "pwa", "offline"],
    body: [
      "Adding 98ish to your Home Screen gives it an icon like any other app. It then opens full screen without Safari's bars, works offline after your first visit, is less likely to have its files cleared by the phone, and can send you notifications.",
      { steps: ["Open **98ish.vercel.app** in **Safari**.", "Tap the **Share** button (the square with an arrow, at the bottom of the screen, or at the top on an iPad).", "Scroll down and tap **Add to Home Screen**, then **Add**.", "Open 98ish from its new icon on your Home Screen."], title: "On an iPhone or iPad:" },
      { steps: ["Open 98ish in **Chrome**.", "Tap the menu (three dots) and choose **Add to Home screen** or **Install app**.", "Open 98ish from its new icon."], title: "On an Android phone:" },
      { warning: "The Home Screen app keeps its own files, separate from Safari. If you already made things in Safari, turn on [[file-sync]] (or use [[backup]]) to bring them across." },
      { tip: "Once you've added it, go to the bell in the taskbar > Settings... > **Turn on notifications** to get IMs, calls and reminders even when 98ish is closed." },
      { note: "Chat, online games and Internet Explorer still need an internet connection." },
    ],
    related: ["phone-basics", "notifications", "push-setup", "storage"],
  },
  {
    id: "phone-keyboard",
    book: "start",
    title: "The 98ish keyboard",
    summary: "The Windows 98-style keyboard that pops up on phones and tablets.",
    keywords: ["keyboard", "on-screen keyboard", "typing", "phone keyboard", "emoji", "dictation", "autofill", "caps lock", "accents"],
    programs: ["Keyboard Properties"],
    body: [
      "On a phone or tablet, tapping a text box brings up the **98ish keyboard**: a gray, Windows 98-style keyboard instead of your phone's own one.",
      { h: "Typing tips" },
      {
        list: [
          "Tap **Shift** for one capital letter. Tap it twice for Caps Lock (the little light turns green).",
          "**123** and **#+=** switch to numbers and symbols.",
          "Press and hold a key for accents and extras (like é, ñ, € or .org), slide to the one you want, and let go.",
          "Hold or drag the **space bar** sideways to move the cursor.",
          "Tap the space bar twice to type a period and a space.",
          "Number boxes get a number pad. The MS-DOS Prompt gets extra keys like Esc, Tab and the arrows.",
        ],
      },
      { h: "Using your phone's own keyboard" },
      "Need emoji, dictation, another language, or your saved passwords? Tap the **phone** button in the keyboard's title bar: that box switches to your phone's keyboard. On sign-in boxes the button is called **Passwords**, for AutoFill.",
      "To always use your phone's keyboard, go to Start > Settings > Keyboard and choose **My phone's own keyboard**.",
      { h: "Hiding it" },
      "Tap the **X** in the keyboard's title bar to hide it. Tapping somewhere else on the screen doesn't close it, so it doesn't vanish while you're busy. If you type on a real keyboard (like a Bluetooth one), it hides by itself, and a small Keyboard button brings it back.",
      { h: "Keyboard Properties" },
      "Start > Settings > Keyboard lets you turn key clicks, vibration, letter previews, automatic capitals and the double-space period on or off. The **Speed** tab sets how fast a held key repeats.",
      { open: "Keyboard Properties", label: "Open Keyboard Properties" },
    ],
    related: ["phone-basics", "keyboard-trouble", "accessibility"],
  },
  {
    id: "notifications",
    book: "start",
    title: "Notifications",
    summary: "The bell in the taskbar, and getting notified when 98ish is closed.",
    keywords: ["notifications", "notification center", "bell", "alerts", "push", "quiet hours", "do not disturb", "badges"],
    body: [
      "When something happens, like a new IM, a missed call, new mail, a calendar reminder, a game invitation or something from your partner in Us, a little message pops up. Everything also goes into the **Notification Center**: the bell in the taskbar.",
      { h: "The Notification Center" },
      {
        list: [
          "Click or tap the bell to see your notifications, grouped by program, newest first.",
          "Click one to go straight to it, or use its X to dismiss it.",
          "**Mark all read** and **Clear all** tidy up. They count for all your devices signed on with the same screen name.",
          "**Settings...** sets up notifications for when 98ish is closed.",
        ],
      },
      { h: "Getting notified when 98ish is closed" },
      { steps: ["Sign on to [[messenger]]. Notifications go to your screen name.", "On an iPhone, first add 98ish to your Home Screen and open it from there (see [[home-screen]]).", "Click the bell, then **Settings...** (or Start > Settings > Notifications...).", "Tap **Turn on notifications** and say **Allow** when asked.", "Tap **Send a test** to check it works."] },
      "You can pick what to be told about: instant messages, calls, calendar reminders, Us, game invitations and mail. **Quiet hours** keep things silent overnight, and **Let calls ring through** lets calls through anyway.",
      { note: "Notifications only arrive when you're away from 98ish (it's closed, in the background, or you're signed off). While you're using it, you see them inside 98ish instead." },
      { warning: "On iPhone, notifications need iOS 16.4 or later and 98ish added to the Home Screen. In Safari itself they can't work." },
    ],
    related: ["push-setup", "home-screen", "messenger", "calendar", "taskbar"],
  },
  {
    id: "search",
    book: "start",
    title: "Finding anything",
    summary: "Search from the Start menu, or use Find for files and folders.",
    keywords: ["search", "find", "find files", "look for", "lost file", "search box", "find people"],
    programs: ["Find"],
    body: [
      "Type in the box at the top of the Start menu and results appear as you type, grouped by kind: programs, settings, files and folders (and the words inside your documents), contacts, calendar events, Messenger conversations, mail, photos and help pages.",
      {
        phone: "On a phone the results fill the screen. Tap one to open it, or tap Cancel to go back.",
        computer: "Use the arrow keys to move through the results and Enter to open one. Enter with nothing picked opens the first one.",
      },
      "At the bottom, **See all results** opens the **Find** window with a tab for each kind.",
      { h: "The Find window" },
      "Start > Find > **Files or Folders...** opens Find, like the one in Windows 98. You can search by:",
      {
        list: [
          "**Named**: part of the name.",
          "**Containing text**: words inside documents.",
          "**Look in**: just one folder (and its subfolders, if you like).",
          "**Date**: changed in the last few days or months, or between two dates.",
          "**Of type** and **Size**: only pictures, only text documents, bigger or smaller than a size.",
        ],
      },
      { tip: "Start > Find > **People...** looks through your Address Book." },
      { note: "Search only looks at your own things on this device. Nothing is found while the computer is locked." },
      { open: "Find", label: "Open Find" },
    ],
    related: ["start-menu", "my-computer", "address-book", "using-help"],
  },
  {
    id: "welcome-tour",
    book: "start",
    title: "The Welcome screen, the tour and Floppy",
    summary: "The screen that greets you, the guided tour, and Floppy the helper.",
    keywords: ["welcome", "tour", "guided tour", "floppy", "helper", "tips", "getting started"],
    programs: ["Welcome to 98ish"],
    body: [
      "**Welcome to 98ish** greets you when 98ish starts. It shows what's on the computer, how to play with friends, things for couples, how to make 98ish yours, and how to get involved.",
      "Untick **Show this screen each time 98ish starts** at the bottom to stop it appearing. Bring it back any time from Start > Help > Welcome to 98ish.",
      { h: "Take the Tour" },
      "The tour is a short walk around 98ish in 13 stops. A yellow balloon points at each thing and explains it.",
      {
        phone: "Tap Next to keep going.",
        computer: "Click Next or press Enter to keep going, and Esc to leave.",
      },
      "If you leave partway, Welcome offers to continue where you stopped. Start it from Start > Help > Take the Tour.",
      { h: "Floppy the helper" },
      "Floppy is the little floppy disk who pops up with tips the first time you open a program. Click him for another tip. His bubble can also open the help page for the program you're using.",
      "**Hide Floppy** in his bubble sends him to rest. To bring him back, click the small floppy in the taskbar tray, or use Display Properties > Startup.",
      { open: "Welcome to 98ish", label: "Open Welcome to 98ish" },
    ],
    related: ["what-is-98ish", "help-home", "display"],
  },
  {
    id: "keyboard-shortcuts",
    book: "start",
    title: "Keyboard shortcuts",
    summary: "Keys that work everywhere, and in some programs.",
    keywords: ["shortcuts", "hotkeys", "keys", "alt+f4", "ctrl+esc", "alt+q", "keyboard shortcuts", "mac"],
    body: [
      "With a real keyboard, these keys save time. On a Mac, **Alt** is the **Option** key, and the **Windows** key is **Command**.",
      {
        title: "Anywhere in 98ish",
        keys: [
          ["F1", "Help for the program you're using"],
          ["Alt+Q (hold Alt)", "Switch between windows. Keep pressing Q to move along, let go of Alt to pick. Alt+` works too; add Shift to go backwards."],
          ["Ctrl+Esc, or the Windows/Command key alone", "Open the Start menu. Then the arrow keys move, Enter opens, Esc goes back."],
          ["Alt+F4", "Close the active window"],
          ["Shift+F10, or the Menu key", "The right-click menu of the selected thing"],
          ["Tab, then Enter", "Move between icons, buttons and boxes; Enter opens"],
          ["Ctrl+Alt+E", "Open My Computer"],
          ["Ctrl+Alt+D", "Show the desktop (press again to bring the windows back)"],
          ["Ctrl+Alt+R", "Run..."],
          ["Ctrl+Alt+K", "The list of shortcuts"],
          ["Ctrl+Alt+L, or Windows/Command+L", "Lock 98ish (set a PIN or password first)"],
        ],
      },
      {
        title: "On the desktop and in My Computer",
        keys: [
          ["Enter", "Open"],
          ["Delete", "Delete"],
          ["F2", "Rename (on the desktop)"],
          ["Ctrl+V", "Paste"],
        ],
      },
      {
        title: "In Notepad",
        keys: [
          ["Ctrl+N / Ctrl+O / Ctrl+S", "New, Open, Save"],
          ["Ctrl+Z", "Undo"],
          ["Ctrl+X / Ctrl+C / Ctrl+V", "Cut, Copy, Paste"],
          ["Ctrl+F / F3", "Find, Find Next"],
          ["Ctrl+H", "Replace"],
          ["F5", "Type the time and date"],
        ],
      },
      "Many other programs show their shortcuts right in their menus, next to each command. Each game's help page lists its keys.",
      { shell: "shortcuts", label: "Show the shortcut list" },
    ],
    related: ["windows", "start-menu", "lock-screen", "accessibility", "notepad"],
  },

  // ---------------- Files, storage and sync ----------------
  {
    id: "my-computer",
    book: "files",
    title: "My Computer: files and folders",
    summary: "Browse drive C:, make folders, and copy, move, rename and delete files.",
    keywords: ["my computer", "files", "folders", "explorer", "drive c", "my documents", "new folder", "rename", "copy", "move"],
    programs: ["My Computer"],
    body: [
      "My Computer shows everything on drive C:, the pretend hard disk where 98ish keeps your files. Open it from the desktop, or press {{Ctrl+Alt+E}}.",
      { h: "The main folders" },
      {
        list: [
          "**My Documents**: your writing from Notepad and WordPad.",
          "**My Pictures**: photos from the Camera and pictures you upload.",
          "**My Music**: songs and recordings.",
          "**Desktop**: whatever is on your desktop.",
          "**Programs**: the programs themselves.",
        ],
      },
      {
        phone: "Tap a folder or file to open it. Press and hold one for its menu.",
        computer: "Double-click to open. Right-click for a menu. Drag files onto folders to move them.",
      },
      { h: "Doing things with files" },
      { steps: ["Select a file or folder.", "Use the **File** or **Edit** menu, or its right-click menu.", "Choose **Cut** or **Copy**, go to another folder, and choose **Paste**."], title: "To move or copy a file:" },
      {
        list: [
          "**File > New** makes a folder or a text document.",
          "**Rename** gives something a new name.",
          "**Delete** sends it to the [[recycle-bin]].",
          "**Create Shortcut** puts a shortcut to it on your desktop.",
          "**Send To > My Phone** shares it to your real phone or computer.",
          "**Back**, **Forward** and **Up One Level** move between folders.",
          "**View** switches between Large Icons and a List.",
        ],
      },
      { tip: "Right-click drive C: and choose **Properties** to see how much space is used and free." },
      { open: "My Computer", label: "Open My Computer" },
    ],
    related: ["files-in-out", "recycle-bin", "storage", "share-phone", "search"],
  },
  {
    id: "recycle-bin",
    book: "files",
    title: "The Recycle Bin",
    summary: "Get back things you deleted, or delete them for good.",
    keywords: ["recycle bin", "trash", "deleted", "undelete", "restore", "empty recycle bin", "garbage"],
    programs: ["Recycle Bin"],
    body: [
      "When you delete a file or folder, it goes to the Recycle Bin first, so you can change your mind. The Recycle Bin shows where each thing came from and when it was deleted.",
      { steps: ["Open the **Recycle Bin** from the desktop.", "Select the file.", "Choose **Restore**. It goes back where it was."], title: "To get something back:" },
      { steps: ["Open the Recycle Bin.", "Choose **Empty Recycle Bin**, then **Yes**."], title: "To free up space:" },
      "You can also right-click (or press and hold) the Recycle Bin on the desktop and choose **Empty Recycle Bin**.",
      { warning: "Emptying the Recycle Bin, or deleting something from inside it, can't be undone." },
      { note: "Files deleted with the DEL command in the MS-DOS Prompt skip the Recycle Bin. And with [[file-sync]] on, files you delete on one device land in the Recycle Bin of your other devices." },
    ],
    related: ["my-computer", "storage-full", "file-sync"],
  },
  {
    id: "files-in-out",
    book: "files",
    title: "Bringing files in and out",
    summary: "Upload real files into 98ish, and download them back to your device.",
    keywords: ["upload", "download", "import", "export", "zip", "drag and drop", "real files", "transfer"],
    body: [
      "98ish keeps its own pretend drive C:, but you can move files between it and your real phone or computer.",
      { h: "Bringing files in" },
      {
        list: [
          "In My Computer, use the **Upload** button (or File > **Upload from Phone...**), and pick files.",
          "Right-click (or press and hold) the desktop and choose **Upload from Phone...** or **Upload from Your Device...**.",
          "On a computer, drag real files from your computer onto a My Computer window.",
          "Copied a picture, link or some text somewhere else? Choose **Paste from Device Clipboard** on the desktop or in My Computer.",
        ],
      },
      "Text, pictures, sounds and web pages come in as files you can open in 98ish.",
      { h: "Taking files out" },
      { steps: ["Select a file or folder in My Computer.", "Choose **File > Download to your computer** (or right-click it).", "It lands in your device's Downloads folder."], title: "To download:" },
      "A folder downloads as a single **.zip** file. Programs, shortcuts and the built-in songs only work inside 98ish, so they're left out.",
      { tip: "To send a file to another app on your phone (Messages, Photos, Files...), use **Send To > My Phone** instead. See [[share-phone]]." },
    ],
    related: ["share-phone", "my-computer", "backup", "photos"],
  },
  {
    id: "share-phone",
    book: "files",
    title: "Sharing with your phone",
    summary: "Send files, photos and text from 98ish to your phone's apps, and back.",
    keywords: ["share", "send to", "my phone", "airdrop", "share sheet", "clipboard", "paste", "other apps"],
    body: [
      "98ish can hand things to the rest of your phone or computer, and take things back in.",
      { h: "Sending things out" },
      "Look for **Send To > My Phone** or **Other Apps...** (or a **Share** button). Your phone's own share sheet opens, so you can save to Photos or Files, AirDrop it, or send it in a message.",
      {
        list: [
          "My Computer and desktop files: right-click > Send To.",
          "Notepad, WordPad, Paint and Sound Recorder: File > Send To.",
          "Photos: the Share menu. Camera: the Share button after you take a picture.",
          "Calendar: an event's **Share...** sends it as a calendar file.",
          "Speed Typist 98 and Word Duel can share your results.",
        ],
      },
      "If your browser can't share, 98ish downloads the file or copies the words instead and tells you.",
      { h: "Bringing things in" },
      {
        list: [
          "**Upload from Phone...** on the desktop or in My Computer picks photos and files from your phone.",
          "**Copy and paste**: copy a picture, link or text in another app, then choose **Paste** (or **Paste from Device Clipboard**) in 98ish.",
          "Copying a file in My Computer also copies its words, link or picture to your phone's clipboard, ready to paste anywhere.",
        ],
      },
      { note: "On Android, when 98ish is installed as an app, it can appear in your phone's share sheet: shared things land in **Received Items**. iPhones don't allow this for web apps, so use Upload from Phone or Paste instead." },
    ],
    related: ["files-in-out", "photos", "camera", "home-screen"],
  },
  {
    id: "storage",
    book: "files",
    title: "How much fits: storage",
    summary: "Where your files are kept, how much room there is, and keeping them safe.",
    keywords: ["storage", "space", "free space", "disk space", "capacity", "drive properties", "persist", "full"],
    programs: ["Storage"],
    body: [
      "Your files, settings and scores are kept in this browser, on this device. Modern browsers give 98ish plenty of room: hundreds of photos fit easily.",
      { h: "Checking your space" },
      {
        list: [
          "In My Computer, right-click (or press and hold) drive C: and choose **Properties** for a pie chart of used and free space.",
          "Control Panel > **Storage** shows the same, plus what's using it and how much the Recycle Bin holds.",
          "Camera and Photos show the free space at the bottom.",
        ],
      },
      { h: "Keeping your files safe" },
      "If a device runs very low on space, a browser may clear a website's files to make room. Storage tells you whether 98ish's files are **Kept**. If not, tap **Keep my files on this device**.",
      { warning: "On iPhone and iPad, Safari clears a website's files after about 7 days without a visit, unless the site is on the Home Screen. Add 98ish to your Home Screen ([[home-screen]]) and open it from there, and sign on to 98 Messenger so [[file-sync]] keeps a copy online." },
      { tip: "Browsers are much more willing to keep files for sites added to the Home Screen. See [[home-screen]]." },
      { warning: "Clearing your browser's history and website data erases everything in 98ish. Use [[file-sync]] or a [[backup]] for anything you care about." },
      { note: "In some private browsing windows, 98ish only gets a small 5 MB drive, and a notice says so." },
      { open: "Storage", label: "Open Storage" },
    ],
    related: ["storage-full", "backup", "file-sync", "privacy-overview", "control-panel"],
  },
  {
    id: "file-sync",
    book: "files",
    title: "Sync your files with 98 Messenger",
    summary: "Keep the same files on your phone and your computer.",
    keywords: ["sync", "cloud", "online drive", "same files everywhere", "other device", "conflict", "sync now"],
    body: [
      "File sync keeps chosen folders the same on every phone and computer where you sign on to 98 Messenger with the same screen name. Make a document on your computer, and it's on your phone too. It's also what keeps your photos safe: if a phone clears its browser storage, or you get a new phone, sign on and everything comes back.",
      "**Sync is on by default.** The first time you sign on to 98 Messenger on a device, My Documents, My Pictures and the Desktop start syncing, and 98ish tells you once. A new photo goes up a few seconds after you take it.",
      { steps: ["Open **Backup** (Start > Programs > System Tools > Backup).", "Under **Sync with 98 Messenger**, tick or untick **Sync my files with my 98 Messenger account**.", "Choose the folders to sync. My Documents, My Pictures and Desktop are picked to start with."], title: "To turn sync off or on, or choose folders:" },
      "Changes go back and forth by themselves. **Sync Now** in Backup does it right away. A small icon in the taskbar tray, and the bottom of My Computer, show how it's going. Without an account, My Computer, Photos and Camera remind you that your files are only on this device.",
      { h: "Good to know" },
      {
        list: [
          "If the same file was changed in two places, both are kept: one gets the other device's name added, like **Notes (from iPhone)**.",
          "Files you delete on one device go to the Recycle Bin on the others, so nothing vanishes by surprise.",
          "Online space is limited: 100 MB per screen name (about 300 photos; Camera and Photos keep each photo under about 400 KB). Backup shows how much you're using. Files over 12 MB don't sync.",
          "The Programs folder and settings aren't synced, just your files.",
          "**Delete Online Files** in Backup removes the online copies (your files on this device stay).",
        ],
      },
      { note: "Your synced files are kept on the 98ish server under your screen name. See [[privacy-server]]." },
      { open: "Backup", label: "Open Backup" },
    ],
    related: ["backup", "messenger-accounts", "storage", "privacy-server", "lost-files"],
  },
  {
    id: "backup",
    book: "files",
    title: "Backup and Restore",
    summary: "Save everything on drive C: to one file, and put it back later.",
    keywords: ["backup", "restore", "back up", "save everything", "98ish file", "move to new phone", "msbackup"],
    programs: ["Backup"],
    body: [
      "Backup saves everything on your drive C: into a single **.98ish** file on your real device. Keep it somewhere safe, and you can always get your files back.",
      { steps: ["Open **Backup** (Start > Programs > System Tools).", "Click **Back Up Now**.", "The file goes to your device's Downloads folder (on iPhone, the Files app)."], title: "To back up:" },
      { steps: ["Open Backup.", "Click **Restore...** and pick a .98ish file.", "Confirm. 98ish puts everything back and reloads."], title: "To restore:" },
      { warning: "Restore replaces everything on C: with what's in the backup. Anything made since the backup is lost, so make a fresh backup first if you're not sure." },
      { tip: "A backup is also an easy way to move your files from Safari into the Home Screen app, or to a new device. [[file-sync]] does this automatically if you sign on to 98 Messenger." },
      "The same window also holds the **Sync with 98 Messenger** settings.",
      { open: "Backup", label: "Open Backup" },
    ],
    related: ["file-sync", "storage", "reset-data", "home-screen"],
  },

  // ---------------- System tools ----------------
  {
    id: "ms-dos",
    book: "system",
    title: "The MS-DOS Prompt",
    summary: "Type commands like it's 1985.",
    keywords: ["dos", "ms-dos", "command prompt", "cmd", "commands", "dir", "terminal"],
    programs: ["MS-DOS Prompt"],
    body: [
      "The MS-DOS Prompt is a black window where you type commands instead of clicking. It works on the same drive C: as My Computer. Find it in Start > Programs > Accessories.",
      {
        table: {
          head: ["Type", "To"],
          rows: [
            ["HELP", "List every command (HELP DIR explains one)"],
            ["DIR", "List the files in this folder"],
            ["CD folder", "Go into a folder (CD .. goes back up)"],
            ["TREE /F", "Draw the whole drive"],
            ["MD, REN, COPY, MOVE, DEL", "Make, rename, copy, move and delete"],
            ["TYPE file", "Show what's in a text file"],
            ["EDIT file", "Open a file in Notepad"],
            ["START name", "Open a program, folder or web address"],
            ["COLOR 0A", "Change the colors"],
            ["CLS", "Clear the screen"],
            ["EXIT", "Close the window"],
          ],
        },
      },
      "Type a program's name to run it, like **TETRIS**, **NOTEPAD**, **WINMINE** or **SPECTRA**. Type **WINHELP** to open this Help, or **HELP** and a program's name (like **HELP TETRIS**) to open that program's help page.",
      {
        keys: [
          ["Up / Down arrows", "Bring back earlier commands"],
          ["Tab", "Finish a file name"],
        ],
      },
      { warning: "DEL and DELTREE delete for good: they skip the Recycle Bin." },
      { phone: "On a phone the 98ish keyboard adds a row with Esc, Tab, Ctrl and the up and down arrows." },
      { tip: "Start > Shut Down > **Restart in MS-DOS mode** fills the whole screen with DOS. Type **WIN** or **EXIT** to get back to Windows." },
      { open: "MS-DOS Prompt", label: "Open the MS-DOS Prompt" },
    ],
    related: ["my-computer", "start-menu", "keyboard-shortcuts"],
  },
  {
    id: "task-manager",
    book: "system",
    title: "Task Manager",
    summary: "See what's running, switch to it, or close a program that's stuck.",
    keywords: ["task manager", "end task", "stuck", "frozen", "processes", "performance", "taskmgr"],
    programs: ["Task Manager"],
    body: [
      "Task Manager lists what's running. Open it from Start > Programs > System Tools, or right-click the taskbar and choose **Task Manager...**.",
      {
        list: [
          "**Applications**: your open windows. Pick one and choose **Switch To** or **End Task**. **New Task...** opens a program by name.",
          "**Processes**: the programs behind the scenes, with **End Process**.",
          "**Performance**: busy-ness graphs, just like 1998.",
        ],
      },
      "The **Options** menu has **Always On Top** and **Hide When Minimized** (Task Manager then waits in the tray by the clock).",
      { warning: "Ending **explorer.exe** brings down the whole desktop, with a blue screen. Nothing is lost: 98ish just restarts." },
      { open: "Task Manager", label: "Open Task Manager" },
    ],
    related: ["windows", "game-trouble", "ms-dos"],
  },
  {
    id: "windows-update",
    book: "system",
    title: "98ish Update",
    summary: "A just-for-fun Windows Update, with authentic modem speeds.",
    keywords: ["windows update", "updates", "update", "restart"],
    programs: ["Windows Update"],
    body: [
      "**Windows Update** at the top of the Start menu is a nostalgic bit of fun. It looks for made-up critical updates, downloads them at (slightly sped up) 56k modem speeds, installs them, and asks to restart, just like 1998.",
      "Updates you've installed are remembered in this browser.",
      { note: "The real 98ish updates itself: whenever there's a new version, you get it the next time you open 98ish. You don't have to do anything." },
      { open: "Windows Update", label: "Open Windows Update" },
    ],
    related: ["system-properties", "start-menu"],
  },
  {
    id: "system-properties",
    book: "system",
    title: "System Properties and achievements",
    summary: "About your computer, and the secrets you've found.",
    keywords: ["system properties", "achievements", "secrets", "trophies", "about", "version", "easter eggs"],
    programs: ["System Properties"],
    body: [
      "Right-click (or press and hold) **My Computer** on the desktop and choose **Properties** to see System Properties.",
      {
        list: [
          "**General**: the version of Windows 98ish, who it's registered to, and the very impressive (pretend) computer it runs on.",
          "**Achievements**: little secrets hidden all over 98ish. Found ones show what you did and when; the rest show a hint.",
        ],
      },
      "When you find one, a trophy pops up in the corner. There are dozens to discover, in games, programs and in places you wouldn't expect.",
      { tip: "Achievements are kept on this device, separately for each user." },
      { open: "System Properties", label: "Open System Properties" },
    ],
    related: ["my-computer", "users", "windows-update"],
  },
]
