// Help topics: Casino 98 (the lobby and chip bank, Texas Hold'em, Blackjack, Roulette, Slots,
// Video Poker, Craps, Baccarat). (Format: see ../helpCore.js. No imports here: Node's tests
// load this file directly.)

export const books = [{ id: "games-casino", title: "Casino 98", parent: "games" }]

export const topics = [
  {
    id: "casino",
    book: "games-casino",
    title: "Casino 98 and your chips",
    summary: "Seven casino games sharing one bank of play chips, with free refills.",
    keywords: ["casino", "chips", "chip bank", "refill", "bankroll", "gambling", "play money", "Casino 98", "lobby"],
    programs: ["Casino 98"],
    body: [
      "**Casino 98** has seven table games: [[texas-holdem|Texas Hold'em]], [[blackjack]], [[roulette]], [[slots]], [[video-poker|Video Poker]], [[craps]] and [[baccarat]]. Open the lobby (Start > Programs > Games > Casino 98) or any game straight from the Casino folder.",
      { h: "Your chips" },
      "Every game bets from the same chips, shown at the top right of each game. You start with 1,000. They're **play chips**: nothing here can be bought, cashed out or won for real.",
      { list: ["Run low (under 5 chips) and a **Free refill** button tops you back up to 1,000.", "The lobby's **More options** shows your record (won, lost, biggest win, refills) and **Start Over** goes back to 1,000 chips.", "Chips are kept on this device, separately for each user. Online Hold'em tables use their own chips and never touch your bank."] },
      { h: "Betting" },
      { phone: "Tap a chip in the rack to pick its value, then tap the table where you want to bet. Each tap adds one chip.", computer: "Click a chip in the rack to pick its value, then click the table where you want to bet. Each click adds one chip." },
      { note: "Closing a game in the middle of a round settles it fairly: Blackjack stands, Video Poker keeps the cards you have, chips waiting on a Roulette, Craps or Baccarat table come back, and a Hold'em table cashes you out." },
      { open: "Casino 98", label: "Open Casino 98" },
    ],
    related: ["texas-holdem", "blackjack", "roulette", "slots", "video-poker", "craps", "baccarat"],
  },
  {
    id: "texas-holdem",
    book: "games-casino",
    title: "Texas Hold'em",
    summary: "No-limit poker against computer players or friends online: blinds, side pots, showdowns.",
    keywords: ["Texas Hold'em", "poker", "no limit", "blinds", "flop", "turn", "river", "all-in", "side pot", "showdown", "buy-in", "cash out", "hand rankings"],
    programs: ["Texas Hold'em"],
    body: [
      "Everyone gets two cards of their own. Five shared cards come out in the middle: three at once (the **flop**), then one (the **turn**), then one more (the **river**), with a round of betting before each and after the last. The best five-card hand from your two and the five on the table wins the pot, unless everyone else folds first.",
      { h: "On your turn" },
      { list: ["**Fold**: give up the hand.", "**Check**: pass, when nobody has bet.", "**Call**: match the bet.", "**Raise** (or **Bet**): put in more. Drag the slider or tap **Min**, **½ Pot**, **Pot** or **All-in**, then the Raise button."] },
      "Before the cards come out, the two players left of the dealer button post the **blinds** (forced bets). The button moves one seat every hand. No-limit means you can bet everything you have at any time.",
      { h: "Hands, best to worst" },
      { table: { head: ["Hand", "Example"], rows: [["Royal flush", "A K Q J 10, one suit"], ["Straight flush", "9 8 7 6 5, one suit"], ["Four of a kind", "7 7 7 7"], ["Full house", "K K K 4 4"], ["Flush", "five of one suit"], ["Straight", "5 6 7 8 9 (A 2 3 4 5 counts too)"], ["Three of a kind", "Q Q Q"], ["Two pair", "J J 4 4"], ["One pair", "10 10"], ["High card", "nothing else"]] } },
      "Ties are decided by the next-best cards (the kickers); a true tie splits the pot. When someone is all-in for less than the others, the extra bets make a **side pot** they can't win.",
      { h: "Against the computer" },
      "**Play the Computer** buys you in from your chips (the buy-in, number of opponents, difficulty and blinds are under **More options**). Blinds go up every few hands. **Cash Out** at any time to take your stack back to your bank (cashing out in the middle of a hand folds it). Win every chip at the table, or go out, and the table is over.",
      { h: "Online" },
      "**Play Online** for 2 to 8 players: Quick Match, or **Create Room** and share the code. Everyone starts with the same chips (the room's own, not your bank) and the last player with chips wins. Each turn has a clock; run out of time and you check or fold. Computer players fill empty seats and take over for anyone who leaves. See [[online-play]].",
      { open: "Texas Hold'em", label: "Play Texas Hold'em" },
    ],
    related: ["casino", "online-play", "video-poker"],
  },
  {
    id: "blackjack",
    book: "games-casino",
    title: "Blackjack",
    summary: "Beat the dealer to 21: hit, stand, double, split and insurance; blackjack pays 3 to 2.",
    keywords: ["Blackjack", "21", "twenty-one", "hit", "stand", "double down", "split", "insurance", "surrender", "soft 17", "basic strategy"],
    programs: ["Blackjack"],
    body: [
      "Get closer to 21 than the dealer without going over. Number cards count their number, J Q K count 10, and an ace counts 1 or 11 (a hand with an ace counted as 11 is **soft**). An ace and a ten-card on the first two cards is a **Blackjack**: it pays 3 to 2.",
      { steps: ["Pick a chip and tap the **BET** circle (more taps, more chips).", "Tap **Deal**.", "**Hit** for another card or **Stand** to stop. **Double** doubles your bet for exactly one more card. **Split** turns a pair into two hands, each with its own bet.", "The dealer turns over the hidden card and draws until 17 or more. Closer to 21 wins; a tie is a push (your bet comes back)."], title: "To play a hand:" },
      { list: ["When the dealer shows an ace, you're offered **Insurance** (half your bet; it pays 2 to 1 if the dealer has Blackjack).", "Split aces get one card each, and an ace and a ten there counts as 21, not Blackjack.", "You can split up to four hands, and double after splitting.", "The shoe is 6 decks, reshuffled when three quarters have been dealt."] },
      { computer: "Keys: {{H}} hit, {{S}} stand, {{D}} double, {{P}} split, {{Enter}} deal." },
      { tip: "**More options** has the house rules (the dealer hits soft 17; late surrender gives back half your bet) and **Show the basic-strategy hint**, which tells you the best play for every hand." },
      { open: "Blackjack", label: "Play Blackjack" },
    ],
    related: ["casino", "baccarat"],
  },
  {
    id: "roulette",
    book: "games-casino",
    title: "Roulette",
    summary: "Bet on numbers, colors, dozens and columns; European or American wheel.",
    keywords: ["Roulette", "wheel", "red", "black", "odd", "even", "straight up", "split", "street", "corner", "six line", "dozen", "column", "zero", "double zero"],
    programs: ["Roulette"],
    body: [
      "Pick a chip, tap the table to bet, then **Spin**. The ball lands in one pocket; every bet that covers that number wins.",
      {
        table: {
          head: ["Bet", "Covers", "Pays"],
          rows: [["Straight up (tap a number)", "1 number", "35 to 1"], ["Split", "2 side by side", "17 to 1"], ["Street", "a row of 3", "11 to 1"], ["Corner", "4 that touch", "8 to 1"], ["Six line", "2 rows", "5 to 1"], ["Dozen, Column (2 to 1)", "12 numbers", "2 to 1"], ["Red, Black, Odd, Even, 1-18, 19-36", "18 numbers", "1 to 1"]],
        },
      },
      "Zero (and double zero) lose every outside bet. **Undo** takes back your last chip, **Clear** all of them, and **Rebet** puts last spin's bets down again.",
      { tip: "Split, street, corner and six-line bets: **More options** > **Bet type**, then tap a number (for a split, tap two numbers next to each other). More options also switches to the American wheel with 0 and 00." },
      { phone: "On a phone the table stands up: 1 2 3 across the top, 34 35 36 at the bottom." },
      { open: "Roulette", label: "Play Roulette" },
    ],
    related: ["casino", "craps"],
  },
  {
    id: "slots",
    book: "games-casino",
    title: "Slots",
    summary: "Lucky 98: three reels, up to five paylines, and the 98 Wild jackpot.",
    keywords: ["Slots", "slot machine", "Lucky 98", "reels", "paylines", "jackpot", "wild", "cherries", "paytable"],
    programs: ["Slots"],
    body: [
      "Choose how many **lines** to play (1 to 5) and the **coin**, then **Spin**. Each line costs one coin. Line 1 is the middle row, 2 the top, 3 the bottom, and 4 and 5 the diagonals.",
      { list: ["Three of a kind on a played line pays (see the paytable under **More options**).", "The **98 Wild** stands in for any symbol; three Wilds is the jackpot (1,000 coins).", "Cherries pay from the left: one cherry on the first reel pays 1, two pay 4."] },
      { computer: "Press {{Space}} to spin." },
      { open: "Slots", label: "Play Slots" },
    ],
    related: ["casino", "video-poker"],
  },
  {
    id: "video-poker",
    book: "games-casino",
    title: "Video Poker",
    summary: "Jacks or Better: deal five, hold, draw. Five coins for the big royal flush.",
    keywords: ["Video Poker", "Jacks or Better", "hold", "draw", "royal flush", "paytable", "9/6", "bet max"],
    programs: ["Video Poker"],
    body: [
      "Choose your bet (**Bet One** adds a coin, **Bet Max** bets five), then **Deal**. Tap the cards you want to keep (they say HELD), then **Draw** to replace the rest. A pair of Jacks or better pays; the paytable is at the top.",
      { tip: "Bet five coins: the royal flush pays 4,000 coins instead of 1,250. More options has the coin size and a hint that suggests which cards to hold." },
      { computer: "Keys: {{1}} to {{5}} hold a card, {{Enter}} deals and draws." },
      { open: "Video Poker", label: "Play Video Poker" },
    ],
    related: ["casino", "texas-holdem"],
  },
  {
    id: "craps",
    book: "games-casino",
    title: "Craps",
    summary: "Roll the dice: the Pass Line and Odds, plus Don't Pass, Come, Field and Place bets.",
    keywords: ["Craps", "dice", "pass line", "don't pass", "odds", "come", "field", "place bet", "point", "seven out", "come-out roll"],
    programs: ["Craps"],
    body: [
      "Bet the **Pass Line**, then **Roll**. On the first roll (the come-out), 7 or 11 wins and 2, 3 or 12 loses. Any other number becomes the **point** (the puck says ON). Then roll that number again before a 7 to win; a 7 first loses (\"seven out\").",
      "Once there's a point, tap **Odds** to back your Pass Line bet. Odds pay true odds (2 to 1 on 4 and 10, 3 to 2 on 5 and 9, 6 to 5 on 6 and 8), up to 3, 4 and 5 times your line bet.",
      { h: "More bets (under More options)" },
      { list: ["**Don't Pass**: the opposite of the Pass Line (a 12 on the come-out is a push), with its own odds.", "**Come** and **Don't Come**: like the line bets, made while there's a point. They move to the next number rolled; then tap **+odds** in that number's box.", "**Field**: one roll. 3, 4, 9, 10 or 11 pay even money, 2 pays double, 12 triple.", "**Place**: tap a number box. Wins if that number comes before a 7 (9 to 5 on 4 and 10, 7 to 5 on 5 and 9, 7 to 6 on 6 and 8) and stays up. Place bets are off on come-out rolls."] },
      "Bets you're allowed to take back are listed under the table with an ×.",
      { open: "Craps", label: "Play Craps" },
    ],
    related: ["casino", "roulette"],
  },
  {
    id: "baccarat",
    book: "games-casino",
    title: "Baccarat",
    summary: "Bet Player, Banker or Tie; the cards follow fixed drawing rules.",
    keywords: ["Baccarat", "punto banco", "player", "banker", "tie", "natural", "commission", "bead road"],
    programs: ["Baccarat"],
    body: [
      "Put chips on **PLAYER**, **BANKER** or **TIE**, then **Deal**. Two hands are dealt; the one closer to 9 wins. Only the last digit counts (7 + 8 = 15 counts as 5); 10s and face cards are 0, aces 1.",
      { list: ["Player wins pay 1 to 1. Banker wins pay 19 to 20 (a 5% commission). A tie pays 8 to 1, and Player and Banker bets come back.", "Nobody decides anything: an 8 or 9 on two cards is a natural and both stand; otherwise the Player draws on 0 to 5, and the Banker follows the table under More options.", "The bead road under the table shows the last results (P, B, T)."] },
      { open: "Baccarat", label: "Play Baccarat" },
    ],
    related: ["casino", "blackjack"],
  },
]
