// Help topics: the games, and playing them online with other people.
// (Format: see ../helpCore.js. No imports here: Node's tests load this file directly.)

export const books = [
  { id: "games", title: "Games", order: 50 },
  { id: "games-online", title: "Playing online", parent: "games" },
  { id: "games-action", title: "Action and sports", parent: "games" },
  { id: "games-cards", title: "Cards and board games", parent: "games" },
  { id: "games-puzzle", title: "Puzzles and word games", parent: "games" },
  { id: "games-sim", title: "Building and strategy", parent: "games" },
]

export const topics = [
  // ---------------- Playing online ----------------
  {
    id: "online-play",
    book: "games-online",
    title: "Playing games online",
    summary: "Quick Match, private rooms with a code, join links and computer players.",
    keywords: ["Play Online", "Quick Match", "room code", "join code", "Join with Code", "Create Room", "multiplayer", "computer players", "lobby", "rematch"],
    body: [
      "Most games for two or more people have a **Play Online** button with a little globe on it. It also shows how many people are online right now. Your friends can be anywhere: on a phone, a laptop, or across the world.",
      { h: "Ways to start a game" },
      {
        list: [
          "**Quick Match** puts you with the next person who's looking for a game. You're matched with people who picked the same settings.",
          "**Create Room** makes a private room with a short code (like K7QX). Share the code, or use **Copy Link** to send a link that opens the game straight to your room.",
          "**Join with Code** is for when a friend sends you a code. Type it in and you're in their room.",
          "**Invite Someone** lists who's online right now. They get an invitation on their screen (see [[game-invites]]).",
          "**Play the Computer** starts right away: computer players fill every other seat.",
        ],
      },
      { phone: "On a phone, Create Room, Join with Code and Invite Someone are under **Play with friends »**, below Quick Match. Once you open it, it stays open in every game.", computer: "On a computer, Play with friends is open to begin with; **Hide** tucks those three away." },
      { steps: ["Open the game and choose **Play Online**.", "Choose **Create Room** (under **Play with friends** on a phone), and pick the settings you want.", "Tap **Copy Code** or **Copy Link** and send it to your friend (in a text, or in [[messenger|98 Messenger]]).", "Your friend opens the same game, chooses **Play Online**, then **Join with Code**.", "When everyone is in the room, everyone taps **I'm Ready**, and the host starts the game."], title: "To play with a friend:" },
      { h: "In the room" },
      "The person who made the room is the **host**. The host picks the settings and starts the game. Empty seats can be filled with computer players (**Add Computer Players**), and if someone drops out in the middle of a game, a computer player takes over their seat. If your connection drops, your seat is kept for 30 seconds so you can come back.",
      "When a game ends you can **Rematch**, go **Back to Lobby** to change the settings, or **Leave**. Closing the game window also leaves the room.",
      { h: "Your name online" },
      "If you're signed on to [[messenger|98 Messenger]], other players see your screen name. Otherwise you play as a guest.",
      { note: "Tetris Online has its own lobby with open rooms and rankings, and the older two-player games (Reversi, Chess, Battleship, Hearts and the Minesweeper race) use invitations instead of codes. See each game's page." },
      { tip: "The game server takes a nap when nobody is around. If you see \"Waking up the game server...\", give it up to a minute. See [[server-waking]]." },
    ],
    related: ["game-invites", "game-chat", "touch-controls", "server-waking", "game-trouble"],
  },
  {
    id: "game-invites",
    book: "games-online",
    title: "Inviting people and answering invitations",
    summary: "Invite someone who's online into a game, and accept or decline invitations.",
    keywords: ["invitation", "invite", "Accept", "Decline", "challenge", "who's online", "Network Neighborhood"],
    body: [
      "You can invite anyone who's on 98ish right now into a game. They get an invitation window on their screen, and when they say yes the game opens for both of you.",
      { steps: ["Open the game and choose **Play Online** (or Game > **Play Online...**).", "Choose **Invite Someone**. You'll see who's online now.", "Click or tap **Invite** next to their name.", "Wait for them to answer. If they accept, the game opens."], title: "To invite someone:" },
      { h: "Other ways to invite" },
      {
        list: [
          "In [[network-neighborhood|Network Neighborhood]], right-click (or press and hold) a computer and choose **Play**, then a game: Checkers, Chess, Reversi, Battleship, Hearts, a Minesweeper Race, Tetris Battle and more.",
          "In Tetris Online, create a room and use **Invite a Friend**.",
          "In Hearts, invite people from the table before you click **Deal**.",
        ],
      },
      { h: "When someone invites you" },
      "An invitation window pops up saying who invited you and to what. Choose **Accept** to play or **Decline** to say no thanks. If you're away from 98ish, the invitation also shows up in the [[notifications|Notification Center]] (the bell on the taskbar), and as a phone notification if you've turned those on.",
      { tip: "Nobody shows up in the list? They need to have 98ish open. Send them the link to 98ish, or a room code instead (see [[online-play]])." },
    ],
    related: ["online-play", "network-neighborhood", "notifications"],
  },
  {
    id: "game-chat",
    book: "games-online",
    title: "Chatting in games",
    summary: "Talk to your opponent or everyone playing the same game.",
    keywords: ["game chat", "chat", "speech bubble", "swear filter", "mute", "lobby chat", "quick chat"],
    body: [
      "Every game has its own chat. Open it with the **speech bubble** button in the game window's title bar, or from the game's menu (**Game Chat**).",
      {
        list: [
          "**In a match**, you talk to the people in your game.",
          "**Otherwise**, you're in the game's lobby: one chat for everyone playing that game right now.",
        ],
      },
      { h: "Chat options" },
      {
        list: [
          "**Swear Filter:** Strict hides messages with swearing; Standard stars out the swear words.",
          "**Mute** someone, or hide a single message, from its menu. Muted Players lists who you've muted.",
          "**Quick chat** has ready-made messages for when typing is a hassle.",
          "Turn chat off for one game (**Chat in This Game**) or for every game (**Chat in All Games**).",
        ],
      },
      { tip: "Be kind. Everyone playing is a real person somewhere." },
    ],
    related: ["online-play", "messenger"],
  },
  {
    id: "touch-controls",
    book: "games-online",
    title: "On-screen controls on phones and tablets",
    summary: "Move, resize and hide the touch buttons in games.",
    keywords: ["touch controls", "on-screen buttons", "Customize controls", "gear", "left-handed", "Mirror", "button size", "opacity", "vibrate"],
    body: [
      "On a phone or tablet, action games show buttons on top of the game: arrows, drop, flippers and so on. You can arrange them however feels best for your thumbs.",
      { steps: ["Tap the small **gear** button on the game (\"Customize controls\"). The game pauses.", "Drag a button to move it.", "Drag a button's corner, or pinch it with two fingers, to make it bigger or smaller.", "Tap a button to pick it: you can then hide it (untick **Show**) or change how see-through it is.", "Tap **Done** to keep your changes, or **Cancel** to forget them."], title: "To customize the controls:" },
      { h: "Handy extras" },
      {
        list: [
          "**Mirror** flips the whole layout for left-handed play.",
          "**All sizes** and **All opacity** change every button at once.",
          "**Reset** puts everything back where it started.",
          "**Vibrate on press** gives a little buzz on each press (Android only; iPhones don't allow it).",
          "Your layout is saved separately for portrait and landscape.",
          "In Tetris the panel also chooses between swiping and buttons (**Play with**), with **Drag speed** and what a tap rotates (see [[tetris]]).",
        ],
      },
      { note: "On a computer with a touch screen, turn the buttons on or off with **Show Touch Controls** in the game's menu." },
    ],
    related: ["tetris", "pinball", "phone-basics"],
  },

  // ---------------- Action and sports ----------------
  {
    id: "tetris",
    book: "games-action",
    title: "Tetris",
    summary: "Fit the falling pieces together and clear lines. Four ways to play alone.",
    keywords: ["blocks", "falling blocks", "Marathon", "Sprint 40L", "Ultra", "Survival", "hold piece", "ghost piece", "T-spin", "line clear", "swipe", "drag", "flick", "gestures", "drag speed"],
    programs: ["Tetris"],
    body: [
      "Pieces made of four squares fall into the well. Move and turn them so they fit together. Fill a whole row and it disappears. If the pile reaches the top, the game is over.",
      { h: "Ways to play" },
      {
        table: {
          head: ["Mode", "Goal"],
          rows: [
            ["Marathon", "15 levels. Each level needs more line points than the last."],
            ["Sprint 40L", "Clear 40 lines as fast as you can."],
            ["Ultra 2:00", "Two minutes. Score as much as you can."],
            ["Survival", "200 lines at rising speed, then a finale in the dark."],
          ],
        },
      },
      "The big **Play** button starts Marathon (or plays the mode you just played again). **More modes »** has Sprint, Ultra and Survival, and **Options »** has the on-screen controls, **Customize controls...** and game chat. Tetris remembers whether you left them open. Your best result in each mode is kept. To play against other people, see [[tetris-online]].",
      { h: "Controls" },
      {
        keys: [
          ["Left / Right arrows", "Move"],
          ["Down arrow", "Soft drop (fall faster)"],
          ["Space", "Hard drop (all the way down)"],
          ["Up arrow or X", "Rotate clockwise"],
          ["Z or Ctrl", "Rotate counterclockwise"],
          ["Shift or C", "Hold the piece for later"],
          ["P or Esc", "Pause"],
          ["V or E", "Use an item (Arena only)"],
        ],
      },
      {
        phone: "Play with your finger on the well, like the Tetris app (see the table below). A slim row of buttons under the well also rotates either way, drops one row (hold it to fall fast) and drops all the way; Hold and Pause are in the left panel.",
        computer: "Use the keys above. Hold an arrow to slide the piece along.",
      },
      { h: "Swipe controls on a phone" },
      {
        table: {
          head: ["Do this on the well", "To"],
          rows: [
            ["Drag left or right", "Move the piece. It follows your finger, one column for each square you slide."],
            ["Drag down slowly", "Soft drop: one row for each square you slide."],
            ["Flick down quickly", "Hard drop: all the way down."],
            ["Swipe up", "Hold the piece for later."],
            ["Tap", "Rotate clockwise."],
          ],
        },
      },
      {
        steps: [
          "Pause, then tap **Controls...** (or choose **Customize controls...** under **Options »** on the start screen).",
          "In **Play with**, pick **Gestures + buttons** (the usual), **Gestures only**, or **Buttons only** (the classic arrows, with no swiping).",
          "**Drag speed** sets how far the piece goes for each square you slide (100% follows your finger exactly).",
          "Tick **Tap left half to rotate left** to turn counterclockwise with a tap on the left side and clockwise on the right.",
        ],
        title: "To change how you play:",
      },
      { tip: "Slide over, then drag down in one motion to soft drop where you want. A sideways slide never drops the piece by itself, even if your finger dips at the end." },
      { note: "Swiping works the same in Tetris Online. The buttons can be moved and resized too (see [[touch-controls]])." },
      { h: "Scoring" },
      "Clearing several lines at once scores more, and four at once (a Tetris) is the best. Twisting a T-shaped piece into a tight spot (a T-spin), clearing lines several pieces in a row (a combo) and emptying the whole well (a perfect clear) earn bonuses. The faint outline at the bottom (the ghost piece) shows where your piece will land.",
      { tip: "Keep one column empty along the side, then drop the long straight piece in for a Tetris." },
    ],
    related: ["tetris-online", "touch-controls", "block-ten"],
  },
  {
    id: "tetris-online",
    book: "games-action",
    title: "Tetris Online: Battle, Arena and Sprint Race",
    summary: "Play Tetris against people anywhere, earn stars and climb the rankings.",
    keywords: ["Tetris Online", "Battle 2P", "Arena", "Sprint Race", "garbage", "items", "stars", "rankings", "Tetris items"],
    body: [
      "Tetris Online pits you against other people (or computer players). Open Tetris and choose **Play Tetris Online**.",
      { h: "Modes" },
      {
        table: {
          head: ["Mode", "Players", "How it works"],
          rows: [
            ["Battle 2P", "2", "Two minutes, one on one. Top out your opponent 3 times."],
            ["Arena", "2 to 6", "Garbage, items, last one standing wins."],
            ["Sprint Race", "2 to 5", "Race to 40 lines on the same pieces."],
          ],
        },
      },
      "In Battle and Arena, clearing lines sends **garbage** rows to someone else's well. T-spins, Tetrises and combos send the most.",
      { h: "Arena items" },
      "Clear lines to earn an item (you can hold one at a time), then press {{V}} or the **Use item** button.",
      {
        list: [
          "**Shield** blocks the next garbage sent to you.",
          "**Sweep** clears the bottom 3 rows of your board.",
          "**Mirror** swaps your target's left and right for 5 seconds.",
          "**Darkness** turns off your target's lights for 5 seconds.",
        ],
      },
      { h: "Starting a game" },
      {
        list: [
          "**Quick Match:** pick a mode and you're matched with whoever's looking.",
          "**Play with a Friend:** pick a mode and **Create a room**, then invite anyone on Network Neighborhood or 98 Messenger. Empty seats can be filled with computer players.",
          "**Open Rooms** lists rooms you can join.",
        ],
      },
      { h: "Stars and rankings" },
      "Sign on to [[messenger|98 Messenger]] and wins earn stars that rank you up. **Rankings** shows the top players in each mode. Stars need another person or hard computer players in the game.",
    ],
    related: ["tetris", "online-play", "game-invites"],
  },
  {
    id: "pickleball",
    book: "games-action",
    title: "Pickleball 98",
    summary: "3D pickleball with real rules, a World Tour, practice drills and online singles and doubles.",
    keywords: ["pickleball", "dink", "kitchen", "serve", "World Tour", "doubles", "drive", "lob", "paddle", "Locker Room", "outfit", "customize", "swimsuit", "beach", "winter"],
    programs: ["Pickleball 98"],
    body: [
      "Pickleball 98 is pickleball in 3D, with real rules and real ball physics. Play the computer, go on a World Tour, practice your shots, play a friend on the same keyboard, or play people online.",
      { h: "Ways to play" },
      {
        list: [
          "**Quick Match:** singles or doubles against the computer (Rookie, Club, Pro or Legend).",
          "**World Tour:** eight matches from the Park Open to the Center Court Masters. Win to unlock new outfits.",
          "**Practice & Tutorial:** learn the controls and drill your shots against a ball machine.",
          "**2 Players:** head to head on one keyboard or two gamepads.",
          "**Play Online:** Quick Match, rooms with a code, and invites. See [[online-play]].",
          "World Tour, Practice & Tutorial and 2 Players are under **More modes »** on the title screen.",
        ],
      },
      { h: "One button to hit" },
      "Aim at their court, then press and hold **hit**, and let go just before the ball reaches you (the marker on the meter in the green). How long you held it decides the pace:",
      {
        list: [
          "A quick **tap** is soft: a dink at the kitchen line, or a drop or reset from farther back.",
          "A long **hold** is hard: a drive, a speed-up or a counter.",
          "A soft ball aimed deep goes up high: a lob.",
        ],
      },
      "The little ring on the ball turns orange when you'll meet it above the net: that one you can attack. Below the net, keep it soft. To **serve**, hold hit to fill the serve meter and let go in the green.",
      { h: "Controls" },
      {
        keys: [
          ["W A S D or the arrows", "Move"],
          ["Mouse", "Aim (point at their court)"],
          ["Click, Space, J or K", "Hit (hold for pace)"],
          ["C", "Change the camera"],
          ["P", "Pause"],
        ],
      },
      {
        phone: "Drag on the left side of the screen to move. Touch anywhere else to hit: touching their court aims right there; elsewhere, drag to steer the aim. Hold longer for more pace.",
        computer: "Move with the keys, aim with the mouse, and click (or press Space) to hit. Two players on one keyboard: Player 1 uses W A S D and F, Player 2 the arrows and L; while holding hit, your move keys steer the aim. A gamepad works too. Change any key in **Controls**.",
      },
      { h: "The Locker Room" },
      "Open **Locker Room** on the title screen (or Game > Locker Room..., or **Locker Room...** on the players screen) to dress any player. Drag the player to turn them around, and pick **Jogging** to see the kit move.",
      {
        list: [
          "**Body:** skin, hair and hair color, a beard, height and build.",
          "**Kit:** a theme (Classic whites, Club colors, Pro kit, Beach, Winter, Retro 80s/90s, Casual) and its style, your two kit colors, then any top, bottom and socks.",
          "**Gear:** hats (caps, visor, headband, bucket hat, beanie), sunglasses, wristbands, gloves and shoes.",
          "**Paddle:** a design and its colors.",
        ],
      },
      "Your look is saved with your user profile and goes with you online, so other people see it. **Auto by venue** puts everyone in the venue's kit (beach kit at Sandy Point, winter kit at Frost Hollow); **Computer players: Random kits** dresses the computer's players in kits of their own.",
      { tip: "Settings > Graphics: Medium and High show the full players with their clothes; Low draws them simply (colors and the main pieces) for slow phones." },
    ],
    related: ["online-play", "touch-controls", "game-trouble"],
  },
  {
    id: "shred",
    book: "games-action",
    title: "Shred 98",
    summary: "A rock rhythm game: play the notes as they cross the line, with six original songs.",
    keywords: ["rhythm game", "guitar", "frets", "strum", "star power", "rock meter", "set list", "calibrate"],
    programs: ["Shred 98"],
    body: [
      "Notes (gems) scroll down five lanes toward the frets at the bottom. Play each one as it crosses the line. Hit notes keep the guitar playing; miss one and it cuts out until you're back on track. There are six original songs, from Garage Days to Voltage Cathedral.",
      { h: "Controls" },
      {
        keys: [
          ["A S D F G (or 1-5)", "The five frets"],
          ["Enter, Space, Up or Down", "Strum (with Easy strum off)"],
          ["Shift or Backspace", "Star power"],
          ["W or Right arrow", "Whammy"],
          ["Esc or P", "Pause"],
        ],
      },
      {
        phone: "Tap the lanes at the bottom of the screen, with two fingers for two-note chords. Hold your finger on long notes, and wiggle it for whammy. The lightning button unleashes star power.",
        computer: "With **Easy strum** on (it's on to start), pressing a fret plays the note. Turn it off in Options for the real thing: hold the frets, then strum. A gamepad works too.",
      },
      { h: "Playing well" },
      {
        list: [
          "**Chords** are two or three gems side by side: play them together. **Sustains** have a tail: hold until it ends for bonus points.",
          "Every 10 notes in a row bumps your multiplier, up to 4x. A miss resets it.",
          "Hit every glowing star-shaped gem to charge **star power**, then unleash it to double your multiplier.",
          "The **rock meter** shows how the crowd feels. Bottom out and you're booed off stage (unless No-Fail is on in Options).",
        ],
      },
      { h: "Career and practice" },
      "Finish songs on Easy, Medium, Hard or Expert to earn 1 to 5 stars. Stars open new venues. **Practice** lets you slow a song down and loop a tricky part.",
      { tip: "Notes feel late or early? Try **Calibrate Lag** on the title screen, especially with Bluetooth headphones." },
    ],
    related: ["touch-controls", "no-sound"],
  },
  {
    id: "pinball",
    book: "games-action",
    title: "Pinball: Deep Sea Dive",
    summary: "An original pinball table with flippers, missions and multiball.",
    keywords: ["pinball", "flippers", "plunger", "nudge", "tilt", "multiball", "missions"],
    programs: ["Pinball"],
    body: [
      "Pull the plunger back and let go to launch the ball. Keep it out of the drain with the flippers. You have 3 balls.",
      { h: "Controls" },
      {
        keys: [
          ["Z or Left Shift", "Left flipper"],
          ["/ or Right Shift", "Right flipper"],
          ["Space or Enter (hold, let go)", "Plunger"],
          ["X, . or Up arrow", "Nudge the table"],
          ["F2", "New game"],
          ["F3", "Pause or resume"],
        ],
      },
      {
        phone: "Hold the left or right half of the table for that flipper (both at once works). Hold **LAUNCH** to pull the plunger, and tap **NUDGE** (or give the phone a shake) to bump the table.",
        computer: "Use the keys above. Hold the plunger key longer for a stronger launch.",
      },
      { h: "Scoring" },
      {
        list: [
          "**Missions** rank you up from Snorkeler to Leviathan, and some ranks earn an extra ball.",
          "Roll through **D-I-V-E** up top to raise the multiplier. The flippers move the lit lanes.",
          "Knock down the **clams**, and sink the **treasure chest** three times for multiball.",
          "Nudging can save a ball, but too much is a **TILT**.",
        ],
      },
      "Game > **High Scores** keeps your best games.",
    ],
    related: ["touch-controls"],
  },
  {
    id: "downhill",
    book: "games-action",
    title: "Downhill",
    summary: "Ski as far as you can, jump ramps and dodge rocks.",
    keywords: ["skiing", "ski", "slalom", "ramp", "jump", "tilt to steer", "SkiFree"],
    programs: ["Downhill"],
    body: [
      "Ski down the mountain as far as you can. Your score is the distance in meters plus style points. After 2,000 m, something big and furry comes down the mountain...",
      { h: "Controls" },
      {
        keys: [
          ["Left / Right (or A / D)", "Turn"],
          ["Down (or S)", "Point straight downhill"],
          ["Up (or W)", "Dig in to slow down"],
          ["Space", "Hop, or spin in the air"],
          ["F2", "Start over"],
          ["P", "Pause"],
        ],
      },
      {
        phone: "Touch and hold where you want the skier to go. Use the **Jump** button to hop. Options > **Tilt to Steer** lets you tilt the phone instead.",
        computer: "Use the arrow keys, or steer with the mouse: the skier heads toward the pointer, and a click jumps.",
      },
      { h: "Tricks and points" },
      {
        list: [
          "Hop over rocks and stumps.",
          "Hit a ramp for a big jump, and press Space in the air to spin. Land before the spin ends!",
          "Ski between the flags of a slalom gate for points.",
          "Turn all the way across the slope to stop.",
        ],
      },
    ],
    related: ["touch-controls"],
  },
  {
    id: "spectra",
    book: "games-action",
    title: "SPECTRA",
    summary: "Fly down a glowing tunnel and slip through the gaps.",
    keywords: ["tunnel", "SPECTRA", "shards", "Overdrive", "multiplier", "3D"],
    programs: ["SPECTRA"],
    body: [
      "Steer the light down an endless, colorful tunnel. Spin around the tunnel to fly through the **gaps** in each gate. Grab **shards** to raise your multiplier, and fill your meter to unleash **Overdrive**: double speed and double points for a few seconds.",
      {
        keys: [
          ["Left / Right (or A / D)", "Spin around the tunnel"],
          ["Space", "Overdrive (when the meter is full)"],
          ["P or Esc", "Pause"],
          ["M", "Mute"],
        ],
      },
      {
        phone: "Drag (or hold the arrow buttons) to spin around the tunnel. Tap the lightning button for Overdrive.",
        computer: "Use the keys above, or drag with the mouse.",
      },
      "Your best score is kept on this device.",
      { warning: "SPECTRA has flashing colors and fast motion." },
      { note: "SPECTRA needs 3D graphics (WebGL). If your browser can't do it, the game says so." },
    ],
    related: ["hover", "game-trouble"],
  },
  {
    id: "hover",
    book: "games-action",
    title: "Hover",
    summary: "A neon spirograph that bursts open when you touch it.",
    keywords: ["spirograph", "neon", "animation", "screensaver-like"],
    programs: ["Hover"],
    body: [
      "Hover isn't really a game: it's a glowing neon spirograph to play with.",
      {
        phone: "Tap the middle of the drawing to burst it open, and tap again to bring it back together.",
        computer: "Move the mouse over the middle (where it says \"Hover here\") and watch it burst outward. Move away and it pulls back in.",
      },
      { tip: "With Reduce Motion turned on (in Accessibility Options, or on your iPhone), it keeps spinning, just more gently." },
    ],
    related: ["spectra", "accessibility"],
  },

  // ---------------- Cards and board games ----------------
  {
    id: "solitaire",
    book: "games-cards",
    title: "Solitaire",
    summary: "Classic Klondike solitaire with Draw One or Draw Three.",
    keywords: ["Klondike", "cards", "Draw Three", "Vegas scoring", "card backs", "patience"],
    programs: ["Solitaire"],
    body: [
      "Build four piles up by suit, from ace to king, at the top right. In the row below, stack cards down in alternating colors (red on black, black on red). Only a king can go in an empty space.",
      { h: "How to move cards" },
      {
        list: [
          "Click the deck to deal. When it's empty, click it again to turn the pile over.",
          "Drag a card (or a run of cards) to move it.",
          "Click a face-down card to turn it over.",
          "Double-click a card to send it up to its suit. Right-click sends everything that can go up.",
        ],
      },
      { phone: "Tap a card to pick it up, then tap where it goes. Dragging works too.", computer: "Drag, click and double-click as above." },
      {
        keys: [
          ["F2", "Deal a new game"],
          ["Ctrl+Z", "Undo"],
        ],
      },
      { h: "Options" },
      "Game > **Options** chooses Draw One or Draw Three, Standard, Vegas or no scoring, a timed game and auto-finish. Game > **Deck** picks the card back.",
    ],
    related: ["freecell", "hearts"],
  },
  {
    id: "freecell",
    book: "games-cards",
    title: "FreeCell",
    summary: "The solitaire game where almost every deal can be won.",
    keywords: ["FreeCell", "free cells", "home cells", "cards", "game number", "solitaire"],
    programs: ["FreeCell"],
    body: [
      "Move every card to the four **home cells** at the top right, building each suit up from the ace. In the columns, stack cards down in alternating colors. The four **free cells** at the top left hold one card each, and any card can go in an empty column.",
      "You can move several cards at once when there are enough free cells and empty columns to shuffle them through. Cards that are no longer needed go home on their own.",
      { phone: "Tap a column, then tap where its card goes. Dragging works too.", computer: "Click a column, then click where it goes, or drag cards. Double-click sends a card home (or to a free cell)." },
      {
        keys: [
          ["F2", "New game"],
          ["F3", "Select a game by number"],
          ["F4", "Statistics"],
          ["F5", "Options"],
          ["F10", "Undo"],
        ],
      },
      { tip: "Every game from 1 to 32000 is the deal you remember, and all but one can be won. Use Select Game to replay a number." },
    ],
    related: ["solitaire"],
  },
  {
    id: "hearts",
    book: "games-cards",
    title: "Hearts",
    summary: "Avoid hearts and the queen of spades, at a table of four.",
    keywords: ["Hearts", "queen of spades", "shoot the moon", "tricks", "passing cards"],
    programs: ["Hearts"],
    body: [
      "Hearts is played at a table of four. Avoid taking hearts (1 point each) and the queen of spades (13 points). The game ends when someone reaches 100, and the lowest score wins.",
      { h: "Rules" },
      {
        list: [
          "Before each hand, pass three cards: left, then right, then across, then no pass.",
          "The 2 of clubs leads first. Follow suit if you can; the highest card of the suit led wins the trick.",
          "Hearts can't be led until one has been played.",
          "Take every heart and the queen to **shoot the moon**: everyone else gets 26 points instead.",
        ],
      },
      { h: "Playing with people" },
      "Opening Hearts from the Start menu sets up a table. Click **Deal** to play against three computer players, or invite people who are online first (the list is on the table). The computer plays any empty seats.",
      { phone: "Tap a card to play it (or to choose it for passing).", computer: "Click a card to play it (or to choose it for passing)." },
      "Game > **Score** shows the scores so far.",
    ],
    related: ["game-invites", "last-card", "solitaire"],
  },
  {
    id: "last-card",
    book: "games-cards",
    title: "Last Card",
    summary: "The card game where you match colors and numbers, and shout LAST CARD!",
    keywords: ["Last Card", "Wild", "Draw Two", "Draw Four", "Skip", "Reverse", "house rules", "stacking", "7-0", "jump-in"],
    programs: ["Last Card"],
    body: [
      "**Get rid of all your cards.** On your turn, play a card that matches the top card's color or its number or symbol, or play a **Wild** and pick the color. Nothing fits? Draw a card.",
      { h: "Action cards" },
      {
        list: [
          "**Skip:** the next player misses a turn. **Reverse:** play changes direction (with two players it works like a Skip).",
          "**Draw Two:** the next player draws 2 and misses a turn.",
          "**Wild Draw Four:** pick a color; the next player draws 4 and misses a turn, unless they challenge it and you were bluffing.",
        ],
      },
      { h: "Last card!" },
      "Down to two cards? Press **LAST CARD!** before you play your next-to-last card. Forget, and anyone can **Catch** you for 3 seconds: you draw 2.",
      "Go out first to win the round. You score the points left in everyone's hands (numbers at face value, action cards 20, wilds 50). First to the target wins.",
      { h: "Controls" },
      { phone: "Tap a card, or drag it up, to play it.", computer: "Click a card, or drag it up, to play it. Press {{D}} to draw and {{K}} to keep a drawn card." },
      { h: "House rules and players" },
      "The title screen shows **Play the Computer** and **Play Online**; **More options »** sets how many opponents and how hard, and has **House Rules...** and **How to Play**. Game > **House Rules** turns on stacking, 7-0, jump-in, draw until you can play, forced play, challenges and extra cards, or picks a preset (Classic, Party, Mayhem, Quick). Play against up to 9 computer players, or 2 to 10 people online with [[online-play|Play Online]].",
    ],
    related: ["online-play", "hearts"],
  },
  {
    id: "monster-duel",
    book: "games-cards",
    title: "Monster Duel",
    summary: "A monster card duel with 170+ original cards, a Deck Builder and card packs.",
    keywords: ["Monster Duel", "trading cards", "Life Points", "deck builder", "card packs", "tribute", "spells", "traps", "chain"],
    programs: ["Monster Duel"],
    body: [
      "Summon monsters, cast spells and set traps to bring your opponent's **Life Points** (8000 to start) down to 0. If you need to draw and your deck is empty, you lose.",
      { tip: "New to it? Choose **Tutorial Duel** from the Game or Help menu for a guided first duel." },
      { h: "A turn, in short" },
      {
        steps: [
          "**Draw** a card (not on the very first turn).",
          "**Main Phase:** summon or set one monster, play spells, set traps.",
          "**Battle:** attack with your monsters. With no monsters in the way, you hit their Life Points directly.",
          "**Main Phase 2**, then **End** your turn (discard down to 6 cards).",
        ],
        title: "Each turn:",
      },
      "Level 5 and 6 monsters need one **tribute** (send one of your monsters to the Graveyard); Level 7 and up need two. When a card is played, the other player may respond, building a **chain** that resolves last-in, first-out. Help > **Rules** has the full rules.",
      { h: "Controls" },
      {
        phone: "Tap a card to see what it can do, then pick from its menu. Press and hold a card to read it in full.",
        computer: "Click a card for its menu, or drag a card onto your rows, or an attacker onto an enemy monster. Hover a card to read it. The phase buttons in the middle move through your turn.",
      },
      { h: "Collecting" },
      "You start with every card in eight starter decks. Beat computer opponents to earn card packs (harder opponents give more), open them, and build your own decks in the **Deck Builder** (30 to 60 cards, at most 3 copies of a card). Play people with [[online-play|Play Online]].",
      { note: "Options > Ask to Respond chooses when you're asked to respond: Always, When I Can, or Never." },
    ],
    related: ["online-play"],
  },
  {
    id: "reversi",
    book: "games-cards",
    title: "Reversi",
    summary: "Trap your opponent's discs between yours to flip them.",
    keywords: ["Reversi", "discs", "flip", "Othello-style", "board game"],
    programs: ["Reversi"],
    body: [
      "Place a disc so that one or more of your opponent's discs lie in a straight line (across, down or diagonally) between it and another of your discs. Every disc you trap flips to your color.",
      "If you can't move, your turn is skipped. When neither player can move, the one with the most discs wins. Black moves first.",
      { phone: "Tap a square to place a disc.", computer: "Click a square to place a disc. Options > **Show Legal Moves** marks where you can go." },
      "From the Start menu you play the computer (Game > New Game picks Black or White). To play a person, use the **Play Online** button to invite someone who's online, or Network Neighborhood.",
      { tip: "Corners can never be flipped. Grab them, and stay off the squares next to them until you can." },
    ],
    related: ["game-invites", "chess", "checkers"],
  },
  {
    id: "chess",
    book: "games-cards",
    title: "Chess",
    summary: "Chess against the computer (three levels) or a person.",
    keywords: ["chess", "checkmate", "castle", "stalemate", "promotion", "Flip Board"],
    programs: ["Chess"],
    body: [
      "Checkmate the other king: attack it so it has no way out.",
      { phone: "Tap a piece to see where it can go, then tap the square.", computer: "Click a piece to see where it can go, then click the square, or drag the piece there." },
      {
        list: [
          "To **castle**, move your king two squares toward a rook.",
          "A pawn that reaches the far side becomes the piece you choose.",
          "Stalemate, the same position three times, 50 moves without a capture or pawn move, or too few pieces to checkmate is a draw.",
        ],
      },
      "From the Start menu you play the computer. The **Level** menu sets it to Easy, Normal or Hard, and Game > New Game picks White or Black. You can **Offer Draw** or **Resign** any time, and View > **Flip Board** turns the board around. To play a person, use **Play Online** to invite someone who's online.",
    ],
    related: ["game-invites", "checkers", "reversi"],
  },
  {
    id: "checkers",
    book: "games-cards",
    title: "Checkers",
    summary: "Checkers online with a room code, Quick Match, or against the computer.",
    keywords: ["checkers", "draughts", "king", "jump", "board game"],
    programs: ["Checkers"],
    body: [
      "Move diagonally forward one square. Jump an opponent's piece to capture it. If you can jump, you must, and keep jumping while you can. Reach the far side to become a king: kings can move backward too.",
      "Take all of your opponent's pieces, or leave them with no moves, to win. Black moves first.",
      { phone: "Tap a piece, then tap where it goes.", computer: "Click a piece, then click where it goes." },
      "Checkers opens to the online choices: **Quick Match**, **Play the Computer** to start right away, and under **Play with friends**: **Create Room** (a code to share), **Join with Code** and **Invite Someone**. See [[online-play]]. During a game you can offer a draw, resign, or ask for a rematch from the Game menu.",
    ],
    related: ["online-play", "chess", "reversi"],
  },
  {
    id: "battleship",
    book: "games-cards",
    title: "Battleship",
    summary: "Hide your fleet, then take turns firing to sink theirs.",
    keywords: ["Battleship", "ships", "fleet", "grid", "sink"],
    programs: ["Battleship"],
    body: [
      "Place your five ships on your grid, then take turns firing at the other grid, one shot each. A white dot is a miss, red is a hit. Sink all five of their ships to win.",
      { h: "Placing your ships" },
      {
        phone: "Pick a ship and tap a square, or drag it. Tap **Rotate** to turn it.",
        computer: "Drag a ship onto your grid. Press {{R}} or right-click to turn it while placing. **Random** places them all for you.",
      },
      "Ships can touch but not overlap.",
      "From the Start menu you play the computer. To play a person, use **Play Online** to invite someone who's online, or right-click them in Network Neighborhood.",
    ],
    related: ["game-invites", "network-neighborhood"],
  },

  // ---------------- Puzzles and word games ----------------
  {
    id: "minesweeper",
    book: "games-puzzle",
    title: "Minesweeper",
    summary: "Clear the minefield without stepping on a mine, alone or in a race.",
    keywords: ["Minesweeper", "mines", "flag", "Beginner", "Expert", "Minesweeper Race", "best times"],
    programs: ["Minesweeper"],
    body: [
      "Find every mine without stepping on one. A number tells you how many mines touch that square.",
      { h: "Controls" },
      {
        phone: "Tap to uncover a square. Press and hold to place a flag, or switch to **Flag** mode.",
        computer: "Left-click to uncover a square. Right-click to place a flag (again for a ?). Click a number when all its mines are flagged to uncover the rest of its neighbors.",
      },
      {
        keys: [
          ["F2", "New game"],
        ],
      },
      "The Game menu picks Beginner, Intermediate, Expert or a Custom field, turns question marks on or off, and shows your **Best Times**.",
      { h: "Minesweeper Race" },
      "Game > **Play Online (Race)** invites someone who's online. You both get the same minefield. First to clear it wins; step on a mine and you lose.",
          ],
    related: ["game-invites", "block-ten"],
  },
  {
    id: "block-ten",
    book: "games-puzzle",
    title: "Block Ten",
    summary: "Fit blocks onto a 10 by 10 board and clear rows and columns.",
    keywords: ["Block Ten", "block puzzle", "Daily Challenge", "Blast", "rows and columns", "streak"],
    programs: ["Block Ten"],
    body: [
      "Drag a piece from the tray onto the board. Fill a whole row or column and it clears. Pieces can't be turned, so plan ahead!",
      "When all three pieces are down you get three more. The game ends when none of the pieces left fits anywhere (pieces with no room turn gray).",
      { h: "Scoring" },
      {
        list: [
          "Every block placed is worth 1 point. A line scores 10; two at once score 30, three score 60, and so on.",
          "Clear lines on moves in a row for a streak bonus.",
          "Empty the whole board for 300 more.",
        ],
      },
      { h: "Modes" },
      "**Daily Challenge** deals everyone the same pieces today. **Blast** gives you three minutes. You get one **Undo** per game ({{Ctrl+Z}}), and {{F2}} starts a new game. The Options menu has color themes: Classic 98, Neon and Pastel.",
      { phone: "Drag pieces with your finger. The piece sits a little above your fingertip so you can see where it goes.", computer: "Drag pieces with the mouse." },
    ],
    related: ["tetris", "minesweeper"],
  },
  {
    id: "word-duel",
    book: "games-puzzle",
    title: "Word Duel",
    summary: "Guess the hidden word in six tries: a daily puzzle, practice and online races.",
    keywords: ["Word Duel", "guess the word", "Daily Word", "green and yellow tiles", "Battle Royale", "Speed Rush", "Absurd", "Sabotage", "word game"],
    programs: ["Word Duel"],
    body: [
      "Guess the hidden word. Type a word and press Enter. Each tile then turns a color:",
      {
        list: [
          "**Green:** the right letter in the right spot.",
          "**Yellow:** in the word, but somewhere else.",
          "**Gray:** not in the word (or not that many times).",
        ],
      },
      { phone: "Tap the letters on the on-screen keyboard in the game, then Enter.", computer: "Type on your keyboard and press Enter. Backspace fixes a letter." },
      { h: "Ways to play alone" },
      {
        list: [
          "**Daily Word:** everyone gets the same word today. Your streak is kept, and you can share your result.",
          "**Practice:** as many words as you like.",
          "**Speed Rush:** three minutes, as many words as you can.",
          "**Multi-board:** four words at once, nine guesses; every guess goes on every board.",
          "**Hard Mode:** any hint you've found must be used in later guesses.",
          "**Absurd:** there's no word yet. Every guess, the game picks whatever dodges you best.",
          "**Custom Game:** word length (4 to 7 letters), number of guesses, timers and more.",
        ],
      },
      "The title screen shows the **Daily Word** and **Play Online**; **More modes »** has the others, Statistics and the word length.",
      { h: "Online" },
      "**Play Online** offers head-to-head races, taking turns on one board, best-of series, Battle Royale for up to 8, Co-op (vote on guesses together) and Sabotage (pick the word your opponent has to guess). Every setting can be changed. See [[online-play]].",
      { tip: "Options > **High Contrast Colors** swaps green and yellow for orange and blue." },
    ],
    related: ["online-play", "speed-typist"],
  },
  {
    id: "speed-typist",
    book: "games-puzzle",
    title: "Speed Typist 98",
    summary: "Race cars by typing: against the computer, your ghost, or people online.",
    keywords: ["typing", "typing race", "WPM", "words per minute", "accuracy", "ghost race", "Daily Prompt", "Sudden Death"],
    programs: ["Speed Typist 98"],
    body: [
      "Everyone gets the same text. After the 3-2-1, type it into the box: your car moves with every letter you get right.",
      {
        list: [
          "The current word is highlighted. A wrong letter turns red, and you have to fix it (Backspace) before you can go on.",
          "**WPM** (words per minute) counts five characters, spaces included, as one word. **Accuracy** is the share of your keys that were right.",
          "Curly quotes and long dashes from phone keyboards count as plain ones.",
        ],
      },
      { h: "Ways to race" },
      {
        list: [
          "**Race the Computer**, with race settings for length, kind of text and the computer's speed.",
          "**Race Your Ghost:** your own best run of a text.",
          "**Daily Prompt:** today's text, the same for everyone.",
          "**Practice Drills** for tricky keys, or your own text.",
          "**Play Online:** Quick Match, private rooms with a code, invitations, Best of 3 and Sudden Death. See [[online-play]].",
          "Race Your Ghost, the Daily Prompt, Practice Drills and Statistics are under **More modes »** on the title screen.",
        ],
      },
      "Options > **Strict Typing** doesn't let wrong keys in and has no backspace. In **Sudden Death**, one wrong key and you're out. Game > **Statistics** tracks your progress, and you can share a result from the results screen.",
      { phone: "Tap the race box after the countdown to bring up the keyboard.", computer: "Just start typing when the countdown ends." },
    ],
    related: ["online-play", "word-duel", "phone-keyboard"],
  },

  // ---------------- Building and strategy ----------------
  {
    id: "sunny-acres",
    book: "games-sim",
    title: "Sunny Acres",
    summary: "Farm, fill orders and build a little town, alone or together with friends.",
    keywords: ["Sunny Acres", "farming", "farm", "crops", "animals", "orders", "co-op town", "visit friends", "clovers"],
    programs: ["Sunny Acres"],
    body: [
      "Grow crops, raise animals, make goods in factories and build your farm into a town.",
      { h: "How to play" },
      {
        list: [
          "**Fields:** tap an empty field and pick a seed, then drag across other fields to plant them all. When crops are ripe, swipe across them to harvest.",
          "**Animals:** make feed at the Feed Mill, then swipe across a pen to feed them. Swipe again to collect milk, eggs or wool.",
          "**Factories:** tap one to see what it makes. Goods wait in the factory until you tap to collect them.",
          "**Orders:** the helicopter pays coins and XP for goods. Don't like an order? Skip it and a new one comes later.",
          "**The train** (from a higher level) trades goods for building materials like bricks and glass.",
          "**Town:** houses bring people, and community buildings make room for more. New factories need enough people.",
        ],
      },
      { phone: "Drag the map to look around and pinch to zoom.", computer: "Drag the map to look around; use the mouse wheel to zoom. **Move** lets you rearrange your town." },
      "Things keep growing while Sunny Acres is closed. Clovers finish anything right away; you earn them by playing.",
      { h: "Playing together" },
      "Sign on to [[messenger|98 Messenger]] to play with people:",
      {
        list: [
          "**Friends:** visit your partner's or buddies' towns, leave little signs, send gifts, and fill their help requests. Your partner can always visit; buddies can when you allow it.",
          "**Co-op Town:** farm one town together, live, with your partner or up to 4 farmers. You plant, harvest and build at the same time, with one Barn and one purse. Your own town stays just as it is.",
        ],
      },
      { note: "Played on two devices? Your town is saved with your account, and if both changed, Sunny Acres asks which one to keep (the other is kept as a backup)." },
    ],
    related: ["us-together", "messenger", "online-play"],
  },
  {
    id: "hexlands",
    book: "games-sim",
    title: "Hexlands",
    summary: "Settle, trade and build on a hex island. First to 10 points wins.",
    keywords: ["Hexlands", "settlement", "city", "road", "resources", "trading", "Bandit", "dice", "board game"],
    programs: ["Hexlands"],
    body: [
      "Build settlements, cities and roads on an island of hexagon tiles. The first to reach 10 points, on their own turn, wins.",
      { tip: "First time? Choose **More options »**, then **How to Play** on the main menu for a step-by-step lesson on a little practice island." },
      { h: "Rules in short" },
      {
        list: [
          "**Setup:** each player places a settlement and a road, then again in reverse order. Your second settlement collects one of each resource around it.",
          "**Your turn:** roll the dice. Tiles with that number pay their corners: 1 card per settlement, 2 per city. Then trade and build, then end your turn.",
          "**Costs:** road = timber + clay. Settlement = timber + clay + wool + grain. City = 2 grain + 3 ore. Development card = wool + grain + ore.",
          "**Sevens:** anyone with more than 7 cards discards half; the roller moves the Bandit (it blocks a tile) and takes a card from someone next to it.",
          "**Points:** settlement 1, city 2, Longest Road (5 or more) 2, Largest Patrol (3 or more Rangers) 2, Monument 1.",
        ],
      },
      { h: "Trading" },
      "Trade with other players by making an offer, or with the bank at 4 of a kind for 1. A settlement on a harbor gets better rates: 3:1, or 2:1 for one resource.",
      { phone: "Tap a spot on the board to build there. Pinch (or the zoom buttons) zooms in, and then you can drag the island around.", computer: "Click a spot on the board to build there. The zoom buttons (or Ctrl and the mouse wheel) zoom in." },
      "Play against 1 to 5 computer players (5 or 6 players get a big island), or people with [[online-play|Play Online]]. Game > **Game Settings** changes points to win, the map, a turn clock and house rules.",
    ],
    related: ["online-play", "sunny-acres"],
  },
]
