// Help topics: the games, and playing them online with other people.
// (Format: see ../helpCore.js. No imports here: Node's tests load this file directly.)

export const books = [
  { id: "games", title: "Games", order: 50 },
  { id: "games-online", title: "Playing online", parent: "games" },
  { id: "games-action", title: "Action and sports", parent: "games" },
  { id: "games-cards", title: "Cards and board games", parent: "games" },
  { id: "games-puzzle", title: "Puzzles and word games", parent: "games" },
  { id: "games-sim", title: "Building and strategy", parent: "games" },
]

export const topics = [
  // ---------------- Playing online ----------------
  {
    id: "online-play",
    book: "games-online",
    title: "Playing games online",
    summary: "Quick Match, private rooms with a code, join links and computer players.",
    keywords: ["Play Online", "Quick Match", "room code", "join code", "Join with Code", "Create Room", "multiplayer", "computer players", "lobby", "rematch"],
    body: [
      "Most games for two or more people have a **Play Online** button with a little globe on it. It also shows how many people are online right now. Your friends can be anywhere: on a phone, a laptop, or across the world.",
      { h: "Ways to start a game" },
      {
        list: [
          "**Quick Match** puts you with the next person who's looking for a game. You're matched with people who picked the same settings.",
          "**Create Room** makes a private room with a short code (like K7QX). Share the code, or use **Copy Link** to send a link that opens the game straight to your room.",
          "**Join with Code** is for when a friend sends you a code. Type it in and you're in their room.",
          "**Invite Someone** lists who's online right now. They get an invitation on their screen (see [[game-invites]]).",
          "**Play the Computer** starts right away: computer players fill every other seat.",
        ],
      },
      { phone: "On a phone, Create Room, Join with Code and Invite Someone are under **Play with friends »**, below Quick Match. Once you open it, it stays open in every game.", computer: "On a computer, Play with friends is open to begin with; **Hide** tucks those three away." },
      { steps: ["Open the game and choose **Play Online**.", "Choose **Create Room** (under **Play with friends** on a phone), and pick the settings you want.", "Tap **Copy Code** or **Copy Link** and send it to your friend (in a text, or in [[messenger|98 Messenger]]).", "Your friend opens the same game, chooses **Play Online**, then **Join with Code**.", "When everyone is in the room, everyone taps **I'm Ready**, and the host starts the game."], title: "To play with a friend:" },
      { h: "In the room" },
      "The person who made the room is the **host**. The host picks the settings and starts the game. Empty seats can be filled with computer players (**Add Computer Players**), and if someone drops out in the middle of a game, a computer player takes over their seat. If your connection drops, your seat is kept for 30 seconds so you can come back.",
      "When a game ends you can **Rematch**, go **Back to Lobby** to change the settings, or **Leave**. Closing the game window also leaves the room.",
      { h: "Your name online" },
      "If you're signed on to [[messenger|98 Messenger]], other players see your screen name. Otherwise you play as a guest.",
      { note: "Tetris Online has its own lobby with open rooms and rankings, and the older two-player games (Reversi, Chess, Battleship, Hearts and the Minesweeper race) use invitations instead of codes. See each game's page." },
      { tip: "The game server takes a nap when nobody is around. If you see \"Waking up the game server...\", give it up to a minute. See [[server-waking]]." },
    ],
    related: ["game-invites", "game-chat", "touch-controls", "server-waking", "game-trouble"],
  },
  {
    id: "game-invites",
    book: "games-online",
    title: "Inviting people and answering invitations",
    summary: "Invite someone who's online into a game, and accept or decline invitations.",
    keywords: ["invitation", "invite", "Accept", "Decline", "challenge", "who's online", "Network Neighborhood"],
    body: [
      "You can invite anyone who's on 98ish right now into a game. They get an invitation window on their screen, and when they say yes the game opens for both of you.",
      { steps: ["Open the game and choose **Play Online** (or Game > **Play Online...**).", "Choose **Invite Someone**. You'll see who's online now.", "Click or tap **Invite** next to their name.", "Wait for them to answer. If they accept, the game opens."], title: "To invite someone:" },
      { h: "Other ways to invite" },
      {
        list: [
          "In [[network-neighborhood|Network Neighborhood]], right-click (or press and hold) a computer and choose **Play**, then a game: Checkers, Chess, Reversi, Battleship, Hearts, a Minesweeper Race, Tetris Battle and more.",
          "In Tetris Online, create a room and use **Invite a Friend**.",
          "In Hearts, invite people from the table before you click **Deal**.",
        ],
      },
      { h: "When someone invites you" },
      "An invitation window pops up saying who invited you and to what. Choose **Accept** to play or **Decline** to say no thanks. If you're away from 98ish, the invitation also shows up in the [[notifications|Notification Center]] (the bell on the taskbar), and as a phone notification if you've turned those on.",
      { tip: "Nobody shows up in the list? They need to have 98ish open. Send them the link to 98ish, or a room code instead (see [[online-play]])." },
    ],
    related: ["online-play", "network-neighborhood", "notifications"],
  },
  {
    id: "game-chat",
    book: "games-online",
    title: "Chatting in games",
    summary: "Talk to your opponent or everyone playing the same game.",
    keywords: ["game chat", "chat", "speech bubble", "swear filter", "mute", "lobby chat", "quick chat"],
    body: [
      "Every game has its own chat. Open it with the **speech bubble** button in the game window's title bar, or from the game's menu (**Game Chat**).",
      {
        list: [
          "**In a match**, you talk to the people in your game.",
          "**Otherwise**, you're in the game's lobby: one chat for everyone playing that game right now.",
        ],
      },
      { h: "Chat options" },
      {
        list: [
          "**Swear Filter:** Strict hides messages with swearing; Standard stars out the swear words.",
          "**Mute** someone, or hide a single message, from its menu. Muted Players lists who you've muted.",
          "**Quick chat** has ready-made messages for when typing is a hassle.",
          "Turn chat off for one game (**Chat in This Game**) or for every game (**Chat in All Games**).",
        ],
      },
      { tip: "Be kind. Everyone playing is a real person somewhere." },
    ],
    related: ["online-play", "messenger"],
  },
  {
    id: "touch-controls",
    book: "games-online",
    title: "On-screen controls on phones and tablets",
    summary: "Move, resize and hide the touch buttons in games.",
    keywords: ["touch controls", "on-screen buttons", "Customize controls", "gear", "left-handed", "Mirror", "button size", "opacity", "vibrate"],
    body: [
      "On a phone or tablet, action games show buttons on top of the game: arrows, drop, flippers and so on. You can arrange them however feels best for your thumbs.",
      { steps: ["Tap the small **gear** button on the game (\"Customize controls\"). The game pauses.", "Drag a button to move it.", "Drag a button's corner, or pinch it with two fingers, to make it bigger or smaller.", "Tap a button to pick it: you can then hide it (untick **Show**) or change how see-through it is.", "The **Customize Controls** box can be dragged by its title bar if it covers a button.", "Tap **Done** to keep your changes, or **Cancel** to forget them."], title: "To customize the controls:" },
      { h: "Handy extras" },
      {
        list: [
          "**Mirror** flips the whole layout for left-handed play.",
          "**All sizes** and **All opacity** change every button at once.",
          "**Reset** puts everything back where it started.",
          "**Vibrate on press** gives a little buzz on each press (Android only; iPhones don't allow it).",
          "Your layout is saved separately for portrait and landscape.",
          "In Tetris the panel also chooses between swiping and buttons (**Play with**), with **Drag speed** and what a tap rotates (see [[tetris]]).",
        ],
      },
      { note: "On a computer with a touch screen, turn the buttons on or off with **Show Touch Controls** in the game's menu." },
    ],
    related: ["tetris", "pinball", "phone-basics"],
  },

  // ---------------- Action and sports ----------------
  {
    id: "tetris",
    book: "games-action",
    title: "Tetris",
    summary: "Fit the falling pieces together and clear lines. Four ways to play alone.",
    keywords: ["blocks", "falling blocks", "Marathon", "Sprint 40L", "Ultra", "Survival", "hold piece", "ghost piece", "T-spin", "line clear", "swipe", "drag", "flick", "gestures", "drag speed"],
    programs: ["Tetris"],
    body: [
      "Pieces made of four squares fall into the well. Move and turn them so they fit together. Fill a whole row and it disappears. If the pile reaches the top, the game is over.",
      { h: "Ways to play" },
      {
        table: {
          head: ["Mode", "Goal"],
          rows: [
            ["Marathon", "15 levels. Each level needs more line points than the last."],
            ["Sprint 40L", "Clear 40 lines as fast as you can."],
            ["Ultra 2:00", "Two minutes. Score as much as you can."],
            ["Survival", "200 lines at rising speed, then a finale in the dark."],
          ],
        },
      },
      "The big **Play** button starts Marathon (or plays the mode you just played again). **More modes »** has Sprint, Ultra and Survival, and **Options »** has the on-screen controls, **Customize controls...** and game chat. Tetris remembers whether you left them open. Your best result in each mode is kept. To play against other people, see [[tetris-online]].",
      { h: "Controls" },
      {
        keys: [
          ["Left / Right arrows", "Move"],
          ["Down arrow", "Soft drop (fall faster)"],
          ["Space", "Hard drop (all the way down)"],
          ["Up arrow or X", "Rotate clockwise"],
          ["Z or Ctrl", "Rotate counterclockwise"],
          ["Shift or C", "Hold the piece for later"],
          ["P or Esc", "Pause"],
          ["V or E", "Use an item (Arena only)"],
        ],
      },
      {
        phone: "Play with your finger on the well, like the official Tetris app (see the table below). The screen is laid out like the app too: the score above the well, Hold and the next 3 pieces beside its top, Pause at the top left and a **Hold** button halfway up the left side, right under your thumb. (Drag it somewhere else in Customize controls if you like.)",
        computer: "Use the keys above. Hold an arrow to slide the piece along.",
      },
      { h: "Swipe controls on a phone" },
      {
        table: {
          head: ["Do this on the well", "To"],
          rows: [
            ["Drag left or right", "Move the piece. It follows your finger, one column for each square you slide."],
            ["Hold and drag down", "Soft drop: one row for each square you slide."],
            ["Swipe down quickly", "Hard drop: all the way down."],
            ["Swipe up (or tap the Hold button)", "Hold the piece for later."],
            ["Tap the right side", "Rotate clockwise."],
            ["Tap the left side", "Rotate counterclockwise."],
          ],
        },
      },
      {
        steps: [
          "Pause, then tap **Controls...** (or choose **Customize controls...** under **Options »** on the start screen).",
          "In **Play with**, pick **Like the Tetris app** (the usual: swipes plus Hold and Pause buttons), **Gestures + buttons** (swipes plus a row of rotate and drop buttons), **Gestures only**, or **Buttons only** (the classic arrows, with no swiping).",
          "**Drag speed** sets how far the piece goes for each square you slide (100% follows your finger exactly).",
          "Untick **Tap left half to rotate left** to make every tap turn clockwise (the app turns left on the left side, right on the right).",
        ],
        title: "To change how you play:",
      },
      { tip: "Slide over, then drag down in one motion to soft drop where you want. A sideways slide never drops the piece by itself, even if your finger dips at the end." },
      { note: "Swiping works the same in Tetris Online. The buttons can be moved and resized too (see [[touch-controls]])." },
      { h: "Scoring" },
      "Clearing several lines at once scores more, and four at once (a Tetris) is the best. Twisting a T-shaped piece into a tight spot (a T-spin), clearing lines several pieces in a row (a combo) and emptying the whole well (a perfect clear) earn bonuses. The faint outline at the bottom (the ghost piece) shows where your piece will land.",
      { tip: "Keep one column empty along the side, then drop the long straight piece in for a Tetris." },
    ],
    related: ["tetris-online", "touch-controls", "block-ten"],
  },
  {
    id: "tetris-online",
    book: "games-action",
    title: "Tetris Online: Battle, Arena and Sprint Race",
    summary: "Play Tetris against people anywhere, earn stars and climb the rankings.",
    keywords: ["Tetris Online", "Battle 2P", "Arena", "Sprint Race", "garbage", "items", "stars", "rankings", "Tetris items"],
    body: [
      "Tetris Online pits you against other people (or computer players). Open Tetris and choose **Play Tetris Online**.",
      { h: "Modes" },
      {
        table: {
          head: ["Mode", "Players", "How it works"],
          rows: [
            ["Battle 2P", "2", "Two minutes, one on one. Top out your opponent 3 times."],
            ["Arena", "2 to 6", "Garbage, items, last one standing wins."],
            ["Sprint Race", "2 to 5", "Race to 40 lines on the same pieces."],
          ],
        },
      },
      "In Battle and Arena, clearing lines sends **garbage** rows to someone else's well. T-spins, Tetrises and combos send the most.",
      { h: "Arena items" },
      "Clear lines to earn an item (you can hold one at a time), then press {{V}} or the **Use item** button.",
      {
        list: [
          "**Shield** blocks the next garbage sent to you.",
          "**Sweep** clears the bottom 3 rows of your board.",
          "**Mirror** swaps your target's left and right for 5 seconds.",
          "**Darkness** turns off your target's lights for 5 seconds.",
        ],
      },
      { h: "Starting a game" },
      {
        list: [
          "**Quick Match:** pick a mode and you're matched with whoever's looking.",
          "**Play with a Friend:** pick a mode and **Create a room**, then invite anyone on Network Neighborhood or 98 Messenger. Empty seats can be filled with computer players.",
          "**Open Rooms** lists rooms you can join.",
        ],
      },
      { h: "Stars and rankings" },
      "Sign on to [[messenger|98 Messenger]] and wins earn stars that rank you up. **Rankings** shows the top players in each mode. Stars need another person or hard computer players in the game.",
    ],
    related: ["tetris", "online-play", "game-invites"],
  },
  // ---- Pickleball 98: Real Games (applets/pbclub, shown inside Pickleball 98) ----
  {
    id: "pickleball-club",
    book: "games-action",
    title: "Pickleball 98: Real Games",
    summary: "Score your real pickleball games, plan open play with your group, and keep a friendly ladder.",
    keywords: ["Real Games", "Pickleball Club", "scorekeeper", "score keeper", "keep score", "score call", "4-2-1", "side out", "rally scoring", "open play", "who's in", "RSVP", "waitlist", "round robin", "king of the court", "mixed doubles", "rating", "ladder", "DUPR", "Los Cab", "Wolf + Bear", "SMASH", "meet me at"],
    body: [
      { img: "/assets/program_icons/pickleball.svg", alt: "Pickleball 98 icon" },
      "**Real Games** is the part of [[pickleball|Pickleball 98]] for the pickleball you play in real life. Open Pickleball 98 and pick **Real Games** on the title screen (or Game > Real Games...). It has four tabs:",
      {
        list: [
          "**Play**: your group's sessions and your courts. **New Session...** picks the court, day, time and how many players, and invites buddies; each person answers **I'm in**, **Maybe** or **Can't**. When it's full, more \"in\"s go on a **waitlist** and the first one is told as soon as a spot opens. On the day: **Running late?** (5 to 30 minutes, or **I'm here**), a little chat, and the **courts**: everyone who's in gets a court each round, sit-outs rotate fairly. Choose **Mix it up** (new partners every round), **King of the court** (tap the winners: they move up a court and split up) or **Two groups** (one from each group on every team, for mixed doubles). **Score this game** opens the scorekeeper with those players.",
          "**Score**: the courtside scorekeeper. Pick the players (you, buddies, or a guest) and **Start Game**, then tap whichever team won each rally. It shows the score call (\"4-2-1\": serving team, receiving team, server 1 or 2), who serves from which side and who receives, says **Side out**, **Switch ends** at 6 (8 in a game to 15, 11 to 21) and **Game point**, and can say the score out loud. **Undo** takes back the last rally. The screen stays on during a game, and a game in progress survives a reload or a locked phone.",
          "**Matches**: every match you've played. A match counts once **someone on the other team confirms** it (they get a notification); **That's Wrong** sends it back. Nobody confirms in 7 days: it expires. To take back a confirmed match, **Remove...** asks the other team to agree. **Log a Match...** adds one you scored on paper.",
          "**Ladder**: the friends' ratings (doubles and singles) for everyone you've played or planned with, and your record, streaks, last 10, best partners and head-to-head.",
        ],
      },
      { h: "Scoring options (More options on the Score tab)" },
      "Singles or doubles; **side-out** scoring (only the serving team scores; in doubles both partners serve, except the very first turn of the game: \"0-0-2\") or **rally** scoring (every rally scores; with **Win only on your serve**, a team can only win the game on its own serve); play to 11, 15 or 21; win by 2 or 1; one game or best of 3 or 5; who serves first.",
      { h: "How the ratings work" },
      "Everyone starts at 1500. Each confirmed game moves the winners up and the losers down: more for beating someone rated higher, a bit more for a blowout than an 11-10. In doubles your own rating counts most, so the stronger partner is expected to win more (gains less, loses more). New players move faster for their first 10 games. **Level** is a rough guide (1500 is about 3.5), not an official rating. Games with a guest are in your record but not the ratings. Change the season (all time, this year, the last 90 or 30 days) above the ladder.",
      { h: "Your courts" },
      "In a session, people who are physically at its court right now (buddies who share their location with you, and you) show **here now**; when you're there yourself, a **Check in** button marks you **I'm here** for everyone in the session.",
      "The Play tab lists Los Cab Sports Village, The Tennis & Pickleball Club at Newport Beach, Wolf + Bear Indoor Pickleball, iPickle Whittier Narrows, The Paseo Club, Sinaloa Middle School and California SMASH, with **Directions** (Apple Maps on Apple devices, Google Maps elsewhere), **Plan** (a session there) and **Meet Me Here**, which sends a buddy an IM with the address. Outdoor sessions in the next week show the weather. In Buddy Locator, **Add a Place** can pick one of these courts too.",
      { phone: "Keep 98ish open on the court: iPhone web apps can't keep a screen awake or talk once they're in the background. The spoken score uses your phone's own voice, so nothing is sent anywhere." },
      { note: "Sessions, RSVPs, chat and matches are kept on the 98ish server for your group (see [[privacy-server]]). Deleting your account turns you into \"Deleted player\" in your friends' match history so their ratings stay the same." },
      { open: "Pickleball 98", label: "Open Pickleball 98" },
    ],
    related: ["pickleball", "buddy-locator", "calendar"],
  },

  {
    id: "pickleball",
    book: "games-action",
    title: "Pickleball 98",
    summary: "3D pickleball with real rules, lessons, a ball machine, drills, a walk-around park with open play, a World Tour and online singles and doubles.",
    keywords: ["pickleball", "My Park", "park", "venue", "real venues", "real sky", "sky", "weather in the game", "sunset", "rain", "Los Cab", "Newport Beach", "Wolf + Bear", "Whittier Narrows", "iPickle", "Paseo Club", "Sinaloa", "California SMASH", "indoor", "favorites", "OpenStreetMap", "open play", "call next", "paddle stacking", "spectate", "watch", "park rep", "dink", "kitchen", "serve", "World Tour", "doubles", "drive", "lob", "paddle", "Locker Room", "outfit", "customize", "swimsuit", "beach", "winter", "practice", "ball machine", "drill", "lesson", "coach", "third shot drop", "reset", "split step", "two-bounce rule", "how to play", "swipe", "move pad", "left-handed", "camera", "swing trail", "swipe trail", "sound", "pop", "Twin Replay", "Twin Clones", "clone", "play my friend", "film a game", "video", "replay my game", "real game", "stats", "heat map", "shot mix", "pose", "Go Live", "live", "broadcast", "watch live", "stream", "live game"],
    programs: ["Pickleball 98"],
    body: [
      "Pickleball 98 is pickleball in 3D, with real rules and real ball physics. Play the computer, learn the game in Practice, go on a World Tour, play a friend on the same keyboard, or play people online.",
      { h: "Ways to play" },
      {
        list: [
          "**Quick Match:** singles or doubles against the computer (Rookie, Club, Pro or Legend).",
          "**Practice:** lessons with a coach, a ball machine and drills (below).",
          "**My Park:** walk round a public park where games are going on, watch from the bleachers, and put your paddle in a rack to play next (below).",
          "**World Tour:** eight matches from the Park Open to the Center Court Masters. Win to unlock new outfits.",
          "**2 Players:** head to head on one keyboard or two gamepads.",
          "**Play Online:** Quick Match, rooms with a code, and invites. See [[online-play]].",
          "The title screen has four places to go: **Play** (Quick Match; its setup screen also has **Play Online**, **World Tour** and **2 Players** under More ways to play), **My Park**, **Practice** and **Real Games** (your real-life pickleball), plus **My Player** (pick your player, then the Locker Room). Settings, Controls and Rules are in the Options and Help menus. The first time you open the game it offers a 2-minute lesson.",
        ],
      },
      { h: "Practice" },
      {
        list: [
          "**Learn to play like a pro:** ten short lessons in the order a point is played. Coach Pat gives a two- or three-sentence tip with a little moving court picture, then you try it on court and the coach tells you how it went. Done lessons get a check mark.",
          "**Ball Machine:** pick what it feeds (dinks, third-shot feeds, drives, volleys, lobs or a random mix) and how fast. **More options »** has spin, placement (forehand, backhand, middle, random, alternate), balls a minute, how many balls and target zones. Zones on their court light up with points when you land in them. Pause any time; at the end you see in/out/net, accuracy and your average speed.",
          "**Drills:** one goal each, 1-3 minutes, up to three stars: serve targets, return deep and move in, third-shot drops, keeping 10 dinks in a row going, resets from mid-court, hand battles, overhead smashes and split-step timing.",
          "After every shot a one-word label shows what it was (Drop, Dink, Drive, Pop-up, Out, Net...). Make the same mistake twice and a tip says what to change.",
        ],
      },
      { h: "My Park" },
      "**My Park** (on the title screen, after Practice) is a public park with four courts, each with a real game of doubles going on between the park's regulars: Court 1 is for Rookies, Courts 2 and 3 for Club players, Court 4 for Pros. The regulars walk between the courts, sit on the benches and bleachers, chat, clap a great point, and put their paddles in the racks to play next. The time of day follows your clock: at night the court lights come on.",
      {
        list: [
          "**Walk** with the move pad (or the arrow keys / W A S D; Shift runs). Push the pad a little to walk, further to jog, all the way to sprint. Only you move yourself. Drag on the picture (or Q and E) to look around.",
          "**One button** shows what you can do where you stand: **Watch** by a court's bleachers, **Call next** at its paddle rack, **Sit** at a bench, **Locker Room** at the pro shop, **Ball Machine** at the practice court.",
          "**Watch:** you sit on the bleachers and the view moves to the court; **Cam** changes the angle (sideline, baseline, high) and **Leave** walks on. Only that court's score shows.",
          "**Call next:** your paddle goes in the rack. When the game on that court ends and it's your turn, you're on court for a game of doubles to 11 with the regulars, with your usual controls. Then it's back to the park. Tap the rack again to take your paddle back.",
          "**Park rep:** every game counts: a win more, a streak and the harder courts more still. Your level (Newcomer, Regular, Local, Court Boss, Park Legend) and record show on your nameplate for other people.",
          "**The menu** (top left) lists the courts with their scores (Watch any of them), has short things to say and cheers, the Locker Room, and Leave My Park.",
        ],
      },
      "Online, other 98ish people in the same park walk around with you, with their names over them, and can call next on the same court: then you play each other (computer players fill the other spots). A park holds 16 people; more open another one.",
      { h: "Real venues" },
      "**My Park** first asks **where to?**: Riverside Park, or one of seven real Southern California venues: Los Cab Sports Village (Fountain Valley), The Tennis & Pickleball Club at Newport Beach, Wolf + Bear Indoor Pickleball (Van Nuys), iPickle Whittier Narrows (South El Monte), The Paseo Club (Valencia), Sinaloa Middle School (Simi Valley) and California SMASH (El Segundo). Tap one to go; **☆** stars your favorites so they're first. **Change venue...** is in the park's menu.",
      "The real venues have real surfaces (court grain, asphalt, grass, stucco, tile roofs, wood and tile floors) and sun shadows that follow the time of day. On an older phone, **Options > Graphics: Low** goes back to the simpler flat look and runs faster (it applies the next time you open a venue).",
      "**Real Sky** (on Medium and High): every venue shows the real sky for where it is, right now. The sun and the moon sit where they really are for that court's location and the time, so shadows fall the way they do there today, and sunsets, twilight and stars follow the real clock. The day's weather comes from Open-Meteo for that venue: clouds, rain or snow (the court gets wet), wind in the trees, and haze or fog. Indoors you see the weather only through the doors and windows. **Options > Sky** turns it off, or picks a fixed sky for fun: Clear, Cloudy, Rain, Sunset or Night. **Real Weather at Classic Venues** (off by default) gives the classic courts a real place's weather today too, keeping their own time of day. Only the venue's location is used, never yours.",
      {
        list: [
          "Each venue is built from the real map: every court where it really is and turned the way it's turned, its banks of fences, the clubhouse and other buildings round it, parking lots, trees and palms, and for the indoor clubs the hall itself (walls, a door, the lights, and at SMASH the raised lounge and the bar). Court colors and the look come from what the clubs look like; the drawing is 98ish's own.",
          "A few courts at each venue have live games, regulars and a paddle rack (they're numbered like the venue's own courts, e.g. **Court 35**), and the other courts have people playing too. Your game is played **on the court you walked up to**, with the rest of the venue round you.",
          "Online, friends who pick the **same venue** meet there. Different venues are different parks.",
          "**Friends here for real.** If a buddy shares their location with you in [[buddy-locator|Buddy Locator]] and is physically at one of the seven real venues, they show up there in My Park, standing beside the court they're on with a red pin and **here for real** over them. A strip at the top says who's here and offers **Say hi** (an IM: \"I see you at Los Cab!\") and **Plan a game** (a Real Games session at that venue). The **where to?** list marks venues with **2 friends here now** (and how many are playing there in 98ish). Someone sharing approximate location only shows as **nearby**. It's court-level only, never their exact spot, and only for people who already share their location with you; stop sharing and they're gone.",
          "**Any court on Earth (Venue Finder).** At the top of **where to?**, type a court's name or a town and tap **Find**, or tap **Near me**. It searches every pickleball venue in OpenStreetMap (tens of thousands, worldwide) right on your device. Tap one and 98ish **builds it from the map** in a few seconds: its courts at their real size and angle, fences, lights where the map says so, buildings, parking, paths and trees round it. Indoor venues get a hall from the building's outline. Star ☆ the ones you like. Filters (indoor, lights, 8+ courts, public) are under **Filters**. Friends who pick the same court meet there too.",
          "Venue Finder builds what the map knows, nothing more: a court missing from OpenStreetMap is missing here, and colors fall back to the classic blue court on green when the map doesn't say. You can fix the map itself at openstreetmap.org, and the next monthly update picks it up. Venue data © OpenStreetMap contributors (ODbL).",
          "**Walk in like you would in real life.** At **Los Cab** you arrive in the parking lot, go through the front doors into the lobby (fountain, front desk, pro shop), down the hall past the locker rooms (each with a sauna and a steam room) and out to the 50 m pool, then on to the courts; the cafe, lounge, fitness centre, spin studio, racquetball, indoor gym, kids club and day spa are all open. At **California SMASH** you walk up the Maple Ave frontage, through the front doors into the lobby, through the bar and restaurant (and past the restrooms) out to the courts and the raised lounge, and out to the patio by the train viaduct. Inside, the camera comes closer and stays in the room. Upstairs spaces (SMASH's VIP mezzanine, Los Cab's ballroom) are shown but not walkable yet.",
          "Some details are best guesses (for example where Wolf + Bear's private court is, or which tennis courts at Whittier Narrows have pickleball lines). No location is needed or used.",
          "Map data © OpenStreetMap contributors, available under the Open Database License.",
        ],
      },
      { h: "Twin Replay: your real games, replayed" },
      "**Game > Twin Replay** turns a video of a real game into a replay in Pickleball 98: the players move where you all really moved and swing when you really hit, at your court (pick one of the real venues and the court number), with stats for everyone.",
      {
        list: [
          "**Film a game** (in 98ish, with the back camera) or **Open a video** you filmed. Best: the phone on the back fence behind a baseline, sideways, the whole court in the picture, sound on (the paddle's pop times the hits).",
          "**Tap the four corners** of the court in the order shown (hold and slide for a magnifier, drag a dot to fix it). Yellow lines show the court as 98ish now sees it. Pick **Doubles** or **Singles**, then **Read the game**.",
          "Reading happens on this device: a pose model (Google's MediaPipe, free) finds the players in each picture, about 15 pictures for each second of video. It takes a while (a progress bar shows the time left; Pause and Stop work). Then name the players by their shirt color.",
          "**Replay:** each rally plays on the athletes. Play/pause, the rally's timeline (ticks are the hits), speed (1x, ½x, ¼x), **Camera** (Broadcast, Side, Top, Follow one player, Fence: where your phone was). **More options »** shows your video beside it in sync, changes the venue and court, and sends the game to a friend.",
          "**Stats:** rally lengths and highlights (tap one to watch it), and for each player where they stood (a heat map of their half), time at the kitchen line, meters covered, their shot mix (serve, return, drive, drop, dink, volley, overhead, lob), third-shot choices, and how often they hit a rally's last shot.",
          "**Send to a friend** makes a small replay file (no video: just everyone's positions and the hits); they open it in **Twin Replay > More options » > Open a replay file...**. **Try the demo rally** (under More options) shows what it does without filming anything.",
          "Honest limits: the shot kinds are a good guess, not a referee; the ball's path is rebuilt between the hits (following the real ball in phone video isn't reliable yet); points and errors aren't judged. People walking through, or a player hidden behind another, can confuse it for a moment.",
        ],
      },
      { h: "Twin Clones: play your friends" },
      "A **clone** is a computer player that plays like a real person, learned from their Twin Replay games: where they stand (do they rush the kitchen line or stay back?), how fast they move and react, their third shot (drop or drive), what they do at the kitchen line (dink or speed it up), resets, lobs, where their dinks and drives go, how deep their serve is.",
      {
        list: [
          "Open a game in Twin Replay, go to **Stats** and press **Make a Clone of...** under a player. Tick **This is me** for yourself. Make more clones from more games, or pick **Add to** an existing clone: the meter goes from \"A first guess\" to \"Plays just like them\". With little film a clone plays close to the level it starts from (Rookie, Club, Pro, Legend) and moves toward the real person as it sees more.",
          "**Play** a clone: on the **Play** screen pick it under **Against** (or as your **Partner** in doubles; clones are at the top as \"Clone: name\"), or in **Twin Replay > More options » > Your clones**. **Rematch against the clones** (a game's More options) puts you back in that game's matchup at the same venue and court, everyone else played by their clone.",
          "**Sharing:** only your own clone (made with This is me) can be sent: **Share...** in Your clones makes a small file (a few KB: counts of what you did, no video); your friend opens it with **Open a friend's clone...**. A clone you made from your video of someone else is labeled \"Built from your video\" and stays on this device; to play their clone together, they make and share their own.",
          "Honest limits: a clone copies tendencies the video can show (positions, shot kinds, timing); it can't copy touch or spin exactly, and the video can't tell a winner from an error, so how often their shots end rallies only nudges the clone's accuracy.",
        ],
      },
      { h: "Go Live: friends watch your real game in 3D" },
      "**Real Games > Go Live** (or Game > Go Live...) streams a real game as you play it: your buddies watch it live in Pickleball 98, the athletes moving where you all move, at your venue and court.",
      {
        list: [
          "Pick the venue and court and type the players' names (near side = by the phone). **Point the camera**: put the phone on the back fence, on its side, the whole court in the picture; tap the four corners like in Twin Replay, then **Go live**. Your buddies get a notice (and a push) saying you're live; **Share the link** sends it to anyone else.",
          "While live, the phone reads the players and listens for the paddle; the little court in the corner shows who it's following. Tap **Point: near / Point: far** after each rally to keep the score (side-out, with the full call) for everyone watching.",
          "**Watching**: tap the notice (or Real Games > a buddy \"is live\", or the LIVE strip in My Park at that venue). The game plays about a second behind real time, with Broadcast, Side, Top and Follow cameras, the score, reactions, how many are watching, and **⟲ 10 s** to see the last moment again (**Go live** catches up). In **My Park** at the same venue the real players are on that court as you walk by.",
          "**End broadcast** stops it; the game is kept in your **Twin Replay** games (positions and hits, no video), and viewers can keep a copy too.",
          "Only where everyone is, the hits and the score leave the phone: never the picture or the sound. A slower phone streams a little less smoothly (the players are carried along between readings); a phone's graphics chip reads several pictures a second.",
        ],
      },
      { h: "Coach: what your film says about your game" },
      "**Coach** (Real Games > **Coach**, or a Twin Replay game's **Stats > Coach ... on this game**) reads your part of your filmed games and compares 13 habits with what Rookie, Club, Pro and Legend players do: getting to the kitchen line after the return (or your team's third shot), a split step right as they hit, paddle up at the line, getting back to your spot, speed around the court, third shots that work, dinks kept in play, speeding up only high balls, resets from mid-court, serve and return depth, how often your shot ends the point, and spacing with your partner.",
      {
        list: [
          "**Your game**: each habit with your number, the target level's number and a verdict (On target, Close, Work on it, Need more film), plus a level estimate with an honest range. Tap a habit for what it means and **Watch** buttons: the replay jumps to a real moment from your film, slowed down, with a **see-through player doing it the Pro way** beside you (for movement habits).",
          "**Plan**: **Make my plan** picks your three biggest fixable weaknesses and builds three short practice sessions from Pickleball 98's drills (sized to how big the gap is), with three cues to remember. **Start** opens the drill. The cues also show on your Real Games sessions.",
          "**Progress**: each game you're in adds a point to a small chart per habit, with the target line; it says better, worse or steady. Coach also counts the weeks in a row you filmed or practiced.",
          "Pick yourself in each game (Coach asks; More options lists them) and your target level (More options). More games make it surer: each habit says how many times it was seen.",
          "Honest limits: it's only as good as Twin Replay's reading of the video; the ball isn't tracked (shot kinds come from where people stood and moved), and a winner and an error look the same. \"Paddle up\" needs games read after this update.",
        ],
      },
      { h: "How a good player plays" },
      {
        steps: [
          "**Serve deep** (and return deep): it keeps the other side back at their baseline.",
          "**Let it bounce twice:** the serve and the return must bounce before anyone volleys.",
          "**Returning? Come in.** After a deep return, go straight to the kitchen line.",
          "**Serving? Drop the third shot** softly into their kitchen, then move up together.",
          "**Live at the kitchen line,** but never volley in the kitchen or let your momentum carry you in after a volley.",
          "**Dink patiently,** low and cross-court, until a ball comes up above the net. Then **speed it up** at their hip or shoulder.",
          "**In trouble mid-court? Reset:** a soft tap into their kitchen, then step in.",
          "**In doubles, move as a unit** with your partner; a ball down the middle goes to the player with the forehand there.",
        ],
      },
      { h: "One button to hit" },
      "Aim at their court, then press and hold **hit**, and let go just before the ball reaches you (the marker on the meter in the green). How long you held it decides the pace:",
      {
        list: [
          "A quick **tap** is soft: a dink at the kitchen line, or a drop or reset from farther back.",
          "A long **hold** is hard: a drive, a speed-up or a counter.",
          "A soft ball aimed deep goes up high: a lob.",
        ],
      },
      "The little ring on the ball turns orange when you'll meet it above the net: that one you can attack. Below the net, keep it soft. To **serve**, hold hit to fill the serve meter and let go in the green.",
      "With the mouse or keys (and Classic touch), a small dot on their court shows where your shot will go, colored by the pace you're holding (blue soft, yellow firm, orange hard). There's no line showing the ball's path: you read the ball, not a guide. Your paddle leaves a short trail through each swing (Settings > Swing trail turns it off).",
      { h: "Swipe trail" },
      "On a touch screen, the swipe you just made is drawn on the screen as you make it: a smooth stroke that follows your finger, thin where you started and full at your fingertip. It takes the color of the shot (blue soft, yellow firm, orange hard, purple a lob, gray a miss) and fades away about half a second after you lift. With Classic controls you get a small ripple where you touch instead, and a bigger one, in the pace's color, where you let go. Turn it off in Settings > Show swipe trail (or Options > Show Swipe Trail).",
      { h: "The sound" },
      "The ball sounds like real pickleball: the bright \"pock\" of the paddle face ringing at about 1,200 Hz for a few hundredths of a second, softer on a dink, sharper on a drive or a put-away, duller off the edge of the paddle. Each paddle design rings a little differently. Bounces are a lower, duller \"tock\", the net a soft thud and rattle, and the fence a metallic clatter. Shots far away are quieter and a little duller. The volume follows the taskbar's speaker.",
      { h: "On screen" },
      "During a match the screen keeps just the score, Pause, one hint line for your first few points, and the controls. What the umpire and the crowd say comes up one line at a time in the middle and goes away by itself. The camera (Broadcast, TV high, Sideline, Behind you) is in the pause menu (or press C); Broadcast, high behind you, is the clearest. TV cuts to the server between points are optional (Settings).",
      { h: "Controls" },
      {
        keys: [
          ["W A S D or the arrows", "Move"],
          ["Mouse", "Aim (point at their court)"],
          ["Click, Space, J or K", "Hit (hold for pace)"],
          ["C", "Change the camera"],
          ["P", "Pause"],
        ],
      },
      {
        phone: "You always move your player yourself: drag on the move pad (bottom left, or bottom right: Pause > Settings > Move pad). Nothing moves your player for you. The first time you play you pick how you hit, and you can switch any time in Pause > Settings > Touch controls. **Swipe:** put a finger down anywhere off the pad and swipe up toward where the ball should go, letting go as the ball comes: the direction is where across their court, the length how deep, the speed the pace (a quick flick is hard, a slow swipe soft, a slow long swipe a lob); a tap is a soft touch shot (a dink). To serve, swipe the same way. **Classic:** touch their court to aim (elsewhere, drag to steer), hold for pace and let go as the ball comes.",
        computer: "Move with the keys, aim with the mouse, and click (or press Space) to hit. Two players on one keyboard: Player 1 uses W A S D and F, Player 2 the arrows and L; while holding hit, your move keys steer the aim. A gamepad works too. Change any key in **Controls**.",
      },
      { h: "The Locker Room" },
      "Open **My Player** on the title screen and pick **Locker Room...** (or Game > Locker Room...) to dress any player. Drag the player to turn them around, and pick **Jogging** to see the kit move.",
      {
        list: [
          "**Body:** skin, hair and hair color, a beard, height and build; **Plays** (right- or left-handed) and **Pro style** (a compact all-court game with a one-handed backhand, or an aggressive two-hander with a two-handed backhand).",
          "**Kit:** a theme (Classic whites, Club colors, Pro kit, Beach, Winter, Retro 80s/90s, Casual) and its style, your two kit colors, then any top, bottom and socks.",
          "**Gear:** hats (caps, visor, headband, bucket hat, beanie), sunglasses, wristbands, gloves and shoes.",
          "**Paddle:** a design and its colors.",
        ],
      },
      "Your look is saved with your user profile and goes with you online, so other people see it. **Auto by venue** puts everyone in the venue's kit (beach kit at Sandy Point, winter kit at Frost Hollow); **Computer players: Random kits** dresses the computer's players in kits of their own.",
      { tip: "Settings > Graphics: Medium and High show the full players with their clothes; Low draws them simply (colors and the main pieces) for slow phones." },
    ],
    related: ["online-play", "touch-controls", "game-trouble", "voice-chat"],
  },
  {
    id: "shred",
    book: "games-action",
    title: "Shred 98",
    summary: "A rock rhythm game: play the notes as they cross the line, with six original songs.",
    keywords: ["rhythm game", "guitar", "frets", "strum", "star power", "rock meter", "set list", "calibrate"],
    programs: ["Shred 98"],
    body: [
      "Notes (gems) scroll down five lanes toward the frets at the bottom. Play each one as it crosses the line. Hit notes keep the guitar playing; miss one and it cuts out until you're back on track. There are six original songs, from Garage Days to Voltage Cathedral.",
      { h: "Controls" },
      {
        keys: [
          ["A S D F G (or 1-5)", "The five frets"],
          ["Enter, Space, Up or Down", "Strum (with Easy strum off)"],
          ["Shift or Backspace", "Star power"],
          ["W or Right arrow", "Whammy"],
          ["Esc or P", "Pause"],
        ],
      },
      {
        phone: "Tap the lanes at the bottom of the screen, with two fingers for two-note chords. Hold your finger on long notes, and wiggle it for whammy. The lightning button unleashes star power.",
        computer: "With **Easy strum** on (it's on to start), pressing a fret plays the note. Turn it off in Options for the real thing: hold the frets, then strum. A gamepad works too.",
      },
      { h: "Playing well" },
      {
        list: [
          "**Chords** are two or three gems side by side: play them together. **Sustains** have a tail: hold until it ends for bonus points.",
          "Every 10 notes in a row bumps your multiplier, up to 4x. A miss resets it.",
          "Hit every glowing star-shaped gem to charge **star power**, then unleash it to double your multiplier.",
          "The **rock meter** shows how the crowd feels. Bottom out and you're booed off stage (unless No-Fail is on in Options).",
        ],
      },
      { h: "Career and practice" },
      "Finish songs on Easy, Medium, Hard or Expert to earn 1 to 5 stars. Stars open new venues. **Practice** lets you slow a song down and loop a tricky part.",
      { tip: "Notes feel late or early? Try **Calibrate Lag** on the title screen, especially with Bluetooth headphones." },
    ],
    related: ["touch-controls", "no-sound"],
  },
  {
    id: "pinball",
    book: "games-action",
    title: "Pinball: Blue Screen",
    summary: "A 90s-style PC pinball table themed on 98ish: missions, ramps, locks and multiball.",
    keywords: ["pinball", "flippers", "plunger", "nudge", "tilt", "multiball", "missions", "blue screen", "ramp", "skill shot", "jackpot", "ranks"],
    programs: ["Pinball"],
    body: [
      "Pull the plunger back and let go to launch the ball. Keep it out of the drain with the flippers. You have 3 balls. The left flipper button also works the little flipper on the upper left.",
      { h: "Controls" },
      {
        keys: [
          ["Z, Left Shift or Left arrow", "Left flippers"],
          ["/, Right Shift or Right arrow", "Right flipper"],
          ["Space or Down (hold, let go)", "Plunger"],
          ["X, . or Up arrow", "Nudge the table"],
          ["F2", "New game"],
          ["F3", "Pause or resume"],
        ],
      },
      {
        phone: "Hold the left or right half of the table for those flippers (both at once works). With the ball in the shooter lane, **drag the plunger down** and let go (or hold **HOLD**). Tap **NUDGE**, or give the phone a shake, to bump the table.",
        computer: "Use the keys above, or click the halves of the table. Hold the plunger key longer for a stronger launch. A gamepad works too: bumpers or triggers flip, A launches.",
      },
      { h: "The table" },
      {
        list: [
          "**M-S-G** lanes up top: light all three to raise the end-of-ball bonus (the flippers move the lit lanes). A launch into the blinking lane is a **skill shot**.",
          "**Start** pop bumpers, slingshots, and the **Hourglass** spinner in the left orbit.",
          "Knock down **9-8-I-S-H** to light the lock, then shoot the **Blue Screen**. Three locked balls start **multiball**: the **My Computer** ramp scores jackpots, the Blue Screen a super jackpot.",
          "The **Floppy drive** relights **Restore**, which kicks a ball back from the left outlane once, and collects extra balls.",
          "The **Hard Drive** is a captive ball: hit it hard enough to bump it to the top.",
          "Nudging can save a ball, but too much is a **TILT**.",
        ],
      },
      { h: "Missions" },
      "The display shows the current mission. Each one done ranks you up, from Intern to Sysadmin; ranks 3 and 6 light an extra ball at the Floppy drive. After Sysadmin the missions go round again and ask for more.",
      {
        table: {
          head: ["Mission", "What to do"],
          rows: [
          ["Dial-up", "Spin the Hourglass 30 times"],
          ["Virus Scan", "Knock down 9-8-I-S-H"],
          ["Defragment", "Shoot the My Computer ramp 3 times"],
          ["Send an IM", "Light M-S-G up top"],
          ["Save to Floppy", "Sink the Floppy drive twice"],
          ["Surf the Web", "Loop the orbits twice"],
          ["Disk Cleanup", "Bump the Hard Drive to the top twice"],
            ["Install Update", "Lock 3 balls in the Blue Screen for multiball"],
          ],
        },
      },
      "Game > **High Scores** keeps your ten best games, with your initials (each person on the computer has their own).",
    ],
    related: ["touch-controls", "critterpinball"],
  },
  {
    id: "critterpinball",
    book: "games-action",
    title: "Critter Catch Pinball",
    summary: "Pinball where you catch critters: reveal them, hit them, evolve them, travel the map and fill your Critter Dex.",
    keywords: ["pinball", "critters", "catch", "monsters", "creatures", "evolve", "evolution", "dex", "collection", "bonus stage", "boss", "Sparkit", "Ember", "Tide", "map"],
    programs: ["Critter Catch Pinball"],
    body: [
      "A pinball game about catching critters, in the spirit of the critter-catching pinball games of the late 90s, with 98ish's own 47 critters. Pick the **Ember** table (meadows, forests, a volcano) or the **Tide** table (beaches, reefs, a glacier): each has its own critters and areas. You have 3 balls.",
      { h: "Controls" },
      {
        keys: [
          ["Z, Left Shift or Left arrow", "Left flipper"],
          ["/, Right Shift or Right arrow", "Right flipper"],
          ["Space or Down (hold, let go)", "Plunger"],
          ["Both flippers, or Space", "Pick the critter to evolve"],
          ["X, . or Up arrow", "Nudge the table"],
          ["F2 / F3", "New game / pause"],
        ],
      },
      {
        phone: "Hold the left or right half of the table for that flipper. With the ball in the shooter lane, **drag the plunger down** and let go (or hold **HOLD**). Tap **NUDGE** or shake the phone to bump the table.",
        computer: "Use the keys above, or click the halves of the table. A gamepad works too: bumpers or triggers flip, A launches.",
      },
      { h: "Catching critters" },
      {
        list: [
          "The **ramp** lights two letters of **C-A-T-C-H**, an **orbit loop** (up one side, down the other) lights one.",
          "With CATCH lit, sink the **Den**. A mystery critter from the area you're in shows on the screen in the middle of the table.",
          "Hit the **bumpers** to reveal it tile by tile. Then it comes out: hit it 3 times (4 for rare ones) before the timer runs out, and it's yours.",
          "Rarer critters live in the far areas. A better ball makes them likelier.",
        ],
      },
      { h: "Evolving, the map and bonus stages" },
      {
        list: [
          "Knock down **E-V-O** to light Evolution at the Den. Sink it, pick one of this game's catches with the flippers (both flippers to choose), hit the 3 flashing shots for items, then sink the Den again.",
          "3 ramp shots light **MAP** at the **Cave**: sink it to travel to another area. After 3 moves in a game, the far areas open.",
          "Every 3 catches or evolutions light **BONUS** at the Cave: **Burrow Bash**, **Phantom Hall** or **Tidal Titan**. Beat the boss before time runs out to catch it. Losing the ball in a bonus stage doesn't cost you a ball.",
          "The top lanes upgrade the ball: Super (2x points), Hyper (3x), Master (5x). Hyper and Master hits count double on critters. An upgrade wears off after a minute.",
          "Spin the spinner to charge **Sparkit**: it kicks a ball back from the outlane it's standing at (each flipper moves it to its side).",
          "Catching or evolving 5 and 10 critters in a game gives an extra ball.",
        ],
      },
      { h: "The Critter Dex" },
      "Game > **Critter Dex** (or Critter Dex on the start screen) shows every critter you've seen and caught on both tables: caught ones in color with their Dex page, seen ones as a shadow. It and the high scores (one list per table) are kept in this browser, for each person on the computer separately.",
    ],
    related: ["pinball", "touch-controls"],
  },
  {
    id: "downhill",
    book: "games-action",
    title: "Downhill",
    summary: "Ski as far as you can, jump ramps and dodge rocks.",
    keywords: ["skiing", "ski", "slalom", "ramp", "jump", "tilt to steer", "SkiFree"],
    programs: ["Downhill"],
    body: [
      "Ski down the mountain as far as you can. Your score is the distance in meters plus style points. After 2,000 m, something big and furry comes down the mountain...",
      { h: "Controls" },
      {
        keys: [
          ["Left / Right (or A / D)", "Turn"],
          ["Down (or S)", "Point straight downhill"],
          ["Up (or W)", "Dig in to slow down"],
          ["Space", "Hop, or spin in the air"],
          ["F2", "Start over"],
          ["P", "Pause"],
        ],
      },
      {
        phone: "Touch and hold where you want the skier to go. Use the **Jump** button to hop. Options > **Tilt to Steer** lets you tilt the phone instead.",
        computer: "Use the arrow keys, or steer with the mouse: the skier heads toward the pointer, and a click jumps.",
      },
      { h: "Tricks and points" },
      {
        list: [
          "Hop over rocks and stumps.",
          "Hit a ramp for a big jump, and press Space in the air to spin. Land before the spin ends!",
          "Ski between the flags of a slalom gate for points.",
          "Turn all the way across the slope to stop.",
        ],
      },
    ],
    related: ["touch-controls"],
  },
  {
    id: "spectra",
    book: "games-action",
    title: "SPECTRA",
    summary: "Fly down a glowing tunnel and slip through the gaps.",
    keywords: ["tunnel", "SPECTRA", "shards", "Overdrive", "multiplier", "3D"],
    programs: ["SPECTRA"],
    body: [
      "Steer the light down an endless, colorful tunnel. Spin around the tunnel to fly through the **gaps** in each gate. Grab **shards** to raise your multiplier, and fill your meter to unleash **Overdrive**: double speed and double points for a few seconds.",
      {
        keys: [
          ["Left / Right (or A / D)", "Spin around the tunnel"],
          ["Space", "Overdrive (when the meter is full)"],
          ["P or Esc", "Pause"],
          ["M", "Mute"],
        ],
      },
      {
        phone: "Drag (or hold the arrow buttons) to spin around the tunnel. Tap the lightning button for Overdrive.",
        computer: "Use the keys above, or drag with the mouse.",
      },
      "Your best score is kept on this device.",
      { warning: "SPECTRA has flashing colors and fast motion." },
      { note: "SPECTRA needs 3D graphics (WebGL). If your browser can't do it, the game says so." },
    ],
    related: ["hover", "game-trouble"],
  },
  {
    id: "hover",
    book: "games-action",
    title: "Hover",
    summary: "A neon spirograph that bursts open when you touch it.",
    keywords: ["spirograph", "neon", "animation", "screensaver-like"],
    programs: ["Hover"],
    body: [
      "Hover isn't really a game: it's a glowing neon spirograph to play with.",
      {
        phone: "Tap the middle of the drawing to burst it open, and tap again to bring it back together.",
        computer: "Move the mouse over the middle (where it says \"Hover here\") and watch it burst outward. Move away and it pulls back in.",
      },
      { tip: "With Reduce Motion turned on (in Accessibility Options, or on your iPhone), it keeps spinning, just more gently." },
    ],
    related: ["spectra", "accessibility"],
  },

  // ---------------- Cards and board games ----------------
  {
    id: "solitaire",
    book: "games-cards",
    title: "Solitaire",
    summary: "Classic Klondike solitaire with Draw One or Draw Three.",
    keywords: ["Klondike", "cards", "Draw Three", "Vegas scoring", "card backs", "patience"],
    programs: ["Solitaire"],
    body: [
      "Build four piles up by suit, from ace to king, at the top right. In the row below, stack cards down in alternating colors (red on black, black on red). Only a king can go in an empty space.",
      { h: "How to move cards" },
      {
        list: [
          "Click the deck to deal. When it's empty, click it again to turn the pile over.",
          "Drag a card (or a run of cards) to move it.",
          "Click a face-down card to turn it over.",
          "Double-click a card to send it up to its suit. Right-click sends everything that can go up.",
        ],
      },
      { phone: "Tap a card to pick it up, then tap where it goes. Dragging works too.", computer: "Drag, click and double-click as above." },
      {
        keys: [
          ["F2", "Deal a new game"],
          ["Ctrl+Z", "Undo"],
        ],
      },
      { h: "Options" },
      "Game > **Options** chooses Draw One or Draw Three, Standard, Vegas or no scoring, a timed game and auto-finish. Game > **Deck** picks the card back.",
    ],
    related: ["freecell", "hearts"],
  },
  {
    id: "freecell",
    book: "games-cards",
    title: "FreeCell",
    summary: "The solitaire game where almost every deal can be won.",
    keywords: ["FreeCell", "free cells", "home cells", "cards", "game number", "solitaire"],
    programs: ["FreeCell"],
    body: [
      "Move every card to the four **home cells** at the top right, building each suit up from the ace. In the columns, stack cards down in alternating colors. The four **free cells** at the top left hold one card each, and any card can go in an empty column.",
      "You can move several cards at once when there are enough free cells and empty columns to shuffle them through. Cards that are no longer needed go home on their own.",
      { phone: "Tap a column, then tap where its card goes. Dragging works too.", computer: "Click a column, then click where it goes, or drag cards. Double-click sends a card home (or to a free cell)." },
      {
        keys: [
          ["F2", "New game"],
          ["F3", "Select a game by number"],
          ["F4", "Statistics"],
          ["F5", "Options"],
          ["F10", "Undo"],
        ],
      },
      { tip: "Every game from 1 to 32000 is the deal you remember, and all but one can be won. Use Select Game to replay a number." },
    ],
    related: ["solitaire"],
  },
  {
    id: "hearts",
    book: "games-cards",
    title: "Hearts",
    summary: "Avoid hearts and the queen of spades, at a table of four.",
    keywords: ["Hearts", "queen of spades", "shoot the moon", "tricks", "passing cards"],
    programs: ["Hearts"],
    body: [
      "Hearts is played at a table of four. Avoid taking hearts (1 point each) and the queen of spades (13 points). The game ends when someone reaches 100, and the lowest score wins.",
      { h: "Rules" },
      {
        list: [
          "Before each hand, pass three cards: left, then right, then across, then no pass.",
          "The 2 of clubs leads first. Follow suit if you can; the highest card of the suit led wins the trick.",
          "Hearts can't be led until one has been played.",
          "Take every heart and the queen to **shoot the moon**: everyone else gets 26 points instead.",
        ],
      },
      { h: "Playing with people" },
      "Opening Hearts from the Start menu sets up a table. Click **Deal** to play against three computer players, or invite people who are online first (the list is on the table). The computer plays any empty seats.",
      { phone: "Tap a card to play it (or to choose it for passing).", computer: "Click a card to play it (or to choose it for passing)." },
      "Game > **Score** shows the scores so far.",
    ],
    related: ["game-invites", "last-card", "solitaire"],
  },
  {
    id: "last-card",
    book: "games-cards",
    title: "Last Card",
    summary: "The card game where you match colors and numbers, and shout LAST CARD!",
    keywords: ["Last Card", "Wild", "Draw Two", "Draw Four", "Skip", "Reverse", "house rules", "stacking", "7-0", "jump-in"],
    programs: ["Last Card"],
    body: [
      "**Get rid of all your cards.** On your turn, play a card that matches the top card's color or its number or symbol, or play a **Wild** and pick the color. Nothing fits? Draw a card.",
      { h: "Action cards" },
      {
        list: [
          "**Skip:** the next player misses a turn. **Reverse:** play changes direction (with two players it works like a Skip).",
          "**Draw Two:** the next player draws 2 and misses a turn.",
          "**Wild Draw Four:** pick a color; the next player draws 4 and misses a turn, unless they challenge it and you were bluffing.",
        ],
      },
      { h: "Last card!" },
      "Down to two cards? Press **LAST CARD!** before you play your next-to-last card. Forget, and anyone can **Catch** you for 3 seconds: you draw 2.",
      "Go out first to win the round. You score the points left in everyone's hands (numbers at face value, action cards 20, wilds 50). First to the target wins.",
      { h: "Controls" },
      { phone: "Tap a card, or drag it up, to play it.", computer: "Click a card, or drag it up, to play it. Press {{D}} to draw and {{K}} to keep a drawn card." },
      { h: "House rules and players" },
      "The title screen shows **Play the Computer** and **Play Online**; **More options »** sets how many opponents and how hard, and has **House Rules...** and **How to Play**. Game > **House Rules** turns on stacking, 7-0, jump-in, draw until you can play, forced play, challenges and extra cards, or picks a preset (Classic, Party, Mayhem, Quick). Play against up to 9 computer players, or 2 to 10 people online with [[online-play|Play Online]].",
    ],
    related: ["online-play", "hearts"],
  },
  {
    id: "monster-duel",
    book: "games-cards",
    title: "Monster Duel",
    summary: "A monster card duel with 170+ original cards, a Deck Builder and card packs.",
    keywords: ["Monster Duel", "trading cards", "Life Points", "deck builder", "card packs", "tribute", "spells", "traps", "chain"],
    programs: ["Monster Duel"],
    body: [
      "Summon monsters, cast spells and set traps to bring your opponent's **Life Points** (8000 to start) down to 0. If you need to draw and your deck is empty, you lose.",
      { tip: "New to it? Choose **Tutorial (start here!)** on the title screen, or Tutorial Duel in the Game menu, for a guided first duel." },
      "The title screen opens with **Duel the Computer** and **Play Online** (and Card Packs while some are waiting). **More modes »** has the Tutorial (once you've done it), the Deck Builder, Card Packs and the Rules.",
      { h: "A turn, in short" },
      {
        steps: [
          "**Draw** a card (not on the very first turn).",
          "**Main Phase:** summon or set one monster, play spells, set traps.",
          "**Battle:** attack with your monsters. With no monsters in the way, you hit their Life Points directly.",
          "**Main Phase 2**, then **End** your turn (discard down to 6 cards).",
        ],
        title: "Each turn:",
      },
      "Level 5 and 6 monsters need one **tribute** (send one of your monsters to the Graveyard); Level 7 and up need two. When a card is played, the other player may respond, building a **chain** that resolves last-in, first-out. Help > **Rules** has the full rules.",
      { h: "Controls" },
      {
        phone: "Tap a card to see what it can do, then pick from its menu. Press and hold a card to read it in full.",
        computer: "Click a card for its menu, or drag a card onto your rows, or an attacker onto an enemy monster. Hover a card to read it. The phase buttons in the middle move through your turn.",
      },
      { h: "Collecting" },
      "You start with every card in eight starter decks. Beat computer opponents to earn card packs (harder opponents give more), open them, and build your own decks in the **Deck Builder** (30 to 60 cards, at most 3 copies of a card). Play people with [[online-play|Play Online]].",
      { note: "Options > Ask to Respond chooses when you're asked to respond: Always, When I Can, or Never." },
    ],
    related: ["online-play"],
  },
  {
    id: "reversi",
    book: "games-cards",
    title: "Reversi",
    summary: "Trap your opponent's discs between yours to flip them.",
    keywords: ["Reversi", "discs", "flip", "Othello-style", "board game"],
    programs: ["Reversi"],
    body: [
      "Place a disc so that one or more of your opponent's discs lie in a straight line (across, down or diagonally) between it and another of your discs. Every disc you trap flips to your color.",
      "If you can't move, your turn is skipped. When neither player can move, the one with the most discs wins. Black moves first.",
      { phone: "Tap a square to place a disc.", computer: "Click a square to place a disc. Options > **Show Legal Moves** marks where you can go." },
      "From the Start menu you play the computer (Game > New Game picks Black or White). To play a person, use the **Play Online** button to invite someone who's online, or Network Neighborhood.",
      { tip: "Corners can never be flipped. Grab them, and stay off the squares next to them until you can." },
    ],
    related: ["game-invites", "chess", "checkers"],
  },
  {
    id: "chess",
    book: "games-cards",
    title: "Chess",
    summary: "Chess against the computer (three levels) or a person.",
    keywords: ["chess", "checkmate", "castle", "stalemate", "promotion", "Flip Board"],
    programs: ["Chess"],
    body: [
      "Checkmate the other king: attack it so it has no way out.",
      { phone: "Tap a piece to see where it can go, then tap the square.", computer: "Click a piece to see where it can go, then click the square, or drag the piece there." },
      {
        list: [
          "To **castle**, move your king two squares toward a rook.",
          "A pawn that reaches the far side becomes the piece you choose.",
          "Stalemate, the same position three times, 50 moves without a capture or pawn move, or too few pieces to checkmate is a draw.",
        ],
      },
      "From the Start menu you play the computer. The **Level** menu sets it to Easy, Normal or Hard, and Game > New Game picks White or Black. You can **Offer Draw** or **Resign** any time, and View > **Flip Board** turns the board around. To play a person, use **Play Online** to invite someone who's online.",
    ],
    related: ["game-invites", "chess-puzzles", "checkers", "reversi"],
  },
  {
    id: "chess-puzzles",
    book: "games-cards",
    title: "Chess Puzzles",
    summary: "Find the best move: rated puzzles, Puzzle Streak, Puzzle Rush, the Daily Puzzle and themes.",
    keywords: ["chess puzzles", "tactics", "puzzle rating", "Puzzle Rush", "Puzzle Streak", "Daily Puzzle", "mate in 2", "fork", "pin", "Lichess", "hint", "Survival"],
    programs: ["Chess Puzzles"],
    body: [
      "Each puzzle starts with your opponent's move. Then find the best reply, and keep going until it's solved: the computer answers each right move. Any move that checkmates counts.",
      { phone: "Tap a piece, then its square, or drag it.", computer: "Click a piece, then its square, or drag it there." },
      "A wrong move is shown for a moment, then taken back: try another move (**Retry**), or **View solution** to watch the answer. **Hint** shows the piece to move; press it again for the square. Chess's Game menu has **Puzzles...** too.",
      { h: "Your puzzle rating" },
      "Puzzles are picked near your rating (it starts at 1500, with a **?** while it's still settling). Solve one without a mistake and it goes up; a wrong move or the solution lowers it, by more for an easy puzzle. Solving with a hint doesn't raise it. More options > **Reset rating** starts over.",
      { h: "Other ways to play (More options or the Game menu)" },
      {
        list: [
          "**Puzzle Streak:** each puzzle is harder than the last. One mistake ends it, and you can skip one puzzle per streak.",
          "**Puzzle Rush:** as many as you can in 3 or 5 minutes, or with no clock in **Survival**. Three wrong moves and it's over. Your best scores are kept.",
          "**Daily Puzzle:** the same puzzle for everyone today.",
          "**Theme:** practice one idea: Mate in 1, 2 or 3, forks, pins, skewers, sacrifices, endgames and more.",
          "**History:** every puzzle you've tried; **Replay** any of them (it doesn't change your rating).",
        ],
      },
      { note: "The 4,000+ puzzles come from the Lichess puzzle database (lichess.org), which Lichess released into the public domain (CC0). They're built in, so puzzles work offline and never contact Lichess. Your rating and history stay on this device." },
    ],
    related: ["chess", "checkers"],
  },
  {
    id: "checkers",
    book: "games-cards",
    title: "Checkers",
    summary: "Checkers online with a room code, Quick Match, or against the computer.",
    keywords: ["checkers", "draughts", "king", "jump", "board game"],
    programs: ["Checkers"],
    body: [
      "Move diagonally forward one square. Jump an opponent's piece to capture it. If you can jump, you must, and keep jumping while you can. Reach the far side to become a king: kings can move backward too.",
      "Take all of your opponent's pieces, or leave them with no moves, to win. Black moves first.",
      { phone: "Tap a piece, then tap where it goes.", computer: "Click a piece, then click where it goes." },
      "Checkers opens to the online choices: **Quick Match**, **Play the Computer** to start right away, and under **Play with friends**: **Create Room** (a code to share), **Join with Code** and **Invite Someone**. See [[online-play]]. During a game you can offer a draw, resign, or ask for a rematch from the Game menu.",
    ],
    related: ["online-play", "chess", "reversi"],
  },
  {
    id: "battleship",
    book: "games-cards",
    title: "Battleship",
    summary: "Hide your fleet, then take turns firing to sink theirs.",
    keywords: ["Battleship", "ships", "fleet", "grid", "sink"],
    programs: ["Battleship"],
    body: [
      "Place your five ships on your grid, then take turns firing at the other grid, one shot each. A white dot is a miss, red is a hit. Sink all five of their ships to win.",
      { h: "Placing your ships" },
      {
        phone: "Drag each ship from the dock onto your grid (or tap it to drop it in). Drag a placed ship to move it, and tap it to turn it. **Random** places them all for you.",
        computer: "Drag each ship from the dock onto your grid (or click it to drop it in). Drag a placed ship to move it; click it, right-click it or press {{R}} to turn it. **Random** places them all for you.",
      },
      "A ship that won't fit shows red and goes back where it was.",
      "Ships can touch but not overlap.",
      "From the Start menu you play the computer. To play a person, use **Play Online** to invite someone who's online, or right-click them in Network Neighborhood.",
    ],
    related: ["game-invites", "network-neighborhood"],
  },

  // ---------------- Puzzles and word games ----------------
  {
    id: "minesweeper",
    book: "games-puzzle",
    title: "Minesweeper",
    summary: "Clear the minefield without stepping on a mine, alone or in a race.",
    keywords: ["Minesweeper", "mines", "flag", "Beginner", "Expert", "Minesweeper Race", "best times"],
    programs: ["Minesweeper"],
    body: [
      "Find every mine without stepping on one. A number tells you how many mines touch that square.",
      { h: "Controls" },
      {
        phone: "Tap to uncover a square. Press and hold to place a flag, or switch to **Flag** mode.",
        computer: "Left-click to uncover a square. Right-click to place a flag (again for a ?). Click a number when all its mines are flagged to uncover the rest of its neighbors.",
      },
      {
        keys: [
          ["F2", "New game"],
        ],
      },
      "The Game menu picks Beginner, Intermediate, Expert or a Custom field, turns question marks on or off, and shows your **Best Times**.",
      { h: "Minesweeper Race" },
      "Game > **Play Online (Race)** invites someone who's online. You both get the same minefield. First to clear it wins; step on a mine and you lose.",
          ],
    related: ["game-invites", "block-ten"],
  },
  {
    id: "block-ten",
    book: "games-puzzle",
    title: "Block Ten",
    summary: "Fit blocks onto a 10 by 10 board and clear rows and columns.",
    keywords: ["Block Ten", "block puzzle", "Daily Challenge", "Blast", "rows and columns", "streak"],
    programs: ["Block Ten"],
    body: [
      "Drag a piece from the tray onto the board. Fill a whole row or column and it clears. Pieces can't be turned, so plan ahead!",
      "When all three pieces are down you get three more. The game ends when none of the pieces left fits anywhere (pieces with no room turn gray).",
      { h: "Scoring" },
      {
        list: [
          "Every block placed is worth 1 point. A line scores 10; two at once score 30, three score 60, and so on.",
          "Clear lines on moves in a row for a streak bonus.",
          "Empty the whole board for 300 more.",
        ],
      },
      { h: "Modes" },
      "**Daily Challenge** deals everyone the same pieces today. **Blast** gives you three minutes. You get one **Undo** per game ({{Ctrl+Z}}), and {{F2}} starts a new game. The Options menu has color themes: Classic 98, Neon and Pastel.",
      { phone: "Drag pieces with your finger. The piece sits a little above your fingertip so you can see where it goes.", computer: "Drag pieces with the mouse." },
    ],
    related: ["tetris", "minesweeper"],
  },
  {
    id: "lan-party",
    book: "games-online",
    title: "LAN Party 98",
    summary: "Shareware DOOM and Heretic by yourself or on a LAN with friends, and Flash movies in the Shockwave Arcade.",
    keywords: ["LAN Party", "DOOM", "Heretic", "DOS games", "MS-DOS", "deathmatch", "co-op", "IPX", "multiplayer", "shareware", "Flash", "swf", "Shockwave", "Ruffle", "js-dos"],
    programs: ["LAN Party 98"],
    body: [
      { img: "/assets/program_icons/lanparty.svg", alt: "LAN Party 98 icon" },
      "**LAN Party 98** (Start > Programs > Games) plays real 1990s DOS games: the shareware episodes of **DOOM** (id Software, 1993) and **Heretic** (Raven Software, 1994), exactly as they were handed around on floppies. Tap **Play** to play alone.",
      { h: "Playing with friends" },
      {
        list: [
          "Tap **With Friends...**, pick how many players (2 to 4) and **Deathmatch** or **Co-op**, then **Host Game**. A **code** appears at the top; send it with **Invite...** (an IM) or tell your friends.",
          "Friends open LAN Party 98 and type the code under **Join a friend's LAN game** (your buddies see your game listed there too).",
          "The game starts by itself once everyone has joined, just like an old office LAN: every player's DOSBox talks over a real IPX network, phone to phone.",
        ],
      },
      { h: "Controls" },
      "With a keyboard: arrows move, **Ctrl** fires, **Space** opens doors, **Shift** runs, **Alt** strafes, **1-7** pick weapons, **Esc** is the menu. On a phone, on-screen buttons do the same; the gear moves and resizes them.",
      { h: "Saving" },
      "Save from the game's own menu (Esc > Save Game). LAN Party 98 keeps what the game wrote in **C:\Games\Saves** (for example DOOM.SAV), so your saves are yours and sync like any file.",
      { h: "Shockwave Arcade" },
      "Flash movies and games (.swf) play with **Ruffle**. Try the demo, or **Open .swf...** to add one from your phone or computer (it's copied to C:\Games\Flash). Flash movies can't reach the internet from here.",
      { phone: "The first game downloads the DOS player (about 2 MB) and the game (2-3 MB) once. DOOM wants a phone in landscape." },
      { note: "The games are the unmodified shareware releases, which their makers asked people to share. Game traffic goes directly between the players; the 98ish server only passes the game's code, and js-dos's free network service (net.dos.zone) connects the players (see [[privacy-third-parties]])." },
      { open: "LAN Party 98", label: "Open LAN Party 98" },
    ],
    related: ["virtual-pc", "online-play"],
  },
  {
    id: "imposter",
    book: "games-puzzle",
    title: "Imposter",
    summary: "The party word game: everyone knows the secret word except the imposter. Give clues, then vote.",
    keywords: ["Imposter", "impostor", "party game", "secret word", "who's the imposter", "pass the phone", "undercover", "spy", "word game", "vote"],
    programs: ["Imposter"],
    body: [
      "Everyone gets the same secret word, except the imposter, who doesn't know it. Take turns giving a clue about the word, talk it over, then vote for who you think the imposter is. Crew: show you know the word without giving it away. Imposter: blend in!",
      { h: "Two ways to play" },
      {
        list: [
          "**Pass the phone** (the main screen): type everyone's names (3 to 20 players) and press **Start**. The phone asks for each player in turn: they tap, look at their card, and tap **Hide it** before passing it on.",
          "**Play Online**: each person on their own phone (3 to 20). Create a room and share the code; say the clues out loud if you're together, or type them. The server deals the cards, so nobody's phone knows anyone else's. **Show my card** brings yours back any time.",
        ],
      },
      "Catch the imposter and the crew wins the round, unless the caught imposter can name the word and steal it. The crew can't say the word itself in a typed clue.",
      { h: "House rules (More options, or the online room's settings)" },
      {
        list: [
          "**Presets:** Classic, Quick (one clue round and timers), Undercover (the imposter gets a close word and isn't told), Chaos (maybe 0 to 3 imposters, guess any time).",
          "**Imposters:** how many (or a random number each round), a chance of a round with no imposter at all (then vote **No imposter**), and whether imposters know each other.",
          "**The imposter's card:** nothing, the category, a hint, or a close word (told, or not told: Undercover).",
          "**Words:** 28 family-friendly categories (pick any mix), or your own words, one per line (\"word:close word\" sets the close word too).",
          "**Clues:** said out loud or typed, 1 to 5 rounds, a clock per clue, a discussion clock (or none), who starts, and whether an imposter may go first.",
          "**Voting:** secret, open (votes show as they come in) or out loud with one shared pick; a vote clock; **No one / skip**; what a tie does (revote, nobody out, one at random, all out); one vote, or keep going until the imposters are caught.",
          "**The imposter's guess:** when caught, any time (a wrong guess loses), or never; pick from 8 words or type it.",
          "**Scoring:** on or off; a number of rounds, first to a score, or until you stop; and whether escaped imposters are revealed.",
        ],
      },
      { note: "Scoring: the crew gets 1 point each for catching the imposter, plus 1 for voting for them; an imposter gets 2 for escaping and 3 for naming the word." },
    ],
    related: ["online-play", "word-duel"],
  },
  {
    id: "word-duel",
    book: "games-puzzle",
    title: "Word Duel",
    summary: "Guess the hidden word in six tries: a daily puzzle, practice and online races.",
    keywords: ["Word Duel", "guess the word", "Daily Word", "green and yellow tiles", "Battle Royale", "Speed Rush", "Absurd", "Sabotage", "word game"],
    programs: ["Word Duel"],
    body: [
      "Guess the hidden word. Type a word and press Enter. Each tile then turns a color:",
      {
        list: [
          "**Green:** the right letter in the right spot.",
          "**Yellow:** in the word, but somewhere else.",
          "**Gray:** not in the word (or not that many times).",
        ],
      },
      { phone: "Tap the letters on the on-screen keyboard in the game, then Enter.", computer: "Type on your keyboard and press Enter. Backspace fixes a letter." },
      { h: "Ways to play alone" },
      {
        list: [
          "**Daily Word:** everyone gets the same word today. Your streak is kept, and you can share your result.",
          "**Practice:** as many words as you like.",
          "**Speed Rush:** three minutes, as many words as you can.",
          "**Multi-board:** four words at once, nine guesses; every guess goes on every board.",
          "**Hard Mode:** any hint you've found must be used in later guesses.",
          "**Absurd:** there's no word yet. Every guess, the game picks whatever dodges you best.",
          "**Custom Game:** word length (4 to 7 letters), number of guesses, timers and more.",
        ],
      },
      "The title screen shows the **Daily Word** and **Play Online**; **More modes »** has the others, Statistics and the word length.",
      { h: "Online" },
      "**Play Online** offers head-to-head races, taking turns on one board, best-of series, Battle Royale for up to 8, Co-op (vote on guesses together) and Sabotage (pick the word your opponent has to guess). Every setting can be changed. See [[online-play]].",
      { tip: "Options > **High Contrast Colors** swaps green and yellow for orange and blue." },
    ],
    related: ["online-play", "speed-typist"],
  },
  {
    id: "speed-typist",
    book: "games-puzzle",
    title: "Speed Typist 98",
    summary: "Race cars by typing: against the computer, your ghost, or people online.",
    keywords: ["typing", "typing race", "WPM", "words per minute", "accuracy", "ghost race", "Daily Prompt", "Sudden Death"],
    programs: ["Speed Typist 98"],
    body: [
      "Everyone gets the same text. After the 3-2-1, type it into the box: your car moves with every letter you get right.",
      {
        list: [
          "The current word is highlighted. A wrong letter turns red, and you have to fix it (Backspace) before you can go on.",
          "**WPM** (words per minute) counts five characters, spaces included, as one word. **Accuracy** is the share of your keys that were right.",
          "Curly quotes and long dashes from phone keyboards count as plain ones.",
        ],
      },
      { h: "Ways to race" },
      {
        list: [
          "**Race the Computer**, with race settings for length, kind of text and the computer's speed.",
          "**Race Your Ghost:** your own best run of a text.",
          "**Daily Prompt:** today's text, the same for everyone.",
          "**Practice Drills** for tricky keys, or your own text.",
          "**Play Online:** Quick Match, private rooms with a code, invitations, Best of 3 and Sudden Death. See [[online-play]].",
          "Race Your Ghost, the Daily Prompt, Practice Drills and Statistics are under **More modes »** on the title screen.",
        ],
      },
      "Options > **Strict Typing** doesn't let wrong keys in and has no backspace. In **Sudden Death**, one wrong key and you're out. Game > **Statistics** tracks your progress, and you can share a result from the results screen.",
      { phone: "Tap the race box after the countdown to bring up the keyboard.", computer: "Just start typing when the countdown ends." },
    ],
    related: ["online-play", "word-duel", "phone-keyboard"],
  },

  // ---------------- Building and strategy ----------------
  {
    id: "sunny-acres",
    book: "games-sim",
    title: "Sunny Acres",
    summary: "Farm, fill orders and build a little town, alone or together with friends.",
    keywords: ["Sunny Acres", "farming", "farm", "crops", "animals", "orders", "co-op town", "visit friends", "clovers"],
    programs: ["Sunny Acres"],
    body: [
      "Grow crops, raise animals, make goods in factories and build your farm into a town.",
      { h: "How to play" },
      {
        list: [
          "**Fields:** tap an empty field and pick a seed, then drag across other fields to plant them all. When crops are ripe, swipe across them to harvest.",
          "**Animals:** make feed at the Feed Mill, then swipe across a pen to feed them. Swipe again to collect milk, eggs or wool.",
          "**Factories:** tap one to see what it makes. Goods wait in the factory until you tap to collect them.",
          "**Orders:** the helicopter pays coins and XP for goods. Don't like an order? Skip it and a new one comes later.",
          "**The train** (from a higher level) trades goods for building materials like bricks and glass.",
          "**Town:** houses bring people, and community buildings make room for more. New factories need enough people.",
        ],
      },
      { phone: "Drag the map to look around and pinch to zoom.", computer: "Drag the map to look around; use the mouse wheel to zoom. **Move** lets you rearrange your town." },
      "Things keep growing while Sunny Acres is closed. Clovers finish anything right away; you earn them by playing.",
      { h: "Playing together" },
      "Sign on to [[messenger|98 Messenger]] to play with people:",
      {
        list: [
          "**Friends:** visit your partner's or buddies' towns, leave little signs, send gifts, and fill their help requests. Your partner can always visit; buddies can when you allow it.",
          "**Co-op Town:** farm one town together, live, with your partner or up to 4 farmers. You plant, harvest and build at the same time, with one Barn and one purse. Your own town stays just as it is.",
        ],
      },
      { note: "Played on two devices? Your town is saved with your account, and if both changed, Sunny Acres asks which one to keep (the other is kept as a backup)." },
    ],
    related: ["us-together", "messenger", "online-play"],
  },
  {
    id: "hexlands",
    book: "games-sim",
    title: "Hexlands",
    summary: "Settle, trade and build on a hex island. First to 10 points wins.",
    keywords: ["Hexlands", "settlement", "city", "road", "resources", "trading", "Bandit", "dice", "board game"],
    programs: ["Hexlands"],
    body: [
      "Build settlements, cities and roads on an island of hexagon tiles. The first to reach 10 points, on their own turn, wins.",
      { tip: "First time? Choose **More options »**, then **How to Play** on the main menu for a step-by-step lesson on a little practice island." },
      { h: "Rules in short" },
      {
        list: [
          "**Setup:** each player places a settlement and a road, then again in reverse order. Your second settlement collects one of each resource around it.",
          "**Your turn:** roll the dice. Tiles with that number pay their corners: 1 card per settlement, 2 per city. Then trade and build, then end your turn.",
          "**Costs:** road = timber + clay. Settlement = timber + clay + wool + grain. City = 2 grain + 3 ore. Development card = wool + grain + ore.",
          "**Sevens:** anyone with more than 7 cards discards half; the roller moves the Bandit (it blocks a tile) and takes a card from someone next to it.",
          "**Points:** settlement 1, city 2, Longest Road (5 or more) 2, Largest Patrol (3 or more Rangers) 2, Monument 1.",
        ],
      },
      { h: "Trading" },
      "Trade with other players by making an offer, or with the bank at 4 of a kind for 1. A settlement on a harbor gets better rates: 3:1, or 2:1 for one resource.",
      { phone: "Tap a spot on the board to build there. Pinch (or the zoom buttons) zooms in, and then you can drag the island around.", computer: "Click a spot on the board to build there. The zoom buttons (or Ctrl and the mouse wheel) zoom in." },
      "Play against 1 to 5 computer players (5 or 6 players get a big island), or people with [[online-play|Play Online]]. Game > **Game Settings** changes points to win, the map, a turn clock and house rules.",
    ],
    related: ["online-play", "sunny-acres"],
  },
]
