// 98ish Help: 98 Messenger, Mail, Internet Explorer, HomePage Studio, Network Neighborhood,
// WinPopup, YouTube '98 and the 98ish.com pages. Format: see ../helpCore.js.

export const books = [{ id: "internet", title: "Internet and friends", order: 40 }]

export const topics = [
  {
    id: "messenger",
    book: "internet",
    title: "98 Messenger",
    summary: "Chat with friends: your Buddy List, instant messages, away messages and chat rooms.",
    keywords: ["instant messages", "IM", "buddy list", "away message", "chat rooms", "SmarterChild", "AIM", "buddies", "block", "profile"],
    programs: ["98 Messenger"],
    body: [
      "98 Messenger is an old-school instant messenger. Make up a screen name, add your friends as buddies, and you can see when they're on and send them messages. It's also your key to everything else that's shared in 98ish: Mail, calls, the couples programs, file sync and online games all use your screen name.",
      { open: "98 Messenger", label: "Open 98 Messenger" },
      "First you need a screen name. See [[messenger-accounts]] for making one and staying signed on.",
      { h: "Your Buddy List" },
      "Once you're signed on, the Buddy List shows your buddies by group. People who are on right now are at the top; everyone else waits in **Offline** at the bottom. A buddy who has been idle for a while or is away looks grayed out.",
      {
        steps: ["Click the **List Setup** tab at the top of the Buddy List.", "Click **Add Buddy**.", "Type your friend's screen name and pick a group, then click OK."],
        title: "To add a buddy:",
      },
      "On the List Setup tab you can also add, rename and delete groups, and remove buddies.",
      { h: "Sending an instant message" },
      { phone: "Tap a buddy, then tap **IM** at the bottom of the Buddy List. You can also press and hold a buddy for more choices.", computer: "Double-click a buddy, or select them and click **IM**. Right-click a buddy for more choices (Call, Video Call, Get Info, Add to Address Book)." },
      "Type in the box at the bottom of the IM window and press Send. The buttons above the box change the font, size, bold, italic, underline and color of your text. The **Games** button invites the buddy to a game (Checkers, Chess, Hearts, Reversi, Battleship, a Minesweeper Race, Tetris Battle, Doodle Together, the Quiz Show or Sunny Acres co-op).",
      { note: "If your buddy is signed off but has turned on notifications, your message waits for them and their phone gets a notification. Otherwise you can only message people who are signed on." },
      { h: "Away messages" },
      "Click **Away** at the bottom of the Buddy List (or My AIM > Away Message...) and pick or write a message. Anyone who IMs you gets it as an automatic reply. Click **I'm Back** (or **Back**) when you return. If you don't touch 98ish for 10 minutes, your buddies see you as idle.",
      { h: "Chat rooms" },
      "Click **Chat** (or People > Join a Chat Room...) to join a room with more than one person. The **98ish Lobby** is where everyone hangs out; type any other name to make your own room, then invite buddies to it.",
      { h: "SmarterChild" },
      "SmarterChild is a friendly robot buddy who is always online. IM it **help** to see what it can do: jokes, trivia, the magic 8-ball, coin flips, dice, fortunes and the time.",
      { h: "Your profile, warnings and blocking" },
      {
        list: [
          "My AIM > **Edit Profile...** sets the words people see when they Get Info on you.",
          "**Get Info** (or the Info button) shows a buddy's profile and how long they've been on.",
          "**Warn** in an IM window slows down someone who's being a pest. Their warning level goes up.",
          "**Block** stops someone from sending you messages or seeing when you're on. People > Block List... shows who you've blocked.",
          "My AIM > **Sounds** turns the door-opening and message sounds on or off.",
        ],
      },
      { tip: "Closing the Buddy List window signs you off. To keep getting messages while you do other things, minimize it instead." },
    ],
    related: ["messenger-accounts", "messenger-calls", "mail", "notifications", "address-book", "game-invites"],
  },
  {
    id: "messenger-accounts",
    book: "internet",
    title: "Screen names and signing on",
    summary: "Get a screen name, sign on, and have 98ish remember you with Sign me on automatically.",
    keywords: ["screen name", "sign on", "sign off", "password", "account", "sign me on automatically", "remember me", "new account", "signed on at a different location"],
    body: [
      "Your screen name is who you are on 98ish. It works on every phone and computer you use, and it's also your mail address, your homepage address and how your partner finds you in Us.",
      {
        steps: [
          "Open 98 Messenger.",
          "Click **Get a Screen Name** under the Screen Name box.",
          "Type the screen name you want. It must be 3 to 16 characters, start with a letter, and use only letters, numbers and spaces.",
          "Type a password (at least 4 characters) twice.",
          "Leave **Sign me on automatically** checked if this is your own phone or computer, then click Sign On.",
        ],
        title: "To make a screen name:",
      },
      "If someone already has that name, you'll be asked to pick another one.",
      { h: "Signing on" },
      "Next time, type your screen name and password and click Sign On. If you get it wrong, check that Caps Lock is off. Screen names don't care about capital letters or spaces, so \"Cool Kid\" and \"coolkid\" are the same person.",
      { h: "Sign me on automatically" },
      "With this box checked, this device remembers you and signs you on by itself whenever you open 98ish, without your password. It stays remembered for 60 days after you last used it. Uncheck it on a shared or borrowed computer.",
      "To make a device forget you, open the Buddy List and choose My AIM > **Sign Off**. Signing off on purpose forgets this device.",
      { h: "One place at a time" },
      "You can be signed on in only one place at a time. If you sign on from your computer while your phone is signed on, the phone says it was disconnected because you signed on at a different location. That's normal: sign on again on whichever one you want to use.",
      { h: "Deleting your account" },
      "My AIM > **Delete My Account...** deletes the account and everything the 98ish server keeps for it, for good. See [[delete-account]].",
      { note: "The 98ish server takes a nap when nobody has used it for a while. If signing on takes a long time, wait up to a minute. See [[server-waking]]." },
      { warning: "There's no way to reset a forgotten Messenger password from here, so pick one you'll remember." },
    ],
    related: ["messenger", "server-waking", "file-sync", "privacy-server"],
  },
  {
    id: "messenger-calls",
    book: "internet",
    title: "Voice and video calls",
    summary: "Call a buddy with voice or video from 98 Messenger, and what to do if a call won't connect.",
    keywords: ["call", "video call", "voice call", "phone call", "camera", "microphone", "mute", "flip camera", "ringing", "FaceTime"],
    body: [
      "You can call any buddy who is signed on, with just your voice or with video. Calls go straight between your two devices.",
      {
        steps: [
          "Sign on to 98 Messenger.",
          "Open an IM window with your buddy and click the phone (voice) or camera (video) button at the top. Or right-click (press and hold on a phone) the buddy in your Buddy List and choose **Call** or **Video Call**.",
          "The first time, allow 98ish to use your microphone and camera when the browser asks.",
          "Wait for them to answer. A call rings for about 45 seconds.",
        ],
        title: "To call someone:",
      },
      "Paired couples can also call each other from the big buttons at the top of Us.",
      { h: "Answering" },
      "When someone calls, an Incoming Call window pops up with **Answer**, **Decline**, and a button to answer with or without video. If you're signed off but have notifications turned on, your phone gets a notification for the call, and missed calls show up in the notification bell.",
      { h: "During a call" },
      {
        list: [
          "**Mute** turns your microphone off and on.",
          "**Camera Off / Camera On** stops or starts your video.",
          "**Flip** (on phones) switches between the front and back camera.",
          "**Share Screen** (on computers that support it) shows your screen instead of your camera.",
          "**Pop Out** puts the other person's video in a little floating window, where the browser allows it.",
          "Drag your own little picture to any corner.",
          "**Hang Up** ends the call.",
        ],
      },
      { h: "Wi-Fi works best" },
      "Calls connect most reliably when both of you are on Wi-Fi. Some cellular networks, and strict school or work Wi-Fi, block direct connections between devices. If that happens, the call window says it couldn't connect after about 30 seconds. Try again with both of you on Wi-Fi.",
      { note: "On an iPhone, switching to another app pauses your camera, and locking the screen may drop the call. Keep 98ish open on screen while you talk." },
      { tip: "If the call says your camera or microphone is being used by another app, close that app (or other tabs using the camera) and try again." },
    ],
    related: ["messenger", "calls-trouble", "notifications", "us-together"],
  },
  {
    id: "mail",
    book: "internet",
    title: "98ish Mail",
    summary: "Send mail with attachments to any screen name, with an Inbox, Sent Items, Drafts and Deleted Items.",
    keywords: ["mail", "email", "e-mail", "inbox", "attachments", "send mail", "reply", "forward", "drafts", "Outlook"],
    programs: ["98ish Mail"],
    body: [
      "98ish Mail is a late-90s style mail program. Your 98 Messenger screen name is your mail address, so you can write to anyone who has a screen name, whether they're on right now or not. You need to be signed on to 98 Messenger to read and send mail.",
      { open: "98ish Mail", label: "Open 98ish Mail" },
      { h: "Folders" },
      { list: ["**Inbox**: mail people sent you.", "**Outbox**: mail being sent right now (or that couldn't be sent).", "**Sent Items**: copies of what you sent.", "**Deleted Items**: deleted mail. Delete it again to remove it for good, or click Restore to put it back.", "**Drafts**: messages you saved to finish later."] },
      {
        steps: [
          "Click **New Mail**.",
          "In **To**, type one or more screen names, separated by commas. People in your Address Book are suggested as you type. Add more people in **Cc** if you like.",
          "Type a subject and your message. Messages are plain text.",
          "To add a file, click **Attach** and pick a document, picture or sound from your 98ish drive.",
          "Click **Send**. Or click **Save** to keep it in Drafts for later.",
        ],
        title: "To write a message:",
      },
      "A message and its attachments can be at most 1 MB in all. Big photos may be too large: a smaller copy from Paint or Photos will fit.",
      { h: "Reading and answering" },
      "Click a message to read it. Use **Reply**, **Reply All** or **Forward** in the toolbar. **Send/Recv** checks for new mail. To keep someone, click the button next to their name to add the sender to your Address Book.",
      "An attachment has **Open** and **Save** buttons. Either way, it's saved in the **Mail Attachments** folder inside My Documents.",
      { tip: "You can send a picture straight from Photos with Share > Send by 98ish Mail." },
      { note: "New mail lights up the envelope in the taskbar tray, and with notifications turned on you get one even when 98ish is closed." },
    ],
    related: ["messenger-accounts", "address-book", "photos", "notifications", "privacy-server"],
  },
  {
    id: "internet-explorer",
    book: "internet",
    title: "Internet Explorer",
    summary: "Browse the web the way it looked in the past, with Favorites, History and the 98ish.com pages.",
    keywords: ["web browser", "browser", "internet", "websites", "favorites", "history", "address bar", "IE"],
    programs: ["Internet Explorer"],
    body: [
      "Internet Explorer in 98ish is a time machine. Instead of today's web, it shows websites as they looked on a date you pick, using copies saved by the Internet Archive's Wayback Machine. Start on the home page to see sites from any year, or type an address.",
      { open: "Internet Explorer", label: "Open Internet Explorer" },
      {
        steps: ["Click in the **Address** box.", "Type a site, like www.yahoo.com.", "Press Enter or click **Go**."],
        title: "To visit a site:",
      },
      "Links on old pages work too, and keep you in the same moment in time. See [[ie-time-machine]] to pick the date.",
      { h: "The toolbar" },
      { list: ["**Back** and **Forward** move through the pages you've seen.", "**Stop** stops a slow page; **Refresh** loads it again.", "**Home** goes to the start page (Internet Options can change it).", "**Favorites** shows the pages you saved. Favorites > Add to Favorites... saves the page you're on, and remembers its date too.", "**History** lists where you've been.", "**Captures** shows when the Archive saved the page you're on."] },
      "The **Links** bar has shortcuts to the 98ish.com pages, like the Guestbook. See [[community-pages]].",
      { note: "Pages come from the Internet Archive, which needs a moment to load. Some sites were never saved, and some old pages are missing pictures. Pages can't play sound or open pop-ups." },
      { tip: "File > View on archive.org opens the same page in a real browser tab." },
    ],
    related: ["ie-time-machine", "community-pages", "homepage-studio", "internet-options", "compass"],
  },
  {
    id: "compass",
    book: "internet",
    title: "Compass: browsing today's web",
    summary: "Visit Wikipedia and a few other safe sites inside 98ish, with tabs, bookmarks and history; other sites open in your real browser.",
    keywords: ["web browser", "browser", "browse", "websites", "tabs", "bookmarks", "history", "downloads", "search the web", "wikipedia", "relay", "open in real browser", "safe sites", "allowlist", "guest", "cookies", "data allowance", "monthly allowance", "resting until"],
    programs: ["Compass"],
    body: [
      "Compass is a web browser for today's web, inside 98ish. It has tabs, an address box that also searches, bookmarks, history, downloads, find in page and zoom. (For the web as it looked years ago, use Internet Explorer: see [[internet-explorer]].)",
      { open: "Compass", label: "Open Compass" },
      {
        steps: ["Click in the address box at the top.", "Type an address (like wikipedia.org) or words to search for.", "Press Enter."],
        title: "To visit a site or search:",
      },
      { h: "Which sites open in Compass" },
      {
        list: [
          "Compass opens **a few safe sites** through the 98ish server, for everyone, signed on or not: Wikipedia and its sister sites (Wiktionary, Wikivoyage, Wikibooks, Wikiquote, Wikimedia Commons), OpenStreetMap and example.com. Searches go to Wikipedia.",
          "**Any other site** shows a page with **Open in Real Browser**, which opens it in your phone's or computer's own browser. With **Data Saver** on (Tools > Compass Options), sites that allow being shown inside other sites open straight from the site instead.",
          "Signing on to 98 Messenger doesn't change which sites open (the server's owner can widen it later; then Compass asks you to sign on for other sites). See [[messenger-accounts]].",
        ],
      },
      { h: "How pages reach you" },
      "Most sites don't allow being shown inside another site, so Compass asks the 98ish server to fetch each page and pass it on (the relay). The page runs in a locked-down frame with no address of its own: it can't read your 98ish files, settings or sign-in, can't use your 98 Messenger account, and can't take over the 98ish window or open pages that can.",
      { h: "Privacy" },
      {
        list: [
          "**Sites see the 98ish server's address** for the pages it fetches. Pictures and scripts usually load straight from the site, so sites can still see your address (View > Relay Pictures Too sends them through the server as well).",
          "**What you type into a relayed page, passwords included, passes through the 98ish server.** For banking, email and other important accounts, use **Open in Real Browser**.",
          "**What the server keeps:** the cookies sites set (so you stay signed in to simple sites) are kept only in the server's memory, for your screen name and only for the site that set them. A guest's cookies go when the browsing session ends; a member's after a day unused or when the server restarts. Tools > Clear Cookies forgets them sooner. The server also counts how much data you used today (for guests, under a scrambled form of their internet address, never the address itself) and how much it sent this month. It doesn't keep the pages.",
          "Your bookmarks, history and open tabs are kept on this device only.",
        ],
      },
      { h: "Limits" },
      {
        list: [
          "The server has a small daily data allowance for everyone together, and a smaller one for each person (smaller still for guests). When it runs out, Compass shows sites that allow it straight from the site, and offers your real browser for the rest. It starts again the next day.",
          "There is also a **monthly** allowance. The 98ish server's free plan includes a fixed amount of data each month for everything (Messenger, file sync, games and Compass). So that Messenger never stops, Compass rests when it, or the whole server, has used its share: it then says \"Compass has used this month's data allowance; it's back on\" the 1st of next month. Everything else in 98ish keeps working.",
          "Too many pages too quickly means a short wait.",
          "Very big pages and files, videos and sounds, Google sign-in, banks and big web apps open in your real browser instead.",
          "The server's owner can turn the relay off. Then Compass shows only sites that allow being framed, with an **Open in Real Browser** button for the rest.",
        ],
      },
      { note: "The 98ish server takes a nap when nobody has used it for a while, so the first page can take up to a minute. See [[server-waking]]." },
    ],
    related: ["internet-explorer", "messenger-accounts", "privacy-server", "server-waking"],
  },
  {
    id: "ie-time-machine",
    book: "internet",
    title: "The time machine: browsing past years",
    summary: "Pick any date since 1996 and see websites as they looked then; step to earlier or later copies.",
    keywords: ["time machine", "Wayback Machine", "old websites", "Internet Archive", "past", "1996", "1998", "captures", "earlier copy", "later copy"],
    body: [
      "Under the address bar, Internet Explorer says **Browsing the Web as of** a date. Every page you open shows the copy the Internet Archive saved closest to that date.",
      {
        steps: ["Click the date next to **Browsing the Web as of**.", "Pick any day from January 1, 1996 to today.", "Visit a site. It shows the copy saved nearest that day."],
        title: "To travel to a date:",
      },
      "The page's own date shows on the right as **Captured** and the date it was saved. It may be a little before or after the day you picked.",
      { h: "Earlier and Later" },
      "**Earlier** and **Later** jump to the copy saved just before or just after the one you're looking at, so you can watch a site change over time. They're also in the Go menu as Earlier Copy and Later Copy.",
      { h: "Captures" },
      "Click **Captures** in the toolbar to see how often the Archive saved the page each year, and a calendar of the days it was saved in one year. Click a day to see that copy.",
      { tip: "Try www.yahoo.com in 1997, or a site you loved as a kid. The start page also suggests sites for each year." },
      { note: "The Internet Archive is a nonprofit library that has been saving the web since 1996. Not every page was saved on every day." },
    ],
    related: ["internet-explorer", "community-pages"],
  },
  {
    id: "homepage-studio",
    book: "internet",
    title: "HomePage Studio",
    summary: "Build a 1990s-style homepage with marquees, clip art and a hit counter, and publish it at www.98ish.com/~yourname.",
    keywords: ["homepage", "web page", "website", "publish", "GeoCities", "marquee", "hit counter", "clip art", "web ring"],
    programs: ["HomePage Studio"],
    body: [
      "HomePage Studio lets you build your own homepage the 1998 way: scrolling marquees, blinking text, clip art, a hit counter and background music. When you publish it, anyone on 98ish can visit it in Internet Explorer.",
      { open: "HomePage Studio", label: "Open HomePage Studio" },
      { h: "Building your page" },
      "Your page is a stack of blocks. Add blocks from the **Insert** menu or the block buttons: Heading, Paragraph, Marquee, Blinking Text, Picture (clip art), Divider, Link List, Hit Counter, Guestbook Button and Web Ring. Click a block to change it; use the arrows to move it up or down, or delete it.",
      "In a paragraph, put *stars* around words for bold and _underscores_ for italics.",
      "The **Page** tab (Page Properties) sets the background, colors, font and background music. Music starts when a visitor clicks on your page, because browsers don't allow sound before that.",
      "To use your own picture, choose Insert > **Picture from My Computer...** and pick one from your 98ish drive.",
      { phone: "On a phone, switch between Blocks, Page and Preview with the tabs at the top.", computer: "The preview on the right shows your page as you build it." },
      {
        steps: ["Sign on to 98 Messenger.", "Click **Publish** (or File > Publish to the Web).", "Click View Published Page to see it in Internet Explorer."],
        title: "To publish your page:",
      },
      "Your page lives at **www.98ish.com/~** followed by your screen name (without spaces). Published pages join the Members directory and the 98ish web ring. Publish again any time to update it.",
      { h: "Drafts and unpublishing" },
      "File > **Save Draft** keeps your work on this device without publishing. File > **Unpublish...** takes your page off the web.",
      { note: "A page can be at most 500 KB. If it's too big, use fewer or smaller pictures." },
      { tip: "Couples can also publish their Our Story timeline as a homepage. See [[our-story]]." },
    ],
    related: ["community-pages", "internet-explorer", "messenger-accounts", "our-story"],
  },
  {
    id: "network-neighborhood",
    book: "internet",
    title: "Network Neighborhood",
    summary: "See every 98ish computer that's on right now, send files and messages, and challenge people to games.",
    keywords: ["network", "who's online", "send file", "computers", "challenge", "LAN", "Received Files", "hide my computer"],
    programs: ["Network Neighborhood"],
    body: [
      "Network Neighborhood shows every 98ish desktop that's open right now as a computer on a network. People signed on to 98 Messenger show up under their screen name; everyone else is a GUEST computer. You don't need to sign on to use it.",
      { open: "Network Neighborhood", label: "Open Network Neighborhood" },
      { phone: "Tap a computer to open it. Press and hold one for a menu.", computer: "Double-click a computer to open it, or right-click it for a menu." },
      "Opening a computer gives you three things you can do:",
      {
        list: [
          "**Send a File**: pick a document, picture or sound from your drive. The other person gets a box asking whether to accept it, and accepted files land in the **Received Files** folder in My Documents. Pictures and sounds can be up to 1.5 MB; documents up to 200 KB (WordPad documents 512 KB).",
          "**Send a Message**: a WinPopup note of up to 500 characters. See [[winpopup]].",
          "**Play**: invite them to Checkers, a Minesweeper Race, Hearts, Reversi, Chess, Battleship, Tetris Battle, Doodle Together, the Quiz Show or Sunny Acres co-op. They choose whether to accept.",
        ],
      },
      { tip: "On a computer you can also drag a file from My Computer onto someone's computer to send it." },
      { h: "Hiding your computer" },
      "Uncheck **Show my computer on the network** at the bottom (or in the View menu) to hide from everyone else's list. The status bar says (hidden) while you're hidden.",
      "View > Details shows more about each computer. View > Refresh updates the list.",
    ],
    related: ["winpopup", "game-invites", "online-play", "messenger"],
  },
  {
    id: "winpopup",
    book: "internet",
    title: "WinPopup",
    summary: "Send short pop-up notes to any computer in Network Neighborhood, no sign on needed.",
    keywords: ["popup", "net send", "messages", "notes", "WinPopup"],
    programs: ["WinPopup"],
    body: [
      "WinPopup sends quick little notes to anyone in Network Neighborhood. You don't need a screen name. Notes you get pop up on your screen and wait in WinPopup until you clear them.",
      { open: "WinPopup", label: "Open WinPopup" },
      {
        steps: ["Click **Send** (or Messages > Send...).", "Pick the computer to send to.", "Type your note (up to 500 characters) and click Send."],
        title: "To send a note:",
      },
      "When you've got notes, use the arrows (or Messages > Previous and Next) to read them, **Reply...** to answer the sender, **Discard** to throw one away and **Clear All** to empty the list.",
      { note: "WinPopup notes only reach people who have 98ish open right now. For someone who is away, use [[mail|98ish Mail]] or an [[messenger|instant message]] instead." },
    ],
    related: ["network-neighborhood", "messenger"],
  },
  {
    id: "youtube98",
    book: "internet",
    title: "YouTube '98",
    summary: "Watch videos in a tiny 1990s-style window, keep Favorites and share videos with buddies.",
    keywords: ["videos", "YouTube", "watch", "search videos", "share video"],
    programs: ["YouTube '98"],
    body: [
      "YouTube '98 is classic YouTube in an Internet Explorer window. Search for videos, watch them, and keep the ones you love.",
      { open: "YouTube '98", label: "Open YouTube '98" },
      {
        steps: ["Type in the **Search videos** box (or in the Address bar) and press Enter.", "Click a video to watch it.", "Related videos from your search are listed beside it."],
        title: "To find a video:",
      },
      "You can also paste a YouTube link into the Address bar to open that video.",
      { list: ["**Back**, **Forward** and **Home** work like a browser.", "Add a video to **Favorites** from its page. Favorites are kept on this device.", "**Share** posts the video to the 98ish Lobby chat room or sends it to a buddy. You need to be signed on to 98 Messenger to share."] },
    ],
    related: ["messenger", "internet-explorer"],
  },
  {
    id: "community-pages",
    book: "internet",
    title: "98ish.com: the Guestbook, Members and the web ring",
    summary: "The pages that live right inside 98ish: sign the Guestbook, see members' homepages and surf the web ring.",
    keywords: ["guestbook", "members directory", "web ring", "98ish.com", "hit counter", "Minesweeper Shrine", "community"],
    body: [
      "Some web pages live right here in 98ish instead of in the past. Open them in Internet Explorer, from the Links bar, or from Start > Programs > Community.",
      {
        list: [
          "**The 98ish Guestbook** (www.98ish.com/guestbook): leave a note for everyone who visits, with your name, your homepage if you have one, and a mood.",
          "**98ish Members** (www.98ish.com/members): the directory of homepages people built in HomePage Studio.",
          "**The Minesweeper Strategy Shrine**, **Cool Links of the Web** and **Rocky's Home Page** (a pet rock with a web page).",
        ],
      },
      { h: "The web ring" },
      "These pages and every published member homepage are linked in the 98ish web ring. Use the web ring links at the bottom of a page to hop to the next or previous site. Each page has its own hit counter, too.",
      {
        steps: ["Open Internet Explorer.", "Click **Guestbook** on the Links bar.", "Fill in your name, pick a mood and write your message, then sign it."],
        title: "To sign the Guestbook:",
      },
      { note: "Anything you write in the Guestbook can be seen by everyone who visits 98ish." },
    ],
    related: ["internet-explorer", "homepage-studio"],
  },
]
