// 98ish Help: 98 Messenger, Mail, Internet Explorer, HomePage Studio, Network Neighborhood,
// WinPopup, YouTube '98 and the 98ish.com pages. Format: see ../helpCore.js.

export const books = [{ id: "internet", title: "Internet and friends", order: 40 }]

export const topics = [
  {
    id: "messenger",
    book: "internet",
    title: "98 Messenger",
    summary: "Chat with friends: your Buddy List, instant messages, away messages and chat rooms.",
    keywords: ["instant messages", "IM", "buddy list", "away message", "chat rooms", "SmarterChild", "AIM", "buddies", "block", "profile"],
    programs: ["98 Messenger"],
    body: [
      "98 Messenger is an old-school instant messenger. Make up a screen name, add your friends as buddies, and you can see when they're on and send them messages. It's also your key to everything else that's shared in 98ish: Mail, calls, the couples programs, file sync and online games all use your screen name.",
      { open: "98 Messenger", label: "Open 98 Messenger" },
      "First you need a screen name. See [[messenger-accounts]] for making one and staying signed on.",
      { h: "Your Buddy List" },
      "Once you're signed on, the Buddy List shows your buddies by group. People who are on right now are at the top; everyone else waits in **Offline** at the bottom. A buddy who has been idle for a while or is away looks grayed out.",
      {
        steps: ["Click the **List Setup** tab at the top of the Buddy List.", "Click **Add Buddy**.", "Type your friend's screen name and pick a group, then click OK."],
        title: "To add a buddy:",
      },
      "On the List Setup tab you can also add, rename and delete groups, and remove buddies.",
      { h: "Sending an instant message" },
      { phone: "Tap a buddy, then tap **IM** at the bottom of the Buddy List. You can also press and hold a buddy for more choices.", computer: "Double-click a buddy, or select them and click **IM**. Right-click a buddy for more choices (Call, Video Call, Get Info, Add to Address Book)." },
      "Type in the box at the bottom of the IM window and press Send. The **Aa** button beside the box shows the buttons that change the font, size, bold, italic, underline and color of your text. **More »** under the box has **Warn**, **Block**, **Add Buddy**, **Get Info** and **Games**; 98 Messenger remembers whether you left them showing. The **Games** button invites the buddy to a game (Checkers, Chess, Hearts, Reversi, Battleship, a Minesweeper Race, Tetris Battle, Doodle Together, the Quiz Show or Sunny Acres co-op).",
      "The **+** button beside the box sends a **picture** or a **voice message**; press and hold a message (right-click on a computer) to **react** to it. Your conversations are saved, so they're still there after a reload and on your other devices. See [[messenger-history]].",
      { note: "If your buddy is signed off but has turned on notifications, your message waits for them and their phone gets a notification (it says **Delivered** once they sign on). Otherwise you can only message people who are signed on." },
      { h: "Away messages" },
      "Click **Away** at the bottom of the Buddy List (or My AIM > Away Message...) and pick or write a message. Anyone who IMs you gets it as an automatic reply. Click **I'm Back** (or **Back**) when you return. If you don't touch 98ish for 10 minutes, your buddies see you as idle.",
      { h: "Chat rooms" },
      "Click **Chat** (or People > Join a Chat Room...) to join a room with more than one person. The **98ish Lobby** is where everyone hangs out; type any other name to make your own room, then invite buddies to it.",
      { h: "SmarterChild" },
      "SmarterChild is a friendly robot buddy who is always online. IM it **help** to see what it can do: jokes, trivia, the magic 8-ball, coin flips, dice, fortunes and the time.",
      { h: "Your profile, warnings and blocking" },
      {
        list: [
          "My AIM > **Edit Profile...** sets the words people see when they Get Info on you.",
          "**Get Info** (or the Info button) shows a buddy's profile and how long they've been on.",
          "**Warn** in an IM window slows down someone who's being a pest. Their warning level goes up.",
          "**Block** stops someone from sending you messages or seeing when you're on. People > Block List... shows who you've blocked.",
          "My AIM > **Sounds** turns the door-opening and message sounds on or off.",
        ],
      },
      { tip: "Closing the Buddy List window signs you off. To keep getting messages while you do other things, minimize it instead." },
    ],
    related: ["messenger-history", "messenger-accounts", "messenger-calls", "mail", "notifications", "address-book", "game-invites"],
  },
  {
    id: "messenger-history",
    book: "internet",
    title: "Pictures, voice messages, reactions and saved conversations",
    summary: "Send pictures and voice messages, react to messages, see when they've been read, and find old conversations on any device.",
    keywords: ["send a picture", "photo in IM", "voice message", "voice note", "record", "reaction", "react", "heart", "read receipt", "seen", "delivered", "history", "old messages", "clear history", "conversation history", "scroll back"],
    body: [
      { h: "Pictures" },
      {
        steps: ["In an IM window, click **+** beside the message box.", "Choose **Picture...**.", "Pick one from My Pictures, or **From Photos on this phone...** / **From this computer...**, or **Take a Photo...** on a phone."],
        title: "To send a picture:",
      },
      "98ish makes it smaller first (up to 1600 pixels, about 600 KB), so it sends quickly. Your buddy sees a small preview at once; tapping it opens the full picture, with **Save to My Pictures**.",
      { h: "Voice messages" },
      {
        steps: ["Click **+**, then **Voice Message**. The first time, allow the microphone.", "**Hold** the **Hold to talk** button and talk (up to a minute).", "Let go to send it. To stop without sending, tap **✕**."],
        title: "To send a voice message:",
      },
      { tip: "On a computer you can also click the button once to start, then click **Send** when you're done." },
      "A voice message shows as a play button with its sound wave and length. It plays at the taskbar's volume.",
      { note: "Pictures and voice messages are kept online for **90 days**; after that the message says it expired (unless your device already has it). If 98ish's free online storage is used up for the month, you'll see \"Picture couldn't be sent: online storage is resting\"; ordinary messages keep working." },
      { h: "Reactions" },
      { phone: "Press and hold a message, then tap one of the six reactions: ❤️ 😂 😮 😢 👍 ‼️.", computer: "Right-click a message, then click one of the six reactions: ❤️ 😂 😮 😢 👍 ‼️." },
      "Reactions show under the message with how many people chose each one. Pick the same one again (or tap it under the message) to take yours back. Works in Buddy Chat rooms too.",
      { h: "Read and Delivered" },
      "Under your last message, **Read 10:42 PM** means your buddy had the conversation open in front of them at that time. **Delivered** means a message that waited for them (they were signed off) reached them when they signed on.",
      "Don't want to send read receipts? Buddy List > My AIM > **Preferences...** > clear **Read receipts**. Then you don't see theirs either.",
      { h: "Saved conversations" },
      "IMs and Buddy Chat messages are kept on this device, so closing the window or reloading 98ish never loses them: open the IM window again and they're there. Scroll up for older ones.",
      "They're also saved on the 98ish server with your screen name, so your other phone or computer (or a new phone) shows them after you sign on. To keep them only on your devices, open My AIM > **Preferences...** and clear **Save my conversations on the server**; that also deletes the copy already on the server. Conversations with SmarterChild stay on this device only.",
      { h: "Clearing a conversation" },
      "In the IM window, open **More »** and click **Clear History**. It's deleted from this device and from your saved copy on the server (your other devices too). The other person keeps their own copy. In a chat room, the button is beside the people list.",
      "See [[privacy-server]] for exactly what's kept and for how long.",
      { open: "98 Messenger", label: "Open 98 Messenger" },
    ],
    related: ["messenger", "privacy-server", "privacy-device", "photos", "notifications"],
  },
  {
    id: "messenger-accounts",
    book: "internet",
    title: "Screen names and signing on",
    summary: "Get a screen name, sign on, and have 98ish remember you with Sign me on automatically.",
    keywords: ["screen name", "sign on", "sign off", "password", "account", "sign me on automatically", "remember me", "new account", "signed on at a different location"],
    body: [
      "Your screen name is who you are on 98ish. It works on every phone and computer you use, and it's also your mail address, your homepage address and how your partner finds you in Us.",
      {
        steps: [
          "Open 98 Messenger.",
          "Click **Get a Screen Name** under the Screen Name box.",
          "Type the screen name you want. It must be 3 to 16 characters, start with a letter, and use only letters, numbers and spaces.",
          "Type a password (at least 4 characters) twice.",
          "Leave **Sign me on automatically** checked if this is your own phone or computer, then click Sign On.",
        ],
        title: "To make a screen name:",
      },
      "If someone already has that name, you'll be asked to pick another one.",
      { h: "Signing on" },
      "Next time, type your screen name and password and click Sign On. If you get it wrong, check that Caps Lock is off. Screen names don't care about capital letters or spaces, so \"Cool Kid\" and \"coolkid\" are the same person.",
      { h: "Sign me on automatically" },
      "With this box checked, this device remembers you and signs you on by itself whenever you open 98ish, without your password. It stays remembered for 60 days after you last used it. Uncheck it on a shared or borrowed computer.",
      "To make a device forget you, open the Buddy List and choose My AIM > **Sign Off**. Signing off on purpose forgets this device.",
      { h: "One place at a time" },
      "You can be signed on in only one place at a time. If you sign on from your computer while your phone is signed on, the phone says it was disconnected because you signed on at a different location. That's normal: sign on again on whichever one you want to use.",
      { h: "Deleting your account" },
      "My AIM > **Delete My Account...** deletes the account and everything the 98ish server keeps for it, for good. See [[delete-account]].",
      { note: "The 98ish server takes a nap when nobody has used it for a while. If signing on takes a long time, wait up to a minute. See [[server-waking]]." },
      { warning: "There's no way to reset a forgotten Messenger password from here, so pick one you'll remember." },
    ],
    related: ["messenger", "server-waking", "file-sync", "privacy-server"],
  },
  {
    id: "messenger-calls",
    book: "internet",
    title: "Voice and video calls",
    summary: "Call a buddy with voice or video from 98 Messenger, and what to do if a call won't connect.",
    keywords: ["call", "video call", "voice call", "phone call", "camera", "microphone", "mute", "flip camera", "ringing", "FaceTime"],
    body: [
      "You can call any buddy who is signed on, with just your voice or with video. Calls go straight between your two devices.",
      {
        steps: [
          "Sign on to 98 Messenger.",
          "Open an IM window with your buddy and click the phone (voice) or camera (video) button at the top. Or right-click (press and hold on a phone) the buddy in your Buddy List and choose **Call** or **Video Call**.",
          "The first time, allow 98ish to use your microphone and camera when the browser asks.",
          "Wait for them to answer. A call rings for about 45 seconds.",
        ],
        title: "To call someone:",
      },
      "Paired couples can also call each other from the big buttons at the top of Us.",
      { h: "Answering" },
      "When someone calls, an Incoming Call window pops up with **Answer**, **Decline**, and a button to answer with or without video. If you're signed off but have notifications turned on, your phone gets a notification for the call, and missed calls show up in the notification bell.",
      { h: "During a call" },
      {
        list: [
          "**Mute** turns your microphone off and on.",
          "**Camera Off / Camera On** stops or starts your video.",
          "**Flip** (on phones) switches between the front and back camera.",
          "**Share Screen** (on computers that support it) shows your screen instead of your camera.",
          "**Pop Out** puts the other person's video in a little floating window, where the browser allows it.",
          "Drag your own little picture to any corner.",
          "**Hang Up** ends the call.",
        ],
      },
      { h: "Wi-Fi works best" },
      "Calls connect most reliably when both of you are on Wi-Fi. Some cellular networks, and strict school or work Wi-Fi, block direct connections between devices. If that happens, the call window says it couldn't connect after about 30 seconds. Try again with both of you on Wi-Fi.",
      { note: "On an iPhone, switching to another app pauses your camera, and locking the screen may drop the call. Keep 98ish open on screen while you talk." },
      { tip: "If the call says your camera or microphone is being used by another app, close that app (or other tabs using the camera) and try again." },
    ],
    related: ["messenger", "calls-trouble", "notifications", "us-together"],
  },
  {
    id: "mail",
    book: "internet",
    title: "98ish Mail",
    summary: "Send mail with attachments to any screen name, with an Inbox, Sent Items, Drafts and Deleted Items.",
    keywords: ["mail", "email", "e-mail", "inbox", "attachments", "send mail", "reply", "forward", "drafts", "Outlook"],
    programs: ["98ish Mail"],
    body: [
      "98ish Mail is a late-90s style mail program. Your 98 Messenger screen name is your mail address, so you can write to anyone who has a screen name, whether they're on right now or not. You need to be signed on to 98 Messenger to read and send mail.",
      { open: "98ish Mail", label: "Open 98ish Mail" },
      { h: "Folders" },
      { list: ["**Inbox**: mail people sent you.", "**Outbox**: mail being sent right now (or that couldn't be sent).", "**Sent Items**: copies of what you sent.", "**Deleted Items**: deleted mail. Delete it again to remove it for good, or click Restore to put it back.", "**Drafts**: messages you saved to finish later."] },
      {
        steps: [
          "Click **New Mail**.",
          "In **To**, type one or more screen names, separated by commas. People in your Address Book are suggested as you type.",
          "Type a subject and your message. Messages are plain text.",
          "Click **Send**.",
        ],
        title: "To write a message:",
      },
      {
        steps: [
          "Click **More options »** under the subject. Its line says who it's from, the Cc and the attachments.",
          "Add more people in **Cc** if you like.",
          "To add a file, click **Attach** (or Message > Attach File...) and pick a document, picture or sound from your 98ish drive.",
          "Click **Save** (or Message > Save Draft) to keep it in Drafts for later.",
        ],
        title: "For Cc, attachments and drafts:",
      },
      "A message and its attachments can be at most 1 MB in all. Big photos may be too large: a smaller copy from Paint or Photos will fit.",
      { h: "Reading and answering" },
      "Click a message to read it. Use **Reply**, **Reply All** or **Forward** in the toolbar. **Send/Recv** checks for new mail. To keep someone, click the button next to their name to add the sender to your Address Book.",
      "An attachment has **Open** and **Save** buttons. Either way, it's saved in the **Mail Attachments** folder inside My Documents.",
      { tip: "You can send a picture straight from Photos with Share > Send by 98ish Mail." },
      { note: "New mail lights up the envelope in the taskbar tray, and with notifications turned on you get one even when 98ish is closed." },
    ],
    related: ["messenger-accounts", "address-book", "photos", "notifications", "privacy-server"],
  },
  {
    id: "internet-explorer",
    book: "internet",
    title: "Internet Explorer",
    summary: "Browse the web the way it looked in the past, with Favorites, History and the 98ish.com pages.",
    keywords: ["web browser", "browser", "internet", "websites", "favorites", "history", "address bar", "IE"],
    programs: ["Internet Explorer"],
    body: [
      "Internet Explorer in 98ish is a time machine. Instead of today's web, it shows websites as they looked on a date you pick, using copies saved by the Internet Archive's Wayback Machine. Start on the home page: pick a **Year**, type an address, or try one of the six popular sites. **More sites »** shows the whole directory (with its own search) and a button for every year.",
      { open: "Internet Explorer", label: "Open Internet Explorer" },
      {
        steps: ["Click in the **Address** box.", "Type a site, like www.yahoo.com.", "Press Enter or click **Go**."],
        title: "To visit a site:",
      },
      "Links on old pages work too, and keep you in the same moment in time. See [[ie-time-machine]] to pick the date.",
      { h: "The toolbar" },
      { list: ["**Back** and **Forward** move through the pages you've seen.", "**Stop** stops a slow page; **Refresh** loads it again. (On a phone, Stop takes Refresh's place while a page loads.)", "**Home** goes to the start page (Internet Options can change it).", "**Favorites** shows the pages you saved. Favorites > Add to Favorites... saves the page you're on, and remembers its date too.", "**History** lists where you've been.", "**Captures** shows when the Archive saved the page you're on."] },
      { phone: "On a phone, History and Captures are in the View menu." },
      "The **Links** bar has shortcuts to the 98ish.com pages, like the Guestbook. See [[community-pages]].",
      { note: "Pages come from the Internet Archive, which needs a moment to load. Some sites were never saved, and some old pages are missing pictures. Pages can't play sound or open pop-ups." },
      { tip: "File > View on archive.org opens the same page in a real browser tab." },
    ],
    related: ["ie-time-machine", "community-pages", "homepage-studio", "internet-options", "compass"],
  },
  {
    id: "compass",
    book: "internet",
    title: "Compass: browsing today's web",
    summary: "Browse today's web inside 98ish, with tabs, bookmarks and history: any site live when you're signed on, Wikipedia and friends as a guest, other sites straight from the site or as a saved copy.",
    keywords: ["web browser", "browser", "browse", "websites", "tabs", "bookmarks", "history", "downloads", "search the web", "wikipedia", "relay", "saved copy", "internet archive", "wayback machine", "open in safari", "safe sites", "allowlist", "guest", "cookies", "data allowance", "monthly allowance", "resting until", "live browsing", "true internet", "duckduckgo", "report this page", "blocked site", "log"],
    programs: ["Compass"],
    body: [
      "Compass is a web browser for today's web, inside 98ish. It has tabs, an address box that also searches, bookmarks, history, downloads, find in page and zoom. (For the web as it looked years ago, use Internet Explorer: see [[internet-explorer]].)",
      { open: "Compass", label: "Open Compass" },
      {
        steps: ["Click in the address box at the top.", "Type an address (like wikipedia.org) or words to search for.", "Press Enter."],
        title: "To visit a site or search:",
      },
      { h: "How each site shows" },
      {
        list: [
          "**Signed on to 98 Messenger: any site, live.** Pages come through the 98ish server (the relay), so they work inside 98ish. Searches go to DuckDuckGo (Tools > Compass Options picks another engine). The first live page shows a short notice: pages you open live are fetched by the 98ish server, so don't use Compass for anything illegal or to get around a network's rules.",
          "**As a guest: Wikipedia and friends, live.** Wikipedia and its sister sites (Wiktionary, Wikivoyage, Wikibooks, Wikiquote, Wikimedia Commons), OpenStreetMap and example.com come through the relay for everyone. Searches go to Wikipedia. Other sites show as below, with a slim bar: **Sign on to browse this site live**. Signing on (from that bar, or in 98 Messenger) turns the open tabs live.",
          "**Other sites that allow it, live from the site.** Many sites let other pages show them; Compass shows those straight from the site.",
          "**Everything else, as a saved copy.** For sites that don't allow it, Compass shows the newest copy the Internet Archive (the Wayback Machine) saved. A slim bar above the page says **Saved copy from the Internet Archive** and its date. Links inside it lead to more saved pages, and the address box shows each page's real address. Some sites block the 98ish server; then you see a saved copy too.",
          "If the Archive has no copy either, Compass says so and offers to search Wikipedia for the site.",
          "**Sites Compass doesn't open:** adult sites, malware test sites, piracy sites and other web proxies (a short list on the server), plus any site the server's owner blocks. Compass says so instead of showing them.",
          "To see a site live outside 98ish (videos, sign-ins, banking), use **Open in Safari** (on a computer, Open in your own browser's name): it's the small link on a saved copy's bar, in the File menu, and in the menu on a phone. View > Show Saved Copy shows the Archive's copy of any page.",
        ],
      },
      { h: "How pages reach you" },
      "Most sites don't allow being shown inside another site, so for the relayed sites Compass asks the 98ish server to fetch each page and pass it on. Every page, relayed, live from the site or saved, runs in a locked-down frame: it can't read your 98ish files, settings or sign-in, can't use your 98 Messenger account, and can't take over the 98ish window or open pages that can.",
      { h: "Privacy" },
      {
        list: [
          "**Relayed pages: sites see the 98ish server's address** for the pages it fetches. Pictures and scripts usually load straight from the site, so sites can still see your address (View > Relay Pictures Too sends them through the server as well).",
          "**Pages live from the site and saved copies load over your own connection**, not through 98ish: the site, or the Internet Archive for saved copies, sees your internet address as with any browser. The 98ish server only looks at a site's headers first, to see whether it allows being shown.",
          "**What you type into a relayed page, passwords included, passes through the 98ish server.** For banking, email and other important accounts, use **Open in Safari** (File menu).",
          "**What the server keeps:** the cookies relayed sites set (so you stay signed in to simple sites) are kept only in the server's memory, for your screen name and only for the site that set them. A guest's cookies go when the browsing session ends; a member's after a day unused or when the server restarts. Tools > Clear Cookies forgets them sooner. The server also counts how much data you used today (for guests, under a scrambled form of their internet address, never the address itself) and how much it sent this month. It doesn't keep the pages.",
          "**A 7-day log, for abuse complaints:** for a signed-on screen name, the server notes which sites it fetched live and how much data, per day: the site's name only (like www.example.com), never the page's address, searches or anything on the page. Each day's lines are deleted after 7 days. Guests aren't in it (they can only open Wikipedia and friends live). Deleting your account deletes it at once. See [[privacy-server]].",
          "**Report This Page** (Tools menu; on a phone, the menu) sends the page's address and your note to the owner of this 98ish, for pages that are illegal, abusive, a scam or malware. Reports are kept 90 days and nobody is notified automatically.",
          "Your bookmarks, history and open tabs are kept on this device only.",
        ],
      },
      { h: "Limits" },
      {
        list: [
          "Each signed-on person has a daily allowance for live pages (25 MB, a hundred or more pages; less for guests), and the server one for everyone together. When it runs out Compass doesn't stop: it shows sites straight from the site or as saved copies, with a slim bar saying **Live browsing resumes tomorrow**.",
          "There is also a **monthly** allowance. The 98ish server's free plan includes a fixed amount of data each month for everything (Messenger, file sync, games and Compass). So that Messenger never stops, the relay rests when Compass, or the whole server, has used its share, until the 1st of next month; sites still show straight from the site or as saved copies (the bar says when live browsing resumes), and everything else in 98ish keeps working.",
          "Too many pages too quickly means a short wait.",
          "Find in page works only on relayed pages. Saved copies can be old, and their videos, sign-ins and forms usually don't work.",
          "The server's owner can turn the relay off. Then every site shows straight from the site or as a saved copy.",
        ],
      },
      { note: "The 98ish server takes a nap when nobody has used it for a while, so the first page can take up to a minute. See [[server-waking]]." },
    ],
    related: ["internet-explorer", "messenger-accounts", "privacy-server", "server-waking"],
  },
  {
    id: "ie-time-machine",
    book: "internet",
    title: "The time machine: browsing past years",
    summary: "Pick any date since 1996 and see websites as they looked then; step to earlier or later copies.",
    keywords: ["time machine", "Wayback Machine", "old websites", "Internet Archive", "past", "1996", "1998", "captures", "earlier copy", "later copy"],
    body: [
      "Under the address bar, Internet Explorer says **Browsing the Web as of** a date. Every page you open shows the copy the Internet Archive saved closest to that date.",
      {
        steps: ["Click the date next to **Browsing the Web as of**.", "Pick any day from January 1, 1996 to today.", "Visit a site. It shows the copy saved nearest that day."],
        title: "To travel to a date:",
      },
      "The page's own date shows on the right as **Captured** and the date it was saved. It may be a little before or after the day you picked.",
      { h: "Earlier and Later" },
      "**Earlier** and **Later** (next to the date once a page is open) jump to the copy saved just before or just after the one you're looking at, so you can watch a site change over time. They're also in the Go menu as Earlier Copy and Later Copy.",
      { h: "Captures" },
      "Click **Captures** in the toolbar to see how often the Archive saved the page each year, and a calendar of the days it was saved in one year. Click a day to see that copy.",
      { tip: "Try www.yahoo.com in 1997, or a site you loved as a kid. The start page's **Year** list jumps there, and **More sites »** suggests sites for each year." },
      { note: "The Internet Archive is a nonprofit library that has been saving the web since 1996. Not every page was saved on every day." },
    ],
    related: ["internet-explorer", "community-pages"],
  },
  {
    id: "homepage-studio",
    book: "internet",
    title: "HomePage Studio",
    summary: "Build a 1990s-style homepage with marquees, clip art and a hit counter, and publish it at www.98ish.com/~yourname.",
    keywords: ["homepage", "web page", "website", "publish", "GeoCities", "marquee", "hit counter", "clip art", "web ring"],
    programs: ["HomePage Studio"],
    body: [
      "HomePage Studio lets you build your own homepage the 1998 way: scrolling marquees, blinking text, clip art, a hit counter and background music. When you publish it, anyone on 98ish can visit it in Internet Explorer.",
      { open: "HomePage Studio", label: "Open HomePage Studio" },
      { h: "Building your page" },
      "Your page is a stack of blocks. Add blocks from the **Insert** menu or the block buttons: Heading, Text and Clip Art are on the toolbar, and **More blocks »** has Marquee, Blinking Text, Divider, Link List, Hit Counter, Guestbook Button and Web Ring. Click a block to change it: its arrows move it up or down and its X deletes it (Format menu too). A block's size, effect, alignment and colors are under **More options »**.",
      "In a paragraph, put *stars* around words for bold and _underscores_ for italics.",
      "The **Page** tab (Page Properties) sets the title and background; **More options »** there has the colors, font, background music, sparkle trail and badge. Music starts when a visitor clicks on your page, because browsers don't allow sound before that.",
      "To use your own picture, choose Insert > **Picture from My Computer...** and pick one from your 98ish drive.",
      { phone: "On a phone, switch between Blocks, Page and Preview with the tabs at the top.", computer: "The preview on the right shows your page as you build it." },
      {
        steps: ["Sign on to 98 Messenger.", "Click **Publish** (or File > Publish to the Web).", "Click View Published Page to see it in Internet Explorer."],
        title: "To publish your page:",
      },
      "Your page lives at **www.98ish.com/~** followed by your screen name (without spaces). Published pages join the Members directory and the 98ish web ring. Publish again any time to update it.",
      { h: "Drafts and unpublishing" },
      "File > **Save Draft** keeps your work on this device without publishing. File > **Unpublish...** takes your page off the web.",
      { note: "A page can be at most 500 KB. If it's too big, use fewer or smaller pictures." },
      { tip: "Couples can also publish their Our Story timeline as a homepage. See [[our-story]]." },
    ],
    related: ["community-pages", "internet-explorer", "messenger-accounts", "our-story"],
  },
  {
    id: "network-neighborhood",
    book: "internet",
    title: "Network Neighborhood",
    summary: "See every 98ish computer that's on right now, send files and messages, and challenge people to games.",
    keywords: ["network", "who's online", "send file", "computers", "challenge", "LAN", "Received Files", "hide my computer"],
    programs: ["Network Neighborhood"],
    body: [
      "Network Neighborhood shows every 98ish desktop that's open right now as a computer on a network. People signed on to 98 Messenger show up under their screen name; everyone else is a GUEST computer. You don't need to sign on to use it.",
      { open: "Network Neighborhood", label: "Open Network Neighborhood" },
      { phone: "Tap a computer to open it. Press and hold one for a menu.", computer: "Double-click a computer to open it, or right-click it for a menu." },
      "Opening a computer gives you three things you can do:",
      {
        list: [
          "**Send a File**: pick a document, picture or sound from your drive. The other person gets a box asking whether to accept it, and accepted files land in the **Received Files** folder in My Documents. Pictures and sounds can be up to 1.5 MB; documents up to 200 KB (WordPad documents 512 KB).",
          "**Send a Message**: a WinPopup note of up to 500 characters. See [[winpopup]].",
          "**Play**: invite them to Checkers, a Minesweeper Race, Hearts, Reversi, Chess, Battleship, Tetris Battle, Doodle Together, the Quiz Show or Sunny Acres co-op. They choose whether to accept.",
        ],
      },
      { tip: "On a computer you can also drag a file from My Computer onto someone's computer to send it." },
      { h: "Hiding your computer" },
      "Uncheck **Show my computer on the network** at the bottom (or in the View menu) to hide from everyone else's list. The status bar says (hidden) while you're hidden.",
      "View > Details shows more about each computer. View > Refresh updates the list.",
    ],
    related: ["winpopup", "game-invites", "online-play", "messenger"],
  },
  {
    id: "winpopup",
    book: "internet",
    title: "WinPopup",
    summary: "Send short pop-up notes to any computer in Network Neighborhood, no sign on needed.",
    keywords: ["popup", "net send", "messages", "notes", "WinPopup"],
    programs: ["WinPopup"],
    body: [
      "WinPopup sends quick little notes to anyone in Network Neighborhood. You don't need a screen name. Notes you get pop up on your screen and wait in WinPopup until you clear them.",
      { open: "WinPopup", label: "Open WinPopup" },
      {
        steps: ["Click **Send** (or Messages > Send...).", "Pick the computer to send to.", "Type your note (up to 500 characters) and click Send."],
        title: "To send a note:",
      },
      "When you've got notes, use the arrows (or Messages > Previous and Next) to read them, **Reply...** to answer the sender, **Discard** to throw one away and **Clear All** to empty the list.",
      { note: "WinPopup notes only reach people who have 98ish open right now. For someone who is away, use [[mail|98ish Mail]] or an [[messenger|instant message]] instead." },
    ],
    related: ["network-neighborhood", "messenger"],
  },
  {
    id: "youtube98",
    book: "internet",
    title: "YouTube '98",
    summary: "Watch videos in a tiny 1990s-style window, keep Favorites and share videos with buddies.",
    keywords: ["videos", "YouTube", "watch", "search videos", "share video"],
    programs: ["YouTube '98"],
    body: [
      "YouTube '98 is classic YouTube in an Internet Explorer window. Search for videos, watch them, and keep the ones you love.",
      { open: "YouTube '98", label: "Open YouTube '98" },
      {
        steps: ["Type in the **Search videos** box (or in the Address bar) and press Enter.", "Click a video to watch it.", "Related videos from your search are listed beside it."],
        title: "To find a video:",
      },
      "You can also paste a YouTube link into the Address bar to open that video.",
      { list: ["**Back**, **Forward** and **Home** work like a browser.", "Add a video to **Favorites** from its page. Favorites are kept on this device.", "**Share** posts the video to the 98ish Lobby chat room or sends it to a buddy. You need to be signed on to 98 Messenger to share."] },
    ],
    related: ["messenger", "internet-explorer"],
  },
  {
    id: "community-pages",
    book: "internet",
    title: "98ish.com: the Guestbook, Members and the web ring",
    summary: "The pages that live right inside 98ish: sign the Guestbook, see members' homepages and surf the web ring.",
    keywords: ["guestbook", "members directory", "web ring", "98ish.com", "hit counter", "Minesweeper Shrine", "community"],
    body: [
      "Some web pages live right here in 98ish instead of in the past. Open them in Internet Explorer, from the Links bar, or from Start > Programs > Community.",
      {
        list: [
          "**The 98ish Guestbook** (www.98ish.com/guestbook): leave a note for everyone who visits, with your name, your homepage if you have one, and a mood.",
          "**98ish Members** (www.98ish.com/members): the directory of homepages people built in HomePage Studio.",
          "**The Minesweeper Strategy Shrine**, **Cool Links of the Web** and **Rocky's Home Page** (a pet rock with a web page).",
        ],
      },
      { h: "The web ring" },
      "These pages and every published member homepage are linked in the 98ish web ring. Use the web ring links at the bottom of a page to hop to the next or previous site. Each page has its own hit counter, too.",
      {
        steps: ["Open Internet Explorer.", "Click **Guestbook** on the Links bar.", "Fill in your name, pick a mood and write your message, then sign it."],
        title: "To sign the Guestbook:",
      },
      { note: "Anything you write in the Guestbook can be seen by everyone who visits 98ish." },
    ],
    related: ["internet-explorer", "homepage-studio"],
  },
]
