// 98ish Help: making 98ish yours (Display, Themes, the Control Panel and its applets), the lock
// screen and user profiles, and Appward 98 / My Projects. Format: see ../helpCore.js.

export const books = [
  { id: "settings", title: "Make it yours", order: 70 },
  { id: "security", title: "Lock screen and users", order: 72 },
  { id: "business", title: "Appward 98 and My Projects", order: 65 },
]

export const topics = [
  // ---------------------------------------------------------------- Make it yours
  {
    id: "display",
    book: "settings",
    title: "Wallpaper, colors and screen savers",
    summary: "Display Properties: pick a wallpaper or your own photo, a color scheme, a screen saver and the startup screen.",
    keywords: ["wallpaper", "background", "desktop picture", "color scheme", "screen saver", "startup screen", "startup sound", "Floppy", "Display Properties", "mouse trail"],
    programs: ["Display Properties"],
    body: [
      "**Display Properties** changes how your desktop looks. Your choices are kept on this device, for you (each person who uses 98ish here has their own).",
      { open: "Display Properties", label: "Open Display Properties" },
      { h: "Change the wallpaper" },
      {
        steps: [
          "Open Display Properties (Start > Settings > Display Properties, or right-click the desktop and choose Properties).",
          "On the **Background** tab, pick a wallpaper from the list. The little monitor shows how it will look.",
          "To use one of your own pictures, click **Browse...** and choose a photo.",
          "Pick **Stretch**, **Center** or **Tile** under Display, then click **OK**.",
        ],
        title: "To change the wallpaper:",
      },
      { tip: "In Photos you can also use **Share > Set as Wallpaper** on any picture. Couples who are paired can pick **Our photos** to show pictures from Our Story, taking turns." },
      { note: "A very big picture may be too large to keep in the browser. If 98ish says so, try a smaller one." },
      { h: "Screen saver" },
      "On the **Screen Saver** tab, choose one (3D Pipes, Starfield Simulation, Mystify Your Mind, Flying 98ish, Scrolling Marquee, Beziers, Aquarium, Flower Garden or Love Notes). **Settings...** changes how it looks, **Preview** shows it now, and **Wait** sets how many minutes of doing nothing before it starts. Move the mouse, press a key or touch the screen to come back.",
      "Tick **Password protected** to lock 98ish when the screen saver starts. That needs a PIN or password first: see [[lock-screen]].",
      { h: "Colors and the mouse trail" },
      "The **Appearance** tab has color schemes for the title bars and the desktop (Windows Standard, Rainy Day, Lilac, Cotton Candy and many more), and a **Mouse trail** of sparkles or hearts. Trails only follow a mouse, not a finger.",
      { h: "Startup" },
      "The **Startup** tab turns the startup screen and the startup sound on or off, turns system sounds (dings, minimize, Recycle Bin) on or off, and shows or hides Floppy, the helper.",
      { note: "Browsers only allow sound after you click or tap, so the startup chime may wait for your first tap." },
    ],
    related: ["themes", "sounds", "accessibility", "power", "photos"],
  },
  {
    id: "themes",
    book: "settings",
    title: "Desktop Themes",
    summary: "Change the wallpaper, colors, sounds, pointers, icons and screen saver all at once with a theme.",
    keywords: ["themes", "Space", "Underwater", "Vaporwave", "Dinosaurs", "Kitty Cafe", "look and feel", "sound scheme", "pointers"],
    programs: ["Desktop Themes"],
    body: [
      "A **Desktop Theme** changes the whole look of 98ish in one go: the wallpaper, colors, icons, mouse pointers, sounds and screen saver all match.",
      "Themes include Space, Underwater, Vaporwave, Dinosaurs, Pastel Dream, Kitty Café, Flower Garden, Y2K Sparkle and Starry Night, plus Windows 98ish Standard to go back to the classic look.",
      {
        steps: [
          "Open Start > Settings > Desktop Themes (or the Themes... button in Display Properties).",
          "Pick a theme from the **Theme** list. The preview shows the wallpaper, a window and the icons.",
          "Click **Screen Saver** or **Pointers, Sounds, etc...** to try those parts out.",
          "Untick anything under **Settings** you don't want to change (for example keep your own wallpaper by unticking Desktop wallpaper).",
          "Click **OK** or **Apply**.",
        ],
        title: "To use a theme:",
      },
      { tip: "Applying a theme is easy to undo: pick Windows 98ish Standard, or change single parts later in Display Properties, Mouse or Sounds." },
      { open: "Desktop Themes", label: "Open Desktop Themes" },
    ],
    related: ["display", "sounds", "mouse"],
  },
  {
    id: "control-panel",
    book: "settings",
    title: "The Control Panel",
    summary: "Every setting in one folder: display, sounds, mouse, accessibility, passwords, storage and more.",
    keywords: ["Control Panel", "settings", "preferences", "options", "control"],
    programs: ["Control Panel"],
    body: [
      "The **Control Panel** is a folder with an icon for each kind of setting. Select an icon to read what it does, and open it to change things.",
      { steps: ["Click **Start**, point to **Settings**, then click **Control Panel**.", "Open the icon you want (double-click with a mouse, tap on a phone)."], title: "To open the Control Panel:" },
      "You can also reach it from My Computer, or by typing **control** in Start > Run.",
      { h: "What's inside" },
      {
        table: {
          head: ["Icon", "What it changes"],
          rows: [
            ["Accessibility Options", "Bigger text, high contrast, less motion, the Magnifier, larger tap targets"],
            ["Add/Remove Programs", "Which programs show on the desktop and in the Start menu"],
            ["Date/Time", "The date, time and time zone 98ish shows"],
            ["Desktop Themes", "The whole look at once"],
            ["Display", "Wallpaper, screen saver, colors, startup screen"],
            ["Fonts", "The fonts 98ish uses, with samples"],
            ["Internet Options", "Internet Explorer's home page, time machine date and History"],
            ["Keyboard", "The 98ish keyboard or your phone's own, and key repeat"],
            ["Mouse", "Double-click speed, pointers, trails, touch and hold"],
            ["Notifications", "Which notifications show, and push to your phone"],
            ["Passwords", "Your PIN or password, the lock screen, users"],
            ["Power Management", "When the screen saver starts and 98ish locks; keeping the screen on"],
            ["Regional Settings", "12- or 24-hour time, date order, first day of the week"],
            ["Sounds", "System sounds, sound scheme and volume"],
            ["Storage", "How much space 98ish uses, keeping your files safe"],
            ["System", "About this computer, and your Achievements"],
            ["Taskbar & Start Menu", "Auto hide, the clock, Quick Launch"],
          ],
        },
      },
      { open: "Control Panel", label: "Open the Control Panel" },
    ],
    related: ["display", "accessibility", "storage", "lock-screen", "taskbar-settings"],
  },
  {
    id: "accessibility",
    book: "settings",
    title: "Accessibility: bigger text, high contrast and less motion",
    summary: "Make 98ish easier to see and use: larger text, High Contrast colors, less motion, the Magnifier and bigger tap targets.",
    keywords: ["accessibility", "bigger text", "text size", "high contrast", "reduce motion", "larger tap targets", "screen reader", "low vision", "zoom"],
    programs: ["Accessibility Options"],
    body: [
      "**Accessibility Options** (in the Control Panel) makes 98ish easier to read and use. Changes apply to every window.",
      { open: "Accessibility Options", label: "Open Accessibility Options" },
      { h: "Display tab" },
      { list: ["**Text size:** Normal, Large or Extra Large. Every window, menu and title bar gets bigger writing.", "**High Contrast:** strong black or white colors that are easier to read. Games, Paint and Photos keep their own colors."] },
      { h: "Motion tab" },
      "**Reduce motion** turns off window and menu animations, the startup animation, moving wallpapers, sliding notifications, confetti and screen shake. **Use my device's setting** follows your phone or computer.",
      { h: "Magnifier tab" },
      "Shows the area around the mouse pointer (or the keyboard focus) bigger, in a window you can move. Pick the magnification (2x to 6x). See [[magnifier]].",
      {
        phone: "The Magnifier needs a mouse. On a phone, use your phone's own zoom (on iPhone: Settings > Accessibility > Zoom), and tick **Larger tap targets** so buttons, menus and lists are easier to hit.",
        computer: "Tick **Follow the mouse pointer** or **Follow the keyboard focus**, then open the Magnifier.",
      },
      { h: "Keyboard tab" },
      "Lists the keys for using 98ish without a mouse: {{Ctrl+Esc}} opens Start, {{Alt+Q}} switches windows, {{Alt+F4}} closes a window, {{Shift+F10}} opens a right-click menu, {{Tab}} and {{Enter}} move and open. A dotted rectangle shows where the keyboard is. Screen readers hear each window's title, the taskbar and the Start menu.",
    ],
    related: ["magnifier", "keyboard-shortcuts", "mouse", "display"],
  },
  {
    id: "mouse",
    book: "settings",
    title: "Mouse and touch settings",
    summary: "Double-click speed, left-handed buttons, pointer schemes and trails, and how long to touch and hold.",
    keywords: ["mouse", "double-click speed", "left-handed", "pointers", "cursor", "pointer trails", "touch and hold", "long press", "tap targets"],
    programs: ["Mouse"],
    body: [
      "**Mouse** in the Control Panel changes how clicking and touching work.",
      {
        list: [
          "**Buttons:** choose Right-handed or Left-handed (swaps the buttons), and set the double-click speed. Double-click the test box to try it.",
          "**Pointers:** pick a pointer scheme. The large ones (Windows Standard large, Black, Yellow) are easier to see. Desktop Themes change pointers too.",
          "**Motion:** turn on pointer trails (pointer, sparkles or hearts). Trails follow a mouse only, and stay off when motion is reduced.",
          "**Touch:** set how long you touch and hold before the right-click menu opens, and turn on larger tap targets.",
        ],
      },
      { phone: "On a phone, touching and holding something is the same as right-clicking it. If menus pop up too easily, or too slowly, change the delay on the Touch tab.", computer: "If double-clicking doesn't open things, slide the double-click speed toward Slow." },
      { open: "Mouse", label: "Open Mouse settings" },
    ],
    related: ["right-click", "accessibility", "themes"],
  },
  {
    id: "regional",
    book: "settings",
    title: "Time and date formats (Regional Settings)",
    summary: "Choose 12- or 24-hour time, the date order and the first day of the week.",
    keywords: ["regional settings", "24-hour clock", "12-hour clock", "date format", "first day of week", "Monday", "region", "locale"],
    programs: ["Regional Settings"],
    body: [
      "**Regional Settings** decides how 98ish writes times and dates. The taskbar clock, Calendar and Clock all follow it.",
      {
        steps: [
          "Open the Control Panel and then **Regional Settings**.",
          "On the **Regional Settings** tab, pick your region (or keep **Same as this device**).",
          "On the **Time** tab, choose **12-hour (7:05 PM)** or **24-hour (19:05)**.",
          "On the **Date** tab, choose the first day of the week (Sunday, Monday or Saturday) and the short date order.",
          "Click **OK**.",
        ],
        title: "To change the formats:",
      },
      { tip: "If the taskbar clock shows AM and PM and you'd rather have 24-hour time, set Time > Clock to 24-hour." },
      { open: "Regional Settings", label: "Open Regional Settings" },
    ],
    related: ["date-time", "calendar", "clock"],
  },
  {
    id: "sounds",
    book: "settings",
    title: "Sounds and volume",
    summary: "The volume, mute, system sounds, the startup sound and sound schemes.",
    keywords: ["sound", "volume", "mute", "system sounds", "sound scheme", "startup sound", "chime", "speaker"],
    programs: ["Sounds"],
    body: [
      "Every sound in 98ish (games, music, dings, ringing calls) follows one volume.",
      { steps: ["Click or tap the **speaker** in the taskbar, next to the clock.", "Drag the slider, or tick **Mute**."], title: "To change the volume:" },
      "**Sounds** in the Control Panel has more:",
      {
        list: [
          "**Events:** the list of system sounds. Select one and press the play button to hear it.",
          "**Scheme:** a set of sounds that go together (98ish Default, Space, Underwater, Synthwave, Dinosaurs, Music Box, Kitty Café, Birdsong).",
          "**Play system sounds** and **Play the startup sound** turn those on or off.",
          "**Volume** and **Mute**, the same as the taskbar speaker.",
        ],
      },
      { note: "No sound at all on an iPhone? See [[no-sound]]." },
      { open: "Sounds", label: "Open Sounds" },
    ],
    related: ["no-sound", "themes", "taskbar"],
  },
  {
    id: "power",
    book: "settings",
    title: "Power Management: screen saver, locking and keeping the screen on",
    summary: "Choose when the screen saver starts and when 98ish locks, and keep your screen from going dark.",
    keywords: ["power management", "keep screen on", "screen timeout", "battery", "wake lock", "auto lock", "idle"],
    programs: ["Power Management"],
    body: [
      "**Power Management** gathers the settings about time passing while you're not doing anything.",
      {
        list: [
          "**Start the screen saver:** Never, or after a number of minutes. Pick which screen saver in Display Properties.",
          "**Lock 98ish:** Never, or after a number of minutes with nothing typed or tapped. This needs a PIN or password first (see [[lock-screen]]).",
          "**Keep the screen on while 98ish is open:** handy for slideshows, the Clock and long games. It uses more battery, and some browsers can't do it.",
        ],
      },
      "If your device shares it, the top shows whether you're plugged in or on battery.",
      { open: "Power Management", label: "Open Power Management" },
    ],
    related: ["display", "lock-screen", "clock"],
  },
  {
    id: "fonts",
    book: "settings",
    title: "Fonts",
    summary: "See the fonts 98ish uses, with samples of each size.",
    keywords: ["fonts", "typefaces", "font samples", "text style"],
    programs: ["Fonts"],
    body: [
      "The **Fonts** folder lists the fonts 98ish uses and where each one shows up. Select a font to see what it's for in the status bar, and click **Open** to see its letters at several sizes.",
      "To make writing bigger everywhere, use Text size in [[accessibility]] instead. WordPad lets you pick fonts for your own documents.",
      { open: "Fonts", label: "Open Fonts" },
    ],
    related: ["accessibility", "wordpad"],
  },
  {
    id: "internet-options",
    book: "settings",
    title: "Internet Options",
    summary: "Set Internet Explorer's home page and time machine date, and clear its History.",
    keywords: ["internet options", "home page", "browser history", "clear history", "time machine date"],
    programs: ["Internet Options"],
    body: [
      "**Internet Options** holds Internet Explorer's settings.",
      {
        list: [
          "**Home page:** type an address, or click **Use Start Page** or **Use 98ish.com**. The Home button in Internet Explorer goes there.",
          "**Time machine:** the date Internet Explorer visits the Web as of. Pages show as the Internet Archive saved them closest to that date.",
          "**History:** **Clear History** forgets the pages you've visited.",
        ],
      },
      { open: "Internet Options", label: "Open Internet Options" },
    ],
    related: ["internet-explorer", "ie-time-machine"],
  },
  {
    id: "add-remove",
    book: "settings",
    title: "Hiding programs (Add/Remove Programs)",
    summary: "Take programs off your desktop and out of the Start menu, and bring them back.",
    keywords: ["add/remove programs", "uninstall", "hide programs", "remove icon", "declutter", "program size"],
    programs: ["Add/Remove Programs"],
    body: [
      "Too many icons? **Add/Remove Programs** hides the programs you don't use. Nothing is deleted: a hidden program's files and scores stay, and you can bring it back any time.",
      {
        steps: [
          "Open the Control Panel and then **Add/Remove Programs**.",
          "Select a program. You'll see its size and where it shows.",
          "Untick **Show on the desktop** or **Show in the Start menu**, or click **Add/Remove** to hide it from both.",
          "Click **OK**.",
        ],
        title: "To hide a program:",
      },
      "To bring it back, select it again (it says **(removed)**) and click **Add/Remove**.",
      { tip: "A hidden program still opens from Start > Run if you type its name." },
      { open: "Add/Remove Programs", label: "Open Add/Remove Programs" },
    ],
    related: ["desktop", "start-menu", "control-panel"],
  },
  {
    id: "date-time",
    book: "settings",
    title: "Date, time and time zone",
    summary: "Set the date, time and time zone 98ish shows, or go back to the real time.",
    keywords: ["date", "time", "time zone", "daylight saving", "clock", "Date/Time Properties", "wrong time"],
    programs: ["Date/Time Properties"],
    body: [
      "**Date/Time Properties** opens when you double-click the clock on the taskbar (or from the Control Panel).",
      {
        list: [
          "**Date & Time tab:** pick a month, year and day, and type a time. A web page can't change your real clock, so this only changes the time 98ish shows. **Use real time** puts it back.",
          "**Time Zone tab:** pick your zone from the list, or click near your city on the map. Tick **Automatically adjust clock for daylight saving changes**.",
        ],
      },
      { phone: "On a phone, touch and hold the taskbar clock for a menu with Adjust Date/Time, Calendar and Clock.", computer: "Right-click the taskbar clock for Adjust Date/Time, Calendar and Clock." },
      { tip: "For 12- or 24-hour time, see [[regional]]." },
      { open: "Date/Time Properties", label: "Open Date/Time Properties" },
    ],
    related: ["regional", "calendar", "clock", "taskbar"],
  },
  {
    id: "taskbar-settings",
    book: "settings",
    title: "Taskbar settings and Quick Launch",
    summary: "Auto hide the taskbar, show or hide the clock, and set up the Quick Launch toolbar.",
    keywords: ["taskbar properties", "auto hide", "hide clock", "Quick Launch", "toolbar", "cascade", "tile windows"],
    body: [
      "Right-click an empty part of the taskbar (or touch and hold it on a phone) and choose **Properties**, or go to Start > Settings > Taskbar & Start Menu.",
      { list: ["**Auto hide:** the taskbar slides away until you move the mouse to the bottom of the screen.", "**Show clock:** shows or hides the clock.", "**Show Quick Launch:** the little icons next to Start."] },
      { note: "Auto hide and Quick Launch are for bigger screens, so they're off on phones." },
      { shell: "taskbar-properties", label: "Open Taskbar Properties" },
      { h: "Quick Launch" },
      "Quick Launch holds one-click buttons for Show Desktop, Internet Explorer, My Computer and the MS-DOS Prompt. Drag any desktop icon onto it to add it. Right-click it for **Add to Quick Launch**, **Reset Quick Launch** and **Hide Quick Launch**; right-click a button to remove it.",
      { h: "The taskbar's right-click menu" },
      "It also has **Cascade Windows**, **Tile Windows Horizontally** and **Vertically**, **Minimize All Windows**, **Task Manager...** and **Keyboard Shortcuts...**.",
    ],
    related: ["taskbar", "windows", "keyboard-shortcuts"],
  },

  // ---------------------------------------------------------------- Lock screen and users
  {
    id: "lock-screen",
    book: "security",
    title: "Locking 98ish with a PIN or password",
    summary: "Set a PIN or password, lock 98ish by hand or after a while, and lock with the screen saver.",
    keywords: ["lock", "lock screen", "PIN", "password", "Lock Computer", "security", "auto lock", "Win+L", "Passwords"],
    programs: ["Passwords"],
    body: [
      "A PIN or password keeps your 98ish private when someone else picks up your phone or sits at your computer. While locked, 98ish keeps running underneath: 98 Messenger stays signed on and unsaved work is safe.",
      {
        steps: [
          "Open Start > Settings > **Passwords and Users**.",
          "On **Change Passwords**, choose **PIN (4 to 12 digits)** or **Password**.",
          "Type it twice and click **OK**.",
        ],
        title: "To set a PIN or password:",
      },
      { open: "Passwords", label: "Open Passwords", extra: { tab: "change" } },
      { h: "Locking" },
      { list: ["Start > **Lock Computer...**", "Keyboard: {{Ctrl+Alt+L}}, or {{Windows+L}} / {{Command+L}}", "Automatically: on the **Lock** tab, choose **Lock after** a number of minutes with no input", "With the screen saver: tick **Lock when the screen saver starts (Password protected)**"] },
      "98ish also opens locked when you come back after the wait, even if your phone reloaded the page.",
      { open: "Passwords", label: "Open the Lock tab", extra: { tab: "lock" } },
      { h: "While it's locked" },
      "Type your PIN or password to unlock. New messages show only as **New message**, so nobody can read them over your shoulder. If someone calls you, you can **Decline** right away, or **Answer** and the call connects once your PIN is right.",
      { note: "After a few wrong tries, 98ish makes you wait before the next one: 5 seconds, then 15, then 45, and longer each time (up to 15 minutes)." },
      "Only a scrambled (salted and hashed) copy of your PIN is kept on this device. The PIN itself is never stored, and it never goes to the server.",
      { tip: "Forgot it? See [[forgot-pin]]. Link your 98 Messenger screen name first, so you can reset it safely." },
    ],
    related: ["forgot-pin", "users", "power", "privacy-overview"],
  },
  {
    id: "users",
    book: "security",
    title: "Sharing a device: user profiles",
    summary: "Give each person their own desktop, files, settings and scores on the same phone or computer.",
    keywords: ["users", "user profiles", "log off", "log on", "switch user", "guest", "share computer", "accounts", "remove user"],
    body: [
      "If more than one person uses 98ish on the same device, each can have their own **user profile**: their own desktop, files, pictures, settings, theme and game scores. Nobody sees anyone else's things.",
      {
        steps: ["Open Start > Settings > **Passwords and Users**, then the **User Profiles** tab.", "Click **New User...**, type a name and click **Create**."],
        title: "To add a user:",
      },
      "Or choose Start > **Log Off** and type a new name at the Log On screen. 98ish asks whether to keep a separate desktop, settings and files for them; say **Yes**.",
      { h: "Switching between people" },
      "Use Start > **Log Off [name]...**, then pick who's next at the Log On screen. From the lock screen, click **Switch User...**. Switching restarts 98ish as the other person, so their open programs close (save your work first).",
      { h: "Your profile" },
      "On the User Profiles tab you can change your name and picture, and link your **98 Messenger screen name**. A linked screen name fills in at 98 Messenger's Sign On and lets you reset a forgotten PIN. **Sign me on automatically** is kept separately for each user.",
      { h: "Removing someone" },
      { warning: "**Remove** deletes that person and everything 98ish keeps for them on this device (desktop, files, pictures, settings and scores). It can't be undone. If they have a PIN, it's needed to remove them." },
      { note: "A user profile is not the same as a 98 Messenger account. Profiles live only on this device; your screen name works on any device." },
      { open: "Passwords", label: "Open User Profiles", extra: { tab: "users" } },
    ],
    related: ["lock-screen", "forgot-pin", "messenger-accounts", "privacy-overview"],
  },
  {
    id: "forgot-pin",
    book: "security",
    title: "Forgot your PIN or password?",
    summary: "Reset a forgotten lock screen PIN through 98 Messenger, or by removing the lock on this device.",
    keywords: ["forgot PIN", "forgot password", "reset PIN", "locked out", "can't unlock"],
    body: [
      "On the lock screen, click **Forgot PIN?** (or Forgot password?). What happens next depends on whether your profile has a linked 98 Messenger screen name.",
      { h: "With a linked screen name" },
      {
        steps: ["Click **Forgot PIN?**.", "Type your **98 Messenger password** and click **Sign In**.", "The PIN is removed and 98ish unlocks. Set a new one in Passwords."],
        title: "To reset it:",
      },
      "This is the safe way: only someone who knows your 98 Messenger password can do it.",
      { h: "Without a linked screen name" },
      "98ish can only remove the lock settings on this device. Tick **I understand** and confirm. Your files, settings and messages stay; only the PIN is removed.",
      { warning: "Anyone holding your device could do this too. To keep the lock strong, link your screen name: Passwords and Users > User Profiles > 98 Messenger screen name." },
      { open: "Passwords", label: "Link a screen name", extra: { tab: "users" } },
    ],
    related: ["lock-screen", "users", "messenger-accounts"],
  },

  // ---------------------------------------------------------------- Appward 98 and My Projects
  {
    id: "appward",
    book: "business",
    title: "Appward 98",
    summary: "A just-for-fun 1998-style tribute to the Appward business suite, with linked business apps and made-up sample data.",
    keywords: ["Appward", "business", "work orders", "App Creator", "Report Builder", "Insights", "CRM", "sample data"],
    programs: ["Appward 98"],
    body: [
      "**Appward 98** is an unofficial, fan-made tribute to Appward, a real business suite, imagined as if it had shipped for Windows 98. It's for fun: the company, people and records in it are all made up.",
      { h: "Getting started" },
      {
        steps: [
          "Open Appward 98 from the desktop or Start > Programs > Business.",
          "Sign in with **any name and password**: your workspace is kept on this computer.",
          "The first time, a Setup Wizard asks for a company name and offers a workspace full of sample records. Say yes to see what it can do.",
        ],
        title: "To start:",
      },
      { h: "Finding your way around" },
      "The **App Launcher** on the left lists dozens of apps by category (Productivity, Sales, People, Operations, Manufacturing, Quality, Development). Conversations, Actions, Calendars, Leads, Work Orders and the rest are linked together, so a record can point to a company, a person or a part. Each app opens in a tab.",
      "The **Tools** menu has the **App Creator** (make your own app), the **Report Builder**, **Insights** charts and the Database Manager.",
      {
        keys: [
          ["Ctrl+N", "New record"],
          ["Ctrl+O", "Open a record by number"],
          ["Ctrl+S", "Save the record"],
          ["Ctrl+F or F3", "Search everything"],
          ["Ctrl+Shift+W", "Close the tab"],
          ["F5", "Sync your workspace"],
          ["F1", "Appward's shortcut list"],
        ],
        title: "Appward 98 shortcuts",
      },
      { note: "Everything you add stays in this browser on this device. It isn't sent anywhere." },
      { open: "Appward 98", label: "Open Appward 98" },
    ],
    related: ["my-projects", "privacy-overview"],
  },
  {
    id: "my-projects",
    book: "business",
    title: "My Projects: Baseline Today, Job Market Radar and One Closet",
    summary: "Brandon's other web apps, each running live in its own 98ish window.",
    keywords: ["My Projects", "Baseline Today", "Job Market Radar", "One Closet", "tennis rankings", "web apps"],
    programs: ["Baseline Today", "Job Market Radar", "One Closet"],
    body: [
      "Start > Programs > **My Projects** has real websites made by Brandon, each opened inside a 98ish window:",
      {
        list: [
          "**Baseline Today:** ATP and WTA singles rankings, recent results, player profiles and season records.",
          "**Job Market Radar:** which US industries are rising and sinking, from job postings, hiring and employment data.",
          "**One Closet:** everything you love from every store, in one place.",
        ],
      },
      "The thin toolbar at the top has a button to go back to the site's start page, and one to open the site in its own browser window.",
      { tip: "If a site won't load in the window, or signing in to One Closet doesn't stick, use the open-in-a-new-window button: some browsers block sign-in inside another site." },
      { note: "These are live websites on the internet, so they need a connection." },
    ],
    related: ["appward", "internet-explorer"],
  },
]
