// 98ish Help: troubleshooting, and privacy (what's kept where, what the server sees).
// Format: see ../helpCore.js.

export const books = [
  { id: "trouble", title: "Troubleshooting", order: 90 },
  { id: "privacy", title: "Privacy and your data", order: 95 },
]

export const topics = [
  // ---------------------------------------------------------------- Troubleshooting
  {
    id: "trouble-start",
    book: "trouble",
    title: "Something's not working: start here",
    summary: "Pick what's wrong and jump to the fix.",
    keywords: ["troubleshooting", "problems", "not working", "help me", "broken", "fix", "bug"],
    body: [
      "Sorry something's not right! Find what's happening below.",
      {
        list: [
          "A game or 98 Messenger says it's connecting or **waking up**: [[server-waking]]",
          "**No sound**, especially on an iPhone: [[no-sound]]",
          "**Notifications** don't come when 98ish is closed: [[push-setup]]",
          "**Drive C: is full**, or a photo won't save: [[storage-full]]",
          "A **call** won't connect, or drops: [[calls-trouble]]",
          "The **on-screen keyboard** is in the way, or you need emoji or AutoFill: [[keyboard-trouble]]",
          "Your **files are missing**: [[lost-files]]",
          "A **game** is stuck or acting up: [[game-trouble]]",
          "You want to **start over** or clear things out: [[reset-data]]",
          "You **forgot your PIN**: [[forgot-pin]]",
        ],
      },
      { h: "Quick things that fix a lot" },
      {
        steps: [
          "Close the program and open it again.",
          "Reload the page (pull down in Safari, or the reload button in your browser). Your files and settings are kept.",
          "Check that your phone or computer is online.",
          "Wait a minute and try again: the 98ish server may be waking up.",
        ],
        title: "Try these first:",
      },
      { tip: "Found a real bug, or have an idea? Welcome to 98ish > Get involved > **Send feedback** opens the 98ish page on GitHub, where you can tell us about it." },
    ],
    related: ["server-waking", "no-sound", "reset-data", "privacy-overview"],
  },
  {
    id: "server-waking",
    book: "trouble",
    title: "\"Waking up the server\" and connection problems",
    summary: "Online games, 98 Messenger and Mail need the 98ish server, which can take up to a minute to wake up.",
    keywords: ["waking up", "server", "connecting", "reconnecting", "can't connect", "offline", "slow to sign on", "game server"],
    body: [
      "Everything you do with other people (98 Messenger, Mail, online games, shared calendars, Us, file sync) goes through the 98ish server. It runs on a free plan, which can take a nap when nobody has used it for a while.",
      "When that happens you'll see something like **Waking up the game server...** with a seconds counter, or 98 Messenger stays on **Connecting...**. Waking up takes **up to about a minute**. Just wait; it connects by itself.",
      { h: "What the messages mean" },
      {
        table: {
          head: ["You see", "What to do"],
          rows: [
            ["Connecting... / Waking up the game server...", "Wait up to a minute."],
            ["Reconnecting...", "The connection blinked (a phone going to sleep, a tunnel). It comes back by itself."],
            ["You're not connected to the internet", "Check Wi-Fi or cellular data, then press **Try Again**."],
            ["Can't reach the game server right now", "Check your connection and press **Try Again** in a minute."],
          ],
        },
      },
      { note: "Things you do alone (your files, Notepad, Paint, playing the computer in most games) work without the server, even offline once 98ish has loaded." },
      { tip: "A Calendar or Dream House change that couldn't reach the server says so, and is sent again when the server is back." },
    ],
    related: ["trouble-start", "online-play", "messenger", "game-trouble"],
  },
  {
    id: "no-sound",
    book: "trouble",
    title: "No sound (especially on iPhone)",
    summary: "Sound starts after your first tap; check the volume, the ringer switch and the 98ish speaker.",
    keywords: ["no sound", "silent", "mute", "audio", "iPhone sound", "ringer switch", "volume", "can't hear"],
    body: [
      "Browsers don't let a web page make any sound until you've **tapped or clicked** something. So the startup chime, game music and other sounds start after your first tap. That's normal.",
      { h: "Still quiet? Check these" },
      {
        steps: [
          "Tap anywhere in 98ish once, then try again.",
          "Check the **speaker** in the 98ish taskbar: is it muted, or the slider all the way down?",
          "Turn up your phone's or computer's own volume.",
          "On iPhone, check the **ring/silent switch** (or Action button) on the side. In silent mode iPhones mute most web page sounds. The Media Player plays through it, like a music app.",
          "Make sure **Play system sounds** is ticked in Sounds (Control Panel) if it's the dings and clicks you're missing.",
          "If 98ish was in the background, tap once after coming back: iPhones pause web sound in the background.",
        ],
        title: "To get sound back:",
      },
      { note: "During a 98 Messenger call, your iPhone picks the speaker or earpiece itself. Use the volume buttons, or Control Center to switch to headphones." },
      { open: "Sounds", label: "Open Sounds" },
    ],
    related: ["sounds", "messenger-calls", "trouble-start"],
  },
  {
    id: "push-setup",
    book: "trouble",
    title: "Notifications don't come when 98ish is closed",
    summary: "On iPhone, notifications need 98ish on the Home Screen (iOS 16.4 or later), turned on from Notifications settings.",
    keywords: ["push notifications", "notifications not working", "no notifications", "iPhone notifications", "Home Screen", "quiet hours", "test notification"],
    body: [
      "While 98ish is open, everything shows in the bell (the Notification Center) on the taskbar. To get IMs, calls, reminders and more **when 98ish is closed**, turn on notifications for each device. You need to be signed on to 98 Messenger: notifications go to your screen name.",
      { h: "On an iPhone" },
      "iPhones only send notifications to web apps that are on the **Home Screen**, and it needs **iOS 16.4 or later**.",
      {
        steps: [
          "Open 98ish in **Safari**.",
          "Tap the **Share** button (the square with an arrow), scroll down and tap **Add to Home Screen**, then **Add**.",
          "Open **98ish from your Home Screen** (not Safari) and sign on to 98 Messenger.",
          "Open Start > Settings > **Notifications...** and tap **Turn on notifications**, then **Allow**.",
          "Tap **Send a test** to check it works.",
        ],
        title: "To turn them on:",
      },
      { shell: "notification-settings", label: "Open Notifications settings" },
      { h: "Still nothing?" },
      {
        list: [
          "If it says notifications are **blocked**, allow them in iPhone Settings > Notifications > 98ish (or your browser's site settings), then come back.",
          "Check **Quiet hours** in the Notifications settings. Calls can ring through if you tick **Let calls ring through**.",
          "Check the kinds under **Notify me about** (Instant messages, Calls, Calendar reminders, Us, Mail, Game invitations).",
          "Notifications only arrive when you're away from 98ish (signed off, or 98ish closed or in the background). While you're using it, they show in the bell instead.",
          "If it says notifications aren't set up on this server, there's nothing to fix on your side.",
        ],
      },
      { note: "A closed 98ish can't ring like a phone call. An incoming call shows as a notification; tap it to open 98ish and answer while it's still ringing." },
    ],
    related: ["notifications", "home-screen", "messenger-calls", "calendar"],
  },
  {
    id: "storage-full",
    book: "trouble",
    title: "\"Drive C: is full\"",
    summary: "Make room on drive C:, keep your files from being cleared, and why a private window has less space.",
    keywords: ["drive full", "disk full", "out of space", "storage full", "can't save", "private browsing", "not enough space"],
    body: [
      "98ish keeps your files in your browser, on this device. If the browser runs out of the space it gives 98ish, saving fails with **Drive C: is full**.",
      {
        steps: [
          "Delete files you don't need, especially big photos and videos in My Pictures.",
          "**Empty the Recycle Bin** (right-click it, or the button in Control Panel > Storage). Deleted files still take space until you do.",
          "Try saving again.",
        ],
        title: "To make room:",
      },
      "**Control Panel > Storage** shows how much 98ish uses and how much is free on this device. In My Computer, right-click drive C: and choose Properties for the same picture.",
      { open: "Storage", label: "Open Storage" },
      { h: "Keep your files safe" },
      "Browsers may clear a website's files when a device runs very low on space. In Storage, click **Keep my files on this device** to ask the browser not to. Browsers usually agree once 98ish is added to the Home Screen or used often.",
      { h: "Private windows" },
      "In a private (incognito) window, some browsers won't give 98ish its bigger storage, so your files go in a small one (about 5 MB), and private windows usually forget everything when they close. 98ish shows a notice when that happens. Use a normal window to keep your files.",
      { tip: "Make a Backup now and then, or turn on file sync, so a full or cleared device never costs you your files." },
    ],
    related: ["storage", "recycle-bin", "backup", "file-sync", "reset-data"],
  },
  {
    id: "reset-data",
    book: "trouble",
    title: "Starting over and clearing data safely",
    summary: "Back up first, then clear just what you need: a user, the Recycle Bin, or all of 98ish's data in the browser.",
    keywords: ["reset", "clear data", "start over", "delete everything", "website data", "clear cache", "fresh start", "remove 98ish"],
    body: [
      { warning: "Clearing 98ish's website data deletes **everything 98ish keeps on this device**: your files and photos, settings, game scores and saves, and every user profile. It can't be undone. Back up first." },
      {
        steps: ["Open **Backup** (Start > Programs > System Tools).", "Click **Back up to your computer**. A .98ish file is saved to your Downloads.", "Or turn on **Sync with 98 Messenger** so My Documents, My Pictures and the Desktop are kept online."],
        title: "Back up first:",
      },
      { open: "Backup", label: "Open Backup" },
      { h: "Try something smaller first" },
      {
        list: [
          "Too many files? Delete them and empty the Recycle Bin.",
          "Too many icons? Hide programs with [[add-remove|Add/Remove Programs]].",
          "Someone else's things? Remove their user profile in Passwords and Users (this deletes only their data).",
          "A messy desktop look? Pick Windows 98ish Standard in Desktop Themes.",
          "Want an old version of your drive back? Backup > **Restore from a backup** replaces everything on C: with the backup.",
        ],
      },
      { h: "Clearing all of 98ish's data" },
      {
        phone: "iPhone (Safari): Settings > Apps > Safari (or Settings > Safari on older iPhones) > Advanced > Website Data, find 98ish.vercel.app and delete it. If 98ish is on your Home Screen, it keeps its own data: deleting the Home Screen icon removes that copy.",
        computer: "Chrome or Edge: click the icon at the left of the address bar, choose Site settings, then Delete data. Firefox and Safari have similar options in their privacy settings.",
      },
      { note: "This only clears this device. Your 98 Messenger account, mail, server calendars, synced files and Us things stay on the server, and come back when you sign on again." },
    ],
    related: ["backup", "storage-full", "users", "privacy-delete"],
  },
  {
    id: "calls-trouble",
    book: "trouble",
    title: "Calls won't connect, or have no picture or sound",
    summary: "Fixes for 98 Messenger voice and video calls: permissions, Wi-Fi vs cellular, and keeping 98ish open.",
    keywords: ["call failed", "call won't connect", "video call problem", "microphone", "camera blocked", "cellular", "Wi-Fi", "call dropped"],
    body: [
      "98 Messenger calls go straight from one device to the other. Most Wi-Fi works fine. Some networks, often **cellular data** or a strict work or school Wi-Fi, block direct connections. Then the call rings and is answered, but after about 30 seconds it says it **couldn't connect**.",
      {
        steps: ["Try again with **both of you on Wi-Fi**.", "If one of you is on cellular, switch that phone to Wi-Fi (or the other way around) and call again."],
        title: "If a call couldn't connect:",
      },
      { h: "Camera or microphone problems" },
      {
        list: [
          "**98ish isn't allowed to use your camera/microphone:** allow it in your browser's site settings. On iPhone: Settings > Safari > Camera and Microphone (or Settings > Apps > Safari).",
          "**No camera or microphone was found:** plug one in, or use a device that has one.",
          "**Being used by another app:** close the other app (a video chat, the Camera app) and try again.",
          "**Your camera stopped:** tap **Camera On** to turn it back on.",
        ],
      },
      { h: "On an iPhone" },
      "Keep 98ish open and on screen during the call: Safari pauses calls in the background or when the screen locks.",
      { note: "Calls need you both signed on to 98 Messenger. If the other person is signed off with notifications on, their phone gets a notification and the call can still reach them if they open 98ish while it rings." },
    ],
    related: ["messenger-calls", "no-sound", "push-setup"],
  },
  {
    id: "keyboard-trouble",
    book: "trouble",
    title: "Keyboard problems on a phone",
    summary: "Hide the 98ish keyboard, or use your phone's own keyboard instead (for emoji, dictation or AutoFill).",
    keywords: ["keyboard", "on-screen keyboard", "emoji", "dictation", "AutoFill", "keyboard covers buttons", "phone keyboard"],
    body: [
      "On touch screens, 98ish types with its own **98ish keyboard**, a Windows 98-style keyboard that sits above the taskbar. It stays up while you tap around, so it doesn't jump up and down.",
      { h: "Common fixes" },
      {
        list: [
          "**It's covering a button:** tap the **X** in the keyboard's title bar (Hide keyboard), then tap the button.",
          "**You need emoji, dictation, another language or password AutoFill:** those come with your phone's own keyboard: open Start > Settings > Keyboard and choose **My phone's own keyboard** (and choose the 98ish keyboard there again to come back).",
          "**You'd rather always use your phone's keyboard:** open Start > Settings > Keyboard and choose **My phone's own keyboard**.",
          "**Key clicks or vibration bother you:** turn them off under **While typing »** in Keyboard Properties.",
        ],
      },
      { open: "Keyboard Properties", label: "Open Keyboard Properties" },
    ],
    related: ["phone-keyboard", "phone-basics"],
  },
  {
    id: "lost-files",
    book: "trouble",
    title: "Where did my files go?",
    summary: "Check the Recycle Bin, the right user, the right browser or Home Screen app, and file sync.",
    keywords: ["lost files", "missing files", "deleted by mistake", "undelete", "recover", "files gone", "(from iPhone)"],
    body: [
      "Files almost never just disappear. Check these, in order:",
      {
        steps: [
          "**The Recycle Bin.** Deleted files go there. Open it, select the file and choose Restore.",
          "**The right person.** If several people use this device, each user has their own files. Check who's logged on (Start > Log Off shows the name).",
          "**The same browser.** Each browser keeps its own 98ish. On iPhone, 98ish opened from the **Home Screen** keeps its files separate from 98ish in **Safari**.",
          "**Search.** Type the file's name in the Start menu's search box, or use Find.",
          "**File sync.** If you sync with 98 Messenger, sign on and let it catch up (Backup > Sync Now). A file deleted on another device lands in this device's Recycle Bin.",
          "**A backup.** Backup > Restore from a backup puts back everything from a .98ish file (it replaces what's on C: now).",
        ],
        title: "To find a missing file:",
      },
      { note: "If a file was changed on two devices before they synced, both copies are kept: one gets a name like \"Notes (from iPhone)\"." },
      { warning: "Files deleted with the DEL command in the MS-DOS Prompt skip the Recycle Bin and are gone for good." },
    ],
    related: ["recycle-bin", "file-sync", "backup", "users", "search"],
  },
  {
    id: "game-trouble",
    book: "trouble",
    title: "Game problems",
    summary: "What to do when a game is stuck, an online match won't start, or the controls get in the way.",
    keywords: ["game stuck", "game frozen", "lag", "online game problem", "controls", "can't join room", "opponent left"],
    body: [
      { h: "A game is stuck or slow" },
      {
        list: [
          "Close the game window and open it again.",
          "Close other big games you have open: the 3D ones (Pickleball 98, Shred 98, SPECTRA) use a lot of power.",
          "Reload the page if it still misbehaves. Your scores are kept.",
        ],
      },
      { h: "Online play" },
      {
        list: [
          "**Waiting a long time to connect:** the server may be waking up. See [[server-waking]].",
          "**A room code doesn't work:** check the letters, and make sure the room is still open (the host may have left). Codes are for the same game.",
          "**Nobody in Quick Match:** choose Play the Computer, or invite a friend with a room code.",
          "**Someone dropped out:** a computer player takes over their seat, so the game keeps going.",
        ],
      },
      { h: "On a phone" },
      "The on-screen buttons can be moved and resized if they cover something: see [[touch-controls]]. Turning the phone sideways gives some games more room.",
      { tip: "No sound in a game? See [[no-sound]]." },
    ],
    related: ["online-play", "touch-controls", "server-waking", "no-sound"],
  },

  // ---------------------------------------------------------------- Privacy
  // Written from the code (client/src/utils, server/*; the full server list with what deleting
  // an account does is at the top of server/account/index.js). Update with each feature.
  {
    id: "privacy-overview",
    book: "privacy",
    title: "What 98ish keeps, and where",
    summary: "Without an account, everything stays on your device. With a 98 Messenger account, some things are kept on the 98ish server too.",
    keywords: ["privacy", "data", "where is my data stored", "local storage", "on this device", "personal information", "what is collected"],
    body: [
      "98ish needs no sign-up. As a guest, **everything stays in your browser, on this device**: nothing about you is kept on the 98ish server. A **98 Messenger account** is optional; with one, the things listed in [[privacy-server]] are kept on the server so they work on all your devices.",
      {
        table: {
          head: ["Where", "What", "How long"],
          rows: [
            ["This device (your browser)", "Your files and photos, settings, scores and saves, lock PIN (scrambled), contacts, notes, notifications. See [[privacy-device]].", "Until you delete them, remove the user, or clear the website's data. Safari on iPhone may clear it after 7 days without a visit unless 98ish is on the Home Screen."],
            ["The 98ish server (with an account)", "Your account, synced files, mail, Address Book, notes, server calendars and tasks, Us things, games and homepage, and your latest location while you share it in Buddy Locator. See [[privacy-server]].", "Until you delete them or [[delete-account|delete your account]]. A few things expire sooner (listed there)."],
            ["Other services", "Push notifications, call setup, YouTube and the Internet Archive. See [[privacy-third-parties]].", "Their own rules."],
          ],
        },
      },
      { h: "Where the server is" },
      "The 98ish server runs on **Render** (a hosting company, US), and keeps what it stores in a **MongoDB Atlas** database (MongoDB's cloud service, free tier). The contents of synced files (your photos and documents) are kept in **Vercel Blob**, Vercel's private file storage: your devices send and fetch them there with links the server signs for your account, good for a few minutes. The 98ish website itself is served by **Vercel**. Live things (who's online, chat rooms, calls, online games) are kept only in the server's memory and are gone when you sign off or the server restarts.",
      { h: "Who can see what" },
      {
        list: [
          "**Only you**: your files (also the synced copies), Address Book, notes you haven't shared, mail (each person has their own copy), your personal calendar and its tasks, notification settings.",
          "**People you share a note with**: that note, and the screen names of everyone in it.",
          "**People you send a program to** (Visual Basic 98): the program and its Shared values (votes, scores, a game board), and the screen names of everyone it was sent to.",
          "**Friends who come over** (Come Over): your pointer, which window you're in (its title, except for private programs), and your desktop's wallpaper, icons and window titles, live while you're together; shared notes, pictures and folders go to everyone in them.",
          "**Buddies you share your location with** (Buddy Locator): your latest position and when it was sent, until the share ends or you pause; and when you're at one of Pickleball 98's real venues, which venue and which court (worked out on the server from that same position, kept in memory only, never stored).",
          "**Your pickleball group** (Pickleball 98's Real Games): a session's details, RSVPs, running-late notes and chat go to everyone invited to it; a match you log goes to everyone who played in it; your rating and record show on the ladder of people you've played or planned with.",
          "**Your buddies, while you're away** (Pickleball 98's Living Park, only if you leave your clone in the park): your clone (the counts of what you did in your games, the same as a shared clone file), your player's look, your name, the venue and the lines you approved for it to say. Only buddies on your Buddy List see it, only at that venue and only while you're signed off; people you've blocked never do.",
          "**Your partner** (in Us, while paired): letters, Our Story and its photos, flowers, Our Pet, Dream House, the Us calendar, your Sunny Acres town, couple quizzes.",
          "**Calendar members**: a shared calendar's events, comments and activity, and your screen name in it. Anyone with a calendar's secret subscription link can read that calendar.",
          "**Signed-on 98 Messenger users**: your screen name, profile text, member-since date, and whether you're online, away or idle (people you block don't see you online).",
          "**Anyone**: published homepages, guestbook entries (under the name you type), Tetris Online top ranks (screen name and stars), and, while 98ish is open, your screen name (or GUEST-XXXX) in Network Neighborhood, game lobbies and game chat.",
        ],
      },
      { h: "Deleting" },
      "**Delete My Account** removes your account and everything the server keeps for it, and can erase this device's copy too. See [[delete-account]] and [[privacy-delete]].",
      { note: "98ish is a small hobby project run by friends, not a company. There are no ads and no tracking or analytics scripts. Don't use it for anything truly secret." },
    ],
    related: ["privacy-device", "privacy-server", "privacy-third-parties", "privacy-couples", "privacy-delete", "delete-account"],
  },
  {
    id: "privacy-device",
    book: "privacy",
    title: "What's kept on this device",
    summary: "98ish keeps your things in this browser's storage, separately for each user profile.",
    keywords: ["device storage", "localStorage", "IndexedDB", "browser storage", "cache", "user profiles privacy", "cleared after 7 days"],
    body: [
      "Everything below stays in this browser on this device. 98ish doesn't send it anywhere unless you use a 98 Messenger feature that says so (like file sync).",
      {
        table: {
          head: ["Kept in", "What"],
          rows: [
            ["IndexedDB (database \"98ish-drive\")", "Drive C: and the Recycle Bin: files, photos, documents, recordings, and file sync's bookkeeping. Each extra user profile has its own database (\"98ish-drive-\" plus an id)."],
            ["IndexedDB (database \"98ish-music\")", "Music 98's album art (small pictures from your songs). The songs themselves are files in Drive C: (C:\\My Music); their names, artists and playlists are in localStorage \"98ish.music\"."],
            ["Drive C:\\My Head\\head.zip", "Be Yourself: your 3D head (a LAM avatar file), if you made or imported one. It syncs like your other files; during a call with 3D Me on, it's sent straight to the friend you're calling (not through 98ish's server) and kept by their 98ish only for that call."],
            ["IndexedDB (database \"98ish-twin\")", "Pickleball 98's Twin Replay: your filmed or opened game videos, the court corners you tapped, what was read from them (everyone's positions and hits, the names you gave) and replays friends sent you. Never uploaded. Each extra user profile has its own (\"98ish-twin-\" plus an id), deleted with the profile."],
            ["IndexedDB (database \"98ish-venues\", shared by the device)", "Pickleball 98's Venue Finder: the last 60 venues it built from the map, so they open again offline. Public map data only, nothing about you."],
            ["localStorage (keys starting \"98ish.\")", "Settings, desktop, scores and game saves (and Casino 98's play chips, and Pickleball 98's last My Park venue and favorite venues; Real Games' scorekeeper settings, a game in progress and matches waiting to be sent; the Visual Basic 98 program you're working on, as a draft; Coach, \"98ish.pickleball.coach\": who you are in each filmed game, your target level, your numbers per game and your practice plan; Twin Clones, \"98ish.pickleball.clones\": the counts of what each clone's person did in your games, never uploaded unless you share your own or leave it in the park; My Park's regulars' memory, \"98ish.pickleball.parkMemory.\" plus the venue: when they last met you and your last 5 results there), Address Book contacts, notes (and which are pinned to this desktop), notifications, \"On this device\" calendars, reminders, Internet Explorer history and favorites, drafts, and 98 Messenger's \"Sign me on automatically\" key. Each extra user profile's keys start \"98ish.u.\" plus an id."],
            ["Cache Storage (\"transformers-cache\", shared by the device)", "Floppy's brain, if you downloaded it: the AI model's files (about 500 MB). What you type to Floppy is never saved or sent; the chat is gone when you close it. Questions SmarterChild answers with the brain are kept only in this device's copy of that conversation, never sent. Delete the brain in Control Panel > Storage."],
            ["The user list (shared by the device)", "User names, pictures, linked screen names, and each user's lock PIN or password, stored only as a salted, scrambled copy (PBKDF2)."],
            ["Service worker caches", "A copy of the 98ish app for offline use, things shared to 98ish from other apps (Android), and notifications that arrived while 98ish was closed."],
          ],
        },
      },
      "**Shared Albums**: previews and photos you've opened or added, and uploads waiting, are kept in IndexedDB database \"98ish-albums\" (the newest 150 photos and videos), separately for each screen name; which albums you've seen and Memories' settings are in localStorage. See [[shared-albums]].",
      "**98 Messenger conversations** (IMs, Buddy Chat messages, reactions, and pictures and voice messages you sent or opened) are kept in IndexedDB database \"98ish-im\" (\"98ish-im-\" plus an id for extra user profiles), separately for each screen name signed on here, until you clear the conversation (More » > Clear History), delete the account, or remove the user. See [[messenger-history]].",
      { h: "How long" },
      "Until you delete them. A browser may clear website storage when the device is very low on space, unless it agreed to keep it (Control Panel > Storage shows **Kept**). **Safari on iPhone and iPad clears a website's storage after about 7 days without a visit**, unless 98ish is added to the Home Screen and opened from there. Signing on to 98 Messenger keeps a copy of your files online ([[file-sync]]), and Backup saves a copy as a file.",
      { h: "Other people on this device" },
      "Each user profile has its own files and settings, but they're in the same browser: anyone who can use this device and its browser could look at the storage with developer tools. A lock PIN keeps people out of 98ish, not out of the browser.",
      { open: "Storage", label: "Open Storage" },
    ],
    related: ["privacy-overview", "storage", "users", "backup", "file-sync", "reset-data"],
  },
  {
    id: "privacy-server",
    book: "privacy",
    title: "What the 98ish server keeps",
    summary: "Exactly what's stored for a 98 Messenger account, for how long, and who can see it.",
    keywords: ["server", "what the server sees", "what is stored online", "messages privacy", "IP address", "security", "who can see", "how long", "MongoDB", "Render"],
    body: [
      "Only with a 98 Messenger account (and only for the features you use). Everything is kept in the 98ish database (MongoDB Atlas) by the server on Render, except the contents of synced files, which are kept in Vercel Blob (private file storage; the database keeps their list).",
      {
        table: {
          head: ["What", "Kept", "Who can see it"],
          rows: [
            ["Account: screen name, password (scrambled with bcrypt), profile text, Buddy List, block list, when you joined", "Until you delete the account", "Profile and member-since: any signed-on user. The rest: only you"],
            ["\"Sign me on automatically\" keys (scrambled), up to 6 devices", "60 days after last use, or until you sign off on purpose", "Nobody"],
            ["Saved conversations: the words of your IMs and Buddy Chat messages, who sent them and when, reactions (only if **Save my conversations on the server** is on, the default; never SmarterChild)", "Up to a year, the newest 2,000 per conversation (1,000 per chat room); until you clear the conversation, turn saving off, or delete the account", "You and the person you were talking to (each has their own copy, kept by their own setting); in a chat room, the people who were in it at the time"],
            ["Pictures and voice messages sent in IMs", "90 days, then deleted", "You and the person you sent it to (fetched with links that work for a few minutes)"],
            ["Shared Albums: the album's name and people, the photos and videos added (in Vercel Blob) with a small preview, who added each and when, captions, likes and comments", "Until removed, or the album is deleted; up to 40 MB added per screen name, 500 items and 20 people per album", "The album's members (photos fetched with links that work for 5 minutes)"],
            ["Read receipts: the newest message each person has seen in a conversation, and when (only while Read receipts is on)", "Until you turn read receipts off or delete the account", "The other person in the conversation"],
            ["IMs sent to you while you were signed off (only if you have notifications on)", "Until you sign on, at most 30 days", "You"],
            ["Synced files (My Documents, My Pictures, Desktop by default) and device sync keys", "Until you delete them (deleted files are remembered as deleted); device keys 60 days after last use", "You"],
            ["98ish Mail: your own copy of every message, with attachments", "Until you delete it; 5 MB per mailbox (oldest Deleted Items go first when full)", "You; the people you send to get their own copy"],
            ["Address Book (when signed on)", "Until you delete contacts (deleted ones are remembered 180 days so other devices hear about it)", "You"],
            ["Notes (when signed on): their words, checklists, colors, and who they're shared with. Which notes are pinned to a desktop stays on that device", "Until you delete them (out of the Recycle Bin: deleted notes are remembered as deleted for 180 days so other devices hear about it). At most 2,000 notes, 20 KB each, 3 MB in all", "You; a shared note: everyone in it"],
            ["Buddy Locator (only while you share): who you share with and until when, your **latest** position (never a history; rounded to about 1 km with Approximate location), your named places and alerts, and who asked to see you", "Your position: until you pause, stop sharing, or the last share runs out (checked every minute). Shares, places and alerts: until you remove them. Asks: 7 days", "Your position: only the buddies you share with, while the share lasts. The rest: only you"],
            ["Come Over's shared notes, pictures and Shared with Friends folders (pointers, desktops and follow are never saved)", "Until the owner deletes them (or everyone leaves)", "The people it's shared with"],
            ["Visual Basic 98 programs you send in 98 Messenger: the program, its Shared values, who it was sent to and how many changes each person made today", "30 days after the last change, or when everyone removes it", "The people it was sent to"],
            ["Pickleball 98's Real Games: play sessions (place, time, who's invited, RSVPs, chat, the courts' rotation) and matches you played (players, scores, place, date)", "Sessions: 30 days after they start. Matches: until someone who played removes them (a confirmed match needs the other team to agree). Matches nobody confirmed expire after 7 days. At most 2,000 matches logged per account", "A session: everyone invited; a match: the people who played; ratings: the people on your ladder"],
            ["Pickleball 98's Living Park (only if you leave your clone in the park; collection \"parkclones\"): your clone, look, name, venue, approved lines, and its log (who played it, the score, when; the newest 50)", "Until you press Take it back, or 60 days without any change", "Your buddies, while you're signed off"],
            ["Calendars on the server: events, tasks (to-dos), comments, activity, invitations", "Until deleted; each calendar's activity keeps the newest 200 lines", "The calendar's members"],
            ["Us: pairing, letters, Our Story, photos, flowers, Our Pet, Dream House, Us calendar", "While paired; after unpairing, 30 days, then deleted", "You two only"],
            ["Quizzes and Photo Puzzles sent or received", "Quizzes 90 days; puzzles until either of you deletes them", "The two people in it"],
            ["Sunny Acres towns, notes and hearts, co-op towns", "Until deleted; couple goals about 5 weeks", "You, your partner, buddies you allow, co-op members"],
            ["Tetris Online ranks", "Until you delete the account", "Everyone playing (top lists)"],
            ["Published homepage", "Until you unpublish it", "Everyone"],
            ["Guestbook entries", "Kept; tied to your account only if you were signed on", "Everyone (under the name you typed)"],
            ["Notification settings and devices (push subscriptions)", "Until you turn notifications off there (or the browser drops them); 10 devices", "You"],
            ["Compass's live-browsing log: for each day, which sites (names only, like www.example.com) the server fetched for you and how much data. No page addresses, searches or page contents", "7 days after the day", "The server's owner, only to answer abuse complaints"],
            ["Pages you reported in Compass (address, your note, the time)", "90 days", "The server's owner"],
            ["Compass data used today (a number)", "3 days", "You (About Compass)"],
          ],
        },
      },
      { h: "Only in memory (never stored)" },
      {
        list: [
          "**Instant messages** pass through the server to your buddy, and **chat rooms** to the people in them. They're saved only as the table above says (turn **Save my conversations on the server** off in My AIM > Preferences... to keep them on your devices only). Pictures and voice messages go straight from your device to Vercel Blob; the server never carries them, and push notifications only say \"📷 Picture\" or \"🎤 Voice message\".",
          "**Calls** go directly between the two devices. The server only passes the setup messages (who's calling, connection details); it never carries your voice or video.",
          "**Voice chat** (My Park, Come Over, Watch Together) goes directly between devices the same way. The server only knows who has voice on in that park, hangout or video, and passes the setup messages. Voice is never recorded or saved.",
          "**Go Live** (Pickleball 98) passes along only where the players are on the court, the hits, the score, the players' names, the court and reactions, to the host's buddies and anyone with the link. The server keeps the last minute in memory for people who join late and forgets the game when it ends (at most 3 hours). The video and sound never leave the filming phone.",
          "**Watch Together** passes along only which YouTube videos are in the queue, play/pause and the position, reactions and the little chat, and only to the people watching. It's kept in memory while someone's watching and gone a minute after everyone leaves.",
          "**Online games, game chat and Network Neighborhood** (files and WinPopup messages sent between computers) go through the server live. Game chat keeps the last 50 lines of a room in memory for people who join later. In Imposter the server holds the secret word, who the imposters are, the clues and the votes only while the room is open.",
          "Who's online, away messages and warning levels.",
          "Your IP address is used for a few minutes to slow down password guessing and spam; it isn't stored with your account. Render (the host) may keep its own short request logs.",
        ],
      },
      { note: "File sync's online space is 300 MB per screen name, on Vercel Blob's free plan (98ish uses at most 750 MB of it for everyone together), so 98ish keeps photos small (under about 400 KB each). When the free plan's monthly allowance is used up, sync says \"Online storage is resting until\" a date; your files stay on your device and sync then." },
    ],
    related: ["privacy-overview", "privacy-third-parties", "privacy-couples", "delete-account", "file-sync", "messenger-calls"],
  },
  {
    id: "privacy-third-parties",
    book: "privacy",
    title: "Other services 98ish uses",
    summary: "Push notifications, call setup, YouTube and the Internet Archive: what each one sees.",
    keywords: ["third parties", "push service", "STUN", "TURN", "YouTube privacy", "Internet Archive", "Wayback", "Vercel", "Render", "Google", "Apple"],
    body: [
      {
        table: {
          head: ["Service", "Used for", "What it sees"],
          rows: [
            ["Vercel", "Serving the 98ish website", "Your device's IP address and the pages and files it loads, like any website host."],
            ["Render and MongoDB Atlas", "The 98ish server and its database", "What's listed in [[privacy-server]]."],
            ["Vercel Blob", "The contents of synced files (only with file sync on), pictures and voice messages sent in 98 Messenger (90 days), and photos and videos in shared albums", "Their contents, stored privately under a scrambled name (not your screen name or the album's name), and your device's IP address when it sends or fetches them."],
            ["Apple, Google or Mozilla push services", "Notifications while 98ish is closed (only if you turn them on)", "That a notification was sent to your device, when, and its size. The words are encrypted for your device; the push service can't read them."],
            ["Google's public STUN servers", "Helping two devices find each other for a call or voice chat", "Your device's IP address during setup. Your voice and video never go through it."],
            ["A TURN relay (only if the 98ish server has one set up)", "Calls and voice chat on networks that block direct connections", "Your IP address and the encrypted audio and video passing through (it can't play them)."],
            ["YouTube (Google)", "YouTube '98, Watch Together and videos shared in 98 Messenger", "Searches go through 98ish's own relay on Vercel to the YouTube Data API. Videos play in YouTube's player, which sees your IP address and may set its own cookies."],
            ["Internet Archive (web.archive.org)", "Internet Explorer's time machine", "The addresses you visit: 98ish's relay asks which dates exist, and the old pages load straight from the Archive."],
            ["Wiktionary", "\"Define\" in Word Duel", "The word you look up (it opens their page)."],
            ["jsDelivr (cdn.jsdelivr.net)", "LAN Party 98's DOS player and Flash player (Ruffle) and Virtual PC 98's PC emulator, downloaded the first time you use them", "Your device's IP address, as for any download."],
            ["js-dos network (net.dos.zone)", "Connecting LAN Party 98 players to each other for a LAN game (the game itself then goes directly between the players)", "Your device's IP address and a random player number while you host or join a LAN game; the other players' devices see your IP address too, as in any direct connection."],
            ["Hugging Face (huggingface.co, Meta's MapAnything Space)", "Pickleball 98's Capture this court (only when you use it)", "The frames picked from your walk-around video of the court, and your device's IP address; the 3D points come back to your device and are saved on drive C:"],
            ["Open-Meteo (open-meteo.com)", "The weather in Weather, for outdoor Real Games sessions, and for Pickleball 98's Real Sky (the sky and weather at the venue you're walking: the venue's own location, never yours)", "Your device's IP address and the court's or place's rough location (rounded to about a kilometer)."],
            ["Apple Maps / Google Maps", "Real Games' Directions links (Pickleball 98) (only when you tap one)", "The court you asked directions to, as with any link you open."],
            ["OpenStreetMap's Overpass API (through the 98ish server)", "Pickleball 98's Venue Finder, when you open a venue nobody has opened lately", "Nothing about you: the 98ish server asks for the map around that venue and keeps the result for everyone. **Near me** uses your location only on your device to pick nearby venues from the list it already has; it's never sent."],
            ["Hugging Face (huggingface.co) and jsDelivr (cdn.jsdelivr.net)", "Floppy's brain: the AI model files and the code that runs them, downloaded once when you choose Give Floppy a brain", "Your device's IP address and which model files it downloads. Nothing you type: Floppy's AI runs on this device."],
            ["OpenFreeMap (tiles.openfreemap.org)", "Buddy Locator's map", "Your device's IP address and which parts of the map it loads (so, roughly where you're looking). Never your position or your buddies'."],
            ["jsDelivr (cdn.jsdelivr.net) and Google (storage.googleapis.com)", "Be Yourself (3D Me in calls): the face tracker's code and model file, downloaded once when you first turn it on; the 3D head renderer comes from 98ish itself", "Your device's IP address, as for any download. Never your camera picture: your face is read on your device into numbers that go only to the friend you're calling."],
            ["jsDelivr (cdn.jsdelivr.net) and Google (storage.googleapis.com)", "Pickleball 98's Twin Replay: the pose model's code and model file, downloaded once when you first read a video", "Your device's IP address, as for any download. Never your video or anything in it: the video is read on your device."],
          ],
        },
      },
      "Chess Puzzles' puzzles come from the Lichess puzzle database (public domain) and are built into 98ish: solving them never contacts Lichess, and your puzzle rating and history stay on this device.",
      "Pickleball 98's real venues in My Park are built from OpenStreetMap data (© OpenStreetMap contributors, ODbL) that ships inside 98ish: choosing a venue never contacts OpenStreetMap or any map service, and 98ish never asks where you are. Online, the 98ish server only learns which venue you picked (so friends at the same venue meet) and your position inside it, as with Riverside Park.",
      "98ish has no ads, analytics or tracking scripts, and sells nothing to anyone.",
    ],
    related: ["privacy-overview", "privacy-server", "push-setup", "messenger-calls"],
  },
  {
    id: "privacy-couples",
    book: "privacy",
    title: "Privacy for couples (Us)",
    summary: "What you share in Us is only for the two of you, and unpairing hides it right away.",
    keywords: ["couples privacy", "Us privacy", "love letters privacy", "unpair", "partner", "who can see"],
    body: [
      "Everything you share in **Us** (Love Letters, Our Story and its photos, flowers, Our Pet, Dream House, couple quizzes, and your Us calendar) can only be seen by your two 98 Messenger accounts. Anyone else asking the server for it is turned away.",
      { list: ["**Sealed letters** stay sealed on the server until their day: not even the person they're for can open them early.", "Your **Us calendar** is visible only while you're paired.", "Your partner can always visit your Sunny Acres town."] },
      { h: "Unpairing" },
      "In Us you can **Unpair**. That hides everything you share right away, for both of you. It's kept for 30 days in case you pair up again, then deleted for good. To delete it immediately, tick **Delete our letters, story and photos now** when you unpair.",
      { h: "If one of you deletes their account" },
      "Everything the two of you kept in Us is deleted at once (nobody could see it again anyway), and the pairing ends. The other person gets a short notice that the person they were paired with closed their account, with no other details.",
      { open: "Us", label: "Open Us" },
    ],
    related: ["us-pairing", "us-together", "privacy-overview", "privacy-delete", "delete-account"],
  },
  {
    id: "delete-account",
    book: "privacy",
    title: "Delete My Account",
    summary: "Permanently delete your 98 Messenger account and everything the 98ish server keeps for it.",
    keywords: ["delete account", "close account", "remove account", "delete my data", "forget me", "erase", "cancel account", "delete screen name"],
    body: [
      "Deleting your 98 Messenger account removes it, and everything the 98ish server keeps for it, **permanently**. It can't be undone.",
      {
        steps: [
          "Sign on to 98 Messenger as the account to delete.",
          "In the Buddy List choose **My AIM > Delete My Account...** (or Control Panel > **Passwords and Users** > User Profiles > **Delete My Account...**).",
          "Read what will be deleted. Leave **Also erase my files and settings on this device** checked to wipe this device too, or clear it to keep them here as a guest's.",
          "Type your screen name and password, then click **Delete Account**.",
        ],
        title: "To delete your account:",
      },
      { h: "What's deleted" },
      {
        list: [
          "Your account: screen name (someone else can take it afterward), password, profile, Buddy List, block list and remembered devices. Your name comes off other people's Buddy Lists.",
          "Synced files and their online contents, and the old online drive copy.",
          "Your mail, every folder. Mail you sent stays in the recipients' mailboxes (it's theirs, like any e-mail), but shows **(deleted account)** instead of your name.",
          "Your Address Book's online copy.",
          "Your notes. Notes you shared stay with the others in them, without your name; a note someone shared with you stays theirs.",
          "Every photo and video you added to shared albums, and your likes and comments. You leave every album (the next person becomes its owner; an album with nobody else in it is deleted), and the others see \"A member deleted their account\".",
          "Your personal calendar and the Us calendar (and the tasks in them). In shared calendars you leave, and your events, comments and activity go; the longest-standing member becomes the owner.",
          "Everything in Us for every pairing you were in, plus Dream House and the couple's Sunny Acres goals and co-op town.",
          "Quizzes and puzzles you sent or got, your Sunny Acres town (and your notes and hearts in friends' towns), Tetris Online ranks, your homepage, and guestbook entries you signed while signed on.",
          "Notification settings and devices, and messages waiting for you or sent by you to someone signed off.",
          "Your saved conversations, reactions and read receipts. The people you talked to keep their copy, but it shows **(deleted account)** instead of your name (like mail), so whoever takes the name later sees none of it. Pictures and voice messages you sent are deleted, except ones someone you sent them to can still see: those stay theirs until they expire (90 days), no longer tied to you.",
          "Compass: the 7-day log of sites fetched live for you, pages you reported, today's data count, and the cookies the server kept for your relayed sites.",
          "Buddy Locator: your position, who you share with, your places and alerts. The buddies who could see you lose you from their map, and you're taken out of theirs (their shares with you, alerts about you, your asks).",
          "Come Over: shared notes, pictures and folders only you were in are deleted; you leave the others (what you typed or drew stays part of them).",
          "Visual Basic 98: you leave every program sent to you or by you; one nobody else is in is deleted. Shared values you set (a vote, a move) stay part of the program for the others.",
          "Pickleball 98's Living Park: your clone left in the park and its log are deleted; in other people's clone logs you become **Deleted player**.",
          "Pickleball 98's Real Games: sessions you host are deleted (the people invited are told); your RSVPs, invitations and chat lines leave everyone else's sessions. In matches you played you become **Deleted player**, a random name not linked to you, so your friends' records and ratings stay as they were; matches with nobody else on 98 Messenger, and ones you logged that nobody confirmed, are deleted.",
        ],
      },
      { h: "On this device" },
      "This device forgets the account (the remembered sign on, sync and notification settings, cached mail and notifications, the conversations, pictures and voice messages it kept for the account, and shared albums' copies and waiting uploads). If you left the box checked, it also erases this 98ish user's files, photos and settings here and restarts fresh. Other devices you were signed on to are signed off and forget the account too, but keep their files.",
      { note: "If deleting stops part way (the server hiccuped), nobody can sign on to the account any more. Choose Delete My Account again (Sign On offers **Finish deleting...**) and type the password to finish." },
      { warning: "Want a copy first? Use [[backup]] to save your files, and 98ish Mail or Calendar's Share to keep anything you need." },
    ],
    related: ["privacy-delete", "privacy-server", "messenger-accounts", "backup"],
  },
  {
    id: "privacy-delete",
    book: "privacy",
    title: "Deleting your things",
    summary: "How to remove files, synced copies, a user, couple data, a homepage, your account, or everything on a device.",
    keywords: ["delete my data", "remove data", "unpublish", "delete online files", "erase", "clear data"],
    body: [
      "You're in charge of what 98ish keeps. Here's how to remove each kind of thing:",
      {
        table: {
          head: ["What", "How"],
          rows: [
            ["A file", "Delete it, then empty the Recycle Bin."],
            ["Synced copies online", "Backup > Sync with 98 Messenger > Sync options > Delete Online Files. The files on your devices stay; sync turns off."],
            ["Someone's profile on this device", "Passwords and Users > User Profiles > Remove."],
            ["Us letters, story and photos", "Unpair in Us and tick Delete our letters, story and photos now."],
            ["Your homepage", "HomePage Studio > Unpublish. Your draft stays on your device."],
            ["Mail", "Delete it, then empty Deleted Items in 98ish Mail."],
            ["A contact", "Delete it in the Address Book (it's deleted on your other devices too)."],
            ["A note", "Delete it in Notes, then Delete Now in View > Recycle Bin (or wait 30 days). A shared note: deleting takes you out of it; the others keep it."],
            ["A task", "Right-click it in Tasks (or touch and hold) > Delete. It's deleted from Calendar too."],
            ["A pickleball match", "Pickleball 98 > Real Games > Matches: Delete (one that isn't confirmed) or Remove... (a confirmed one: someone on the other team agrees)."],
            ["Your clone in the park", "Pickleball 98 > My Park > the menu > My clone in the park... > Take it back. The server deletes it and its log right away."],
            ["Your location in Buddy Locator", "Stop Sharing Everywhere (the tray's location arrow, or Buddy Locator > More options). The server forgets your position right away."],
            ["A 98 Messenger conversation", "In the IM window: More » > Clear History (this device, your other devices and your copy on the server; the other person keeps theirs)."],
            ["All your conversations on the server", "Buddy List > My AIM > Preferences... > clear Save my conversations on the server. Your devices keep theirs."],
            ["Your 98 Messenger account and everything on the server", "My AIM > Delete My Account... (see [[delete-account]])."],
            ["Everything on this device", "Delete My Account's \"erase this device\" box, or clear the website's data (see [[reset-data]])."],
          ],
        },
      },
      { warning: "Deleting can't be undone. Make a Backup first if you might want something back." },
      { note: "A guestbook entry you signed as a guest isn't tied to any account: ask the 98ish owners (Welcome to 98ish > Get involved) if you want it taken down." },
    ],
    related: ["delete-account", "reset-data", "privacy-overview", "privacy-couples", "backup"],
  },
]
