// 98ish Help: Us, the programs for couples (pairing, letters, Our Story, Our Pet, the Quiz
// Show, Photo Puzzle, Doodle Together, Dream House). Format: see ../helpCore.js.

export const books = [{ id: "us", title: "Us (for couples)", order: 60 }]

export const topics = [
  {
    id: "us-pairing",
    book: "us",
    title: "Pairing up with your partner",
    summary: "Pair two 98 Messenger screen names once, and Us opens a private little space for the two of you.",
    keywords: ["pair", "pairing", "couple", "partner", "girlfriend", "boyfriend", "pair request", "unpair", "Us"],
    programs: ["Us"],
    body: [
      "Us turns 98ish into a little place just for the two of you. Before you can use it, you pair your two 98 Messenger screen names. You only do this once, and it works on every phone and computer you sign on from.",
      { open: "Us", label: "Open Us" },
      {
        steps: [
          "You each need your own screen name. See [[messenger-accounts]] if you don't have one yet.",
          "Both of you sign on to 98 Messenger.",
          "One of you opens Us (Start > Programs > Us, or People > Pair with a partner... in the Buddy List).",
          "Type your partner's screen name and click **Send pair request**.",
          "Your partner opens Us and clicks to accept. If they're signed off, they'll see the request the next time they sign on.",
        ],
        title: "To pair up:",
      },
      "That's it. Us moves onto both your desktops, a heart appears in the taskbar tray, and everything in the Us folder (Start > Programs > Us) is shared between the two of you.",
      "While you wait, Us says it's waiting for your partner, and you can cancel the request. If someone sends you a request, Us shows it with buttons to accept or decline.",
      { note: "You can only be paired with one person at a time." },
      { h: "Unpairing" },
      "In Us, click **Settings...**, then **Unpair from** your partner. Everything you share is hidden for both of you right away. It's kept for 30 days in case you pair up again, then deleted for good. Check **Delete our letters, story and photos now** to delete it immediately instead.",
      { warning: "Your partner sees it when you unpair." },
    ],
    related: ["us-together", "messenger-accounts", "privacy-couples", "calendar-sharing"],
  },
  {
    id: "us-together",
    book: "us",
    title: "What you can do in Us",
    summary: "Days together, video calls, flowers that need watering, and everything else in the Us folder.",
    keywords: ["flowers", "send flowers", "water", "bouquet", "days together", "anniversary", "tray heart", "wallpaper", "our photos"],
    body: [
      "Once you're paired, Us shows both your names, whether your partner is online, and how long you've been together (counted from your anniversary if you set one in Our Story, or from the day you paired).",
      { h: "Call your partner" },
      "The big buttons at the top start a video call or a voice call with your partner. See [[messenger-calls]].",
      { h: "Send flowers" },
      {
        steps: [
          "Open Us and click **Send Flowers**.",
          "Pick up to a dozen flowers, a vase and a ribbon.",
          "Write a card, then send it.",
        ],
        title: "To send flowers:",
      },
      "The bouquet appears on your partner's desktop (a little corner widget on phones). It slowly wilts over a few days unless they **water** it once a day, so they have to keep coming back. A bouquet left without water for five days is past saving.",
      { h: "Everything else" },
      {
        list: [
          "[[love-letters]]: letters that stay sealed until the day you choose.",
          "[[our-story]]: your relationship as a timeline of photos.",
          "[[our-pet]]: a little creature you raise together.",
          "[[quiz-show]]: how well do you know each other?",
          "[[photo-puzzle]]: turn a photo into a puzzle with a secret message.",
          "[[doodle]]: draw on the same page at the same time.",
          "[[dream-house]]: decorate a dollhouse together.",
          "Your shared **Us** calendar in Calendar, for date nights and trips. See [[calendar-sharing]].",
        ],
      },
      { h: "The heart in the tray" },
      "The heart next to the clock shows a badge when there's a new letter, flowers or a pair request, with a balloon saying what's new.",
      { tip: "Display Properties has an **Our photos** wallpaper that shows your Our Story photos, taking turns while you're signed on." },
    ],
    related: ["us-pairing", "messenger-calls", "notifications", "privacy-couples"],
  },
  {
    id: "love-letters",
    book: "us",
    title: "Love Letters",
    summary: "Write letters on pretty stationery and send them now, on a date, as an \"Open when...\" letter, or as a countdown.",
    keywords: ["letters", "love letter", "scheduled letter", "open when", "countdown", "sealed", "anniversary letter", "stationery"],
    programs: ["Love Letters"],
    body: [
      "Love Letters lets you write a letter, seal it in an envelope and send it to your partner. Letters can wait for a special day: until then, they stay sealed, and even the server won't show a word of them early.",
      { open: "Love Letters", label: "Open Love Letters" },
      {
        steps: [
          "Open Love Letters and click the **Write** tab.",
          "Pick the stationery, an envelope color and a handwriting style.",
          "Give it a title and write your letter. You can add a photo too.",
          "Under **Delivery**, choose when it opens (see below).",
          "Send it. It's sealed with a kiss and on its way.",
        ],
        title: "To write a letter:",
      },
      { h: "When it opens" },
      {
        list: [
          "**Deliver now**: they can open it right away.",
          "**Open on a date**: pick a day and time, like your anniversary. Until then it shows a countdown.",
          "**Open when...**: a letter for a moment, like \"you miss me\", \"you can't sleep\" or \"it's your birthday\". Pick one or write your own. They open it whenever they need it.",
          "**Countdown (a letter a day)**: write 2 to 14 letters, and one unlocks each day. You can start today or tomorrow morning.",
        ],
      },
      { h: "Reading letters" },
      "Your **Inbox** tab shows the letters you got. Sealed ones show when they open. Click an open one to break the wax seal and read it. Tap the heart to add it to **Favorites**. The **Sent** tab shows what you've sent and whether it has been opened.",
      { tip: "With notifications on, your partner hears about a new letter even when 98ish is closed." },
    ],
    related: ["us-together", "our-story", "notifications", "privacy-couples"],
  },
  {
    id: "our-story",
    book: "us",
    title: "Our Story",
    summary: "A shared timeline of your relationship: moments with dates, places, words and up to four photos.",
    keywords: ["timeline", "photos", "memories", "moments", "slideshow", "anniversary", "together since", "how we met"],
    programs: ["Our Story"],
    body: [
      "Our Story is your relationship as a timeline, written together. Each moment has a date, a title, a place, a few words, a sticker for the mood and up to four photos. Anything one of you adds, the other sees too.",
      { open: "Our Story", label: "Open Our Story" },
      {
        steps: ["Open Our Story and add a new moment.", "Fill in the date, title, place and a few words, and pick a sticker.", "Add up to four photos from your phone or computer.", "Save it. It takes its place on the timeline."],
        title: "To add a moment:",
      },
      "Click a moment to change it. The story's settings let you set a title, the day you got together (**Together since**, which Us counts from), the day you met and how you met.",
      { h: "Ways to look at it" },
      { list: ["**Timeline**: every moment in order.", "**Photos**: a wall of all your photos.", "**Slideshow**: your photos one after another, with buttons to pause and go back or forward."] },
      { h: "Publishing as a homepage" },
      "Click **Publish...** to turn your story into a homepage that anyone on 98ish can visit. It replaces your current homepage. Mark a photo **private** (the lock button) and it never goes on a homepage.",
      { warning: "Publishing makes your story public. Nothing is published unless you choose to." },
      { tip: "Pick the **Our photos** wallpaper in Display Properties to see your Our Story photos on your desktop." },
    ],
    related: ["us-together", "homepage-studio", "display", "privacy-couples"],
  },
  {
    id: "our-pet",
    book: "us",
    title: "Our Pet",
    summary: "Adopt a little creature together, then feed it, play, cuddle, bathe it, put it to bed and dress it up.",
    keywords: ["pet", "virtual pet", "Tamagotchi", "feed", "adopt", "bond level", "Grandma's", "Bunnycat", "Dragonlet"],
    programs: ["Our Pet"],
    body: [
      "Our Pet is a little creature the two of you raise together. Choose a Bunnycat, a Dragonlet, a Puffsheep or a Mochi Sprout, pick its colors and give it a name. Your partner can suggest a different name, and you say yes or no.",
      { open: "Our Pet", label: "Open Our Pet" },
      { h: "Looking after it" },
      {
        list: [
          "**Feed**: pick a snack, like a strawberry or a heart cookie.",
          "**Play**: a game of catch. Treats rain down for 20 seconds; steer your pet to catch them (drag, tap or use the arrow keys). Hearts are worth 3, stars 2.",
          "**Cuddle**: rub or tap your pet.",
          "**Bath**: scrub it all over, then click Done.",
          "**Lights off**: tuck it in to sleep (and **Wake up** in the morning).",
          "**Dress up**: hats and outfits. More unlock as your bond grows.",
        ],
      },
      "If you both have Our Pet open at the same time, you see each other's hands and everything the other one does, live.",
      { h: "Growing up" },
      "Your bond grows every time either of you looks after your pet, and extra when you both do on the same day. Over a couple of weeks of care it grows from a baby to all grown up.",
      { note: "Your pet never dies. If nobody visits for five days, it goes to stay at Grandma's until you both come to get it." },
      { h: "Options" },
      "Click **Options...** to let your pet wander along the bottom of your desktop while Our Pet is closed (it starts off on phones), and to turn its gentle reminders (at most once a day) on or off. With notifications on, you may also get a reminder when it needs care.",
    ],
    related: ["us-together", "notifications"],
  },
  {
    id: "quiz-show",
    book: "us",
    title: "Lovebirds Quiz Show",
    summary: "A game show for two (or a party): How Well Do You Know Me, This or That, Deep Talk cards and Party Trivia.",
    keywords: ["quiz", "game show", "how well do you know me", "this or that", "deep talk", "trivia", "compatibility", "Lulu", "quiz builder"],
    programs: ["Lovebirds Quiz Show"],
    body: [
      "The Lovebirds Quiz Show is a TV game show hosted by Lulu the lovebird. It's made for couples, but friends can play too.",
      { open: "Lovebirds Quiz Show", label: "Open the Quiz Show" },
      { h: "The four games" },
      {
        list: [
          "**How Well Do You Know Me?** One of you answers secretly, the other guesses. Then swap. Shows have rounds, double points, a lightning round and a final bet.",
          "**This or That**: quick picks, both at once. Pick the same side and you both score.",
          "**Deep Talk Cards**: conversation cards from light to deep. No points, just talking.",
          "**Party Trivia**: classic trivia for a group. Fast right answers score the most.",
        ],
      },
      { h: "Three ways to play" },
      {
        list: [
          "**Live, on two phones**: each of you on your own screen at the same time. Reveals pop up on both at once.",
          "**Pass the phone**: sitting together? Play on one device and hand it back and forth. It tells you when to hand it over (no peeking!).",
          "**Take turns**: answer now, and the other person gets a notification and plays when they're free. Results wait in both your **Inboxes**.",
        ],
      },
      "Live games and taking turns need 98 Messenger. Game > **Play Live Online...** lets you invite anyone who's online, and you can also start a live game from the Games button in an IM window.",
      { h: "More fun" },
      "There are also **Compatibility** quizzes, **Trivia About Us** (questions about the two of you), and a **Quiz Builder** to write your own quiz. Game > **Past Shows & Badges** keeps your history.",
      { tip: "Help > How to Play shows three quick illustrated steps for each game." },
    ],
    related: ["us-together", "online-play", "game-invites"],
  },
  {
    id: "photo-puzzle",
    book: "us",
    title: "Photo Puzzle",
    summary: "Turn any picture into a jigsaw or a slide puzzle, and send it to someone with a secret message.",
    keywords: ["jigsaw", "puzzle", "slide puzzle", "secret message", "photo", "pieces"],
    programs: ["Photo Puzzle"],
    body: [
      "Photo Puzzle turns a picture into a jigsaw (12, 24, 48 or 96 pieces) or a slide puzzle (3x3, 4x4 or 5x5). Use a built-in picture, one from your 98ish drive, or a photo from your phone or computer.",
      { open: "Photo Puzzle", label: "Open Photo Puzzle" },
      { h: "Playing" },
      { phone: "Drag pieces up from the tray under the board. Pieces that fit snap together, and a group near its spot snaps onto the board.", computer: "Drag pieces onto the board. Pieces that fit snap together, and a group near its spot snaps onto the board." },
      "With rotation turned on, tap or click a piece to turn it. In a slide puzzle, tap a square in the gap's row or column to slide it (or use the arrow keys). The missing corner comes back when it's solved.",
      { list: ["Options > **Show Preview** shows the whole picture.", "Options > **Edge Pieces Only** helps you start with the border.", "Game > **Fit to Window** brings every piece back into view."] },
      "Puzzles in progress are kept on this device, so you can come back later.",
      { h: "Sending a puzzle" },
      {
        steps: ["Make a new puzzle and choose to send it.", "Pick who it's for: your partner comes first, then your 98 Messenger buddies.", "Give it a title and write a secret message.", "Send it. They see your message once they solve it."],
        title: "To send a puzzle:",
      },
      "Game > **Puzzles I Sent** shows how long it took them.",
      { tip: "In Photos, Share > Photo Puzzle turns the picture you're looking at into a puzzle." },
    ],
    related: ["photos", "us-together", "messenger"],
  },
  {
    id: "doodle",
    book: "us",
    title: "Doodle Together",
    summary: "One canvas, up to four people drawing at the same time, with pencils, brushes, a fill bucket and stickers.",
    keywords: ["draw", "drawing", "doodle", "canvas", "draw together", "stickers", "sketch"],
    programs: ["Doodle Together"],
    body: [
      "Doodle Together is a shared drawing page. Draw on your own, or invite your partner or a buddy and you all draw at once, each with a colored cursor so you can see who's where.",
      { open: "Doodle Together", label: "Open Doodle Together" },
      { h: "Tools" },
      "Pick the **Pencil**, **Brush**, **Eraser**, **Fill** (paint bucket) or **Stickers**, and a color. The Background menu changes the paper.",
      { phone: "One finger draws. Two fingers move around and pinch to zoom.", computer: "Draw with the mouse. View > Zoom In, Zoom Out and Fit to Window change the view." },
      { h: "Drawing with someone" },
      {
        steps: ["Choose File > **Draw Online with Someone...**", "Pick your partner or a buddy to invite.", "When they accept, your drawing comes along, and you both see every stroke as it's drawn."],
        title: "To invite someone:",
      },
      "You can also start from Network Neighborhood or the Games button in an IM window. Up to four people can draw together, and there's a chat beside the canvas.",
      { list: ["**Undo My Last** ({{Ctrl+Z}}) takes back only your own strokes.", "**Clear Drawing...** asks the others first.", "File > **Save to My Documents** saves a picture in the Doodles folder for everyone in the room. **Open in Paint** opens it in Paint."] },
    ],
    related: ["paint", "network-neighborhood", "game-chat", "us-together"],
  },
  {
    id: "dream-house",
    book: "us",
    title: "Dream House",
    summary: "Decorate a dollhouse room by room, dress up little people, and share one house with your partner.",
    keywords: ["dollhouse", "decorate", "house", "furniture", "dress up", "rooms", "wallpaper"],
    programs: ["Dream House"],
    body: [
      "Dream House is a dollhouse to decorate. Fill the rooms with furniture from the catalog, change wallpaper and floors, and dress up the little people who live there. It's saved on this device, or shared with your partner.",
      { open: "Dream House", label: "Open Dream House" },
      { phone: "Tap **Catalog** and tap something to put it in the room you're looking at, then drag it where you like. Pinch to zoom; double-tap a room to zoom right in.", computer: "Drag things from the catalog into any room, or click one to drop it in the selected room. Scroll to zoom, drag an empty spot to look around, and double-click a room to zoom in." },
      {
        list: [
          "Small things (lamps, cakes, plants) land on the tabletop or shelf below them. Wall things stay on the wall, and lights hang from the ceiling.",
          "Tap a room's empty wall, then **Walls & Floors** to change its wallpaper and floor.",
          "The Edit menu flips, duplicates, deletes and changes what's in front.",
          "Select a person and choose **Dress Up...** to change their name, hair, outfit and more.",
          "View > **Nighttime** makes the lamps glow.",
          "House > **Take a Photo** saves a picture in the Dream House folder in My Documents.",
        ],
      },
      { keys: [["Del", "Delete"], ["F", "Flip"], ["Arrow keys", "Nudge"], ["Ctrl+Z", "Undo"], ["Ctrl+D", "Duplicate"]], title: "Keys" },
      { h: "Decorating together" },
      "If you're paired, click **Share** in the toolbar to open one house that you both decorate. Changes from either of you show up for the other.",
    ],
    related: ["us-together", "us-pairing"],
  },
]
