// Generated by tools/venues/build-venues.mjs: the real venues My Park can load (each spec lazy-loaded).
// Venue data © OpenStreetMap contributors (ODbL 1.0), with 98ish corrections.
export const VENUE_LIST = [
  {
    "id": "loscab",
    "name": "Los Cab Sports Village",
    "short": "Los Cab",
    "city": "Fountain Valley, CA",
    "indoor": false,
    "access": "members",
    "lat": 33.714515,
    "lon": -117.923701,
    "lit": true,
    "courts": 54,
    "tennis": 13,
    "live": 6,
    "kb": 86.7
  },
  {
    "id": "newport",
    "name": "The Tennis & Pickleball Club at Newport Beach",
    "short": "Newport Beach Club",
    "city": "Newport Beach, CA",
    "indoor": false,
    "access": "members",
    "lat": 33.611121,
    "lon": -117.879536,
    "lit": true,
    "courts": 44,
    "tennis": 12,
    "live": 6,
    "kb": 95.3
  },
  {
    "id": "wolfbear",
    "name": "Wolf + Bear Indoor Pickleball",
    "short": "Wolf + Bear",
    "city": "Van Nuys, CA",
    "indoor": true,
    "access": "public",
    "lat": 34.180921,
    "lon": -118.458081,
    "lit": true,
    "courts": 14,
    "tennis": 0,
    "live": 6,
    "kb": 81.2
  },
  {
    "id": "whittier",
    "name": "iPickle Whittier Narrows",
    "short": "Whittier Narrows",
    "city": "South El Monte, CA",
    "indoor": false,
    "access": "public",
    "lat": 34.043765,
    "lon": -118.057659,
    "lit": true,
    "courts": 20,
    "tennis": 12,
    "live": 6,
    "kb": 46.8
  },
  {
    "id": "paseo",
    "name": "The Paseo Club",
    "short": "Paseo Club",
    "city": "Valencia, CA",
    "indoor": false,
    "access": "members",
    "lat": 34.436651,
    "lon": -118.562242,
    "lit": true,
    "courts": 11,
    "tennis": 11,
    "live": 6,
    "kb": 76.9
  },
  {
    "id": "sinaloa",
    "name": "Sinaloa Middle School",
    "short": "Sinaloa MS",
    "city": "Simi Valley, CA",
    "indoor": false,
    "access": "public",
    "lat": 34.265631,
    "lon": -118.785571,
    "lit": false,
    "courts": 12,
    "tennis": 0,
    "live": 6,
    "kb": 67.9
  },
  {
    "id": "smash",
    "name": "California SMASH Pickleball & Social Club",
    "short": "California SMASH",
    "city": "El Segundo, CA",
    "indoor": true,
    "access": "public",
    "lat": 33.927233,
    "lon": -118.38817,
    "lit": true,
    "courts": 9,
    "tennis": 0,
    "live": 6,
    "kb": 44
  },
  {
    "id": "bouquet",
    "name": "Bouquet Canyon Park",
    "short": "Bouquet Canyon",
    "city": "Santa Clarita, CA",
    "indoor": false,
    "access": "public",
    "lat": 34.453523,
    "lon": -118.505113,
    "lit": true,
    "courts": 8,
    "tennis": 0,
    "live": 6,
    "kb": 55.4
  }
]
export const loadVenueSpec = (id) => {
  switch (id) {
    case "loscab":
      return import("./loscab.json").then((m) => m.default || m)
    case "newport":
      return import("./newport.json").then((m) => m.default || m)
    case "wolfbear":
      return import("./wolfbear.json").then((m) => m.default || m)
    case "whittier":
      return import("./whittier.json").then((m) => m.default || m)
    case "paseo":
      return import("./paseo.json").then((m) => m.default || m)
    case "sinaloa":
      return import("./sinaloa.json").then((m) => m.default || m)
    case "smash":
      return import("./smash.json").then((m) => m.default || m)
    case "bouquet":
      return import("./bouquet.json").then((m) => m.default || m)
    default:
      return Promise.resolve(null)
  }
}
