// Generated by tools/venues/build-venues.mjs: the real venues My Park can load (each spec lazy-loaded).
// Venue data © OpenStreetMap contributors (ODbL 1.0), with 98ish corrections.
export const VENUE_LIST = [
  {
    "id": "loscab",
    "name": "Los Cab Sports Village",
    "short": "Los Cab",
    "city": "Fountain Valley, CA",
    "indoor": false,
    "access": "members",
    "courts": 54,
    "tennis": 13,
    "live": 6,
    "kb": 86.7
  },
  {
    "id": "newport",
    "name": "The Tennis & Pickleball Club at Newport Beach",
    "short": "Newport Beach Club",
    "city": "Newport Beach, CA",
    "indoor": false,
    "access": "members",
    "courts": 44,
    "tennis": 12,
    "live": 6,
    "kb": 95.4
  },
  {
    "id": "wolfbear",
    "name": "Wolf + Bear Indoor Pickleball",
    "short": "Wolf + Bear",
    "city": "Van Nuys, CA",
    "indoor": true,
    "access": "public",
    "courts": 14,
    "tennis": 0,
    "live": 6,
    "kb": 81.4
  },
  {
    "id": "whittier",
    "name": "iPickle Whittier Narrows",
    "short": "Whittier Narrows",
    "city": "South El Monte, CA",
    "indoor": false,
    "access": "public",
    "courts": 20,
    "tennis": 12,
    "live": 6,
    "kb": 46.8
  },
  {
    "id": "paseo",
    "name": "The Paseo Club",
    "short": "Paseo Club",
    "city": "Valencia, CA",
    "indoor": false,
    "access": "members",
    "courts": 11,
    "tennis": 11,
    "live": 6,
    "kb": 74.6
  },
  {
    "id": "sinaloa",
    "name": "Sinaloa Middle School",
    "short": "Sinaloa MS",
    "city": "Simi Valley, CA",
    "indoor": false,
    "access": "public",
    "courts": 12,
    "tennis": 0,
    "live": 6,
    "kb": 70.6
  },
  {
    "id": "smash",
    "name": "California SMASH Pickleball & Social Club",
    "short": "California SMASH",
    "city": "El Segundo, CA",
    "indoor": true,
    "access": "public",
    "courts": 9,
    "tennis": 0,
    "live": 6,
    "kb": 44
  }
]
export const loadVenueSpec = (id) => {
  switch (id) {
    case "loscab":
      return import("./loscab.json").then((m) => m.default || m)
    case "newport":
      return import("./newport.json").then((m) => m.default || m)
    case "wolfbear":
      return import("./wolfbear.json").then((m) => m.default || m)
    case "whittier":
      return import("./whittier.json").then((m) => m.default || m)
    case "paseo":
      return import("./paseo.json").then((m) => m.default || m)
    case "sinaloa":
      return import("./sinaloa.json").then((m) => m.default || m)
    case "smash":
      return import("./smash.json").then((m) => m.default || m)
    default:
      return Promise.resolve(null)
  }
}
