import React, { useEffect, useState } from "react"
import "./WindowsUpdate.css"
import { unlock } from "../../../utils/achievements"
import BASELINE from "../../../../release-notes.json"

// "98ish Update": the real thing. It shows what's new in 98ish (the feature merges of the
// last 60 days, release-notes.json from the build: client/releaseNotes.mjs), checks whether a
// newer version has been deployed (the server's sw-manifest.json version against the one
// this page was built as), and restarts into it. The owner chose this over the old made-up
// updates (Y2K Readiness...), 2026-10-06.

/* global __BUILD_VERSION__ */
const RUNNING = typeof __BUILD_VERSION__ !== "undefined" ? __BUILD_VERSION__ : "dev"
const DEV = RUNNING === "dev"

const day = (t) => new Date(t).toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" })
const when = (t) => new Date(t).toLocaleString(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })
const cap = (s) => (s ? s[0].toUpperCase() + s.slice(1) : s)

// the notes this page was built with (or the checked-in ones in development)
const loadNotes = async () => {
  try {
    const r = await fetch("/release-notes.json", { cache: "no-store" })
    if (r.ok) {
      const data = await r.json()
      if (Array.isArray(data?.notes)) return data
    }
  } catch {
    // offline or a dev server: the checked-in notes
  }
  return { version: RUNNING, builtAt: DEV ? null : Number(RUNNING), notes: BASELINE }
}

// what's deployed now: the service worker's manifest is regenerated by every build
const deployedVersion = async () => {
  const r = await fetch("/sw-manifest.json", { cache: "no-store" })
  if (!r.ok) throw new Error("not found")
  const data = await r.json()
  return String(data.version || "")
}

const restartIntoNew = async () => {
  try {
    const reg = await navigator.serviceWorker?.getRegistration?.()
    await reg?.update?.()
  } catch {
    // no service worker (a dev server, a private window): a plain reload still gets it
  }
  window.location.reload()
}

const WindowsUpdate = ({ onClose }) => {
  const [stage, setStage] = useState("welcome") // welcome | checking | uptodate | available | error | dev
  const [info, setInfo] = useState(null) // { version, builtAt, notes }
  const [fresh, setFresh] = useState([]) // notes newer than this page

  useEffect(() => {
    let live = true
    loadNotes().then((d) => live && setInfo(d))
    return () => {
      live = false
    }
  }, [])

  const check = async () => {
    if (DEV) return setStage("dev")
    setStage("checking")
    try {
      const [deployed] = await Promise.all([deployedVersion(), new Promise((r) => setTimeout(r, 900))])
      if (deployed && deployed !== RUNNING) {
        // the newer build's notes, if its file says more than ours
        let newer = []
        try {
          const r = await fetch(`/release-notes.json?v=${encodeURIComponent(deployed)}`, { cache: "no-store" })
          const d = r.ok ? await r.json() : null
          const builtAt = Number(RUNNING)
          newer = (d?.notes || []).filter((n) => n.at > builtAt)
        } catch {
          newer = []
        }
        setFresh(newer)
        setStage("available")
      } else {
        unlock("updates")
        setStage("uptodate")
      }
    } catch {
      setStage("error")
    }
  }

  const notes = info?.notes || []
  const builtAt = info?.builtAt || (DEV ? null : Number(RUNNING))

  const NoteList = ({ list, max = 40 }) => (
    <ul className="wuList wuNotes">
      {list.slice(0, max).map((n) => (
        <li key={n.hash}>
          <span className="wuDate">{day(n.at)}</span>
          <span>{cap(n.title)}</span>
        </li>
      ))}
    </ul>
  )

  return (
    <div className="wuRoot">
      <div className="wuBanner">
        <span className="wuGlobe" aria-hidden="true" />
        <div>
          <b>98ish Update</b>
          <span>Keeping your computer up to date since 1998</span>
        </div>
      </div>

      <div className="wuBody" data-selectable>
        {stage === "welcome" && (
          <>
            <p>{DEV ? "You're running a development copy of 98ish." : builtAt ? `You're running the version of 98ish built ${when(builtAt)}.` : "98ish Update checks for a newer version of 98ish."}</p>
            <button type="button" className="wuBig" onClick={check} data-wu-check>
              Check for updates
            </button>
            <p>
              <b>What's new in 98ish</b>
            </p>
            {notes.length ? <NoteList list={notes} /> : <p className="wuAbout">Loading the list of changes...</p>}
          </>
        )}

        {stage === "checking" && (
          <>
            <p>Checking update.98ish.com for a newer version...</p>
            <div className="progress-indicator segmented wuBar">
              <span className="progress-indicator-bar wuIndeterminate" />
            </div>
          </>
        )}

        {stage === "uptodate" && (
          <>
            <p>
              <b>98ish is up to date.</b> You have the newest version.
            </p>
            <button type="button" className="wuBig" onClick={() => setStage("welcome")}>
              OK
            </button>
          </>
        )}

        {stage === "available" && (
          <>
            <p>
              <b>A new version of 98ish is ready.</b> Restart to update. Your files and settings stay as they are.
            </p>
            {fresh.length > 0 && (
              <>
                <p>New since your version:</p>
                <NoteList list={fresh} max={20} />
              </>
            )}
            <div className="wuButtons">
              <span />
              <button type="button" className="wuBig" onClick={() => (unlock("updates"), restartIntoNew())} data-wu-restart>
                Restart to Update
              </button>
              <button type="button" className="wuBig" onClick={() => onClose?.()}>
                Later
              </button>
            </div>
          </>
        )}

        {stage === "error" && (
          <>
            <p>
              <b>98ish Update couldn't reach the server.</b> Check your connection and try again.
            </p>
            <button type="button" className="wuBig" onClick={check}>
              Try Again
            </button>
          </>
        )}

        {stage === "dev" && (
          <>
            <p>This is a development copy of 98ish, which updates itself as the code changes. Updates are checked on the published 98ish.</p>
            <button type="button" className="wuBig" onClick={() => setStage("welcome")}>
              OK
            </button>
          </>
        )}
      </div>

      <div className="status-bar">
        <p className="status-bar-field">{stage === "checking" ? "Connecting to update.98ish.com..." : "Done"}</p>
        <p className="status-bar-field wuStatusRight">Internet zone</p>
      </div>
    </div>
  )
}

export default WindowsUpdate
