// An Internet Explorer window, optionally opening a page (as of the date IE is set to)
export const ieWindow = (url) => ({
  name: "Internet Explorer",
  app: "ie",
  url,
  minimized: false,
  maximized: false,
  active: true,
  closed: false,
  width: 900,
  height: 640,
  positionX: 10,
  positionY: 0,
  icon_url: "/assets/internet_explorer.png",
})

export const programs = [
  {
    name: "SPECTRA",
    image_url: "/assets/program_icons/spectra.svg",
    icon_url: "/assets/program_icons/spectra.svg",
    width: 860,
    height: 600,
  },
  {
    name: "Tetris",
    image_url: "./assets/program_icons/tetris3-48.png",
    icon_url: "./assets/program_icons/tetris3-48.png",
    width: 600,
    height: 600,
  },
  {
    name: "Internet Explorer",
    app: "ie",
    image_url: "/assets/internet_explorer.png",
    icon_url: "/assets/internet_explorer.png",
    width: 900,
    height: 640,
  },
  {
    name: "Task Manager",
    image_url: "./assets/program_icons/taskManager-48.png",
    icon_url: "./assets/program_icons/taskManager-48.png",
    width: 430,
    height: 480,
  },
  {
    name: "Hover",
    image_url: "./assets/program_icons/hover2-48.png",
    icon_url: "./assets/program_icons/hover2-48.png",
    width: 600,
    height: 600,
  },
  {
    name: "YouTube '98",
    image_url: "./assets/program_icons/video-48.png",
    icon_url: "./assets/program_icons/video-48.png",
    width: 820,
    height: 620,
  },
  {
    name: "My Computer",
    image_url: "/assets/program_icons/computer_explorer.png",
    icon_url: "./assets/program_icons/computer_explorer.png",
    width: 600,
    height: 400,
  },
  {
    name: "Notepad",
    image_url: "/assets/note.png",
    icon_url: "/assets/note.png",
    width: 400,
    height: 400,
  },
  {
    name: "Minesweeper",
    image_url: "/assets/program_icons/mine-48.png",
    icon_url: "/assets/program_icons/mine-48.png",
    width: 373,
    height: 456,
  },
  {
    name: "98 Messenger",
    image_url: "/assets/program_icons/aim2-48.png",
    icon_url: "/assets/program_icons/aim2-48.png",
    width: 260,
    height: 520,
  },
]
