// Turn a venue's reference measurements into an override layer (the fidelity workflow,
// docs/pickleball-venues.md): numbers only, no imagery.
//
//   node tools/venues/ingest-refs.mjs <venue> --refs DIR [--tile #hex] [--flat #hex] [--palms R] [--max-trees N]
//
// Reads DIR/<venue>/ (made by the reference pack: none of it is committed):
//   aerial.json   the aerial's anchor (lat, lon) and scale; layout/segment points are metres east
//                 (x) and north (y) of it
//   layout.json   traced courts: osm_id, colors (or colors_albedo_from_aerial): kitchen/service/
//                 surround (pickleball), service/backcourt/alley/surround (tennis)
//   segment.json  pools (rects), tree canopies (pt, r), OSM buildings with a roof class
//   colors.json   optional: { courts: { <osm_id>: { court, kitchen, ... } }, roofs: { tile, flat } }
//   palette.json  optional, hand-made from the ground and drone photos (aerial colors are hazy):
//                 { pickleball: { court, kitchen, kitchenPale, surround, paleL },
//                   tennis: { blue, slate, surround, slateL }, roofs: { tile, flat }, pool }
//                 a court's class comes from its aerial lightness (kitchen > paleL: the pale
//                 kitchen; tennis service > slateL: slate, else blue); alleys take the surround
// Writes tools/venues/overrides/<venue>.refs.json: courts.byId (paint per court), buildings.style
// (roof style and colors by OSM id), areas.add (pools), trees.add (canopies: small ones palms).
// build-venues.mjs merges it under the hand-written overrides/<venue>.json (that one wins).
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const HERE = path.dirname(fileURLToPath(import.meta.url))
const args = process.argv.slice(2)
const opt = (k, d) => {
  const i = args.indexOf(`--${k}`)
  return i >= 0 ? args[i + 1] : d
}
const id = args[0]
const DIR = path.resolve(opt("refs", process.env.VENUE_REFS || "venues/refs"), id || "")
if (!id || !fs.existsSync(path.join(DIR, "aerial.json"))) {
  console.log("usage: node tools/venues/ingest-refs.mjs <venue> --refs DIR (DIR/<venue>/aerial.json must exist)")
  process.exit(1)
}
const read = (f) => (fs.existsSync(path.join(DIR, f)) ? JSON.parse(fs.readFileSync(path.join(DIR, f), "utf8")) : null)
const aerial = read("aerial.json")
const layout = read("layout.json")
const segment = read("segment.json")
const colors = read("colors.json") || {}
const pal = read("palette.json")
const lum = (h) => (h ? 0.299 * parseInt(h.slice(1, 3), 16) + 0.587 * parseInt(h.slice(3, 5), 16) + 0.114 * parseInt(h.slice(5, 7), 16) : 0)
const lat0 = aerial.anchor.lat
const lon0 = aerial.anchor.lon
const R = 111319.49
const ll = (x, y) => [Math.round((lat0 + y / R) * 1e7) / 1e7, Math.round((lon0 + x / (R * Math.cos((lat0 * Math.PI) / 180))) * 1e7) / 1e7]
const out = { _: `Generated by tools/venues/ingest-refs.mjs from reference measurements (${new Date().toISOString().slice(0, 10)}): numbers only. Put corrections in ${id}.json, not here.` }

// ---------- courts: paint per OSM id ----------
const byId = {}
for (const c of layout?.courts || []) {
  if (!c.osm_id) continue
  const k = c.colors || c.colors_albedo_from_aerial || c.colors_albedo || {}
  const fin = colors.courts?.[c.osm_id] || colors.courts?.[c.id]
  const tennis = /^t/.test(c.type || c.sport || "")
  let p = tennis ? { court: k.service || k.court, alley: k.alley, surround: k.surround } : { court: k.service || k.court, kitchen: k.kitchen, surround: k.surround }
  if (pal && tennis && pal.tennis) {
    const T = pal.tennis
    p = { court: lum(k.service) > (T.slateL ?? 120) ? T.slate : T.blue, alley: T.alley || T.surround, surround: T.surround }
  } else if (pal && !tennis && pal.pickleball) {
    const Q = pal.pickleball
    p = { court: Q.court, kitchen: lum(k.kitchen) > (Q.paleL ?? 190) ? Q.kitchenPale || Q.kitchen : Q.kitchen, surround: Q.surround }
  }
  if (fin) Object.assign(p, fin)
  for (const key of Object.keys(p)) if (!p[key]) delete p[key]
  if (Object.keys(p).length) byId[c.osm_id] = p
}
if (Object.keys(byId).length) out.courts = { byId }

// ---------- buildings: roof style by class ----------
const style = {}
for (const b of segment?.buildings_osm || []) {
  const cls = b.roof_class || ""
  if (/tile/.test(cls)) style[b.osm_id] = { roofStyle: pal?.roofs?.tileStyle || "hip", tile: true, roof: opt("tile") || pal?.roofs?.tile || colors.roofs?.tile || b.roof_hex_raw, ...(pal?.roofs?.band ? { band: pal.roofs.band, top: pal.roofs.flat } : {}) }
  else if (/flat light/.test(cls)) style[b.osm_id] = { roofStyle: "flat", roof: opt("flat") || pal?.roofs?.flat || colors.roofs?.flat || b.roof_hex_raw, parapet: 0.7, ...(b.area_m2 > 700 ? { hvac: true } : {}) }
}
if (Object.keys(style).length) out.buildings = { style }

// ---------- pools ----------
const pools = (segment?.pools || []).map((p) => {
  const [x0, y0, x1, y1] = p.rect
  const big = p.area_m2 > 300
  return { kind: "pool", poly: [ll(x0, y0), ll(x1, y0), ll(x1, y1), ll(x0, y1)].map((q) => ({ ll: q })), color: pal?.pool || colors.pool || "#3fb4e6", ...(big ? { lanes: Math.max(4, Math.round(Math.min(x1 - x0, y1 - y0) / 2.5)) } : {}) }
})
if (pools.length) out.areas = { add: pools }

// ---------- trees: canopies (small ones are palms) ----------
const palmR = Number(opt("palms", 1.9))
const maxTrees = Number(opt("max-trees", 420))
const trees = (segment?.trees || [])
  .slice()
  .sort((a, b) => b.r - a.r)
  .slice(0, maxTrees)
  .map((t) => ({ ll: ll(t.pt[0], t.pt[1]), s: Math.round(Math.min(2.2, Math.max(0.6, t.r / (t.r < palmR ? 2.2 : 1.6))) * 100) / 100, kind: t.r < palmR ? "palm" : "broadleaf" }))
if (trees.length) out.trees = { add: trees }

const file = path.join(HERE, "overrides", `${id}.refs.json`)
fs.writeFileSync(file, JSON.stringify(out, null, 1) + "\n")
console.log(`${id}: ${Object.keys(byId).length} courts painted, ${Object.keys(style).length} roofs, ${pools.length} pools, ${trees.length} trees -> ${path.relative(process.cwd(), file)}`)
