// Fun Facts: written fresh for Speed Typist 98, in plain ASCII
export default [
  "Octopuses have three hearts, and two of them take a break while the octopus swims.",
  "A single day on Venus lasts longer than a whole year on Venus.",
  "To a botanist, a banana counts as a berry, but a strawberry does not.",
  "Sharks were cruising the oceans long before the first trees grew on land.",
  "Wombats are famous for leaving droppings shaped like little cubes.",
  "On a hot summer day, the Eiffel Tower stands a few centimeters taller.",
  "Butterflies taste their lunch with sensors on their feet.",
  "A bolt of lightning is hotter than the surface of the sun, if only for an instant.",
  "Sea otters sometimes hold paws while they nap so they don't drift apart.",
  "The heart of a blue whale is roughly the size of a small car.",
  "Saturn is so light for its size that it would float in a bathtub big enough to hold it.",
  "A shuffled deck of cards is almost surely in an order no deck has ever been in before.",
  "Koalas can sleep up to twenty hours a day, because a diet of leaves gives them very little energy to spend.",
  "Antarctica is the biggest desert on Earth. A desert is about how little rain or snow falls, not how hot it gets.",
  "Hummingbirds can fly backward, and their wings beat so quickly that they hum, which is how they got their name.",
  "Sunlight needs a little over eight minutes to reach Earth, so the warmth on your face left the sun a few minutes ago.",
  "Crows can recognize individual human faces, and they seem to remember who was kind to them and who was not.",
  "Some kinds of bamboo can grow almost a meter in one day, which makes bamboo one of the fastest growing plants around.",
  "Mount Everest gets a tiny bit taller every year, because the plates of rock underneath it are still pushing together.",
  "A giraffe's tongue is dark blue or purple, and it is long enough for the giraffe to clean out its own ears.",
  "Honeybees share directions by dancing. A bee back from a good patch of flowers wiggles in a figure eight, and the angle of the wiggle points the others toward the food.",
  "Tardigrades, also called water bears, are animals smaller than a grain of sand. They can dry out completely, wait for years, and wake up again when water comes back. Some even survived a trip to outer space.",
  "Your skeleton is always under construction. Some cells break down old bone while others build new bone, so over about ten years most of it gets replaced, one small piece at a time, without you noticing.",
  "The deepest spot in the ocean is deeper than the tallest mountain is tall. Drop Mount Everest into the Mariana Trench and its peak would still sit more than a mile beneath the waves.",
  "Pluto has not finished a single lap around the sun since it was discovered in 1930. One year on Pluto lasts about 248 Earth years, so that first full lap will not be done until the 2170s.",
  "The moon drifts a few centimeters farther away from Earth every year. Long ago it hung much closer in the sky, and it looked noticeably bigger to anything that happened to be looking up.",
  "A teaspoon of soil can hold more living things than there are people on the whole planet. Most of them are bacteria and fungi far too small to see, quietly turning old leaves into food for new plants.",
  "Male seahorses are the ones that carry the babies. The female places her eggs in a pouch on his belly, and a few weeks later he gives birth to a cloud of tiny seahorses.",
  "Glass frogs have skin so clear on their bellies that you can see their hearts beating and their dinner being digested.",
  "The fingerprints of a koala look so much like human fingerprints that even an expert would struggle to tell them apart under a microscope.",
  "Snow is not really white. Each flake is made of clear ice, but all those tiny crystal faces bounce light in every direction, so a fresh drift looks bright white to our eyes.",
]
