// Retro Computing: 90s computer nostalgia, written fresh for Speed Typist 98
export default [
  "Please wait while the modem finishes screaming at the phone line.",
  "Insert disk 2 of 14, then go make a sandwich.",
  "My mouse had a ball inside it, and the ball collected all the dust in the house.",
  "Nobody pick up the phone, I'm downloading a picture!",
  "The screensaver had flying toasters, and I thought it was the future.",
  "Save early, save often, and label every floppy disk you own.",
  "It is now safe to turn off your computer. Good night, old friend.",
  "The printer jammed again, so I printed the report one page at a time.",
  "I burned a mix CD for the road trip and wrote the song list in marker on the case.",
  "We had one family computer, and it lived in the hallway where everyone could see the screen.",
  "My first email address had my favorite animal, my birthday and three underscores in it.",
  "The computer lab smelled like warm dust and dry erase markers, and it was the best room in the whole school.",
  "Before search engines got good, I kept a notebook full of web addresses that I copied down by hand.",
  "The family photo took three full minutes to load, one stripe at a time, from the top of Aunt June's hat down to her shoes.",
  "I spent an entire Saturday making a personal web page with a spinning globe, a hit counter and a guest book that only my cousin ever signed.",
  "Defragmenting the hard drive was oddly relaxing. You could watch the little colored blocks shuffle into neat rows for an hour.",
  "Every computer game came in a box the size of a pizza, and inside was one disk and a manual thick enough to be a phone book.",
  "The chat room went quiet when someone typed in all capital letters, and then everyone politely asked them to turn off caps lock.",
  "If the program froze, you pressed three keys at once and hoped for the best. If that failed, you reached for the big button.",
  "Our school had a typing class where they covered the keys with little rubber caps so you could not peek. I still type faster because of it.",
  "The installer said twenty minutes remaining, then four hours remaining, then two minutes remaining, and then it asked me to restart.",
  "I kept a stack of free trial discs from the mail on my desk. They made great coasters, and better shiny mobiles for my bedroom ceiling.",
  "The clicking of a busy hard drive meant something was happening. Today computers are so quiet that you can never tell if they are thinking or just ignoring you.",
  "My dad bought a scanner and scanned every photo in the house, including a few of his thumb. Those are still in a folder called Family Pics Final Final.",
  "On the old computer, the start button felt like a doorway. Click it and there were games, a paint program, a calculator, and a whole world of little windows to explore.",
  "We had a dial-up account with a limited number of hours each month. My sister and I made a schedule on the fridge, and arguing over it became a family tradition.",
  "When the new computer finally arrived, the whole family stood around the box like it was a birthday cake. It had a CD drive, a whole gigabyte of storage and speakers that could almost fill the room. Dad read the manual out loud while we fought over who would get to click on things first.",
  "Every afternoon after school I would log on, wait for the familiar tones, and check to see which friends were online. Most days we talked about nothing at all, but it felt like the most important conversation in the world.",
  "I learned to type by playing a game where letters fell from the sky like rain, and you had to type them before they hit the ground. By the end of the summer I could clear an entire storm without ever looking down at my hands.",
  "The computer in the back of the classroom had one game on it, a slow adventure where you rode a covered wagon across the country. We played it every recess, lost every oxen we ever owned, and loved every minute.",
]
