// Tiny Stories: little original scenes for Speed Typist 98
export default [
  "The cat knocked the last pencil off the desk, then looked at me as if I had done it.",
  "Grandpa's toaster only worked if you hummed to it, so breakfast was always a little musical.",
  "The lighthouse keeper waved at every ship, even the ones that never waved back.",
  "My umbrella flipped inside out, so I wore it like a hat and kept walking.",
  "The robot at the bakery always gave one extra cookie to anyone who said please.",
  "A lost balloon floated past the classroom window, and the whole room went quiet to watch it go.",
  "The snowman lasted three whole days, which was a new record for our street.",
  "She planted one sunflower seed in a coffee cup, and by August it was taller than the mailbox.",
  "The bus driver knew everyone's name, including the dog who rode to the park every Saturday morning.",
  "We built a blanket fort so big that Dad had to crawl in on his elbows to deliver the popcorn.",
  "The old radio in the attic still worked, but it only picked up one station, and that station only played polkas.",
  "On the first warm day of spring, the whole neighborhood came outside at once, blinking like bears after a long nap.",
  "The goldfish watched the movie with us every Friday night. It seemed to prefer the ones with a lot of explosions.",
  "Our teacher brought in a jar of tadpoles on Monday. By the end of the month the jar was empty and the pond out back was a lot noisier.",
  "The library cat slept on the dictionary every afternoon, so if you needed to look up a word, you had to ask her politely first.",
  "Mom tried to fix the squeaky door with oil, then tape, then a stern talking to. The talking to worked best.",
  "The garage sale had a sign that said everything was one dollar, including the guy running it, who was mostly joking.",
  "Two pigeons fought over a single french fry for ten whole minutes while a third pigeon quietly ate the rest of the bag.",
  "Every night at nine, the dog next door howled along with the ice cream truck, even in winter, when there was no truck at all.",
  "I found a note in a library book that said, if you are reading this, have a wonderful day. So I did.",
  "The kite climbed higher and higher until the string ran out, and for a moment it felt like I was the one being pulled into the sky.",
  "The new kid at camp could not swim, so every morning before breakfast the lifeguard taught her one small thing. By the last week of summer she won the race across the lake, and the lifeguard cheered louder than anyone.",
  "The night the power went out, nobody knew what to do at first. Then my brother found the board games, my sister made shadow puppets on the ceiling, and by the time the lights came back on, no one wanted them.",
  "Every year my aunt bakes a cake shaped like whatever she is excited about. One year it was a volcano, the next it was a sailboat, and last year it was a very lumpy giraffe that somehow tasted the best of all.",
  "The tiny bookstore on the corner had no sign, no website and no cash register, just a bell, a cat named Chapter, and a jar where you left whatever you thought the book was worth. Somehow it never ran out of customers.",
  "When the bridge closed for repairs, the town ran a little ferry across the river. It was slow, and it smelled a bit like fish, but people started taking it even after the bridge opened again, just for the view.",
  "My little brother insisted the moon followed our car on long drives. We tried to prove him wrong by taking every turn we could, but the moon kept up, and by the end of the night we were all on his side.",
  "The old man at the park fed the ducks at exactly noon every day. One rainy Tuesday he did not come, and the ducks marched all the way to his front porch to check on him. He had a cold, and they kept him company until it passed.",
  "The bake sale was supposed to raise money for new band uniforms. Instead, the brownies were so good that people kept coming back, and by the end of the day the band could afford uniforms, a new drum, and a pizza party.",
  "On the last day of school, the janitor opened the gym, turned up the radio, and let everyone dance until the buses came. Nobody remembers the final exams from that year, but everyone remembers the dancing.",
  "Every spring our town holds a kite festival on the hill behind the library. Last year a gust lifted my little red diamond so high that it vanished into a cloud. I held the string for ten minutes, feeling it tug, before it drifted back down and landed gently in the arms of a very surprised mail carrier.",
  "The science fair volcano was supposed to fizz politely. Instead, my partner doubled the baking soda, and a foamy orange river poured off the table, across the gym floor and right up to the judges. We did not win first place, but the principal still talks about it at every assembly.",
  "Our neighbor grows tomatoes the size of softballs, and every August she leaves a basket of them on each porch on the block. Nobody knows her secret. Some say it is the music she plays in the garden at dawn, and some say it is the coffee grounds, but she only smiles and hands out more tomatoes.",
  "At the county fair, I spent my whole allowance trying to toss a ring onto a glass bottle. On the very last throw, the ring wobbled, spun twice and settled perfectly over the neck. The prize was a giant stuffed giraffe that rode home in the back seat with its head poking out of the sunroof.",
  "The power went out during the big storm, so we lit candles, dragged every blanket into the living room and told stories until midnight. When the lights finally flickered back on, nobody moved to turn on the television. We just kept talking, and the storm became one of our favorite nights of the year.",
  "My first job was at a tiny video rental shop on the corner. I learned which customers wanted scary movies, which wanted cartoons for the kids and which only came in for the popcorn by the register. On slow nights the owner let me pick the movie that played on the little set above the counter.",
]
