// Tongue Twisters: invented for Speed Typist 98 (they tangle fingers as well as tongues)
export default [
  "Six slick seals slid swiftly south.",
  "Blue bugs blew big bubbles by the brook.",
  "Fresh fried fish flips freely in the frying pan.",
  "Tricky Trish tracks twelve trucks through town.",
  "Greedy geese gobble green grapes gladly.",
  "Plump plums plop past the purple plum pot.",
  "Shiny shoes shuffle shyly through the shallow shop.",
  "Clever Clara clips crisp clover by the creek.",
  "Brisk breezes bring brittle brown branches.",
  "Fuzzy flies flap fast from fizzy flavored fudge.",
  "Lazy lizards lounge lightly on little lily leaves.",
  "Quick Quinn quietly quizzed the quacking quail.",
  "Wally whistled while wobbly whales went west.",
  "Prickly porcupines pick plump pears in the pale pink parlor.",
  "Sheila's shop sells sheer sheets and short shirts for sheep.",
  "Crispy crackers crumble crookedly in Craig's crowded cupboard.",
  "Seven silly sailors sold seventy salty sandwiches on Sunday.",
  "Twelve twin twisty twigs twirled between two tweeting twins.",
  "Bold Bob bought bright blue bowls, but Bob's bowls broke before brunch.",
  "Funny Frank found four fat frogs frolicking in the foggy forest, and Frank fed the four frogs fried figs.",
  "Merry Mabel mixes marmalade in a metal mug, while mellow Milo munches muffins in the middle of the misty meadow.",
  "Thick thistles thrive through thirty thundering Thursdays, though the thrifty thatcher thinks they're thoroughly thrilling.",
]
